from scripts.nvme_qa_model import add

add(1,'Host 應如何從 CAP 與 VS 確認 NVMe 版本、最大 Queue 大小、Timeout、Doorbell 間距、Memory Page Size 及支援的 Command Set？ || How does a host discover version, queue limits, timeouts, doorbell stride, page sizes and command sets from CAP and VS?', 'register',['cap','crto','init'],'''
在送命令以前，先知道介面允許的配置；CAP 是能力，CC 才是 Host 選擇。不要把能力位元直接複製成設定值。 || Discover legal interface configurations before issuing commands. CAP advertises capabilities; CC contains host selections. Capability bits are not values to copy blindly into configuration fields.
這次讀取只觀察目標 controller，不改變 queue 或媒體。版本號也不能代替逐項選配能力檢查。 || These reads observe one controller without changing queues or media. A version number does not establish support for every optional feature.
VS 的 MJR／MNR／TER 表示版本；CAP.MQES+1 是 I/O queue entry 上限，CQR 是實體連續要求，CSS 表示 command set 支援方式。 || VS.MJR/MNR/TER encode the version. CAP.MQES+1 limits I/O queue entries, CQR specifies physical-contiguity requirements, and CSS describes command-set support.
CAP.TO 單位為 500 ms；Doorbell stride=2^(2+DSTRD) bytes；支援頁面範圍為 2^(12+MPSMIN) 至 2^(12+MPSMAX) bytes。啟用逾時還要讀 CRTO。 || CAP.TO uses 500 ms units. Doorbell stride is 2^(2+DSTRD) bytes; supported pages range from 2^(12+MPSMIN) to 2^(12+MPSMAX) bytes. Enable timeout also requires CRTO.
先映射 NVMe Register，讀 VS、CAP，選合法 MPS／CSS／AMS／Ready Mode，再配置 queue。若 IOCSS=1，Enable 後用 Identify CNS 1Ch 探索組合。 || Map the NVMe registers, read VS/CAP, select legal MPS/CSS/AMS and ready mode, then configure queues. If IOCSS=1, discover combinations with Identify CNS 1Ch after enabling.
得到可用的配置範圍，不是 CQE。例：MQES=03FFh 表示最多 1024 slots；DSTRD=2 表示相鄰 Doorbell 間距 16 bytes。 || The result is configuration information, not a CQE. For example, MQES=03FFh means up to 1024 slots; DSTRD=2 means adjacent doorbells are 16 bytes apart.
讀唯讀 Register 沒有 Invalid Field CQE。後續若把不支援值寫入 CC.MPS／AMS，規範可定義為 undefined behavior，不能要求固定錯誤碼。 || Reading read-only registers has no Invalid Field CQE. Later programming unsupported CC.MPS/AMS values can be undefined behavior, not a condition with a guaranteed error completion.
將 CAP.CSS 接到 CC.CSS 與 Identify 的 command-set 組合；將 MQES 接到 Create Queue 的 QSIZE。Admin Queue 的 4096-slot 上限另看 AQA，不把兩個上限混用。 || Cross-check CAP.CSS against CC.CSS and Identify combinations, and MQES against Create Queue QSIZE. Admin queues have their separate 4096-slot AQA limit.
先檢查位元位置、little-endian 讀取及 zero-based 編碼；MQES=1023 不是只能放 1023 個實體 slots。 || First check bit positions, little-endian decoding and zero-based encoding. MQES=1023 does not mean only 1023 physical slots.
''', {12:'CAP／VS 是能力與版本 Register。Controller Reset 後重新讀它們，再重設 CC 的選擇；不要將唯讀能力當成需寫回的設定。 || CAP/VS are capability and version registers. Re-read them after Controller Reset before configuring CC; do not write capabilities back as settings.',13:'NVM Subsystem Reset 後重新確認 Register 可存取及版本／能力，尤其重設同時啟用新韌體時。 || Rediscover register accessibility and capabilities after NVM Subsystem Reset, especially if it also activates firmware.',14:'Power Cycle 後重新探索 CAP／VS；本次讀取沒有需要保存的 Host 設定。 || Rediscover CAP/VS after a power cycle; the read itself creates no host setting to persist.',15:'讀取不改變其他 controller 或 namespace；不同 controller 可以有不同能力，不能用一份快照代替全部。 || Reads do not change another controller or namespace. Controllers may differ in capability, so one snapshot is not a substitute for all of them.'})

add(2,'AQA、ASQ、ACQ 與 CC 各欄位應按照什麼順序設定？設定錯誤時可能發生什麼？ || In what order are AQA, ASQ, ACQ and CC programmed, and what happens if they are wrong?', 'register',['adminreg','cc','init'],'''
讓 controller 在 Enable 時就能找到合法的 Admin SQ／CQ；先有記憶體和指標，再允許處理命令。 || Provide valid Admin SQ/CQ storage before enabling the controller. Establish memory and pointers before allowing command processing.
影響此 controller 的管理介面。錯誤 queue 位址可能使所有後續 Identify、Get Features 都無法正常完成。 || This controls the controller's management interface. A wrong queue address may prevent every subsequent Identify or Get Features from completing.
讀 CAP 的 MPS 範圍、CSS、AMS、CRMS，並使用 AQA 的 Admin queue 長度限制。 || Check CAP's MPS range, CSS, AMS and CRMS, together with AQA's Admin queue limits.
AQA.ASQS／ACQS 是 entries−1；ASQ／ACQ 是對齊 CC.MPS 的實體起始位址。CC 設 CSS、MPS、AMS、CRIME；NVM I/O 的 IOSQES=6、IOCQES=4。 || AQA.ASQS/ACQS encode entries−1. ASQ/ACQ contain physical bases aligned to CC.MPS. Configure CSS, MPS, AMS and CRIME in CC; NVM I/O uses IOSQES=6 and IOCQES=4.
等待前次重設的 RDY=0；配置連續 Admin queue 記憶體，清 Admin CQ Phase；在 EN=0 時寫 AQA／ASQ／ACQ 與合法 CC 設定；設 EN=1 後等待 RDY=1。I/O entry size 必須在 Create I/O Queue 前設定。 || Wait for the previous reset to reach RDY=0. Allocate contiguous Admin queues and clear Admin CQ phases. Program AQA/ASQ/ACQ and legal CC fields with EN=0, then enable and wait for RDY=1. Set I/O entry sizes before Create I/O Queue.
Admin queue 可用，Host 可提交 Identify。這不表示 I/O queue 已自動建立，也不表示所有媒體在 independent mode 中已 ready。 || The Admin queues become usable for Identify. I/O queues are not automatically created, and independent mode does not imply that every medium is ready.
AQA size=0 後 Enable、EN=1 時改 MPS、不支援 MPS／AMS 等有 undefined 結果；不能替這些 Register 誤用指定 Invalid Field CQE。 || Enabling with an AQA size of zero, changing MPS while enabled or selecting unsupported MPS/AMS has undefined results. Do not invent Invalid Field CQEs for these register violations.
先驗 Register 編碼，再驗 Admin CQ 可收到正確 CID 的 Identify 回覆；只看到 CC.EN=1 不足以證明初始化完成。 || Validate register encodings and then a correctly identified Identify completion. CC.EN=1 alone does not establish successful initialization.
先檢查 ASQ／ACQ 是裝置可使用的位址、頁面對齊與配置長度；不要拿一般程式的虛擬位址直接當 queue base。 || First check device-usable queue addresses, page alignment and allocation length. An ordinary process virtual address is not automatically a valid queue base.
''')

add(3,'Host 設定 CC.EN 後，應如何根據 CAP.TO 與 CSTS.RDY 判斷 Controller 是否成功 Enable？ || How does a host judge enable completion using CC.EN, CSTS.RDY and the timeout fields?', 'register',['cap','crto','ready','init'],'''
區分「要求啟用」與「已可處理命令」，並避免 Host 用錯逾時而過早重設。Base 2.4 需要把 CRTO 納入判斷。 || Separate the enable request from readiness and avoid premature recovery caused by a wrong timeout. Base 2.4 requires considering CRTO as well.
判斷目標 controller 的啟用；媒體是否可用還取決於 Ready Mode。 || This establishes readiness of the target controller; media availability also depends on the selected ready mode.
讀 CAP.CRMS、CC.CRIME、CRTO.CRWMT／CRIMT 與 CAP.TO；不可只假設 CAP.TO 足以表示所有 Enable 等待時間。 || Read CAP.CRMS, CC.CRIME, CRTO.CRWMT/CRIMT and CAP.TO. CAP.TO alone does not cover every enable timeout.
CC.EN 由 0→1 是計時起點；CSTS.RDY 是觀察值。CRTO 單位為 500 ms：With Media 用 CRWMT，Independent 用 CRIMT 判 RDY，再以 CRWMT 判媒體期限。 || Start timing at CC.EN 0→1 and observe CSTS.RDY. CRTO units are 500 ms: use CRWMT for With Media, CRIMT for Independent readiness, and CRWMT for its media deadline.
記錄模式與啟用時間，poll RDY／CFS；RDY=1 後按該模式送合法命令。初始化失败處理另有要求，不可把每個 RDY=1 都解讀成媒體健康。 || Record mode and enable time, poll RDY/CFS, then issue commands permitted by that mode. Initialization-failure rules also apply; RDY=1 is not an unconditional media-health verdict.
正常情況在適用期限內 RDY=1。例：CRIMT=2、CRWMT=20，分別是 1 s 的介面就緒期限與 10 s 的媒體期限，兩者都從 Enable 起算。 || Normally RDY becomes 1 within the applicable deadline. CRIMT=2 and CRWMT=20 mean 1 s for interface readiness and 10 s for media readiness, both measured from enable.
Register 啟用沒有 CQE。媒體尚未 ready 時，僅符合條件的命令可回 Namespace Not Ready（SCT=0, SC=82h）或 Admin Command Media Not Ready（0/24h）。 || Register enabling has no CQE. While media is unready, eligible commands may return Namespace Not Ready (SCT=0, SC=82h) or Admin Command Media Not Ready (0/24h).
把時間軸、CRIME、命令種類與回傳 Status 一起核對。Figure 84 列出的 Admin 命令及限制，不能擴張成所有 Admin 都可暫時拒絕。 || Correlate timing, CRIME, command type and status. Figure 84's eligible Admin commands and restrictions do not permit rejecting every Admin command temporarily.
先檢查用了哪個 timeout、起算點與 500 ms 單位；不要在 RDY=1 時把媒體等待時間重新從零計算。 || First check timeout selection, starting time and the 500 ms unit. Do not restart the media deadline when RDY becomes 1.
''',{8:'Register 啟用本身無 DNR／More。Independent mode 合法等待期間的媒體未就緒回覆允許 DNR=0；超過 CRWMT 不得繼續用同一暫時性理由回報 DNR=0。More 依有無 Error Information 補充資訊設定。 || Enabling has no DNR/More. Eligible media-not-ready responses may have DNR=0 during the allowed Independent-mode interval; that transient explanation cannot continue with DNR=0 beyond CRWMT. More reflects additional Error Information.',11:'符合 §3.5.4.1 的初始化期限失敗時，若支援 PEL，須記錄 NVM Subsystem Hardware Error Event，錯誤原因為 Controller Ready Timeout Exceeded。這不是每次成功 Enable 都記一筆。 || For an initialization-deadline failure meeting §3.5.4.1, a controller supporting PEL shall record an NVM Subsystem Hardware Error Event with Controller Ready Timeout Exceeded. This is not a record for every successful enable.'})

add(4,'Host 清除 CC.EN 後，應如何判斷 Controller 是否成功 Disable？尚未 Disable 完成時能否重新 Enable？ || How is disable completion detected, and may the host re-enable before it completes?', 'register',['cc','cap','reset'],'''
確保舊命令處理已停止，才能安全開始下一輪 controller 初始化。 || Establish that old command processing has stopped before beginning another initialization lifetime.
清 EN 觸發此 controller 的重設，包括所有 I/O queue；不是只暫停一條 SQ。 || Clearing EN resets this controller and all its I/O queues; it does not merely pause one SQ.
CAP.TO 定義清 EN 後等待 RDY 由 1→0 的最壞等待時間；同時保留 CC／CSTS 快照。 || CAP.TO defines the worst-case wait for RDY 1→0 after EN is cleared. Preserve CC/CSTS snapshots too.
只在已啟用且 RDY=1 的正常條件下啟動 EN 1→0；觀察 RDY=0 才代表 controller 已可重新 Enable。 || In the normal enabled state, initiate EN 1→0 with RDY=1; RDY=0 indicates readiness to enable again.
停止新增提交，清 EN，poll RDY；等 RDY=0 後重整 Admin CQ 與 Host 追蹤，設定 CC，再設 EN。 || Stop new submissions, clear EN and poll RDY. Once zero, reinitialize Admin CQ and host tracking, configure CC and enable again.
成功停用的證據是 RDY=0，不是收齊每一筆舊命令 CQE。舊 I/O queue 已失效。 || RDY=0 establishes disable completion; receiving a CQE for every old command is not required. Old I/O queues are invalid.
在 RDY 仍為 1 時把 EN 由 0→1，結果 undefined。不是規範要求回 Command Sequence Error 的 Admin 命令錯誤。 || Setting EN 0→1 while RDY remains 1 has undefined results. This is not an Admin request requiring Command Sequence Error.
核對 EN／RDY 轉移及舊 queue 不再被使用；不能用舊 queue 上偶然看見的資料證明它可繼續工作。 || Check EN/RDY transitions and retirement of old queues. Residual data in an old queue does not prove it is reusable.
先看是不是清 EN 後立刻設回 1，或把 CAP.TO 當成毫秒值直接使用。 || First check for an immediate re-enable or interpretation of CAP.TO as plain milliseconds.
''')

add(5,'Host 能否在 CSTS.RDY 為 0 時送出 Command 或更新 Doorbell？ || May a host submit commands or update doorbells while CSTS.RDY is zero?', 'register',['qattr','queue','cc','pcie'],'''
將「在 Host 記憶體準備 SQE」與「正式提交命令」分開；Doorbell 是提交邊界，不能提早使用。 || Distinguish preparing an SQE in host memory from submitting it. A doorbell is the submission boundary and cannot be used prematurely.
適用此 PCIe controller 的 Admin 及 I/O 提交；先配置 Admin queue Register 是初始化的一部分，與送命令不同。 || This applies to Admin and I/O submission on this PCIe controller. Configuring Admin queue registers during initialization is different from command submission.
用 CSTS.RDY、CC.EN 及該 queue 是否存在判斷。RDY=1 仍須確認 queue 已建立及 shutdown 狀態。 || Check CSTS.RDY, CC.EN and queue existence. Even RDY=1 requires a created queue and consideration of shutdown state.
SQ Tail Doorbell 通知新命令；CQ Head Doorbell 通知已消費完成。它們不是讓 controller 變 ready 的命令。 || SQ Tail announces submissions; CQ Head announces consumed completions. Neither is a command for making the controller ready.
等待 RDY=1，確認 queue 的有效生命週期，先讓 SQE 對裝置可見，再更新 SQ Tail。 || Wait for RDY=1 and a valid queue lifetime, make the SQE visible to the device, then update SQ Tail.
正確提交後 controller 才能取得命令；準備好記憶體但沒更新 Tail，還不能算命令已提交。 || The controller can fetch a correctly submitted command. Prepared memory without an updated tail is not yet a submission.
違反 ready／queue 使用前提，不可期待固定 CQE；停用狀態本來就不能依賴 Admin Queue 回覆錯誤。 || Violating readiness or queue-lifetime preconditions has no guaranteed CQE. A disabled Admin Queue cannot be relied upon to report the misuse.
若看見 EN=1、RDY=0 與超時，先判初始化階段；不要把尚未合法提交的 Identify 當作裝置不支援 Identify。 || EN=1, RDY=0 and a timeout first indicate an initialization-state issue; an illegally early Identify is not evidence that Identify is unsupported.
先比對 Doorbell 寫入時間與 RDY 變成 1 的時間，再檢查 queue 建立成功時間。 || First compare doorbell timing with the RDY transition, then with successful queue creation.
''')

add(6,'CSTS.CFS 代表什麼？Controller 初始化失敗或進入 Fatal 狀態時，Host 應如何恢復？ || What does CSTS.CFS mean, and how should the host recover from initialization failure or a fatal state?', 'register',['cc','fatal','ready','reset'],'''
CFS 是 controller 發生嚴重故障的狀態指示，不是單一 Read／Write 的一般失敗碼。 || CFS indicates a serious controller failure, not an ordinary error code for one Read or Write.
可能影響該 controller 整體命令服務。CFS 與某個 namespace 的媒體錯誤不能互相替代。 || The failure may affect controller-wide command service. CFS and an individual namespace media error are not interchangeable.
CSTS.CFS 與 RDY、CC.EN、適用 timeout 一起觀察；沒有一個 Identify 選配位元能讓 Host 忽略 CFS。 || Observe CSTS.CFS with RDY, CC.EN and the applicable timeout. No Identify optional-capability bit permits ignoring CFS.
先保存 Register 與已取得的 CQE／Log；若管理路徑仍可用再取診斷，不能無限等待不可能回覆的 Get Log Page。 || Preserve registers and available CQEs/logs first. Collect diagnostics if the Admin path still works, without waiting indefinitely for an inaccessible Get Log Page.
依故障及控制介面可達性執行 Controller Level Reset，等待合法狀態轉移，再重新初始化。若控制介面無回應，交由平台恢復；不把所有故障都保證成一次 CC.EN 重設即可修好。 || Perform Controller Level Reset as appropriate to the failure and accessible interface, then reinitialize. An unresponsive interface requires platform recovery; a CC.EN reset is not guaranteed to repair every fault.
恢復後需再次驗證 RDY、Identify 與新 queue 的命令完成；CFS 消失本身不是資料完整性驗證。 || Verify RDY, Identify and command completion on new queues after recovery. Clearing CFS alone does not validate data integrity.
若仍能完成受影響命令，Internal Error（SCT=0, SC=06h）可能適用；無法經 CQE 溝通的嚴重故障可能設定 CFS，不能要求每筆都留下 CQE。 || Internal Error (SCT=0, SC=06h) may apply when affected commands can still complete. Serious failure preventing CQE communication may set CFS; do not require a CQE for every command.
把同一時間的 CFS、初始化期限與硬體錯誤紀錄核對；不要把一次命令 Invalid Field 升級解釋為 controller fatal。 || Correlate CFS, initialization deadlines and hardware records at the same time. One Invalid Field completion is not itself controller-fatal evidence.
先確認 Register 讀取仍有效，以及 CFS 真的是 1；不可將失效讀取的全 1 值直接解碼成每個狀態位都成立。 || First confirm valid register access and an actual CFS value of 1. An all-ones failed read is not evidence that every status bit is asserted.
''')

add(7,'Controller 初始化後可能進入哪些 Ready Mode？Host 應如何處理暫時或限制性的 Ready 狀態？ || Which ready modes exist, and how should the host handle limited readiness?', 'register',['ready','crto','cc'],'''
讓管理命令可以在媒體初始化尚未完成前開始，但仍有明確的媒體就緒期限。 || Allow management work before media initialization finishes while retaining an explicit media-readiness deadline.
兩種模式是 Controller Ready With Media 與 Controller Ready Independent of Media；不是新增一組任意的 degraded-ready 編碼。 || The modes are Controller Ready With Media and Controller Ready Independent of Media, not arbitrary degraded-ready encodings.
CAP.CRMS.CRWMS／CRIMS 表示支援；CAP.CRMS=11b 時可用 CC.CRIME 選擇模式。 || CAP.CRMS.CRWMS/CRIMS advertise support. With CAP.CRMS=11b, CC.CRIME selects the mode.
CRIME=0 選 With Media；CRIME=1 選 Independent。CSTS.RDY、CRTO.CRIMT／CRWMT 及 Figure 84 的命令分類共同決定當下可做什麼。 || CRIME=0 selects With Media; CRIME=1 selects Independent. RDY, CRTO.CRIMT/CRWMT and Figure 84's command classes determine permitted work.
在 Enable 前選模式。Independent 的 RDY=1 後先做不依賴媒體的探索，媒體命令依暫時性 Status 延後，並追蹤自 Enable 起的 CRWMT。 || Select before enable. After Independent-mode RDY=1, perform media-independent discovery; defer eligible media operations based on transient status and track CRWMT from enable.
With Media 正常完成時可處理所要求的媒體存取；Independent 的 RDY=1 只先滿足介面及適用命令就緒，不代表所有 namespace ready。 || Normal With Media readiness includes required media readiness. Independent RDY=1 initially establishes interface and eligible-command readiness, not readiness of every namespace.
符合條件時可回 0/82h 或 0/24h；0/24h 只限 Independent mode 的合適 Admin 命令。媒體期限後仍用 DNR=0 表示暫時等待，不符合該期限規則。 || Eligible cases may return 0/82h or 0/24h. The latter is restricted to appropriate Admin commands in Independent mode. Continuing the same transient DNR=0 explanation beyond the media deadline violates that timing rule.
同時核對 CAP 宣告、CC 選擇、timeout 與命令行為。CSTS.PP 是另一種暫停處理指示，不是第三個 Ready Mode。 || Cross-check CAP support, CC selection, timeouts and behavior. CSTS.PP is a separate processing-pause indication, not a third ready mode.
先問正在失敗的命令是否需要媒體，再看它是否真的屬 Figure 84 允許的種類。 || First determine whether the failing command needs media and whether Figure 84 permits that response for it.
''',{8:'本題的 Register 讀寫沒有 DNR／More；媒體未就緒的 CQE 則按條件處理。在允許等待期間可用 DNR=0，CRWMT 後不得繼續用同一暫時性理由；More 仍表示 Error Information 的額外資訊。 || Register accesses have no DNR/More. Eligible media-not-ready CQEs may use DNR=0 during the permitted interval, not indefinitely after CRWMT. More still identifies additional Error Information.',11:'若符合 §3.5.4.1 的初始化失敗條件且支援 PEL，須記錄 Controller Ready Timeout Exceeded 的 NVM Subsystem Hardware Error Event。正常選擇某種 Ready Mode 本身不要求此錯誤事件。 || An initialization failure meeting §3.5.4.1 requires a Controller Ready Timeout Exceeded hardware event when PEL is supported. Normal selection of a ready mode does not require that error event.'})

add(8,'Controller Enable、Disable、Controller Reset、NVM Subsystem Reset 與 Shutdown 有什麼差異？ || How do Enable, Disable, Controller Reset, NVM Subsystem Reset and Shutdown differ?', 'register',['cc','shutdown','reset'],'''
分開「開始服務」「停止並重設」與「為移除電源做準備」，避免用 Reset 代替正常 Shutdown。 || Separate starting service, stopping/resetting and preparing for power removal. Reset is not a replacement for orderly shutdown.
Enable／CC.EN 清除針對 controller；NVM Subsystem Reset 涵蓋規定的 subsystem／domain 範圍；Shutdown 另有 controller 與 subsystem 類型。 || Enable and CC.EN clearing target a controller. NVM Subsystem Reset covers its defined subsystem/domain scope. Shutdown also distinguishes controller and subsystem types.
CAP.NSSRS 確認 NSSR 支援；CAP 的 shutdown 能力與 CSTS.ST 區分 Shutdown 範圍。 || CAP.NSSRS advertises NSSR support; shutdown capability and CSTS.ST distinguish shutdown scope.
Enable：EN 0→1。Controller Reset：EN 1→0。NSSR.NSSRC 寫 4E564D65h 觸發支援的 subsystem reset。正常 controller shutdown 用 CC.SHN=01b，觀察 CSTS.SHST=10b。 || Enable is EN 0→1; Controller Reset is EN 1→0. Writing 4E564D65h to supported NSSR.NSSRC requests subsystem reset. Normal controller shutdown uses CC.SHN=01b and waits for SHST=10b.
正常移除電源前協調 I/O，再通知 Shutdown 並等待完成；故障恢復才選合適 Reset，之後重建操作環境。 || Coordinate I/O, notify shutdown and await completion before normal power removal. Select a suitable reset for recovery, then rebuild the operating environment.
Enable 看 RDY=1；Disable／Reset 完成看相應狀態；Shutdown 看 SHST=10b。Shutdown 完成不是所有 Register 都回到 reset value。 || Enable uses RDY=1; disable/reset uses its corresponding state; shutdown uses SHST=10b. Completed shutdown does not mean every register has its reset value.
Register 操作沒有統一 CQE。Shutdown 中 controller 可對命令回 Commands Aborted due to Power Loss Notification（0/05h）；不能將此碼套用到所有 Reset 的未完成命令。 || Register operations have no common CQE. During shutdown, commands may return Commands Aborted due to Power Loss Notification (0/05h); that code is not universal for commands interrupted by reset.
記錄觸發方法與 scope，再對照保留值；只在紀錄寫「reset」不足以解釋 AQA、PCIe 狀態與 Feature 為何不同。 || Record the trigger and scope before comparing retained state. A log saying only “reset” cannot explain differences in AQA, PCIe state or features.
先辨認到底寫了 EN、SHN 還是 NSSRC，以及是否有平台重設同時發生。 || First identify whether EN, SHN or NSSRC was written and whether a platform reset occurred concurrently.
''')

add(9,'Controller Reset 後，哪些 Register、Admin Queue、Feature 與 I/O Queue 需要重新設定？ || What must be reinitialized after Controller Reset?', 'register',['reset','feature','setfeat','adminreg'],'''
建立新一輪有效操作環境，避免沿用上一輪 queue 指標、Phase 與尚未完成的命令。 || Establish a fresh operating lifetime rather than reusing old pointers, phases and outstanding commands.
本題專指清 CC.EN 觸發的 Controller Reset；FLR、NVM Subsystem Reset 的 Register 保留規則不能混入。 || Here Controller Reset specifically means clearing CC.EN. Do not mix in the register-retention rules of FLR or NVM Subsystem Reset.
看 §3.7.2 的例外清單與個別 Register Reset 欄，Feature 再看 scope、saveable、Figure 126／127 與 466。 || Use §3.7.2's exceptions and register Reset columns; for features examine scope, saveability and Figures 126/127/466.
AQA／ASQ／ACQ、指定 PMR Register、CMBMSC 在此重設中不清除；Admin queue 指標仍會 reset。I/O SQ／CQ 全部刪除，CC 選擇需重新配置。可保存 Feature 按重設範圍恢復 Saved（沒有 Saved 則 Default）；不可保存者另看持續性，HMB 需重新配置。 || This reset preserves AQA/ASQ/ACQ, specified PMR registers and CMBMSC, but still resets Admin Queue pointers. All I/O queues are deleted and CC selections require reconfiguration. Saveable features restore Saved, or Default without Saved, under reset-scope rules; unsaveable features use their persistence rules. Reconfigure HMB.
等 RDY=0；確認保留的 Admin 記憶體仍有效，將 Admin CQ Phase 初始化成 0；配置並 Enable；重查必要能力、Feature，重新協商 Number of Queues，再建立 CQ→SQ。 || Wait for RDY=0, verify retained Admin memory remains valid and initialize Admin CQ phases to zero. Configure and enable, rediscover needed capabilities/features, renegotiate Number of Queues, then create CQs before SQs.
新命令在新 queue 生命週期正確完成。即使使用相同 QID／位址，也不能把它當成舊 queue 繼續。 || New commands complete in the new queue lifetime. Reusing a QID or address does not resume the old queue.
舊 CQE 沒有可要求的統一「Reset Status」；重建時的非法 QID／大小依 Create 命令判斷。對舊記憶體誤寫 Doorbell 不能期待正常恢復。 || There is no universal Reset Status owed for every old command. Invalid reconstruction parameters follow Create-command rules; writing doorbells for stale memory is not a recovery method.
前後比對 Register、Get Features 與實際 Queue 能力。尤其 AQA 值保留與 Admin CQ 內容有效，是不同事情。 || Compare register values, Get Features and actual queue capability. Retention of AQA is distinct from validity of Admin CQ contents.
先檢查 Host 是否清除舊 outstanding 對照與重新初始化 Phase；相同 CID 不應對到前一輪命令。 || First check retirement of old outstanding tracking and phase reinitialization. A reused CID must not resolve to a command from the previous lifetime.
''')
