from scripts.nvme_scenarios import case

case('maintenance',('如何查詢單一 namespace 是否支援 Overwrite Sanitize？','Can a single namespace support Overwrite Sanitize?'),
('需求是「只清除 NSID=7，使用 Sanitize Namespace with Overwrite」。Identify 顯示 OWS=1，是否已足夠？','The requirement is to sanitize only NSID=7 using Sanitize Namespace with Overwrite. Is Identify OWS=1 sufficient?'),
[('Base Revision 2.4；SANICAP.OWS=1、CES=1；假設 Commands Supported and Effects 亦回報 Sanitize Namespace 受支援。','Base Revision 2.4; SANICAP.OWS=1 and CES=1; assume Commands Supported and Effects also reports Sanitize Namespace support.'),('需求明確限制單一 namespace，不允許把清除範圍擴大成整個 NVM subsystem。','The requested target is one namespace; expanding sanitization to the entire NVM subsystem is not permitted.')],
('先查 Base §5.2.27 允許的操作 → Identify CNS=01h 的 SANICAP → Commands Supported and Effects 的命令支援 → 目標 namespace 狀態。','First check operations defined by Base §5.2.27 → Identify CNS=01h SANICAP → command support in Commands Supported and Effects → target namespace state.'),
[('這版規格的 Sanitize Namespace 只有 Crypto Erase 這一種開始清除的操作。Figure 454 的 SANACT=011b（Overwrite 在另一個命令使用的值）在此屬於 Reserved。因此原需求無法由此標準命令組合實現。','This revision defines only Crypto Erase as a starting operation for Sanitize Namespace. In Figure 454, SANACT=011b—the value used for Overwrite in the other command—is reserved. The requested combination is therefore not provided by this standard command.'),('SANICAP.OWS=1 表示支援 Overwrite sanitize，不會替 Sanitize Namespace 增加新的合法 action。Subsystem Sanitize 與 Sanitize Namespace 必須先分清命令與作用範圍，再解能力。','SANICAP.OWS=1 reports Overwrite sanitize support; it does not add a legal action to Sanitize Namespace. Distinguish command and target scope before interpreting the capability.'),('應回報「單一 namespace 的 Overwrite Sanitize 不在此版標準命令定義內」，並請需求端決定是否接受單一 namespace Crypto Erase 等其他方式。不能偷偷改送 subsystem Overwrite，也不能用一般 Write 覆寫冒充 Sanitize 保證。','Report that single-namespace Overwrite Sanitize is not defined by this revision, then resolve whether an alternative such as namespace Crypto Erase satisfies the requirement. Do not silently substitute subsystem Overwrite or claim ordinary Writes provide Sanitize guarantees.')],
'B338 B454 B451 B217','B@5.2.27:478-479 B454:479 B338:387-388 B451:476-477 B217:254-255')

case('maintenance',('一個 namespace 已清除，是否整台都清除了？','Does one sanitized namespace establish subsystem-wide sanitization?'),
('驗證程式拿 NSID=7 的成功結果，宣稱整個 subsystem 已清除，而且還能再啟動 4 個並行操作。哪些推論越過了資料範圍？','A validator uses NSID=7’s success to claim subsystem sanitization and capacity for four additional concurrent operations. Which claims exceed the evidence?'),
[('LID=81h、NSID=7：STNSID=7、SOS=1；MNSOIP=FFFFFFFFh。','LID=81h, NSID=7: STNSID=7, SOS=1, MNSOIP=FFFFFFFFh.'),('另讀 subsystem target（NSID=0）的 log：MNSOIP=4；尚未盤點其他進行中的 namespace sanitize。','A separate subsystem-target query (NSID=0) reports MNSOIP=4; other ongoing namespace sanitizations have not been inventoried.')],
('Get Log Page LID=81h，分清 NSID=0／FFFFFFFFh 的 subsystem target 與 allocated NSID 的 namespace target。','Get Log Page LID=81h, distinguishing subsystem targets NSID=0/FFFFFFFFh from allocated-NSID namespace targets.'),
[('STNSID=7 確認這份回覆是 namespace 7 的狀態；SOS=1 表示相應最近 sanitize 已成功且 state machine 回到 Idle。它沒有宣告其他 namespace 也完成相同操作。','STNSID=7 confirms the namespace target. SOS=1 reports successful sanitization for that target with its state machine in Idle; it says nothing equivalent about other namespaces.'),('namespace target 的 MNSOIP 按規則為 FFFFFFFFh，不能解成可並行數十億次。並行上限需讀 subsystem target；其值 4 是最多同時進行 4 個，不是現在剩餘 4 個。','For a namespace target, MNSOIP is required to be FFFFFFFFh; it does not permit billions of concurrent operations. The subsystem value four limits total concurrent operations, not four remaining slots.'),('要算目前餘額，還需完整且時間一致的進行中操作資訊，並考慮並行管理造成的變動。即使有名額，命令被接受也仍須另查目標 log 的最終結果。','Remaining capacity requires complete, time-consistent information about ongoing operations and concurrent management changes. Even an available slot and accepted command still require target-specific final-result verification.')],
'B312 B454','B312:340-345 B@5.2.27:478-479')

case('maintenance',('新韌體已在 slot 2，現在跑的就是它嗎？','Does firmware stored in slot two mean it is running?'),
('更新工具看到 slot 2 的新版本字串，便把升級標示為已生效。請用目前與下一次啟用欄位重新判讀。','An updater sees a new version string in slot two and marks activation complete. Reinterpret current and next-active fields.'),
[('Firmware Slot Information：CAFS=1、NAFS=2；FRS1="A100"、FRS2="B200"。','Firmware Slot Information: CAFS=1, NAFS=2; FRS1="A100", FRS2="B200".'),('Identify Controller.FR="A100"；FRMW.FAWR=0；沒有後續可啟用該版本的 reset 紀錄。','Identify Controller.FR="A100"; FRMW.FAWR=0; no later reset capable of activation is recorded.')],
('Identify CNS=01h 的 FR／FRMW → Get Log Page LID=03h 的 AFI 與 slot revisions → Firmware Commit 的 action／status 與 reset 紀錄。','Identify CNS=01h FR/FRMW → LID=03h AFI and slot revisions → Firmware Commit action/status and reset trace.'),
[('CAFS=1 與 FR=A100 支持目前仍執行 slot 1 的版本。FRS2=B200 證明 slot 2 有該 revision，不等於 controller 現在已執行它。','CAFS=1 and FR=A100 support that slot one’s revision is still running. FRS2=B200 identifies a revision in slot two, not that it is currently executing.'),('NAFS=2 指向下一次能造成啟用的 Controller Level Reset 所要啟用的 slot。FAWR=0 表示不支援無 reset 啟用；不能把任何未分類的 reset 都當作已滿足啟用條件。','NAFS=2 identifies the slot scheduled for the next Controller Level Reset capable of activation. FAWR=0 means no reset-free activation support; an unspecified reset is not enough to establish activation.'),('完整驗證應在適用的啟用步驟之後重新讀 FR 與 CAFS，再與預期版本比對。本題只指出尚未生效的證據，不要求現在執行 reset 或下載韌體。','After the applicable activation step, reread FR and CAFS and compare against the intended revision. This exercise identifies evidence of pending activation without performing a reset or download.')],
'B215 B187 B338','B215:252 B187:229 B338:366-367,380 B@5.2.9:228-231')

case('maintenance',('Format 指定 NSID，就只會影響那一個嗎？','Does a Format NSID always confine its effects to one namespace?'),
('要求是只對 NSID=7 做 secure erase；審查時看到命令 NSID=7 就放行。還少查哪一組 scope？','A request intends secure erase only for NSID=7. Review checks the command NSID and accepts it. Which scope evidence is missing?'),
[('OACS.FNVMS=1；FNA.FNS=0、SENS=1、FNVMBS=0。','OACS.FNVMS=1; FNA.FNS=0, SENS=1, FNVMBS=0.'),('擬定 Format NVM：NSID=7、SES=1；其他格式欄位均合法，本題不執行命令。','Proposed Format NVM: NSID=7, SES=1; other format fields are valid. The command is not executed in this exercise.')],
('Identify CNS=01h 的 OACS／FNA → Format NVM 的 NSID、SES 與格式參數。','Identify CNS=01h OACS/FNA → Format NVM NSID, SES and format parameters.'),
[('FNS 與 SENS 回答不同問題：格式變更的範圍與 secure erase 的範圍。本例 FNS=0 不能抵消 SENS=1；所要求的 secure erase 會作用於 subsystem 所有 namespaces。','FNS and SENS answer different questions: formatting scope and secure-erase scope. FNS=0 does not cancel SENS=1; the requested secure erase affects all namespaces in the subsystem.'),('因此這組參數不符合「只清除 namespace 7」的需求。NSID 看起來很精確，仍須與 controller attributes 合併判讀，不能只憑命令目標欄位推定所有副作用的範圍。','The combination fails the requirement to erase only namespace seven. An explicit command NSID must still be interpreted with controller attributes; it does not by itself bound every effect.'),('FNVMBS 的位值方向也要照定義：1 表示不支援 FFFFFFFFh broadcast，不是支援。這題的重點是先做範圍判定，再決定是否有符合需求的操作方式。','FNVMBS also uses an easily misread direction: one means FFFFFFFFh broadcast is unsupported. Establish scope before deciding whether an operation meets the requirement.')],
'B338 B195 N91','B338:379,399 B195:234-235 N91:63')

case('maintenance',('不可保存的保護狀態，reset 後就會解除嗎？','Does an unsaveable protection feature clear on reset?'),
('工具看到 FID=84h 的 SVBL=0，就說 reset 會解除所有 namespace write protection。請比較兩個 namespace。','A tool sees SVBL=0 for FID=84h and claims a reset clears all namespace write protection. Compare two namespaces.'),
[('Get Features FID=84h、SEL=0：NSID=2 的 WPS=2；NSID=9 的 WPS=3。','Get Features FID=84h, SEL=0: NSID=2 has WPS=2; NSID=9 has WPS=3.'),('controller 支援這些狀態；計畫中的動作只是 Controller Level Reset，沒有斷電。','These states are supported; the planned action is only a Controller Level Reset, without a power cycle.')],
('Identify CNS=01h 查 NWPC → Get Features FID=84h、SEL=0 查各 namespace 目前 WPS → 對照 §8.1.18 的狀態持續規則。','Identify CNS=01h NWPC → Get Features FID=84h, SEL=0 for each current WPS → apply §8.1.18 state-persistence rules.'),
[('WPS=2 是 Write Protect Until Power Cycle，會跨沒有斷電的 Controller Level Reset 持續。因此題目的 reset 不能使 NSID=2 回到未保護；真正 power cycle 才是該狀態定義的解除條件。','WPS=2 is Write Protect Until Power Cycle and persists across Controller Level Reset without power cycling. The stated reset does not unprotect NSID=2; an actual power cycle is the defined release condition.'),('WPS=3 是 Permanent Write Protect，不能把 power cycle 當解除方法。可支援某種保護、允許進入保護、目前處在什麼狀態，是三個不同問題。','WPS=3 is Permanent Write Protect; a power cycle is not its release mechanism. Supported protection states, permission to enter them and current state are separate questions.'),('SVBL=0 描述 Feature 是否接受保存要求，不改寫狀態本身的持續規則。報告應保留 NWPC、必要的 WPC 許可與 WPS，不能由單一 saveable 位推論復原行為。','SVBL=0 describes whether the feature accepts a save request, not state persistence. Retain NWPC, relevant WPC permissions and WPS rather than deriving recovery behavior from one saveability bit.')],
'B541 B201 B338','B541:538 B201:238 B338:401 B@8.1.18:690-692')

case('maintenance',('Boot protection 的 0，和 namespace 的 0 一樣嗎？','Does zero mean the same for Boot and namespace protection?'),
('一個共用解碼器把所有 protection state=0 都顯示為未保護。用以下歷史命令與讀取結果，判斷會誤解哪裡。','A shared decoder displays every protection state zero as unprotected. Which interpretation fails for this command and response?'),
[('先前 Set Features FID=85h：BP0WPS=0、BP1WPS=0，成功。','A prior Set Features FID=85h used BP0WPS=0 and BP1WPS=0 and succeeded.'),('現在 Get Features FID=85h、SEL=0：BP0WPS=2、BP1WPS=4。','Current Get Features FID=85h, SEL=0 reports BP0WPS=2 and BP1WPS=4.')],
('按 FID 區分 Namespace Write Protection（84h）與 Boot Partition Write Protection（85h），再區分 Set 要求與 Get 回報。','Distinguish Namespace Write Protection FID=84h from Boot Partition Write Protection FID=85h, then distinguish Set requests from Get responses.'),
[('FID=85h 的 Set 值 0 是「不要求改變該 partition」，不是解鎖。兩個 0 的成功命令可能保持兩者原狀，不能拿它當作解除保護的證據。','For FID=85h, Set value zero requests no change for that partition, not unlocking. A successful all-zero request may leave both unchanged and is not evidence of protection removal.'),('目前 BP0WPS=2 表示 partition 0 為 Write Locked；BP1WPS=4 表示 partition 1 的保護由 RPMB 控制。4 是可回報的狀態，不能原樣當一般 Set 的要求值。','Current BP0WPS=2 means partition zero is Write Locked; BP1WPS=4 means partition one’s protection is controlled by RPMB. Four is a reportable state, not a general Set request value.'),('Get 不會以 0 表示這兩個 partition 的狀態，因此共用函式至少需要 FID 與方向。若還涉及 shared multi-domain partition，必須另查其特定限制，不能只套 namespace 的 WPS 表。','Get does not return zero as either partition’s state, so a decoder needs at least FID and direction. Shared multi-domain partitions have additional specific restrictions; the namespace WPS table cannot stand in for them.')],
'B542 B541','B542:539-540 B541:538')
