"""Definitions emitted locally once; field tables supply the detailed decoding."""
TERMS={
 'LPA':('Log Page Attributes，Identify Controller中回報log相關能力的欄位。','Log Page Attributes, the Identify Controller field advertising log capabilities.'),
 'PES':('Persistent Event Support，LPA內表示是否支援PEL的bit。','Persistent Event Support, the LPA bit advertising PEL.'),
 'PELS':('Persistent Event Log Size，最大PEL空間，以64KiB為單位。','Persistent Event Log Size, the maximum capacity in 64KiB units.'),
 'SEB':('Supported Events Bitmap，按事件種類宣告支援的位元圖。','Supported Events Bitmap, advertising support by event type.'),
 'TNEV':('Total Number of Events，本次回報實際包含的事件筆數。','Total Number of Events in this report.'),
 'TLL':('Total Log Length，這份回報包含header在內的總byte長度。','Total Log Length, the report size in bytes including its header.'),
 'LHL':('Log Header Length，log header中前20 bytes之後的長度。','Log Header Length, excluding the first20 bytes.'),
 'EHL':('Event Header Length，單筆event header中前3 bytes之後的長度。','Event Header Length, excluding the first three bytes.'),
 'EL':('Event Length，事件header之後VSI與ED合計的byte長度。','Event Length, counting VSI and ED after the event header.'),
 'VSIL':('Vendor Specific Information Length，可選廠商附加資料的byte長度。','Vendor Specific Information Length in bytes.'),
 'LREV':('Log Revision，整份log與共同event header的格式版本。','Log Revision, the outer log and common event-header revision.'),
 'ETSTP':('Event Timestamp，共同header內記錄事件發生時間的欄位。','Event Timestamp, the event time recorded in the common header.'),
 'SANICAP':('Sanitize Capabilities，清除方法、驗證及回報的支援能力。','Sanitize Capabilities, advertising methods, verification and reporting support.'),
 'SOS':('Status of Sanitize Operation，SSTAT內表示清除操作狀態的代碼。','Status of Sanitize Operation, the state code within SSTAT.'),
 'Persistent Event Log':('持久事件紀錄；保存subsystem重要事件的LID 0Dh紀錄。','The LID 0Dh history of significant subsystem events.'),
 'PEL':('Persistent Event Log，本篇的持久事件紀錄。','Persistent Event Log, the history examined in this report.'),
 'reporting context':('一次回報所用的事件集合、資料位置及讀取追蹤資訊；不是整份持久紀錄本身。','The event selection, locations and tracking information for one report, distinct from the underlying persistent history.'),
 'context':('本次讀取使用的回報內容與追蹤資訊；建立後新增的事件不加入其中。','The report selection and tracking state used by this retrieval; later events are excluded.'),
 'ACT':('Action，Get Log Page中選擇PEL讀取、建立或釋放的動作。','Action, selecting PEL read, establish or release operations.'),
 'GNUM':('Generation Number，用於比較分段讀取前後是否仍是同一代回報內容。','Generation Number, compared before and after multipart retrieval.'),
 'RCE':('Reporting Context Exists，表示處理命令前是否已存在context。','Reporting Context Exists, indicating a context already present when processing began.'),
 'ECRH':('Establish Context and Read Header，支援ACT3及GNUM的能力位。','Establish Context and Read Header, the capability for ACT3 and GNUM.'),
 'ET':('Event Type，事件種類代碼。','Event Type, the record’s type code.'),
 'ETR':('Event Type Revision，該種類事件內容的格式版本。','Event Type Revision, the type-specific payload revision.'),
 'ED':('Event Data，扣除共同header與廠商附加資訊後的事件內容。','Event Data, the type-specific content after the common header and optional vendor information.'),
 'VSI':('Vendor Specific Information，共同事件格式中可選的廠商附加資訊。','Vendor Specific Information, the optional addition in the common event format.'),
 'index':('項目編號；要連同表格規則判斷從0或1起算，與byte位置不同。','An entry number, with its own zero/one-based convention, distinct from a byte position.'),
 'offset':('相對指定起點的位移；本篇未另註明時以bytes計算，從0起算。','A displacement from the specified origin, in bytes from zero unless stated otherwise.'),
 'header':('資料前端的共同說明區，記載種類、大小、版本等讀取內容所需資訊。','The leading descriptive structure containing the type, size, revision and related interpretation data.'),
 'snapshot':('某個時間點保存的資料副本；後續狀態改變不會把它變成最新值。','A copy captured at one time, distinct from later current state.'),
 'power cycle':('斷電再上電的電源循環；不等同所有形式的reset。','A power-off/power-on cycle, not every form of reset.'),
 'SCT':('Status Code Type，完成狀態所屬的類型。','Status Code Type, the category of a completion result.'),
 'SC':('Status Code，指定SCT類型內的結果代碼。','Status Code within the selected SCT category.'),
 'Telemetry':('控制器或subsystem內部狀態的診斷資料；本篇事件只保存其header。','Diagnostic internal-state data; the event here preserves only its header.'),
 'FLBAS':('Formatted LBA Size，保存格式編號與metadata傳輸方式，不是直接記錄bytes大小。','Formatted LBA Size, encoding a format index and metadata transfer mode, not a literal byte size.'),
 'DPS':('End-to-end Data Protection Type Settings，資料保護資訊的類型及位置設定。','End-to-end Data Protection Type Settings, selecting protection-information type and position.'),
 'PI':('Protection Information，用於檢查資料完整性及關聯資訊的保護資料。','Protection Information used to check data integrity and associated information.'),
 'SFEL':('Set Feature Event Layout，指明事件內命令、資料buffer與完成值的位置。','Set Feature Event Layout, locating command words, buffer data and completion DW0.'),
 'AHEI':('Additional Hardware Error Information，依硬體錯誤子類選擇格式的附加資訊。','Additional Hardware Error Information, whose format depends on the error subtype.'),
 'NSHEEC':('NVM Subsystem Hardware Error Event Code，ET05內選擇硬體錯誤子類的代碼。','NVM Subsystem Hardware Error Event Code, selecting an ET05 subtype.'),
 'CDP':('Configurable Device Personality，可設定的裝置運作特性組合。','Configurable Device Personality, a configurable set of device operating characteristics.'),
 'freeze':('凍結設定變更；事件中的請求狀態與實際成功結果需分開判讀。','Freeze configuration changes; distinguish a request from successful application.'),
 'TCG':('Trusted Computing Group；此處Base把特定安全事件內容保留給其定義。','Trusted Computing Group, to which Base reserves the relevant security-event payload definition.'),
 'UUID':('Universally Unique Identifier；索引用來選擇對應的廠商資料定義。','Universally Unique Identifier; its index selects the corresponding vendor data definition.'),
}
