"""Worked capability lookup routes attached to existing canonical questions."""
from scripts.nvme_qa_model import COMMON, QUESTIONS, REFS, pair


def apply():
    byid={q['id']:q for q in QUESTIONS}
    byid[118]['title']=pair('如何查詢 Format、Sanitize 與 Sanitize Namespace 的支援能力？ || How is support for Format, Sanitize and Sanitize Namespace discovered?')
    REFS['adminsupport']='B|3.1.3.4 (Figure 28 PCIe I/O-controller rows and O/M/P note only)|71-73|28'

    def revise(n,values,refs=(),related=()):
        q=byid[n]
        q['answers'].update({i:pair(v) for i,v in values.items()})
        q['refs']=list(dict.fromkeys(q['refs']+list(refs)))
        q['related']=list(dict.fromkeys(q.get('related',[])+list(related)))

    def route(n,title,intro,rows,conclusion,refs):
        q=byid[n]
        q['lookup']=dict(title=pair(title),intro=pair(intro),
                        headers=[pair(s) for s in ['查詢步驟與原文位置 || Step and source location','要取出的資訊 || Information to retrieve','這一步能判斷什麼 || What this establishes']],
                        rows=[[pair(c) for c in row] for row in rows],
                        conclusion=pair(conclusion),refs=refs)
        q['refs']=list(dict.fromkeys(q['refs']+refs))

    revise(118,{
      3:'Format 查 OACS 與 FNA；Sanitize 查 SANICAP 的 CES、BES、OWS。要確認 Sanitize Namespace 命令本身，先由 Figure 28 找到 Admin Opcode 8Ch，再讀 LID05h 的對應 Admin entry，以 Figure 217 的 bit0（CSUPP）判讀。CSUPP 是命令支援宣告；SANICAP.CES、NVERS 則分別補充清除方法與 namespace 媒體驗證能力。 || Use OACS/FNA for Format and SANICAP CES/BES/OWS for Sanitize. For the Sanitize Namespace command itself, find Admin opcode8Ch in Figure28, then decode bit0 (CSUPP) of its Admin entry in LID05h using Figure217. CSUPP declares command support; CES and NVERS separately describe the method and namespace media-verification capability.',
      4:'Format NVM、Sanitize、Sanitize Namespace 的 Admin Opcode 分別是80h、84h、8Ch。這裡要送出的查詢命令是 Identify（06h）與 Get Log Page（02h）；Get Log Page 的 LID=05h 才選到命令支援表。不能把8Ch填進LID，也不能只查Get Log Page本身的CSUPP，就當成所有Log或所有管理命令都受支援。 || Format, Sanitize and Sanitize Namespace have Admin opcodes80h,84h and8Ch. Discovery submits Identify (06h) and Get Log Page (02h), with LID05h selecting the command table. Do not put8Ch in LID or treat support for Get Log Page itself as support for every log or management command.',
      5:'先確認查詢通道與Log支援，再讀正確entry；若CSUPP=1，才繼續查方法、參數與目標狀態。查詢過程只讀取資訊，不需要啟動清除。準備真的執行時，才進一步確認Active NSID、寫入保護、Sanitize狀態、並行上限與待啟用韌體限制。 || Establish query access and log support, read the correct entry, then check method, parameters and target state when CSUPP=1. Discovery requires no sanitize initiation. Before actual execution, additionally check active NSID, protection, sanitize state, concurrency and pending-firmware restrictions.',
      6:'Identify與Get Log Page成功，表示已取得可判讀的能力資料。若8Ch的CSUPP=1，可以回答「controller宣告支援Sanitize Namespace」；這不表示NSID=7現在一定能接受命令，更不表示資料已經清除。 || Successful Identify/Get Log Page provides capability evidence. CSUPP=1 for8Ch establishes advertised Sanitize Namespace support, not current eligibility of NSID7 or completed erasure.',
      7:'查詢LID05h不受支援時，Get Log Page一般以Invalid Log Page（1/09h）失敗；這時沒有有效的CSUPP可讀，不能當成CSUPP=0。真正提交不支援的Opcode，與受支援命令使用非法SANACT，是另外兩種條件，分別按Invalid Command Opcode（0/01h）與Invalid Field in Command（0/02h）判斷。 || An unsupported LID05h generally causes Invalid Log Page (1/09h), leaving no valid CSUPP result; it is not CSUPP=0. An unsupported submitted opcode and an invalid SANACT in a supported command are separate conditions using0/01h and0/02h respectively.',
      9:'這條路徑只讀Identify與能力Log，不會因查到支援就產生Sanitize開始或完成通知。其他同時發生的事件仍依各自條件處理。 || Reading Identify and capability logs does not initiate sanitization or generate its start/completion notices. Unrelated concurrent events retain their own rules.',
      10:'成功的能力查詢不會更新Sanitize Status為進行中，也不會替目標namespace清除資料。若查詢本身失敗，再依該CQE及Error Information規則追查；不能拿Sanitize背景結果代替查詢的完成結果。 || Successful capability discovery neither starts the Sanitize Status state machine nor erases target data. Diagnose a failed query from its own CQE/error information, separately from background sanitize outcomes.',
      11:'唯讀能力查詢不會建立Sanitize Start或Sanitize Completion的Persistent Event。這些紀錄屬於實際操作，不能因controller宣告支援，就期待PEL已有對應歷史。 || Read-only discovery does not create Sanitize Start or Completion persistent events. Support does not imply a history of performing the operation.',
      16:'交叉比對時，要保持controller、命令集與查詢時點一致。CSUPP=1但操作失敗時，先排除非法參數及目前狀態；CSUPP=0卻有同一命令的合法成功行為，才構成需要追查的支援宣告矛盾。SANICAP.OWS=1也不會把namespace Overwrite變成合法操作。 || Compare the same controller, command-set context and configuration period. With CSUPP=1, exclude invalid parameters/state before alleging inconsistency. CSUPP=0 with valid successful execution needs investigation. OWS=1 does not legalize namespace Overwrite.',
      17:'先確認讀的是LID05h的Admin區、Opcode8Ch那一筆，並且Get Log Page已成功。讀錯84h、漏掉位移單位，或把失敗查詢留下的buffer當成有效資料，都會讓支援結論出錯。 || First confirm a successful LID05h read and the Admin entry for8Ch. Selecting84h, using the wrong offset units or decoding a buffer from a failed query invalidates the support conclusion.'
    },['adminsupport','getlog','idcmd'],[81,126,134,135])
    # The question is now explicitly read-only discovery; it must not inherit
    # Format/Sanitize operation retention from the earlier comparison profile.
    for i in range(12,16):byid[118]['answers'][i]=COMMON['identify'][i]
    byid[118]['practice']=pair('需求：只透過查詢，確認controller是否支援Sanitize Namespace。先說明要找哪個Opcode、讀哪個Log、取哪個entry，以及支援位元在哪裡，再展開解答。 || Task: determine Sanitize Namespace support using queries only. Identify the opcode, log, entry and support bit before revealing the answer.')

    route(118,'查詢範例：從 Sanitize Namespace 名稱找到 CSUPP || Worked lookup: from Sanitize Namespace to CSUPP',
      '以下回傳值都是教學假設。使用同一個PCIe I/O controller、CC.CSS=000b及UUID Index=0；查詢成功後才解讀buffer。Figure 28是規格的命令清單，不是這台SSD的實測能力表。 || All values below are hypothetical. Use one PCIe I/O controller, CC.CSS=000b and UUID Index0; decode buffers only after successful queries. Figure28 is the specification’s command catalog, not the device’s measured capability list.',[
        ['1 · Figure 28，文件頁46／PDF 72 || 1 · Figure28, printed46/PDF 72','Sanitize Namespace → Admin Opcode=8Ch，支援要求為O（Optional）。 || Sanitize Namespace → Admin opcode8Ch; O means optional.','找到要查的命令與編碼。Optional表示實作可選，還不能判定這台controller有支援。 || Identifies the command and encoding. Optional does not establish this controller’s support.'],
        ['2 · Identify Controller，Figure 338，文件頁355、361～362／PDF 381、387～388 || 2 · Identify Controller, Figure338, printed355,361–362/PDF 381,387–388','CNS=01h；假設LPA.CSES=1、SANICAP.CES=1、NVERS=0。CSES是LPA bit1。 || CNS01h; assume LPA.CSES=1, SANICAP.CES=1 and NVERS=0. CSES is LPA bit1.','可以讀Commands Supported and Effects；有Crypto Erase能力，但沒有namespace Media Verification能力。CES本身不能取代8Ch的命令支援查詢。 || Effects log and Crypto Erase are supported; namespace media verification is not. CES alone does not replace8Ch support discovery.'],
        ['3 · Get Log Page，Figures 204～208，文件頁213～215／PDF 239～241 || 3 · Get Log Page, Figures204–208, printed213–215/PDF 239–241','Opcode=02h、LID=05h、NSID=0、NUMDL=03FFh、NUMDU=0；LPO=0、OT=0、RAE=0，讀取4096 bytes。 || Opcode02h, LID05h, NSID0, NUMDL=03FFh, NUMDU=0, LPO=0, OT=0 and RAE=0 retrieve4096 bytes.','NUMD是數量減1：(03FFh+1)×4=4096 bytes。這是讀能力表，沒有提交8Ch清除命令。 || NUMD encodes count−1: (03FFh+1)×4=4096 bytes. This reads a directory without submitting opcode8Ch.'],
        ['4 · Figure 216，文件頁227／PDF 253 || 4 · Figure216, printed227/PDF 253','Admin entry由byte0開始，每筆4 bytes；8Ch=140，因此4×140=560=230h，取bytes560～563。 || Admin entries begin at byte0 and occupy4 bytes each. 8Ch=140, so offset4×140=560=230h selects bytes560–563.','這是Admin命令，不加I/O區的1024-byte起點。若只讀一段，buffer內的位置還需扣掉該段的起始byte offset。 || This Admin entry does not use the I/O region’s1024-byte base. For a partial read, subtract that segment’s starting byte offset to find the buffer-relative position.'],
        ['5 · Figure 217，文件頁228～229／PDF 254～255 || 5 · Figure217, printed228–229/PDF 254–255','假設bytes依序是03h、00h、01h、00h，依little-endian組成00010003h；bit0=1。 || Hypothetical bytes03h,00h,01h,00h form little-endian00010003h; bit0=1.','Command Supported（CSUPP）=1，所以controller宣告支援8Ch。本例也有LBCC=1、CSE=001b：命令可能改變資料，且有同namespace的提交協調建議；這些不是執行結果。 || CSUPP=1 advertises8Ch. LBCC=1 and CSE=001b additionally describe possible data change and same-namespace coordination recommendations, not an operation result.'],
        ['6 · §5.2.27、Figure 454，文件頁452～453／PDF 478～479 || 6 · §5.2.27/Figure454, printed452–453/PDF 478–479','開始namespace清除的SANACT=100b（Crypto Erase）；010b、011b為Reserved。準備執行前，再查Active NSID、保護狀態與並行限制。 || Namespace initiation uses SANACT100b (Crypto Erase);010b/011b are reserved. Check active NSID, protection and concurrency before execution.','可回答「支援這個命令」，但不能回答「支援namespace Overwrite」，也不能保證任意目標現在都能執行。範例NVERS=0，也不提供進入Media Verification的能力。 || Command support does not establish namespace Overwrite or current eligibility of every target. NVERS=0 also does not provide entry to Media Verification.'],
      ],'如果有效entry的CSUPP=0，就是該命令不受支援，且這筆結構其餘欄位須為0。若LPA.CSES=0或讀Log失敗，則這條路徑沒有取得有效命令支援證據，不能把它改寫成「已讀到CSUPP=0」。 || A valid entry with CSUPP=0 reports no command support and requires its other fields to be zero. CSES=0 or a failed log query instead leaves this route without valid support evidence; neither is an observed CSUPP=0.',
      ['adminsupport','idctrl','idcmd','getlog','commandseffects','sanitizecmd'])

    revise(81,{
      3:'先讀Identify Controller的LPA.CSES（Figure338 bit1），確認是否提供LID05h，再固定命令集與UUID選擇。這個位元只表示能力Log可讀，Log裡各Opcode是否受支援仍要逐筆查CSUPP。CSP=0則表示未回報scope，不能解成「不影響任何物件」。 || First check Figure338 LPA.CSES bit1 for LID05h availability and fix command-set/UUID selection. CSES advertises the log, while per-opcode CSUPP advertises each command. CSP=0 means unreported scope, not no impact.',
      4:'Figure216先決定entry位置：Admin使用4×Opcode，I/O使用1024+4×Opcode，單位都是bytes。Figure217再定義這4 bytes中的CSUPP、LBCC、NCC、NIC、CCC、CSE、CSER、USS及CSP。例如Admin Opcode02h是Get Log Page，NVM I/O Opcode02h卻是Read；即使編碼相同，也不能查同一筆entry。 || Figure216 locates the four-byte entry: Admin uses4×opcode and I/O uses1024+4×opcode, in bytes. Figure217 decodes its support/effect fields. Admin opcode02h is Get Log Page, whereas NVM I/O opcode02h is Read; identical numbers do not identify the same entry.',
      17:'先確認Admin或I/O區，再核對Opcode、byte offset與成功的查詢CQE。Log中資料的起點、分段buffer的起點，以及entry內的bit位置是三種座標；把任一種誤當另一種，都可能讀到別的命令或欄位。 || First establish Admin/I/O region, opcode, byte offset and query success. Log-relative position, segment-buffer position and entry bit position are distinct coordinates; confusing them can select another command or field.'
    },['adminsupport'],[118,69,54])

    revise(69,{
      3:'Get Log Page使用LID=00h。Identify.LPA.MLPS=1保證提供Supported Log Pages；MLPS=0仍可能提供，不能直接判成所有Log都不支援。LPA.LPEDS（Figure338 bit2）說明延伸offset與長度能力；目標entry的LSUPP、IOS則分別表示該LID是否支援及是否接受index offset。 || Use LID00h. LPA.MLPS=1 guarantees Supported Log Pages, while MLPS=0 may still provide it and does not negate all logs. Figure338 LPA.LPEDS bit2 describes extended offsets/length; per-LID LSUPP and IOS describe log support and index-offset support.'
    },[],[81,54,128])
    byid[69]['practice']=pair('需求：確認能不能讀Sanitize Status，並判斷可否用index offset讀取。這兩個問題應查同一個位元嗎？先找出要讀的Log與目標entry，再展開解答。 || Task: discover Sanitize Status support and whether it accepts index offsets. Do the two questions use the same bit? Find the directory and entry before revealing the answer.')
    route(69,'查詢範例：支援 Log，不等於支援每一種讀法 || Worked lookup: log support versus permitted read modes',
      '教學假設：同一PCIe Admin介面，CC.CSS=000b、UUID Index=0，LPA.MLPS=1、LPEDS=1。此處要查的是Sanitize Status的LID81h，不是Sanitize Namespace的Opcode8Ch。 || Assume one PCIe Admin interface, CC.CSS=000b, UUID Index0, MLPS=1 and LPEDS=1. Discover Sanitize Status LID81h, not Sanitize Namespace opcode8Ch.',[
        ['1 · §5.2.13.1.1、Figure 210，文件頁217／PDF 243 || 1 · §5.2.13.1.1/Figure210, printed217/PDF 243','Get Log Page：LID=00h、NSID=0、NUMDL=00FFh、NUMDU=0、LPO=0、OT=0、RAE=0。 || Get Log Page with LID00h, NSID0, NUMDL=00FFh, NUMDU=0, LPO=0, OT=0 and RAE=0.','讀取256筆、每筆4 bytes，共1024 bytes的支援清單；查詢成功不表示256個LID全部受支援。 || Retrieves256 four-byte entries (1024 bytes), not a declaration that every LID is supported.'],
        ['2 · Figure 210，文件頁217／PDF 243 || 2 · Figure210, printed217/PDF 243','目標LID=81h=129；entry位於4×129=516=204h，取bytes516～519。 || LID81h=129 selects offset4×129=516=204h and bytes516–519.','用LID當索引。Opcode與FID即使同為81h，也不是這張清單要查的對象。 || Index by LID; an opcode or FID with the same numeric value is a different identifier.'],
        ['3 · Figure 211，文件頁217～218／PDF 243～244 || 3 · Figure211, printed217–218/PDF 243–244','假設entry=00000001h：bit0 LSUPP=1，bit1 IOS=0。 || Assume entry00000001h: LSUPP bit0=1 and IOS bit1=0.','支援Sanitize Status，但不支援該Log的index offset。LPEDS=1只提供一般延伸讀取能力，不能推翻IOS=0。 || Sanitize Status is supported, but its index-offset mode is not. General extended-read support does not override IOS=0.'],
        ['4 · Figures 206、312，文件頁214、313起／PDF 240、339起 || 4 · Figures206/312, printed214,313 onward/PDF 240,339 onward','後續讀LID81h時使用OT=0，依目標scope選NSID；再解讀回傳的Sanitize Status。 || Read LID81h with OT=0 and the correct target NSID, then decode the returned status.','LSUPP只回答Log是否提供；清除是否進行或完成，要看後續Status內容。即使LSUPP=1，強行使用不支援的OT=1仍須回Invalid Field。 || LSUPP establishes availability; operation progress/outcome requires the actual status. Unsupported OT=1 still requires Invalid Field despite LSUPP=1.'],
      ],'如果Supported Log Pages本身不可取得，不能把缺少清單當成所有LID都不支援；應改查該Log在規格中的支援條件及對應Identify欄位。任何查詢失敗後留下的buffer，都不能拿來解讀LSUPP。 || An unavailable directory does not establish that every LID is unsupported; use log-specific specification requirements and Identify fields. A failed query’s buffer is not valid LSUPP evidence.',
      ['getlog','idctrl','sanitizelog'])

    revise(54,{
      3:'先分開查「這個FID是否提供」與「提供後有哪些設定能力」。Feature Identifiers Supported and Effects（LID12h）的FSUPP回答前者；Identify.ONCS.SSFS表示是否支援Save／Select機制，支援時再用Get Features.SEL=3查CHANG、NSSPEC及SVBL。SEL=3的DW0 bit0是SVBL，不是FSUPP。 || Separate FID availability from its settings capabilities. LID12h FSUPP reports availability; Identify.ONCS.SSFS advertises Save/Select, under which Get Features.SEL3 returns CHANG/NSSPEC/SVBL. SEL3 DW0 bit0 is SVBL, not FSUPP.',
      6:'例如SEL=3回傳DW0=5，表示CHANG=1、SVBL=1、NSSPEC=0，也就是可變更、可保存。NSSPEC=0表示這個位元沒有指出scope，仍需查該FID的FSP或規範定義；不能直接推成controller scope。這個5也不是Current的工作值。 || SEL3 DW0=5 reports CHANG=1, SVBL=1 and NSSPEC=0: changeable and saveable. NSSPEC=0 does not indicate scope; consult FSP or the FID definition rather than assuming controller scope. Five is not the Current operating value.'
    },['featureeffects','vwc'],[69,81,55,60])
    byid[54]['practice']=pair('需求：確認Volatile Write Cache Feature是否提供、能否保存，以及目前有沒有啟用。這三個答案分別在哪一份回覆？先想好查詢順序，再展開解答。 || Task: establish Volatile Write Cache feature availability, saveability and current enable state. Identify the separate responses before revealing the answer.')
    route(54,'查詢範例：FSUPP、SVBL 與 Current.WCE 分別回答什麼？ || Worked lookup: FSUPP, SVBL and Current.WCE',
      '教學假設：CC.CSS=000b、UUID Index=0；Identify顯示LPA.MLPS=1、ONCS.SSFS=1、VWC.VWCP=1。本例只做Get，不執行Set Features或改動快取。 || Assume CC.CSS=000b, UUID Index0, MLPS=1, SSFS=1 and VWC.VWCP=1. The example performs queries only and does not change the cache.',[
        ['1 · Figure 200，文件頁211／PDF 237 || 1 · Figure200, printed211/PDF 237','Volatile Write Cache對應FID06h；MLPS=1也保證LID12h可讀。 || Volatile Write Cache uses FID06h; MLPS=1 also guarantees LID12h.','找到Feature識別碼及查詢入口。VWCP=1表示有快取，不等於快取目前已啟用。 || Identifies the feature and discovery log. Cache presence does not establish current enablement.'],
        ['2 · Figures 270～271，文件頁276～278／PDF 302～304 || 2 · Figures270–271, printed276–278/PDF 302–304','讀LID12h完整1024 bytes（NUMD=255）；FID06h位於4×6=24=18h，取該entry bit0 FSUPP，假設為1。 || Read1024 bytes of LID12h (NUMD=255); FID06h is at byte4×6=24=18h. Assume its FSUPP bit0 is1.','controller宣告提供FID06h。這裡尚未回答是否可保存，也還沒有讀到WCE。 || FID06h is advertised; saveability and current WCE are still unknown.'],
        ['3 · Figures 198、201，文件頁210、212／PDF 236、238 || 3 · Figures198/201, printed210,212/PDF 236,238','Get Features：Opcode0Ah、FID06h、SEL=3、NSID=0。假設成功CQE的DW0=00000005h。 || Get Features opcode0Ah, FID06h, SEL3 and NSID0 returns successful CQE DW0=00000005h.','bit2 CHANG=1、bit1 NSSPEC=0、bit0 SVBL=1：可變更且可保存。這個5是能力bitmap，不能解成快取工作值。 || Bits2/1/0 give CHANG=1/NSSPEC=0/SVBL=1: changeable and saveable. Five is a capability bitmap, not the cache setting.'],
        ['4 · Figure 471，文件頁464～465／PDF 490～491 || 4 · Figure471, printed464–465/PDF 490–491','再送相同FID的Get Features，但SEL=0。假設DW0=0，依VWC格式讀bit0 WCE=0。 || Query the same FID with SEL0. Assume DW0=0; the VWC format decodes bit0 as WCE=0.','Feature受支援、可保存，但快取目前未啟用。不能因Current=0，就改判成Feature不支援；也不能拿它和SEL=3的5直接比較是否相等。 || The feature is supported and saveable while caching is currently disabled. Current0 is not lack of support and need not equal the SEL3 bitmap5.'],
      ],'三種bit0的名字與用途不同：LID12h entry是FSUPP，SEL=3的CQE是SVBL，本例SEL=0的CQE則是WCE。判讀前必須連同LID或FID、SEL及回覆格式一起保存；只留下數字會失去意義。 || Three different bit0 definitions are involved: FSUPP in LID12h, SVBL in SEL3 CQE and WCE in this FID’s SEL0 CQE. Preserve LID/FID, SEL and response format with the numeric value.',
      ['featureeffects','getfeat','idctrl','vwc'])

    revise(134,{3:'先查LID05h中Admin Opcode8Ch的CSUPP，再查SANICAP.CES及所需的NVERS／SPRRS能力；查詢路徑見Q118。接著確認Active List、Write Protection與MNSOIP並行上限，不能把命令受支援直接當成目標目前可執行。 || Check Admin opcode8Ch CSUPP in LID05h, then CES and any required NVERS/SPRRS capability; Q118 gives the lookup. Separately establish active namespace, protection and MNSOIP limits before claiming current eligibility.'},['commandseffects'],[118])
    revise(135,{3:'先以LID05h中8Ch的CSUPP區分命令是否受支援，再以SANICAP、Active／Allocated Lists、Write Protection及LID81h.MNSOIP建立方法、目標與並行條件。這些欄位回答不同問題，不能用其中一個取代其他前提。 || First use8Ch CSUPP in LID05h for command support, then SANICAP, namespace lists, protection and MNSOIP for method, target and concurrency conditions. These are distinct prerequisites.'},['commandseffects'],[118])
