"""Definitions whose meaning depends on this report's command or structure."""
TERMS = {
 'AER': ('Asynchronous Event Request；主機預先提交，讓控制器日後以命令完成回報事件的 NVMe Admin 命令。', 'Asynchronous Event Request: an NVMe Admin command posted in advance so that the controller can later complete it to report an event.'),
 'LBA': ('Logical Block Address；以 logical block 為單位的地址。例如每 block 為 4096 bytes 時，LBA 2 的資料起點對應第 8192 byte。', 'Logical Block Address: an address measured in logical blocks. With 4096-byte blocks, LBA 2 starts at data byte 8192.'),
 'FUA': ('Force Unit Access；其效果由命令定義。對 Write 而言，要求資料與 metadata 提交至非揮發性媒體後才完成。', 'Force Unit Access: its effect is command-specific. For Write, data and metadata must be committed to non-volatile media before completion.'),
 'STC': ('此縮寫有多種用途：I/O 的 Storage Tag Check 控制保護檢查；Device Self-test 命令的 Self-test Code 選測試動作；Self-test 結果的 Status Code 則補充失敗狀態。先看所在結構，再解讀數值。', 'Context-dependent: Storage Tag Check controls I/O protection checks; Self-test Code selects a Device Self-test action; Status Code in a self-test result qualifies a failure. Interpret the containing structure first.'),
 'NVMSETID': ('NVM Set Identifier；辨識 NVM Set。Identify 用它查詢資源，Create SQ 則用它指定該 SQ 的關聯。', 'NVM Set Identifier: identifies an NVM Set; used for resource queries in Identify and for the association selected by Create SQ.'),
 'ENDGID': ('Endurance Group Identifier；辨識一個耐久度資源群組，須連同其所在結構解讀。', 'Endurance Group Identifier: identifies an endurance resource group within the containing structure.'),
 'DPS': ('End-to-end Data Protection Type Settings；Identify 回報目前 PI 類型與位置，Create payload 則提出新 namespace 的設定。', 'End-to-end Data Protection Type Settings: Identify reports current PI type/location; the Create payload requests settings for a new namespace.'),
 'NMIC': ('Namespace Multi-path I/O and Namespace Sharing Capabilities；Identify 回報共享能力，Create payload 則提出新 namespace 的共享設定。', 'Namespace Multi-path I/O and Namespace Sharing Capabilities: Identify reports sharing capabilities; the Create payload requests sharing settings.'),
 'LBSTM': ('Logical Block Storage Tag Mask；配合 PI 格式，決定 Storage Tag 哪些位元參與檢查。', 'Logical Block Storage Tag Mask: used with the PI format to determine which Storage Tag bits participate in checking.'),
 'PIC': ('Protection Information Capabilities；NVM Identify 中描述 PI 格式及 Storage Tag 支援能力的欄位。', 'Protection Information Capabilities: describes PI-format and Storage Tag capabilities in NVM Identify.'),
 'MPS': ('須看所在結構：CC.MPS 是 Memory Page Size；Power State Descriptor 的 MPS 是 Max Power Scale，用來換算 MP 的功率。', 'Context matters: CC.MPS is Memory Page Size; MPS in a Power State Descriptor is Max Power Scale, used to scale MP.'),
 'MUD': ('Multiple Update Detected；Firmware Commit 回覆中的 2-bit 欄位，分別回報兩種來源的更新序列重疊偵測。', 'Multiple Update Detected: a two-bit Firmware Commit result reporting update-sequence overlap from two sources.'),
 'LPOL': ('Log Page Offset Lower；LPO 的低 32 bits，合成後由 OT 決定使用 byte 位移或 Log 定義的索引。', 'Log Page Offset Lower: the low 32 bits of LPO; OT selects bytes or a log-defined index after assembly.'),
 'LPOU': ('Log Page Offset Upper；LPO 的高 32 bits，與 LPOL 合成完整的 64-bit 位置。', 'Log Page Offset Upper: the high 32 bits, combined with LPOL into the full 64-bit position.'),
 'IANP': ('Immediate Abort Not Performed；1 表示沒有執行立即中止，0 表示已執行。', 'Immediate Abort Not Performed: 1 means immediate abort was not performed; 0 means it was.'),
 'AET': ('Asynchronous Event Type；先選事件類型，再在該類型內解讀事件資訊。', 'Asynchronous Event Type: selects the category in which event information is interpreted.'),
 'AEI': ('Asynchronous Event Information；由 AET 選定的事件類型決定此值的意義。', 'Asynchronous Event Information: its meaning depends on the event type selected by AET.'),
 'NLB': ('Number of Logical Blocks；本篇讀寫、Copy 及 LBA Range Type 的此欄位採零起算，實際 block 數為 NLB+1。', 'Number of Logical Blocks: this field is zero-based in this report’s read/write commands, Copy, and LBA Range Type; the count is NLB+1.'),
 'LLB': ('Length in Logical Blocks；DSM 範圍描述子直接填 block 數。例如 8 blocks 填 8。', 'Length in Logical Blocks: a direct count in a DSM range descriptor; eight blocks are encoded as 8.'),
 'NLBAF': ('Number of LBA Formats；共用能力群組的格式數減 1，至少定義 1 個格式。', 'Number of LBA Formats: the common-capability group count minus one; at least one format is defined.'),
 'NULBAF': ('Number of Unique Attribute LBA Formats；直接表示非共用能力的格式數，0 表示沒有。', 'Number of Unique Attribute LBA Formats: a direct count of non-common formats; 0 means none.'),
}
