"""Local first-use terminology; displayed definitions are deduplicated by reader."""
TERMS = {
 'FDP': ('Flexible Data Placement；主機參與資料放置以降低回收搬移成本的能力。','Flexible Data Placement; host-directed organization of placement to reduce reclamation relocation.'),
 'Endurance Group': ('耐久度群組；FDP 配置生效的媒體管理範圍。','The media-management scope to which an FDP configuration applies.'),
 'Reclaim Group': ('回收群組，簡寫 RG；包含多個可輪替使用的回收單位。','A group, abbreviated RG, containing Reclaim Units.'),
 'Reclaim Unit Handle': ('回收單位控制代號，簡寫 RUH；在每個 RG 各參照一個目前的 RU。','A handle, abbreviated RUH, referencing one current RU in each RG.'),
 'Reclaim Unit': ('回收單位，簡寫 RU；FDP 模型中接收一批資料的媒體單位。','A media unit, abbreviated RU, that receives a group of data in the FDP model.'),
 'Placement Identifier': ('放置識別值，簡寫 PID；16-bit 值，依配置含 PHNDL 與可能存在的 RGID。','A 16-bit PID containing PHNDL and, according to the configuration, RGID.'),
 'PHNDL': ('Placement Handle；namespace 的映射清單索引，用來查出 RUHID。','Placement Handle; a namespace-local mapping index that selects a RUHID.'),
 'RUHID': ('Reclaim Unit Handle Identifier；識別 Endurance Group 內的一個 RUH。','Reclaim Unit Handle Identifier within an Endurance Group.'),
 'RGID': ('Reclaim Group Identifier；選擇 Reclaim Group 的編號。','Reclaim Group Identifier; selects a Reclaim Group.'),
 'RGIF': ('Reclaim Group Identifier Format；PID 高位分配給 RGID 的 bit 數。','Reclaim Group Identifier Format; the number of high PID bits allocated to RGID.'),
 'Initially Isolated': ('初始隔離；新寫入分開，內部搬移可合併不同同類型 RUH 的資料。','New writes are separated; relocation may combine data from different handles of this type.'),
 'Persistently Isolated': ('持續隔離；內部搬移後目的 RU 仍只含同一 RUH 寫入的資料。','After relocation a destination RU contains only data originally written through the same RUH.'),
 'RUHT': ('Reclaim Unit Handle Type；指定搬移時的隔離類型。','Reclaim Unit Handle Type; selects the relocation-isolation rule.'),
 'NUMFDPC': ('Number of FDP Configurations；配置清單數量減 1。','Number of FDP Configurations, encoded as count minus one.'),
 'DSZE': ('Descriptor Size；本筆配置描述器的 byte 長度，含補齊。','Descriptor Size; configuration-descriptor bytes including padding.'),
 'SZE': ('Size；整份 FDP Configurations log 的 byte 長度。','Size; total FDP Configurations log length in bytes.'),
 'FDPCV': ('FDP Configuration Valid；該候選配置目前是否可用。','FDP Configuration Valid; whether the candidate is currently available.'),
 'FDPCIDX': ('FDP Configuration Index；選清單的第幾筆，從 0 開始。','FDP Configuration Index; a zero-based list index.'),
 'FDPVWC': ('FDP Volatile Write Cache；該配置是否包含揮發性寫入快取。','FDP Volatile Write Cache; indicates cache presence for a configuration.'),
 'NRG': ('Number of Reclaim Groups；RG 數，直接計數。','Number of Reclaim Groups; a direct count.'),
 'NRUH': ('Number of Reclaim Unit Handles；RUH 數，直接計數。','Number of Reclaim Unit Handles; a direct count.'),
 'MAXPIDS': ('Max Placement Identifiers；Update 的 NPID 編碼上限。','Max Placement Identifiers; the maximum encoded Update NPID.'),
 'RUNS': ('Reclaim Unit Nominal Size；每個 RU 的名目 byte 大小。','Reclaim Unit Nominal Size in bytes.'),
 'ERUTL': ('Estimated Reclaim Unit Time Limit；配置中的估計時間上限，秒。','Estimated Reclaim Unit Time Limit in seconds.'),
 'EARUTR': ('Estimated Active Reclaim Unit Time Remaining；狀態回覆中的剩餘估計秒數。','Estimated Active Reclaim Unit Time Remaining in seconds.'),
 'RUAMW': ('Reclaim Unit Available Media Writes；目前還可寫的 logical block 數。','Reclaim Unit Available Media Writes; currently writable logical blocks.'),
 'NPHNDLS': ('Number of Placement Handles；建立 namespace 時明確提供的映射項目數。','Number of Placement Handles explicitly supplied at namespace creation.'),
 'NPID': ('Number of Placement Identifiers；Update 清單 PID 數減 1。','Number of Placement Identifiers; Update count minus one.'),
 'NRUHSD': ('Number of Reclaim Unit Handle Status Descriptors；狀態描述器直接計數。','Number of Reclaim Unit Handle Status Descriptors; a direct count.'),
 'RUHA': ('Reclaim Unit Handle Attributes；Usage 中的配置來源分類。','Reclaim Unit Handle Attributes; allocation-origin classification in Usage.'),
 'FDPS': ('Flexible Data Placement Support；控制器是否支援 FDP 的能力位。','Flexible Data Placement Support; the controller capability bit.'),
 'FDPE': ('Flexible Data Placement Enable；FID 1Dh 中的群組啟用位。','Flexible Data Placement Enable; the group enable bit in FID 1Dh.'),
 'FDPEE': ('FDP Event Enable；事件啟用位，與整體 FDP 啟用不同。','FDP Event Enable; event enablement, distinct from FDP enablement.'),
 'NOET': ('Number of FDP Event Types；事件類型的直接計數。','Number of FDP Event Types; a direct count.'),
 'HBMW': ('Host Bytes with Metadata Written；含 metadata 的主機相關寫入 byte 計數。','Host Bytes with Metadata Written; host write accounting in bytes.'),
 'MBMW': ('Media Bytes with Metadata Written；含 metadata 與相關內部寫入的媒體 byte 計數。','Media Bytes with Metadata Written; includes relevant internal writes.'),
 'MBE': ('Media Bytes Erased；媒體擦除 byte 計數。','Media Bytes Erased; erased-byte accounting.'),
 'PIV': ('Placement Identifier Valid；事件 PID 是否有有效報告。','Placement Identifier Valid in an event.'),
 'NSIDV': ('NSID Valid；事件的 namespace 識別值是否有效。','NSID Valid in an event.'),
 'LV': ('Location Valid；事件 RGID 與 RUHID 是否有效。','Location Valid; validity of event RGID and RUHID.'),
 'ETYP': ('Event Type；紀錄內的事件種類編碼。','Event Type; the event code inside a record.'),
 'ETSP': ('Event Type Specific；由事件類型決定格式的 16-byte 內容。','Event Type Specific; sixteen bytes interpreted by event type.'),
 'NLBAM': ('Number of LBAs Moved；搬移數量，0 與 FFFFh 有特殊意義。','Number of LBAs Moved; zero and FFFFh have special meanings.'),
 'LBAV': ('LBA Valid；Media Reallocated 是否提供有效的示例 LBA。','LBA Valid; validity of the example relocated LBA.'),
 'DPTR': ('Data Pointer；指向資料傳輸的主機記憶體描述，不是資料內容本身。','Data Pointer; describes host transfer memory, not the payload itself.'),
 'DTYPE': ('Directive Type；依命令情境選操作類型或 I/O 附加資訊類型。','Directive Type; selects the management or I/O directive interpretation.'),
 'DOPER': ('Directive Operation；所選 Directive 中的管理動作。','Directive Operation; the management action within a directive.'),
 'DSPEC': ('Directive Specific；Data Placement 的 I/O 中承載 PID。','Directive Specific; carries the PID for Data Placement I/O.'),
 'MO': ('Management Operation；I/O Management 的操作選擇。','Management Operation in I/O Management commands.'),
 'MOS': ('Management Operation Specific；由 MO 決定含義，Update 時保存 NPID。','Management Operation Specific; holds NPID for Update.'),
 'NUMD': ('Number of Dwords；4-byte 傳輸單位的個數減 1。','Number of Dwords; four-byte transfer units minus one.'),
 'CETYPE': ('Command Extension Type；決定 Write 的擴充欄位格式，本篇例子固定 0。','Command Extension Type; examples use the zero-valued Write layout.'),
 'VWCNP': ('Volatile Write Cache Not Present；1 表示此 namespace 沒有揮發性寫入快取。','Volatile Write Cache Not Present; one means no cache for this namespace.'),
 'index': ('索引；清單中第幾個項目的編號，與項目距起點多少 bytes 不同。','An item’s position in a list, distinct from its byte displacement.'),
 'offset': ('位移；距結構起點的距離，讀本篇時需確認單位是否為 bytes。','A displacement from a structure’s start; check the unit, usually bytes here.'),
 'little-endian': ('低有效 byte 放在低位址的整數儲存方式。','Integer storage with the least-significant byte at the lowest address.'),
 'buffer': ('緩衝區；主機準備給命令提供或接收資料的記憶體。','Host memory prepared to supply or receive command data.'),
 'metadata': ('隨資料儲存的附加資訊；統計與格式判斷時不能只看 data bytes。','Additional stored information considered alongside data bytes in accounting and formats.'),
 'User Data Out Commands': ('把 user data 寫向媒體的命令分類；此分類不等於必須有等量 PCIe payload。','A command category writing user data to media, not necessarily an equal-size PCIe payload.'),
 'garbage collection': ('垃圾回收；控制器整理有效與失效資料，以便回收媒體空間。','Controller reorganization of valid and invalid data to reclaim media space.'),
 'advisory': ('建議性；符合規格的控制器可選擇不依該提示採取動作。','Advisory information need not cause the controller to take action.'),
}

TERMS.update({
 'ENDGID': ('Endurance Group Identifier；選定耐久度群組的編號。','Endurance Group Identifier; identifies the target group.'),
 'ENDIR': ('Enable Directive；控制目標 Directive 的啟用或停用。','Enable Directive; enables or disables the target directive.'),
 'DPDIRS': ('Data Placement Directive Supported；是否支援該 Directive。','Data Placement Directive Supported.'),
 'DPDIRE': ('Data Placement Directive Enabled；指定 namespace 的啟用狀態。','Data Placement Directive Enabled for the selected namespace.'),
 'DPDIRCLR': ('Data Placement Directive Persistent Across Controller Level Resets；啟用狀態是否跨此類 reset 保留。','Data Placement Directive persistence across Controller Level Resets.'),
 'FDPA': ('FDP Attributes；配置描述器內的屬性位元組。','FDP Attributes; the configuration descriptor attribute byte.'),
 'FDPEF': ('FDP Event Flags；控制事件各識別欄位有效性的位元組。','FDP Event Flags; contains identifier-validity bits.'),
 'FDPET': ('依所在結構而定：log 請求中是選 host／controller 的 1-bit 值；supported descriptor 中是事件種類的 byte 值。','Context-dependent: a host/controller selector bit in the log request, or the event-type byte in a supported descriptor.'),
 'ETMSP': ('Event Timestamp；事件發生時保存的 Timestamp 值與屬性。','Event Timestamp; the timestamp value and attributes captured at occurrence.'),
 'SEF': ('Specific Event Flags；NVM Media Reallocated 的屬性位元組。','Specific Event Flags for the NVM Media Reallocated extension.'),
 'NUMFDPE': ('Number of FDP Events；log 內實際事件紀錄數。','Number of FDP Events actually contained in the log.'),
 'VER': ('Version；資料結構版本欄。','Version of the data structure.'),
 'VSS': ('Vendor Specific Size；廠商定義內容的 byte 數。','Vendor Specific Size in bytes.'),
 'VS': ('Vendor Specific；廠商定義的內容，需廠商文件才可進一步解讀。','Vendor Specific content requiring the vendor’s definition.'),
 'PAD': ('Padding；為滿足結構對齊而補入的 bytes。','Padding bytes added to align the structure.'),
 'NNS': ('Number of Namespaces Supported；配置容許的 namespace 數。','Number of Namespaces Supported by the configuration.'),
 'MNAN': ('Maximum Number of Allowed Namespaces；控制器回報的 subsystem namespace 數量上限。','Maximum Number of Allowed Namespaces in the subsystem.'),
 'NN': ('Number of Namespaces；此欄實際表示有效 NSID 的最大值，數量上限還需參照 MNAN。','Number of Namespaces; this field defines the maximum valid NSID, interpreted with MNAN for namespace-count limits.'),
 'SSFS': ('Save and Select Feature Support；是否支援保存設定及選擇非零 SEL 查詢。','Save and Select Feature Support.'),
 'SV': ('Save；Set Features 是否要求保存設定。','Save; requests saving a Set Features value.'),
 'SEL': ('Select；Get Features 要讀目前、預設、保存值，還是支援能力。','Select; chooses current, default, saved values or supported capabilities.'),
 'FSP': ('FID Scope；Feature 作用範圍的位元欄。','FID Scope; feature-scope bits.'),
 'FSUPP': ('Feature Supported；該 FID 是否受支援。','Feature Supported for the selected FID.'),
 'RUHS': ('Reclaim Unit Handle Scope；Feature 作用於 RUH 的範圍位。','Reclaim Unit Handle Scope.'),
 'LSI': ('Log Specific Identifier；依 log 定義選對象，本篇 FDP logs 用它放 ENDGID。','Log Specific Identifier; holds ENDGID for the FDP logs.'),
 'LSP': ('Log Specific Field；依 log 定義的選擇位元。','Log Specific Field; interpreted by the selected log.'),
 'NUMDL': ('Number of Dwords Lower；NUMD 編碼的低 16 bits。','Number of Dwords Lower; low sixteen bits of NUMD.'),
 'NUMDU': ('Number of Dwords Upper；NUMD 編碼的高 16 bits。','Number of Dwords Upper; high sixteen bits of NUMD.'),
 'LPOL': ('Log Page Offset Lower；起讀位移的低 32 bits。','Log Page Offset Lower; low thirty-two offset bits.'),
 'LPOU': ('Log Page Offset Upper；同一個起讀位移的高 32 bits。','Log Page Offset Upper; high thirty-two bits of the same offset.'),
 'OT': ('Offset Type；區別 byte 位移與項目索引。','Offset Type; distinguishes byte displacement from entry indexing.'),
 'RAE': ('Retain Asynchronous Event；讀取 log 時的非同步事件保留選項，是否相關依該 log 定義。','Retain Asynchronous Event; log-dependent asynchronous-event retention control.'),
 'UIDX': ('UUID Index；通用介面中的 UUID 選擇，本篇範例使用 0。','UUID Index; examples use zero.'),
 'CTRATT': ('Controller Attributes；Identify Controller 的能力屬性欄。','Controller Attributes in Identify Controller.'),
 'ONCS': ('Optional NVM Command Support；可選命令與功能的支持位元欄。','Optional NVM Command Support; optional command and feature capabilities.'),
 'NSFEAT': ('Common Namespace Features；此處 CNS08h 中的共同 namespace 屬性。','Namespace Features; here the common namespace properties in CNS08h.'),
 'VWCP': ('Volatile Write Cache Present；控制器是否回報有揮發性寫入快取。','Volatile Write Cache Present at controller scope.'),
 'FUA': ('Force Unit Access；對這筆 Write 要求資料及 metadata 在成功完成前寫入非揮發媒體。','Force Unit Access; requires data and metadata to reach nonvolatile media before successful completion.'),
 'NLB': ('Number of Logical Blocks；Write 的資料區塊數減 1。','Number of Logical Blocks; Write count minus one.'),
 'SLBA': ('Starting LBA；一段邏輯資料的起始 LBA。','Starting LBA of a logical range.'),
 'AD': ('Attribute–Deallocate；DSM 中標示可解除配置範圍的選項。','Attribute–Deallocate in Dataset Management.'),
 'NR': ('Number of Ranges；DSM 的範圍項目數減 1。','Number of Ranges; DSM entry count minus one.'),
 'LLB': ('Length in Logical Blocks；DSM 單一範圍的區塊數，直接計數。','Length in Logical Blocks; direct block count for a DSM range.'),
 'CATTR': ('Context Attributes；DSM 範圍的附加使用提示。','Context Attributes; additional usage hints for a DSM range.'),
 'DMRL': ('Dataset Management Ranges Limit；範圍項目數的限制。','Dataset Management Ranges Limit.'),
 'DMRSL': ('Dataset Management Range Size Limit；每個範圍的 logical block 數限制。','Dataset Management Range Size Limit in logical blocks.'),
 'DMSL': ('Dataset Management Size Limit；整筆命令的 logical block 總數限制。','Dataset Management Size Limit for the command’s total blocks.'),
 'NVMDSMSV': ('Dataset Management Support Variants；決定如何連同限制欄位判斷 DSM 支援。','Dataset Management Support Variants; controls interpretation of DSM support and limit fields.'),
 'TSTMP': ('Timestamp；48-bit 毫秒計時值。','Timestamp; the 48-bit millisecond value.'),
 'TSTMPS': ('Timestamp Attribute；時間來源與計時狀態的屬性位元組。','Timestamp Attribute byte.'),
 'TSTMPO': ('Timestamp Origin；計時值由 reset 初始化還是主機設定。','Timestamp Origin; reset initialization versus host setting.'),
 'SYNC': ('Synch；表示計時是否可能曾在某些區間停止。','Synch; indicates whether counting may have paused.'),
 'PSDT': ('PRP or SGL for Data Transfer；決定 DPTR 的描述格式。','PRP or SGL for Data Transfer; selects the DPTR representation.'),
 'PRP': ('Physical Region Page；用記憶體頁描述主機資料 buffer 的方式。','Physical Region Page; a page-based host-buffer representation.'),
 'SGL': ('Scatter Gather List；用一個或多個區段描述主機資料 buffer 的方式。','Scatter Gather List; a segment-based host-buffer representation.'),
})
for abbreviation, full in [('RUH','Reclaim Unit Handle'),('RU','Reclaim Unit'),('RG','Reclaim Group'),('PID','Placement Identifier')]:
    zh, en = TERMS[full]
    TERMS[full] = (full+'；'+zh, full+'; '+en)
    TERMS[abbreviation] = TERMS[full]
