from scripts.nvme_scenarios import case

case('identify',('最多還能建立幾個 namespace？','How many more namespaces can be created?'),
('管理程式把 NN 當成可建立的 namespace 數量。你要怎麼修正它，並回答「現在還能建立幾個」？','A management tool treats NN as the namespace creation limit. How should it answer how many more can be created now?'),
[('OACS.NMS=1；NN=1000；MNAN=16；MAXCNA=8。','OACS.NMS=1; NN=1000; MNAN=16; MAXCNA=8.'),('完整 Allocated Namespace ID list 有 10 筆；此 controller 的 Active list 有 6 筆。剩餘容量與建立參數尚未查詢。','The complete allocated list has 10 entries; this controller’s active list has 6. Remaining capacity and creation parameters have not been checked.')],
('Identify CNS=01h → CNS=10h 完整已配置清單 → CNS=02h 此 controller 的活動清單；必要時再查容量與 Namespace Management 參數。','Identify CNS=01h → complete allocated list with CNS=10h → this controller’s active list with CNS=02h; then inspect capacity and Namespace Management parameters.'),
[('NN 是有效 NSID 的最大值；MNAN 才是此例的 subsystem namespace 數量上限。NSID 可以不連續，所以最大編號 1000 不代表存在 1000 個 namespace。MAXCNA=8 則限制此 I/O controller 可附接的數量，不能拿來取代 MNAN。','NN is the largest valid NSID; MNAN gives the subsystem namespace count limit in this example. Sparse IDs mean a highest valid ID of 1000 does not imply 1000 namespaces. MAXCNA=8 separately limits attachments to this I/O controller.'),('只看數量，上限還有 16−10=6 個名額；此 controller 的附接名額還有 8−6=2 個。建立與附接是不同步驟，建立第 3 個新 namespace 不等於也能把它附接到這個 controller。','The count limits leave 16−10=6 creation slots and 8−6=2 attachment slots on this controller. Creation and attachment are distinct: creating a third new namespace would not establish that it can also attach here.'),('這不是保證能成功建立 6 個：每個 namespace 所需容量、格式、資源及同時發生的管理操作仍會影響結果。若 MNAN=0，NN 仍是可配置 namespace 數量的上限依據；例如 NN=1000 不能解成可建立無限個 namespace。','This does not guarantee six successful creations. Required capacity, formats, resources and concurrent management operations still matter. If MNAN=0, NN still bounds the allocated namespace count; for example, NN=1000 does not allow an unlimited namespace count.')],
'B338 B336 B446 N134','B338:379,396,404 B@3.2.1:104-106 B336:364-365 B446:472-473 N134:112-113')

case('identify',('namespace 存在，為什麼這個 controller 看不到？','Why is an existing namespace absent from this controller?'),
('盤點程式在 subsystem 找到 NSID=27，卻沒有對應的可存取 namespace。這足以判定資料遺失嗎？','Inventory finds NSID=27 in the subsystem but no accessible namespace on this controller. Does that establish data loss?'),
[('NN=100；CNS=10h 回傳 [2, 9, 27]；CNS=02h 回傳 [2, 9]；兩張清單均已讀完。','NN=100; CNS=10h returns [2, 9, 27]; CNS=02h returns [2, 9]. Both lists are complete.'),('裝置支援 Namespace Management；查詢期間沒有變更 namespace 配置。','Namespace Management is supported, and inventory remains stable during the queries.')],
('Identify CNS=01h 確認範圍與能力；分別讀 CNS=10h、02h；若需確認附接對象，使用 CNS=12h、NSID=27。','Identify CNS=01h for bounds and capability; CNS=10h and 02h for the two lists; CNS=12h with NSID=27 to inspect its controller attachments.'),
[('27 在有效範圍，而且出現在 Allocated list，表示該 namespace 已存在。它不在此 controller 的 Active list，只能得出它未附接到此 controller；不能說它不存在，更不能說媒體上的資料已遺失。','27 is valid and allocated, so the namespace exists. Its absence from this controller’s active list means it is not attached here; it does not establish nonexistence or media data loss.'),('CNS=12h 回答該 namespace 附接到哪些 controller。這可區分「附接在別處」與「已建立但尚未附接」；是否應改配置是後續決策，不是盤點查詢本身的結論。','CNS=12h identifies the controllers to which it is attached. This distinguishes attachment elsewhere from creation without attachment. Whether to change that configuration is a separate decision.'),('大量 namespace 時，每次清單最多容納 1024 個 NSID。下一次以最後一個非零 NSID 作為起點，取得大於該值的項目；不能只讀第一頁就把後面的 namespace 判成不存在。','For large inventories, a list holds at most 1024 NSIDs. Continue from the last nonzero NSID to obtain greater IDs; absence from the first page alone does not establish absence from the inventory.')],
'B336 B443 B346','B@3.2.1:104-106 B336:364 B@5.2.14.2.2:413 B@5.2.14.2.9:421 B@5.2.14.2.11:421')

case('identify',('重開機後 NSID 改了，還是同一份資料嗎？','Did a changed NSID identify the same namespace?'),
('開機前的 NSID=3，開機後變成 NSID=9。你會比容量、NSID，還是另一種識別資訊？','A namespace used NSID=3 before a power cycle and NSID=9 afterward. Would you compare capacity, NSID or another identifier?'),
[('前後 CNS=03h 的非零 Namespace UUID 相同；兩次都來自同一個已確認的 subsystem。','CNS=03h returns the same nonzero Namespace UUID before and after, from the same verified subsystem.'),('容量相同，但尚未讀取使用者資料。','Capacity matches, but user data has not been read.')],
('Identify CNS=03h，分別指定當時 NSID；依 NIDT、NIDL 解析識別描述子，保留識別值。','Identify CNS=03h for the respective NSIDs; parse identifier descriptors using NIDT and NIDL and retain the identifier values.'),
[('NSID 是命令選擇 namespace 的編號，可能跨斷電改變。Namespace UUID 是用來辨識 namespace 的資訊；本例相同的 UUID 支持它是同一個 namespace，不能只因 NSID 改變就視為新建物件。','An NSID selects a namespace in commands and may change across power loss. The matching Namespace UUID supports identifying the same namespace; a changed NSID alone does not make it a new object.'),('解析時先看 NIDT 指定識別種類，再依 NIDL 取出該種類的 bytes；不要把整個描述子連同表頭直接當作 UUID 比較。若改用 NGUID 或 EUI64，也要考慮 UIDREUSE 所描述的重用特性。','Use NIDT to select the identifier type and NIDL to extract its bytes. Do not compare a descriptor header as part of a UUID. When using NGUID or EUI64, account for the reuse characteristics reported through UIDREUSE.'),('識別相同不代表內容從未變動，也不能證明每個 LBA 都完整。若問題改成「資料有沒有改過」，需要另訂資料校驗方法；如果沒有可用的唯一識別資訊，僅靠相同容量不足以下定論。','Identity does not prove unchanged contents or integrity of every LBA. Data-change questions need separate verification. If no usable unique identifier is available, matching capacity alone is insufficient.')],
'B342 B346','B@3.2.1:106 B342:414 B346:417-420')

case('identify',('容量是位址範圍、可配置量，還是已使用量？','Which capacity does each namespace field describe?'),
('容量報告把 NSZE、NCAP、NUSE 三個數字相加。請用這份回傳值解釋為什麼不對。','A capacity report adds NSZE, NCAP and NUSE. Explain why that is incorrect using these observations.'),
[('目前 LBAF 的 LBADS=12、MS=0；NSZE=8192、NCAP=4096、NUSE=1024。','The selected LBAF has LBADS=12 and MS=0; NSZE=8192, NCAP=4096 and NUSE=1024.'),('這是支援 thin provisioning 的 NVM namespace，數值有效，沒有不可存取狀態造成的清零。','This is a thin-provisioned NVM namespace with valid values, not values cleared by an inaccessible state.')],
('Identify CNS=00h、目標 NSID → 由 FLBAS 選取 LBAF → 同時讀 NSZE、NCAP、NUSE。','Identify CNS=00h for the target NSID → select the LBAF through FLBAS → read NSZE, NCAP and NUSE together.'),
[('LBADS=12 表示每個 LBA 的資料大小是 2^12=4096 bytes。NSZE=8192 給出 32 MiB 的可定址資料範圍，合法 LBA 是 0 到 8191，不是到 8192。','LBADS=12 means 2^12=4096 data bytes per LBA. NSZE=8192 describes a 32 MiB addressable data range, with LBAs 0 through 8191, not through 8192.'),('NCAP=4096 是最多可配置的 logical blocks，換算為 16 MiB；NUSE=1024 是目前已配置的 logical blocks，換算為 4 MiB。它們從不同角度描述同一 namespace，並不是三塊可相加的獨立空間。','NCAP=4096 represents at most 16 MiB of allocatable logical blocks; NUSE=1024 represents 4 MiB currently allocated. These are different properties of one namespace, not three independent spaces to add.'),('NUSE 也不是檔案系統的已用容量。檔案刪除、deallocation、控制器的配置粒度與更新時機可能使兩者不同；要回答檔案還能存多少，需要檔案系統資訊，而不是改寫 NSZE 的意義。','NUSE is not filesystem used space. File deletion, deallocation, allocation granularity and update timing can make them differ. Filesystem free-space questions require filesystem evidence, not a reinterpretation of NSZE.')],
'N123 N125','N123:85-87 N125:94')

case('identify',('128 KiB 資料為什麼可能超過 MDTS？','How can 128 KiB of data exceed MDTS?'),
('主機準備一次傳輸 32 個 4 KiB logical blocks。請判斷 interleaved metadata 會不會讓這筆命令超限。','The host plans to transfer 32 logical blocks of 4 KiB each. Can interleaved metadata make the command exceed its limit?'),
[('CAP.MPSMIN=0；CC.MPS=1；Identify Controller 的 MDTS=5、CTRATT.MEM=0。','CAP.MPSMIN=0; CC.MPS=1; Identify Controller reports MDTS=5 and CTRATT.MEM=0.'),('使用中 LBAF：LBADS=12、MS=16；metadata 與資料交錯，這筆傳輸包含全部 16 metadata bytes／LBA。','Selected LBAF: LBADS=12, MS=16. Metadata is interleaved, with all 16 metadata bytes per LBA included in this transfer.')],
('讀取 CAP.MPSMIN → Identify CNS=01h 的 MDTS／CTRATT.MEM → CNS=00h 的使用中格式；再檢查命令本身的限制。','Read CAP.MPSMIN → Identify CNS=01h for MDTS/CTRATT.MEM → CNS=00h for the active format; also check command-specific limits.'),
[('MDTS 以最小記憶體頁大小為基準，並非目前 CC.MPS。此例上限是 2^5 × 2^(12+0)=131072 bytes，即 128 KiB；不能因主機選了 8 KiB 頁，就把上限放大為 256 KiB。','MDTS uses the minimum memory page size, not current CC.MPS. The limit is 2^5 × 2^(12+0)=131072 bytes, or 128 KiB. Selecting 8 KiB host pages does not raise it to 256 KiB.'),('MEM=0 時，MDTS 計算包括交錯的 metadata。32 × (4096+16)=131584 bytes，已超出 131072；在本例條件下，31 個完整 blocks 才能放進此上限。','With MEM=0, MDTS includes interleaved metadata. 32 × (4096+16)=131584 bytes exceeds 131072; under these assumptions, only 31 complete blocks fit this limit.'),('若 MEM=1，這個 MDTS 比較只算資料，32 blocks 可通過這項檢查，但仍要滿足其他命令與 buffer 條件。MDTS=0 也只表示這個欄位未設最大值，不能推成每種命令都能接受任意長度。','With MEM=1, this MDTS comparison excludes metadata, so 32 blocks pass this check while other command and buffer rules still apply. MDTS=0 removes this reported limit, not every limit on every command.')],
'B36 B338 N123 N125','B36:81-84 B338:368,371 N123:86-87 N125:94')

case('identify',('Dataset Management 的限制是 0，代表不支援嗎？','Do zero Dataset Management limits mean unsupported?'),
('兩個 controller 的 DMRL 都是 0。請判斷能否只靠這個值關閉 Dataset Management 功能。','Two controllers both report DMRL=0. Is that enough to disable Dataset Management in software?'),
[('A：ONCS.NVMDSMSV=1；DMRL=0、DMRSL=0、DMSL=0。','A: ONCS.NVMDSMSV=1; DMRL=0, DMRSL=0, DMSL=0.'),('B：ONCS.NVMDSMSV=0；DMRL=0、DMRSL=0、DMSL=0。','B: ONCS.NVMDSMSV=0; DMRL=0, DMRSL=0, DMSL=0.')],
('Identify CNS=01h 讀 ONCS；CNS=06h、CSI=00h 讀 NVM 專屬 controller 資料，再一起解 DMRL／DMRSL／DMSL。','Identify CNS=01h for ONCS; CNS=06h with CSI=00h for NVM-specific controller data; interpret DMRL/DMRSL/DMSL with the support variant.'),
[('A 的 NVMDSMSV=1 已表示支援此命令；三個 0 表示這些欄位沒有報出相應的處理限制。不能把 DMRL=0 解成「允許 0 個 range」。','A reports command support through NVMDSMSV=1; the three zero fields do not specify corresponding processing limits. DMRL=0 does not mean zero ranges are allowed.'),('B 使用另一種支援判斷：在 NVMDSMSV=0 的情況，必須連同這些 limit 的非零條件判讀。此組全 0 不提供 Dataset Management 支援，不能照搬 A 的結論。','B uses the other support interpretation: with NVMDSMSV=0, support depends on the nonzero limit conditions. This all-zero combination does not indicate Dataset Management support; A’s conclusion cannot be reused.'),('即使 A 支援，仍須遵守命令格式、namespace 範圍與每個 range 的定義。這題要練的是先讀能力版本，再解數值；0 沒有跨所有欄位通用的意思。','Even on A, command encoding, namespace bounds and range definitions still apply. The key is to interpret the capability variant before its numeric fields; zero has no universal meaning across fields.')],
'B338 N129 N47','B338:398 N129:103-106 N@3.3.3.1:45-47')

case('identify',('有 LID 編號，就一定能讀那張 log 嗎？','Does a defined LID guarantee an available log?'),
('軟體認得某個 LID，但裝置可能不支援。應查哪一種資料，才不會把「軟體有名稱」當成「controller 有功能」？','Software recognizes an LID, but a controller may not support it. What evidence separates a known name from an implemented log?'),
[('Supported Log Pages 的目標項目 LSUPP=0；另一个項目 LSUPP=1。','The target entry in Supported Log Pages has LSUPP=0; another entry has LSUPP=1.'),('本題先假設可成功讀取 Supported Log Pages；各目標 log 的 namespace、CSI 與 LSP 要求仍須另外確認。','Assume Supported Log Pages can be retrieved successfully; target-specific namespace, CSI and LSP rules still require checking.')],
('Get Log Page，LID=00h；找到以目標 LID 編排的 supported-and-effects 項目，再讀該 log 的定義。','Get Log Page with LID=00h; locate the supported-and-effects entry indexed by the target LID, then consult that log’s retrieval rules.'),
[('LSUPP 是這個 controller 對該 log 的支援回報。0 的項目不能因軟體已有解碼器就視為受支援；1 的項目則通過支援檢查。','LSUPP reports this controller’s support for the log. A software decoder does not turn a zero entry into support; a one entry passes that support check.'),('支援並不表示 log 裡一定已有事件或量測結果。空紀錄、尚未產生的 Telemetry、以及不支援的 log 是不同狀態，報告應分開顯示。','Support does not imply existing events or measurements. An empty log, a capture not yet generated and an unsupported log are different states that a report should distinguish.'),('後續要依各 log 的 NSID、CSI、LSP、LSI、長度及 offset 規則送命令。LSUPP=1 不能讓錯誤的讀取參數自動變合法，也不能替代內容格式或版本檢查。','Subsequent requests must follow the log’s NSID, CSI, LSP, LSI, length and offset rules. LSUPP=1 does not legalize incorrect selectors or replace payload-format and revision checks.')],
'B211 B204 B208','B211:243-244 B204:239 B205:240 B208:240-241')
