from scripts.nvme_scenarios import case

case('features',('Get Features 成功，為什麼還不知道目前值？','Why can a successful Get Features leave the current value unknown?'),
('程式讀到 DW0=5，便把某功能的「目前設定」顯示為 5。請檢查它解錯了哪一層。','A tool displays DW0=5 as a feature’s current setting. Which interpretation layer did it miss?'),
[('這是支援 Save／Select 的 controller；命令 SEL=3，目標 FID 合法，CQE success、DW0=00000005h。','The controller supports Save/Select; SEL=3 targets a valid FID; CQE reports success and DW0=00000005h.'),('目前值、預設值與已保存值都尚未讀取。','Current, default and saved values have not been retrieved.')],
('保留原 Get Features 的 FID／SEL／NSID → 按 SEL=3 解能力 → 再以同一 FID、正確對象、SEL=0 讀目前值。','Retain FID/SEL/NSID from the request → interpret SEL=3 capabilities → query the same FID and correct target with SEL=0 for the current value.'),
[('5 的二進位是 101b：CHANG=1、NSSPEC=0、SVBL=1。這表示有可變更屬性、不是 namespace-specific、可保存；不是功能值 5，也不是這個功能一定已啟用。','Five is binary 101: CHANG=1, NSSPEC=0, SVBL=1. This reports changeable attributes, non-namespace-specific scope and saveability, not a current value of five or proof of enablement.'),('SEL=0、1、2 分別取得 Current、Default、Saved；三者可能不同。NSSPEC=0 也不能直接推定只影響這一個 controller，實際 scope 仍由該 Feature 定義決定。','SEL=0, 1 and 2 retrieve Current, Default and Saved respectively; they can differ. NSSPEC=0 also does not by itself establish controller-only scope; the feature definition determines that.'),('報告若只保存 DW0 而丟掉 SEL，這次查詢的語意就無法可靠重建。需要資料 buffer 的 Feature 還要保存該 buffer；成功 CQE 不代表 DW0 已包含全部回傳資訊。','If a report retains DW0 but discards SEL, the meaning cannot be reliably reconstructed. Features with a data buffer also require that buffer; successful completion does not mean DW0 contains the complete response.')],
'B198 B201 B466','B198:235-236 B201:238 B466:483-485')

case('features',('要求 16 組 queues，實際能建立幾組？','How many queues follow from a request for sixteen?'),
('驅動要求 16 個 SQ、16 個 CQ，就直接建立 QID 1 到 16。回傳資訊是否允許這樣做？','A driver requests sixteen SQs and sixteen CQs, then creates QIDs 1 through 16. Does the response allow that?'),
[('Set Features FID=07h：NSQR=15、NCQR=15；成功回傳 DW0=00030007h。','Set Features FID=07h requests NSQR=15 and NCQR=15; successful DW0=00030007h.'),('CAP.MQES=1023；尚未執行 Create I/O CQ／SQ。','CAP.MQES=1023; no Create I/O CQ/SQ commands have been issued.')],
('解 FID=07h 完成回覆的 NCQA／NSQA；另讀 CAP.MQES，再規劃 Create I/O CQ／SQ 的數量與深度。','Decode NCQA/NSQA in the FID=07h completion; read CAP.MQES separately before planning queue creation and depths.'),
[('DW0 高 16 bits=3、低 16 bits=7，因此分配的是 4 個 CQ、8 個 SQ。要求 16 不等於獲配 16，不能用要求值覆蓋 controller 的回覆。','DW0 has upper half three and lower half seven, allocating four CQs and eight SQs. A request for sixteen is not an allocation of sixteen; the response governs the result.'),('MQES=1023 表示每個 I/O queue 最多 1024 entries，與 queue 數量不同。多個 SQ 可依合法設定共用 CQ，因此 SQ 與 CQ 的分配數不必相同。','MQES=1023 allows up to 1024 entries per I/O queue, distinct from the number of queues. Multiple SQs may share a CQ under valid configuration, so the allocated counts need not match.'),('此時只是取得可用資源，還沒有建立 queue。後續需先有可關聯的 CQ，再建立 SQ，檢查各次 Create 的完成結果；也不能把 queue 數直接當 MSI-X vector 數。','Resources have been allocated, but queues do not yet exist. Establish an appropriate CQ before its SQ and verify each Create completion. Queue counts also do not directly specify MSI-X vector counts.')],
'B472 B473 B36','B472:491 B473:492 B36:81-84')

case('features',('APST 表有兩條轉換，空閒 700 ms 會在哪裡？','What do two APST transitions imply after 700 ms idle?'),
('你要畫出自動省電流程，而不是只列出最低功耗 state。如何從 table entry 讀出轉換的起點與計時位置？','You need to explain the autonomous power path, not merely list the lowest-power state. How do the entries define source states and timing?'),
[('APSTE=1；PS0 entry：ITPT=100、ITPS=2；PS2 entry：ITPT=500、ITPS=3。','APSTE=1; PS0 entry: ITPT=100, ITPS=2; PS2 entry: ITPT=500, ITPS=3.'),('PS2、PS3 均為支援的 non-operational state；其餘相關 entries 停用；起始 PS0，連續 idle 700 ms。','PS2 and PS3 are supported non-operational states; other relevant entries are disabled. Start in PS0 with 700 ms of uninterrupted idle.')],
('Identify CNS=01h 的 APST 能力與 Power State Descriptors → Get Features FID=0Ch、SEL=0，同時取得 APSTE 與完整 APST buffer。','Identify CNS=01h for APST capability and power-state descriptors → Get Features FID=0Ch, SEL=0 for both APSTE and the full APST buffer.'),
[('表格的 entry index 是來源，ITPS 是目的地。因此流程是 PS0 ─ idle 門檻 100 ms → PS2 ─ 在 PS2 的 idle 門檻 500 ms → PS3。第二個 500 ms 不是從一開始在 PS0 就一併倒數。','The entry index selects the source; ITPS selects the destination. The path is PS0 → after its 100 ms idle threshold, PS2 → after the 500 ms threshold in PS2, PS3. The second timer is not simply counted from the initial PS0 idle instant.'),('若先忽略轉換耗時，700 ms 足以讓兩個門檻依序到達；但這只是教學時間線，不是讀取即時 state 的證據。實際轉換時間與控制器行為須一併考慮，APST 表本身是設定。','Ignoring transition time for illustration, 700 ms allows the two thresholds to be reached in sequence. This timeline is not a measurement of the current state: actual transition time and controller behavior matter, and the table is configuration evidence.'),('要討論下一筆 I/O 的代價，再查目的 state 的 EXLAT。若 EXLAT=0，意思是未回報，不能補成零延遲；若中途有工作打斷 idle，也不能照這條無工作時間線推論。','To assess the next I/O’s exit cost, inspect the destination descriptor’s EXLAT. Zero means unreported, not zero latency. Work that interrupts idle also invalidates this uninterrupted-idle timeline.')],
'B475 B477 B340 B468','B475:494 B477:495 B340:410-412')

case('features',('溫度升高時變慢，就能說是 HCTM 嗎？','Does a slowdown at high temperature establish HCTM activity?'),
('效能測試變慢，同時讀到溫度高於 TMT1。哪些回報能補強熱管理的判斷，哪些仍無法證明因果？','Performance falls while temperature is above TMT1. Which reports strengthen the thermal-management interpretation, and what remains unproven?'),
[('Get Features FID=10h：TMT1=340 K、TMT2=350 K；Identify 允許這組設定。','Get Features FID=10h: TMT1=340 K, TMT2=350 K; Identify limits permit these settings.'),('SMART Composite Temperature=345 K；測試區間內 Thermal Management Temperature 1 Transition Count 增加 1，Total Time 增加 20 seconds。','SMART composite temperature is 345 K; during the test, Thermal Management Temperature 1 Transition Count rises by one and Total Time by 20 seconds.')],
('Identify CNS=01h 查 HCTM 能力與允許溫度範圍 → Get Features FID=10h、SEL=0 → 兩次 Get Log Page LID=02h 比較計數。','Identify CNS=01h for HCTM capability and valid temperature limits → Get Features FID=10h, SEL=0 → compare two LID=02h SMART samples.'),
[('345 K 約 71.85°C，介於兩個設定門檻之間。門檻與量測值都要先確認單位，不能把 K 直接當攝氏，也不能把 Feature 的設定值當成當下溫度。','345 K is about 71.85°C, between the configured thresholds. Confirm units for settings and measurements; Kelvin is not Celsius, and a feature threshold is not the current temperature.'),('transition count 與 time 的增加，支持這段期間發生過第一階段 host-controlled thermal management。這比單張高溫快照多了行為證據，但它仍是區間累計，未交代每筆 I/O 的時間點。','The counter and time increases support stage-one host-controlled thermal management activity during the interval. This is stronger than a high-temperature snapshot, but remains interval evidence rather than per-I/O timing.'),('因此可報告熱管理曾介入，卻不能把整段效能下降都歸因給它。還需對齊量測時段、工作負載、power state 與 PCIe link 等資訊，才能分析各因素的影響。','You can report that thermal management was active, but cannot attribute the entire slowdown to it. Align measurement intervals, workloads, power states and PCIe link observations to investigate contributions.')],
'B482 B213 B338','B482:498 B213:247-251 B338:385-386')

case('features',('HMB 位址一樣，就能聲稱原記憶體已返還嗎？','Does an unchanged HMB address establish an intact return?'),
('重設後 host 把原位址的 HMB 清零，再宣稱 MR=1。只比對實體位址，是否足以驗證這個設定？','After reset, the host clears an HMB at the same address and declares MR=1. Is address equality enough?'),
[('停用前後 descriptor 位址與總大小相同，但 buffer 內容已被清零。','Descriptor address and total size match the previous allocation, but buffer contents have been cleared.'),('擬用 Host Memory Buffer Feature：EHM=1、MR=1；本題只判讀紀錄，不送出設定。','The proposed Host Memory Buffer feature has EHM=1, MR=1. This exercise only interprets the trace; no setting is applied.')],
('Identify CNS=01h 查 HMB 能力；查 Feature FID=0Dh 與保存的停用前 descriptor／buffer 紀錄。','Identify CNS=01h for HMB capability; inspect FID=0Dh and retained descriptors/buffer records from before disablement.'),
[('MR=1 表示返還先前同一份 HMB，要求的不只是相同位址與大小，也包含 descriptor 與 buffer 內容的一致。清零已破壞這項條件，所以這個宣稱不成立。','MR=1 declares return of the previous HMB, requiring more than matching address and size: descriptors and buffer contents must also remain consistent. Clearing the buffer breaks that condition.'),('EHM=1 只要求啟用，不能補足 MR 的真實性。讀到目前 Feature 已啟用，也不足以倒推 host 過去是否保持了每個 byte；必須有生命週期與記憶體管理紀錄。','EHM=1 requests enablement but cannot validate MR. Observing an enabled feature cannot reconstruct whether the host preserved every byte; lifecycle and memory-management records are needed.'),('若是重新配置的記憶體，應按新的 HMB 配置流程處理，而不是把位址偶然相同當成原內容仍在。這是能力查詢與 host 履約證據不同的一個例子。','Newly allocated memory must follow the new-HMB configuration path rather than treating an identical address as preserved contents. Controller capability and host compliance require different evidence.')],
'B545 B338','B545:542-543 B338:383,388')

case('features',('權重 7：3，能保證 IOPS 是 2：1 嗎？','Do weights seven and three guarantee a two-to-one IOPS ratio?'),
('高、低優先級 workload 的實測 IOPS 沒有依設定成比例。該直接判 controller 排程錯誤嗎？','Measured high- and low-priority IOPS do not match configured weights. Does that prove an arbitration defect?'),
[('CC.AMS 已選擇有權重的仲裁模式，且 CAP 表示支援；FID=01h：HPW=7、MPW=3、LPW=3、AB=2。','CC.AMS selects a supported weighted arbitration mode; FID=01h reports HPW=7, MPW=3, LPW=3, AB=2.'),('高、低優先級分別使用不同 I/O 大小與讀寫比例。','High- and low-priority workloads use different I/O sizes and read/write mixes.')],
('讀 CAP 與 CC.AMS → Get Features FID=01h、SEL=0 → 對照 SQ priority 與實際 workload。','Read CAP and CC.AMS → Get Features FID=01h, SEL=0 → correlate SQ priorities and actual workloads.'),
[('HPW=7 與 LPW=3 分別解成每輪 8 與 4 個命令的權重；AB=2 則用 2^2=4 計算單次 burst。相同大小的數字不代表相同編碼方式。','HPW=7 and LPW=3 encode per-round weights of eight and four commands. AB=2 instead encodes a burst of 2^2=4. Similar-looking numbers do not necessarily use the same encoding.'),('權重描述命令服務機會，沒有把不同大小、不同執行成本的 I/O 變成相同工作量。因此不能從 8：4 直接推出穩定的 2：1 IOPS，更不能推出 2：1 bandwidth。','Weights describe command-service opportunities, not equal work for commands with different sizes and execution costs. Eight-to-four weights do not directly guarantee a steady two-to-one IOPS or bandwidth ratio.'),('若要驗證仲裁，應記錄模式、各 SQ 的 priority、命令是否持續待處理與觀測時段，再用規格對應的服務規則判斷。單張應用 throughput 圖不足以證明排程違規。','Arbitration validation needs the mode, SQ priorities, pending work and observation interval, evaluated against the specified service rules. An application throughput chart alone does not establish a violation.')],
'B467 B41 B36','B467:486 B41:86-89 B36:81-84')
