"""Connections and learning destinations, beyond a list of chapter names."""

OVERVIEWS = {
 'nvm-command-set-1.3': {
  'zh': ['可以沿著一筆資料的生命週期讀這篇：先建立 namespace 並選格式，讓主機知道 LBA、資料及 metadata 如何對應；接著使用命令讀寫或搬移資料，再判斷順序、原子性及保護資訊能提供哪些保證。', '後半部把單筆操作放回整個裝置：效能提示影響操作安排，Rate Limiting 管理共享資源，FDP／Streams 描述資料放置，追蹤與狀態結構記錄資源變化。這些功能都要回到前面的格式與能力資訊判斷能否使用。學完應能解釋一筆命令的範圍、資料長度、必要條件與完成結果。'],
  'en': ['Follow the life of data: create a namespace and select a format to establish the relationship among LBAs, data, and metadata; then read, write, or move data and determine the guarantees from ordering, atomicity, and protection information.', 'The later lessons place individual operations in the whole device: performance hints guide operation sizing, Rate Limiting manages shared resources, FDP/Streams describe placement, and tracking/state structures record changes. These features depend on the earlier format and capability information. The aim is to explain a command’s range, transfer size, requirements, and completion result.']},
 'base-boot-telemetry-sanitize': {
  'zh': ['這篇涵蓋三個管理問題：開機前如何取得映像、運作中如何收集裝置狀態、退役或重新使用前如何處理使用者資料。三者不構成每次都必須依序執行的流程，而是不同時機會使用的管理功能。', '共同的閱讀方式是先確認操作對象，再分清主機要求、控制器目前狀態與回報資料。Boot 要區分讀取與啟用，Telemetry 要區分快照建立與取得，Sanitize 要區分啟動命令與背景作業完成。學完應能沿一個實際情境說明下一步該讀哪個結果，以及這個結果能證明多大的範圍。'],
  'en': ['This report addresses three management needs: obtaining an image before boot, collecting device state during operation, and handling user data before retirement or reuse. They are functions used at different times, not a sequence that every device operation must follow.', 'For each, establish the target and distinguish the host request, controller state, and reported data. Separate Boot reads from activation, Telemetry creation from retrieval, and Sanitize command completion from background completion. The aim is to explain which result to examine next and the scope of what it establishes.']},
 'base-ch1-2': {
  'zh': ['先用主機、控制器及 namespace 建立整體關係，再跟著一筆命令看提交與完成。規格分工告訴我們這些關係分別由哪份文件定義，數值與單位則是讀懂後續欄位的共同工具。', '閱讀後應能畫出主機到儲存空間的路徑，說明命令與資料各放在哪裡，並分辨同一份儲存空間的多條路徑和多個主機的共享。這些基本概念會在後續各篇的具體機制中再次被使用。'],
  'en': ['Establish hosts, controllers, and namespaces, then follow command submission and completion. The specification family assigns responsibility for those relationships, while numeric conventions and units provide the tools for reading later fields.', 'The aim is to draw the path from host to storage, explain where commands and data reside, and distinguish multiple paths to one storage object from sharing by multiple hosts. Later reports apply these foundations to specific mechanisms.']},
 'base-ch3': {
  'zh': ['控制器從被發現到可接受命令，會經過能力辨識、記憶體及佇列配置、啟用與就緒確認。開始運作後，還要安排不同佇列的工作，管理 namespace 與控制器記憶體，最後處理關機或重設。', '這條生命週期把各組 properties 連在一起：有些回報能力，有些接受主機設定，有些回報當前狀態。學完應能說明每個階段由誰採取動作、依什麼資訊前進，以及停止或重設後哪些資源需要重新確認。'],
  'en': ['A controller becomes usable through capability reporting, memory and queue configuration, enablement, and readiness confirmation. During operation it selects work, manages namespaces and controller memory, and eventually handles shutdown or reset.', 'This lifecycle connects properties that report capabilities, accept host choices, or report current state. The aim is to identify who acts at each stage, which information permits progress, and what must be re-established after shutdown or reset.']},
 'base-ch4': {
  'zh': ['把一次操作拆成三份資訊：SQE 說明主機要做什麼，PRP／SGL 描述資料在哪裡，CQE 回報是哪筆命令完成及其結果。識別碼與清單則協助主機選擇正確對象。', '本篇由共同布局逐步深入位元、長度與指標。讀完應能從一個命令範圍算出資料量，選擇正確的指標解讀方式，再利用完成項目找回原命令。每次計算都要先確認單位，而不是只憑欄位名稱推測。'],
  'en': ['Separate an operation into the request in the SQE, data locations described by PRP/SGL, and the command identity and result in the CQE. Identifiers and lists help select the intended objects.', 'The lessons move from common layouts to bits, lengths, and pointers. The aim is to calculate transfer size, interpret pointers correctly, and associate a completion with its command. Establish units before calculations rather than inferring them from field names.']},
 'pcie-transport-1.4': {
  'zh': ['Base 定義的提交與完成機制，在 PCIe 上需要具體的位址、記憶體存取和通知方式。先找到控制器的暫存器空間，再看 SQ／CQ 如何交換命令，最後理解中斷及 PCIe 狀態回報。', 'Configuration Space、錯誤紀錄與眼圖量測又提供不同層次的資訊：裝置如何呈現、傳輸發生了什麼、接收端量測資料如何排列。它們不等同 NVMe 命令完成狀態。學完應能沿一次交換辨認資料、Doorbell 和中斷的分工。'],
  'en': ['The submission/completion model defined by Base needs concrete addresses, memory accesses, and notifications over PCIe. Locate the controller register space, follow SQ/CQ exchanges, and then interpret interrupts and PCIe status.', 'Configuration Space, error records, and eye measurements describe device presentation, transport events, and receiver measurement layouts at different levels. They are distinct from NVMe command completion status. The aim is to explain the roles of data, doorbells, and interrupts in an exchange.']},
 'base-admin-fw-logs': {
  'zh': ['更新韌體可分成能力確認、映像傳輸、保存與啟用、結果確認。這個順序連接了 Identify 的能力資訊、Download 的長度與偏移、Commit 的選擇，以及 LID 03h 的目前與待啟用版本。', '本篇只以 Firmware Slot Information 完成更新結果的閱讀，不延伸成所有 log 的介紹。學完應能解釋為什麼下載成功還不等於新版本正在執行，並能用實際的分段長度與 slot 狀態走完一個例子。'],
  'en': ['Firmware update connects capability reporting, image transfer, storage and activation, and result verification. These stages link Identify capabilities, Download lengths and offsets, Commit choices, and the current/pending slots in LID 03h.', 'The report uses Firmware Slot Information to interpret the update result without expanding into all log pages. The aim is to explain why a successful download does not establish that new firmware is running and to follow an example using actual portions and slot states.']},
 'base-power-features': {
  'zh': ['電源管理在功耗、恢復服務所需時間與溫度之間安排操作。先理解電源狀態有哪些能力，再看主機如何讀寫 Feature；APST 依閒置時間轉換狀態，溫度門檻與 HCTM 則依溫度處理不同問題。', '通知門檻用來回報溫度事件，熱管理門檻用來控制行為，兩者不能互換。學完應能解釋選擇較省電狀態可能帶來哪些延遲，以及設定值、目前狀態和累計統計分別告訴我們什麼。'],
  'en': ['Power management relates power consumption, time to resume service, and temperature. Establish power-state capabilities and Feature access first; APST changes states after idle periods, while thresholds and HCTM address temperature-related needs.', 'Notification thresholds report temperature events; thermal-management thresholds control behavior. They are not interchangeable. The aim is to explain the latency tradeoff of lower-power states and distinguish settings, current state, and accumulated statistics.']},
 'base-self-test-hmb-emulation': {
  'zh': ['這篇把背景診斷、主機記憶體的借用，以及特殊命令的位址與長度安排放在一起。共同問題是：主機提出要求後，控制器取得什麼資源，何時才可以判斷工作結束或收回資源。', 'Self-test 需要接著讀取進度和歷史結果；HMB 需要等控制器完成停用後才收回記憶體；Doorbell Emulation 與 Vendor Commands 則需要各自正確的編碼與單位。學完應能解釋相同成功狀態在不同命令中確認了什麼。'],
  'en': ['This report connects background diagnostics, use of host-provided memory, and address/length arrangements for specialized commands. The common question is what resource the controller receives and when the host can establish completion or reclaim it.', 'Self-test requires progress and history reads; HMB requires completed disablement before memory reclamation; Doorbell Emulation and Vendor Commands need their own encodings and units. The aim is to explain what the same success status establishes for different commands.']},
 'base-self-test-namespace-management': {
  'zh': ['診斷裝置與配置儲存空間是不同工作。前者啟動背景測試並讀取結果，後者先決定容量與格式，再建立 namespace 和控制器的存取關係。兩者都需要把命令完成與後續狀態分開閱讀。', 'Namespace 的主線是容量→建立資料→Create→Attach→存取→Detach／Delete，恢復預設配置與通知則接在這條主線上理解。學完應能分清空間是否存在、是否已連接到特定控制器，以及容量是否符合所選格式與粒度。'],
  'en': ['Device diagnosis and storage provisioning are different tasks. Diagnosis starts a background test and retrieves its result; provisioning selects capacity and format, creates a namespace, and establishes controller access. Both require separating command completion from subsequent state.', 'The namespace path runs from capacity and creation data through Create, Attach, access, and Detach/Delete. Default restoration and notifications connect to that path. The aim is to distinguish existence, attachment to a controller, and capacity/format/granularity relationships.']},
}
