"""Local terminology; detailed field semantics live in one field guide."""
TERMS={
 'Endurance Group':('耐用度群組；一起管理儲存耐用度的一組容量，可分給零個或多個 NVM Set。','A collection of capacity managed together for endurance, potentially allocated to zero or more NVM Sets.'),
 'NVM Set':('在邏輯上分開的一組非揮發性儲存，可包含數個 namespace。','A logically separate collection of non-volatile storage that can contain namespaces.'),
 'namespace':('主機可用 NSID 指定的邏輯儲存空間。','Logical storage addressed by the host using an NSID.'),
 'ENDGID':('Endurance Group Identifier；本篇用來指定要查詢或設定哪一組的 16-bit 識別值。','Endurance Group Identifier; a 16-bit value selecting the group to query or configure.'),
 'LID':('Log Page Identifier；Get Log Page 用來選擇回覆資料種類的代碼。','Log Page Identifier; selects which log format Get Log Page returns.'),
 'FID':('Feature Identifier；Get／Set Features 用來選擇查詢或設定功能的代碼。','Feature Identifier; selects the feature queried or configured by Get/Set Features.'),
 'EGCW':('Endurance Group Critical Warning(s)；在 log 中是警告狀態，在 FID18h 中是選擇哪些警告觸發事件的遮罩。','Endurance Group Critical Warning(s); warning state in the log, but a reporting-selection mask in FID18h.'),
 'mask':('位元遮罩；每個 bit 分別選擇一種條件，可以同時選多種。','A bit mask that selects individual conditions, including several at once.'),
 'RAE':('Retain Asynchronous Event；Get Log Page 的事件保留控制，1 保留、0 在成功完成後確認對應事件。','Retain Asynchronous Event; one retains the event, zero acknowledges the associated event after successful completion.'),
 'AER':('Asynchronous Event Request；主機先送出並等待控制器用完成結果回報事件的命令。','Asynchronous Event Request; a host-posted command completed by the controller to report an event.'),
 'CQE':('Completion Queue Entry；控制器寫入完成佇列的一筆命令結果。','Completion Queue Entry; a command result posted by the controller.'),
 'CDW11':('Command Dword 11；命令中的第 11 個 dword 欄位，其內容依命令而定。','Command Dword 11; its fields depend on the command.'),
 'DW0':('Dword 0；此處指完成項目的第 0 個 dword，內容要配合命令種類與 SEL 解讀。','Dword 0 of the completion entry; interpreted according to the command and SEL.'),
 'LSI':('Log Specific Identifier；依 log 種類指定對象，LID09h 用它指定 ENDGID。','Log Specific Identifier; LID09h uses it to select ENDGID.'),
 'NUMD':('Number of Dwords；此處為 NUMDU 與 NUMDL 合併的數值，Get Log Page 採傳輸 dword 數減 1。','Number of Dwords; the combined NUMDU/NUMDL value encodes transfer dwords minus one in Get Log Page.'),
 'NUMENT':('Number of Entries；清單實際項目數，直接計數。','Number of Entries; a direct count of list entries.'),
 'ENDGIDMAX':('Endurance Group Identifier Maximum；合法 ENDGID 的最大值，不是目前 Group 數量。','Endurance Group Identifier Maximum; the identifier ceiling, not the current group count.'),
 'index':('索引；本文程式表示法從 0 起算，用來定位清單中的一筆。','A zero-based position used here to locate a list entry.'),
 'offset':('偏移量；相對起點的位置。byte offset 以 bytes 計距離，index offset 以項目計位置。','A position relative to a start: a byte offset counts bytes, while an index offset counts entries.'),
 'header':('資料開頭的固定區域；LID0Fh 的前 8 bytes 放 NUMENT。','The leading fixed area; LID0Fh uses eight bytes for NUMENT.'),
 'entry':('清單中的一筆項目；LID0Fh 每筆存一個 2-byte Group 識別值。','One list record; each LID0Fh entry contains a two-byte group identifier.'),
 'write amplification':('寫入放大；為完成主機寫入，媒體還可能承受內部搬移等額外寫入。','Additional media writes, such as internal relocation, beyond host-requested writes.'),
 'PUSED':('Percentage Used；Group 已使用壽命的廠商估計百分比。','Percentage Used; a vendor estimate of group life consumed.'),
 'AVSP':('Available Spare；Group 剩餘備用容量的正規化百分比。','Available Spare; normalized remaining spare percentage for the group.'),
 'AVSPT':('Available Spare Threshold；判斷備用容量偏低所用的百分比門檻。','Available Spare Threshold; the percentage used to detect low spare capacity.'),
 'EGRO':('Endurance Group Read-Only；非 namespace 寫入保護狀態變更所造成的整組唯讀警告。','Endurance Group Read-Only; a group-wide condition not caused by namespace write-protection state changes.'),
 'EGDR':('Endurance Group Degraded Reliability；Group 可靠度下降警告。','Endurance Group Degraded Reliability; a warning of reduced group reliability.'),
 'EGASB':('Endurance Group Available Spare Below；備用容量低於門檻的警告。','Endurance Group Available Spare Below; spare capacity below threshold.'),
 'EE':('Endurance Estimate；假設寫入放大為 1 時，Group 全生命週期可寫入量的估計。','Endurance Estimate; estimated lifetime writable bytes assuming write amplification of one.'),
 'DUR':('Data Units Read；Group 累積讀取量，不含控制器內部讀取。','Data Units Read; cumulative group reads excluding internal controller reads.'),
 'DUW':('Data Units Written；Group 累積寫入量，不含控制器內部寫入。','Data Units Written; cumulative group writes excluding internal controller writes.'),
 'MUW':('Media Units Written；包含主機與控制器內部寫入的 Group 累積量。','Media Units Written; cumulative group writes including host and internal controller writes.'),
 'SEL':('Select；Get Features 選擇目前值、預設值、保存值或支援能力。','Select; chooses current, default, saved or supported-capability information.'),
 'SV':('Save；Set Features 要求保存屬性的控制位元，需確認支援與可保存能力。','Save; requests persistence of feature attributes, subject to support and saveability.'),
 'EGS':('Endurance Groups；CTRATT 中表示支援耐用度群組的能力位元。','Endurance Groups; the support bit in CTRATT.'),
 'EGEAN':('Endurance Group Event Aggregate Log Page Change Notices；OAES 中表示支援此通知的位元。','Endurance Group Event Aggregate Log Page Change Notices; the OAES support bit.'),
 'EGEALCN':('Endurance Group Event Aggregate Log Change Notices；FID0Bh 中啟用清單變更通知的位元。','Endurance Group Event Aggregate Log Change Notices; the FID0Bh enable bit.'),
 'AERL':('Asynchronous Event Request Limit；同時未完成的 AER 上限採數量減 1 編碼。','Asynchronous Event Request Limit; encodes maximum outstanding AERs minus one.'),
 'CTRATT':('Controller Attributes；控制器能力與屬性的位元欄位。','Controller Attributes; capability and attribute bits.'),
 'OAES':('Optional Asynchronous Events Supported；回報控制器支援哪些選用非同步事件。','Optional Asynchronous Events Supported; reports support for optional events.'),
 'ONCS':('Optional NVM Command Support；包含本篇需要的 Save／Select 支援位元。','Optional NVM Command Support; includes the Save/Select support bit used here.'),
 'SSFS':('Save and Select Feature Support；支援非零 Save 與 Select 欄位值的能力。','Save and Select Feature Support; support for nonzero Save and Select values.'),
 'HRC':('Host Read Commands；按所用 I/O Command Set 分類的已完成讀取類命令筆數。','Host Read Commands; completed commands in the applicable I/O command set’s read class.'),
 'HWC':('Host Write Commands；已完成的 User Data Out 類命令筆數。','Host Write Commands; completed commands in the User Data Out class.'),
 'MDIE':('Media and Data Integrity Errors；未恢復資料完整性錯誤的累積次數。','Media and Data Integrity Errors; cumulative unrecovered integrity errors.'),
 'NEILE':('Number of Error Information Log Entries；與該 Group 相關的累積錯誤紀錄項目數。','Number of Error Information Log Entries; cumulative entries for this group.'),
 'TEGCAP':('Total Endurance Group Capacity；Group 的總 NVM 容量。','Total Endurance Group Capacity; total NVM capacity in the group.'),
 'UEGCAP':('Unallocated Endurance Group Capacity；Group 尚未配置給 Set 的容量。','Unallocated Endurance Group Capacity; group capacity not allocated to sets.'),
 'EGFEAT':('Endurance Group Features；此處用其中的媒體種類 bit 描述 Group。','Endurance Group Features; includes the group’s media-kind bit.'),
 'DID':('Domain Identifier；表示 Group 所屬的 domain。','Domain Identifier; identifies the domain containing the group.'),
 'AET':('Asynchronous Event Type；非同步事件類型，本文使用 Notice。','Asynchronous Event Type; this report uses Notice.'),
 'AEI':('Asynchronous Event Information；在事件類型內進一步指出發生哪種事件。','Asynchronous Event Information; identifies the event within its type.'),
 'LPOL':('Log Page Offset Lower；讀取起始位置的低 32 bits。','Log Page Offset Lower; low 32 bits of the starting position.'),
 'LPOU':('Log Page Offset Upper；讀取起始位置的高 32 bits。','Log Page Offset Upper; high 32 bits of the starting position.'),
 'OT':('Offset Type；選擇 offset 以 byte 或項目索引計算。','Offset Type; selects byte or entry-index interpretation.'),
 'NUMDL':('Number of Dwords Lower；傳輸數量編碼的低 16 bits。','Number of Dwords Lower; low 16 bits of the transfer-count encoding.'),
 'NUMDU':('Number of Dwords Upper；傳輸數量編碼的高 16 bits。','Number of Dwords Upper; high 16 bits of the transfer-count encoding.'),
}
