"""Paired conceptual review questions, authored independently of body paragraphs."""

BANK = {}


def b(zh, en):
    return {'zh': zh, 'en': en}


def add(report, prefix, key, sources, question, answer):
    BANK.setdefault(report, []).append(dict(
        id=f'{report}-{key}', question=question, answer=answer,
        sources=[prefix + '-' + s for s in sources.split(',')], informative=True))


r, p = 'nvm-command-set-1.3', 'NVMCS13'
add(r,p,'capacity','CAPACITY',b('NSZE=1000、NCAP=800、NUSE=600 時，3 個數值各回答什麼問題？','With NSZE=1000, NCAP=800, and NUSE=600, what question does each value answer?'),b('NSZE 描述可定址的範圍，LBA 從 0 到 999；NCAP 描述最多可配置 800 個 logical blocks；NUSE 描述目前已配置 600 個。這些都是 logical block 數，換成 bytes 還需要 data size。','NSZE gives the addressable range, LBA 0 through 999; NCAP allows up to 800 allocated logical blocks; NUSE reports 600 currently allocated blocks. These are logical-block counts, so conversion to bytes also needs the data size.'))
add(r,p,'fused','ORDER-FUSED',b('把 Compare 和 Write 相鄰放入 SQ，就能保證兩者之間沒有其他修改嗎？','Does placing Compare and Write next to each other in an SQ prevent intervening modifications?'),b('不能只靠相鄰位置。要使用支援的 fused operation，依規則設定第 1 與第 2 個命令，並滿足相同範圍等配對條件；一般命令的提交順序不提供這種保證。','Adjacency alone is insufficient. Use a supported fused operation, mark its first and second commands correctly, and satisfy pairing conditions such as matching ranges. Ordinary submission order does not provide that guarantee.'))
add(r,p,'atomic-persistent','ATOMIC,READ-WRITE',b('符合 atomic write 大小，是否就表示斷電後資料一定保存？','Does satisfying the atomic-write size guarantee that the data survives a power loss?'),b('Atomicity 關注規定情境下是否可能讀到部分更新；persistence 關注資料是否已保存到非揮發性媒體。仍要分別考慮 normal／power-fail atomicity、對齊邊界、volatile write cache 與 FUA／Flush 規則。','Atomicity concerns whether a partial update can be observed in the specified circumstances; persistence concerns storage on nonvolatile media. Normal versus power-fail atomicity, boundaries, volatile write cache, and FUA/Flush rules still need separate consideration.'))
add(r,p,'compare-verify','COMPARE-VERIFY',b('已知一段預期資料，想確認媒體內容與它相同，應使用 Compare 還是 Verify？','Given expected data, should Compare or Verify be used to check that stored content matches it?'),b('Compare 會使用 host 提供的比較資料。Verify 用來確認指定範圍的可讀性及適用的完整性檢查，不會把資料傳回 host，也不以一份 host 預期內容作逐項比較。','Compare uses comparison data supplied by the host. Verify checks readability and applicable integrity conditions for the range without returning its data or comparing it against a host-supplied expected payload.'))
add(r,p,'zero-allocation','DEALLOC,ZERO-UNCORRECTABLE',b('Read 得到全零，可以推論這些 LBAs 仍然已配置嗎？','Can an all-zero Read establish that the LBAs remain allocated?'),b('不能。已寫入的零資料與 deallocated block 的零值讀取行為都可能產生相同結果。要結合配置狀態、DRB，以及 DULBE 是否支援且啟用，才能解釋這次讀取。','No. Written zero data and zero-valued reads from deallocated blocks can produce the same result. Interpret the read using allocation state, DRB, and whether DULBE is supported and enabled.'))
add(r,p,'format','FOUNDATION,FORMAT-LIST,METADATA',b('只知道 data size 是 4096 bytes，足以建立正確的 I/O buffer 嗎？','Is a data size of 4096 bytes enough to construct the correct I/O buffer?'),b('還不夠。需要確認使用中的 Format Index、metadata 大小、PI 格式與 metadata 傳輸方式；separate buffer 與 extended LBA 的記憶體排列不同。','No. The active Format Index, metadata size, PI format, and metadata transfer mechanism are also needed. A separate buffer and extended LBAs use different memory layouts.'))
add(r,p,'pi-checks','PI-CHECKING',b('PRACT=1 是否代表關閉所有 PI 檢查？','Does PRACT=1 turn off every PI check?'),b('PRACT 控制 PI 如何在傳輸中處理，並非總檢查開關。Guard、Application Tag、Reference Tag 的要求由 PRCHK 指定，Storage Tag 另由 STC 指定；實際傳輸內容還取決於 metadata 與 PI 大小。','PRACT controls how PI is handled during transfer; it is not a master check switch. PRCHK specifies Guard, Application Tag, and Reference Tag checks, while STC controls Storage Tag checking. Transferred contents also depend on metadata and PI sizes.'))
add(r,p,'rate-modes','RATE-MODES',b('Soft Limit 為何可能觀察到高於設定值的 throughput？','Why can throughput under a Soft Limit exceed its configured value?'),b('Soft Limit 允許利用尚未被其他工作使用的頻寬或 IOPS；當資源不足時才依設定比例分配。Hard Limit 則提供上限。Appendix A 的 token buckets 是說明性實作，不能視為所有 controller 的內部結構。','A Soft Limit permits use of bandwidth or IOPS left unused by other work; resource shortfalls are distributed proportionally to configured limits. A Hard Limit supplies a ceiling. Appendix A token buckets are an illustrative implementation, not a required controller architecture.'))

r, p = 'base-boot-telemetry-sanitize', 'BASEBTS'
add(r,p,'boot-active','BOOT-UPDATE,BOOT-MODEL',b('新 boot image 已寫入 partition，下一次使用的 active partition 就已改變了嗎？','Does writing a new boot image to a partition also change the active partition?'),b('寫入與選擇 active ID 是兩個動作。CA=110b 寫入指定 partition；可讀回確認內容後，再以 CA=111b 選擇 active ID。把兩步分開，才能在切換前確認新 image。','Writing and selecting the active ID are separate actions. CA=110b writes the selected partition; after an optional readback, CA=111b selects the active ID. This separation allows checking the image before switching.'))
add(r,p,'boot-reset','BOOT-FID,BOOT-RESET',b('Boot Partition 解鎖後，Controller Level Reset 一定會重新上鎖嗎？','Must a Controller Level Reset relock an unlocked Boot Partition?'),b('要先知道由哪個機制控制。Set Features 的 unlocked 狀態可跨此 reset 保留，但 power cycle 會上鎖；已啟用的 RPMB 保護則在這兩種事件都會重新上鎖。','First identify the controlling mechanism. The Set Features unlocked state survives this reset but a power cycle relocks it. With RPMB protection enabled, either event relocks it.'))
add(r,p,'telemetry-areas','TEL-MODEL',b('Area 1 的 Last Block=3，Area 2 的 Last Block=7；Area 2 包含哪些 payload blocks？','If Area 1 Last Block is 3 and Area 2 Last Block is 7, which payload blocks belong to Area 2?'),b('Area 2 包含 blocks 1 到 7，共 7×512=3584 bytes，已包含 Area 1 的 blocks 1 到 3。Header 是 block 0，另占 512 bytes；Last Block 是包含在範圍內的最後編號。','Area 2 contains blocks 1 through 7, totaling 7×512=3584 bytes, including Area 1 blocks 1 through 3. The header is block 0 and occupies another 512 bytes. Last Block is inclusive.'))
add(r,p,'telemetry-generation','TEL-CONSISTENCY,TEL-TCDA',b('分段讀完 Telemetry 後，為何還要重讀 header？','Why reread the Telemetry header after collecting its data in chunks?'),b('分段期間可能出現另一代 snapshot。重讀 generation 可確認資料是否仍屬同一代；若改變便須重收。Controller-initiated 資料還要檢查 TCDA，避免忽略其他讀取者已確認資料的情況。','A new snapshot generation may appear during collection. Rereading generation checks that the chunks still belong together; a change requires recollection. For controller-initiated data, also check TCDA to account for acknowledgement by another reader.'))
add(r,p,'sanitize-completion','SAN-BACKGROUND,SAN-STATUS,SAN-PROGRESS',b('Sanitize 命令回報 Successful Completion，是否可以立即宣告清除完成？','Does Successful Completion of the Sanitize command mean sanitization has finished?'),b('它表示啟動命令成功，背景 operation 可能仍在進行。後續要用相應的 Sanitize Status 判斷 operation 狀態；SPROG 與時間估計提供進度資訊，不能取代最終狀態。','It indicates success of the initiating command; the background operation may still be running. Use the corresponding Sanitize Status to determine the operation state. SPROG and time estimates describe progress and do not replace the final status.'))
add(r,p,'sanitize-data','SAN-METHOD,NVM-VALUES,NVM-VERIFY',b('為何不能用「讀回全零」作為所有 sanitize 方法的共同成功標準？','Why is an all-zero readback not a universal success criterion for sanitization?'),b('各方法的讀值規則不同，且 deallocation 會改用另一組規則。Block Erase、Crypto Erase、Overwrite 不能用同一預期 pattern 判斷；Media Verification state 也有自己的讀取語意。先確認 operation 狀態，再按方法與 block 狀態解釋資料。','Methods have different read-value rules, and deallocation selects another set of rules. Block Erase, Crypto Erase, and Overwrite do not share one expected pattern; Media Verification also has its own read semantics. Establish the operation state before interpreting data by method and block state.'))

r, p = 'base-ch1-2', 'BASE12'
add(r,p,'spec-family','FAMILY,COMMANDSET',b('要了解 Read 做什麼，以及它如何經 PCIe 傳送，為何需要查不同規格？','Why do Read semantics and delivery over PCIe require different specifications?'),b('Command Set 定義命令對資料的作用；Transport 定義命令與完成如何經連接方式交換；Base 提供共用的 controller、queue 與管理模型。三者共同描述一次完整操作。','The Command Set defines the operation on data; the Transport defines how commands and completions cross the connection; Base supplies the shared controller, queue, and management model. Together they describe the complete operation.'))
add(r,p,'queue-doorbell','QUEUE',b('Host 寫 doorbell 時，命令本身放在哪裡？','Where is the command itself when the host writes a doorbell?'),b('命令已放在 Submission Queue 的 entry 中。Doorbell 更新 queue 的進度資訊，讓 controller 知道可處理的範圍；它不是整筆命令的承載位置。','The command is already in a Submission Queue entry. The doorbell updates queue progress so the controller can determine the available work; it does not carry the entire command.'))
add(r,p,'shared-namespace','SUBSYSTEM,MULTIPATH',b('同一 namespace 可由 2 個 controllers 存取，是否代表有 2 份資料？','If two controllers access one namespace, does that imply two data copies?'),b('不代表。Controller 是存取端點，namespace 是邏輯儲存空間；多個存取端點可以連到同一空間。是否有實體副本屬另一層的儲存實作問題。','No. A controller is an access endpoint, while a namespace is logical storage. Multiple endpoints can reach the same space. Physical replication is a separate storage-implementation concern.'))
add(r,p,'units','NUMBERS,DWORD',b('看到某長度欄位的 raw value 為 3，為何不能立即說它是 3 bytes？','Why can a raw length value of 3 not immediately be interpreted as 3 bytes?'),b('必須先確認單位和編碼。若是 zero-based 的 dword 數，3 代表 4 dwords，也就是 16 bytes；若是實際 byte 數，才是 3 bytes。','The unit and encoding must be established first. A zero-based dword count of 3 means 4 dwords, or 16 bytes. An actual byte count of 3 instead means 3 bytes.'))

r, p = 'base-ch3', 'BASE3'
add(r,p,'ready','PROPERTY,INIT',b('讀到 controller 支援某功能，是否表示它已準備接收 I/O？','Does a reported controller capability establish that it is ready for I/O?'),b('Capability 描述能做什麼；初始化與 ready state 描述目前能否開始操作。仍須完成 queue 設定、啟用與 readiness 確認，再依適用條件使用該功能。','Capability describes what is supported; initialization and ready state describe whether operation can begin now. Queue setup, enablement, and readiness checks still precede use under the applicable conditions.'))
add(r,p,'queue-order','QUEUE,PROCESS',b('SQ 中先提交的命令，是否必定先完成？','Must a command submitted earlier in an SQ complete first?'),b('Queue 提交順序、controller 選取工作及完成順序是不同概念。一般不能只靠 SQ 位置推論完成順序；有相依性時應使用規格定義的同步或命令機制。','Submission order, controller work selection, and completion order are distinct. SQ position alone generally cannot establish completion order; dependencies require the synchronization or command mechanisms defined by the specification.'))
add(r,p,'shutdown-reset','SHUTDOWN,RESET',b('為何正常關機流程不能直接等同 reset？','Why is an orderly shutdown not equivalent to a reset?'),b('Shutdown 包含 host 的通知及 controller 的完成狀態，讓關機前的處理有明確交接；reset 依其層級改變 controller 或 subsystem 狀態。它們的觸發、範圍和保留狀態不同。','Shutdown includes host notification and controller completion status, providing an explicit handoff before power removal. A reset changes controller or subsystem state according to its level. Their triggers, scope, and retained states differ.'))
add(r,p,'memory-regions','MEDIA,CAPACITY',b('Controller 可見的記憶體區域，為何不能全都當成 namespace 容量？','Why can controller-visible memory regions not all be counted as namespace capacity?'),b('Namespace 提供以 logical blocks 存取的儲存空間；CMB、PMR 等區域有各自用途、存取方式及持久性規則。位於同一裝置不代表它們使用相同的容量與資料模型。','A namespace provides storage addressed as logical blocks. Regions such as CMB and PMR have their own purposes, access methods, and persistence rules. Being on the same device does not give them the same capacity or data model.'))

r, p = 'base-ch4', 'BASE4'
add(r,p,'command-id','CID,CQE',b('2 個 SQ 都使用 CID=5，收到 completion 時該如何分辨命令？','If two SQs use CID=5, how is a completion associated with its command?'),b('CID 的唯一性範圍是同一 SQ 的 outstanding commands。完成資訊需要連同 SQ identifier 解讀，才能找到正確 SQ 中的那筆命令。','CID is unique among outstanding commands within one SQ. Interpret it together with the SQ identifier in the completion information to find the command in the correct queue.'))
add(r,p,'phase-status','PHASE,STATUS',b('CQE 的 Phase Tag 符合 host 期待值，是否表示命令成功？','Does a CQE with the expected Phase Tag establish command success?'),b('Phase Tag 讓 host 辨認這個位置的新 completion；是否成功則由 Status Code Type、Status Code 等狀態資訊決定。新資料與成功結果是兩個判斷。','The Phase Tag identifies a new completion at that location. Success is determined from status information such as Status Code Type and Status Code. Freshness and success are separate decisions.'))
add(r,p,'prp-offset','PRP',b('PRP1 位於 page 中間時，為何跨頁後不能直接延續同一段實體地址？','Why can a PRP1 starting inside a page not imply physically contiguous memory across the next page?'),b('PRP1 提供第一段的 page offset；跨頁後由後續 PRP page address 或 PRP List 指定資料位置。Host 的邏輯連續 buffer 不必對應連續的實體 pages。','PRP1 supplies the page offset of the first segment. Subsequent PRP page addresses or a PRP List find data after a boundary. A logically continuous host buffer need not occupy physically adjacent pages.'))
add(r,p,'pointer-format','PSDT,SGL',b('為何解讀 DPTR 前要先看 PSDT？','Why inspect PSDT before interpreting DPTR?'),b('DPTR 的同一組 bits 可依選定格式表達 PRP 或 SGL。先確認 PSDT 與命令支援條件，才知道應把後續資料當 page pointers 或 segment descriptors。','The same DPTR bits can represent PRPs or an SGL depending on the selected format. PSDT and command support determine whether to interpret them as page pointers or segment descriptors.'))

r, p = 'pcie-transport-1.4', 'PCIE14'
add(r,p,'memory-mmio','MMIO,QUEUE',b('PCIe MMIO properties 和 host memory 中的 queues 分別扮演什麼角色？','What roles do PCIe MMIO properties and host-memory queues play?'),b('Properties 提供 controller 設定、狀態與 queue 通知介面；queues 承載命令和完成項目。將控制介面與資料結構分開，才能理解一次提交如何運作。','Properties provide controller configuration, status, and queue notification interfaces. Queues carry command and completion entries. Separating the control interface from those structures explains how submission works.'))
add(r,p,'doorbell-stride','DOORBELL',b('為何不能假設所有 controller 的相鄰 doorbells 都相距 4 bytes？','Why is it unsafe to assume adjacent doorbells are always 4 bytes apart?'),b('Doorbell spacing 由 CAP.DSTRD 決定，stride 是 2^(2+DSTRD) bytes。只有 DSTRD=0 時才是 4 bytes；SQ Tail 與 CQ Head 的位置還需搭配 queue ID 計算。','CAP.DSTRD determines the spacing: stride is 2^(2+DSTRD) bytes. It is 4 bytes only when DSTRD=0; queue ID also determines the SQ Tail and CQ Head locations.'))
add(r,p,'interrupt','INTERRUPT,COMMAND',b('收到 interrupt 後，為何仍需讀取 CQ？','Why must the host inspect the CQ after an interrupt?'),b('Interrupt 是通知，CQE 才包含命令識別與完成狀態。一個通知不必等於一個完成項目；host 應依 queue 的有效項目與進度處理完成。','The interrupt is a notification; CQEs contain command identity and completion status. One notification need not correspond to one completion entry, so the host processes valid entries according to queue progress.'))
add(r,p,'error-layer','ERROR,CONFIG',b('NVMe 命令的 status 與 PCIe 錯誤回報，為何需要分開看？','Why distinguish NVMe command status from PCIe error reporting?'),b('前者描述命令處理結果，後者描述傳輸與裝置層的錯誤資訊。兩者可能相關，但解釋的對象不同，不能把某一層的成功當成所有層都沒有問題。','The former describes command processing; the latter describes transport and device-level errors. They can be related, but they address different objects. Success in one layer does not establish the state of every layer.'))

r, p = 'base-admin-fw-logs', 'BASEFWLOG'
add(r,p,'download-activate','DOWNLOAD-RANGE,COMMIT-PURPOSE',b('Firmware Image Download 完成後，controller 是否已執行新韌體？','Is new firmware executing as soon as Firmware Image Download completes?'),b('Download 是傳送 image；Commit 才依 action 決定保存或啟用，且啟用可能需要指定 reset。要結合 Commit 結果與 slot 資訊確認目前執行版本。','Download transfers the image. Commit selects storage or activation behavior, and activation may require a specified reset. Commit results and slot information establish the currently running version.'))
add(r,p,'download-units','DOWNLOAD-FIELDS',b('NUMD=255 與 OFST=256 分別描述什麼？','What do NUMD=255 and OFST=256 describe?'),b('NUMD 是 zero-based dword 長度，表示這次傳送 256 dwords，也就是 1024 bytes；OFST 是從 image 起點算的 dword offset，表示起點在 1024 bytes。相同數量附近的值，編碼用途不同。','NUMD is a zero-based dword length: 256 dwords, or 1024 bytes, are transferred. OFST is a dword offset from the image start, so the transfer begins at byte 1024. Their encoding roles differ.'))
add(r,p,'slot-version','LID03-AFI,LID03-FRS',b('某 slot 的 FRS 顯示新版本，能否單憑這一點宣告它正在執行？','Does a new version in a slot’s FRS prove that it is running?'),b('FRS 描述 slot 中的 revision；還需看 active slot 與 next-active slot 資訊。已儲存、目前執行和下次啟用可以指向不同狀態。','FRS describes the revision stored in a slot. Active-slot and next-active-slot information are also needed. Stored, currently running, and pending activation are distinct states.'))
add(r,p,'firmware-domain','MODEL-DOMAIN',b('為何不能總把 firmware update 視為單一 controller 的私有變更？','Why is a firmware update not always a private change to one controller?'),b('Firmware 的作用範圍可能涉及共用的 domain 或 NVM subsystem 資源。先建立 controller 與更新範圍的關係，才能理解其他 controllers 受到的影響。','Firmware scope may involve shared domain or NVM subsystem resources. Establish the relationship between the controller and update scope to understand effects on other controllers.'))

r, p = 'base-power-features', 'BASEPOWER'
add(r,p,'feature-values','GET-SELECT,GET-SAVED,GET-CAP',b('Supported、Current、Default、Saved 為何不能視為同一個 Feature 值？','Why are Supported, Current, Default, and Saved not interchangeable Feature values?'),b('Supported Capabilities 描述該 Feature 可如何使用；Current 是目前值，Default 是預設值，Saved 是已保存值且須符合支援條件。讀取時的選擇決定回覆意義。','Supported Capabilities describes how the Feature may be used. Current is the active value, Default the default value, and Saved the persisted value subject to support. The read selection determines the reply’s meaning.'))
add(r,p,'power-latency','POWER-METRICS,TRANSITION',b('閒置功率最低的 Power State，為何未必適合頻繁進出 I/O 的負載？','Why might the lowest-idle-power state be unsuitable for a workload that frequently resumes I/O?'),b('每次進出狀態都可能付出 transition latency。短暫閒置省下的電力，需要連同進入與離開延遲、工作反應時間一起評估；不能只比較 power 數字。','Transitions can incur latency on every entry and exit. Savings during a short idle period must be evaluated alongside entry/exit delays and response-time needs, rather than power numbers alone.'))
add(r,p,'apst','FID0C,APST-ENTRY',b('APST entry 的 idle time 與 target state 各決定什麼？','What do idle time and target state determine in an APST entry?'),b('Idle time 指定符合條件後等待多久才自動轉換；target 指定要轉往哪個 Power State。兩者要搭配目標狀態的能力與限制，才能形成可用的節能策略。','Idle time specifies the wait before an automatic transition under the applicable conditions. The target selects the destination Power State. Both must be combined with that state’s capabilities and restrictions.'))
add(r,p,'thermal-controls','FID04,HCTM',b('Temperature Threshold 和 HCTM 為何需要分開設定與解讀？','Why configure and interpret Temperature Threshold separately from HCTM?'),b('Temperature Threshold 用於溫度條件與通知；HCTM 提供 host 控制的熱管理行為。得知溫度越界與要求 controller 採取熱管理不是同一動作。','Temperature Threshold governs temperature conditions and notifications; HCTM provides host-controlled thermal-management behavior. Learning that a threshold was crossed and requesting thermal management are different actions.'))

r, p = 'base-self-test-hmb-emulation', 'BASEDIAGMEM'
add(r,p,'selftest-progress','SELFTEST-COMPLETION,SELFTEST-CURRENT',b('Device Self-test 啟動命令成功後，如何知道測試是否還在執行？','After a successful Device Self-test start command, how can ongoing execution be determined?'),b('啟動 completion 不包含整個測試的最終結果。Device Self-test log 的 current operation 與 completion percentage 描述目前進度；結果紀錄則用於已結束的測試。','The start completion is not the test’s final outcome. The Device Self-test log reports current operation and completion percentage for ongoing work, while result records describe finished tests.'))
add(r,p,'flba-valid','SELFTEST-VALIDITY,SELFTEST-NVM-FLBA',b('Self-test result 中 FLBA 看起來是合理地址，就一定可以當作失敗位置嗎？','Can a plausible FLBA in a self-test result always be treated as the failure location?'),b('要先檢查對應的 validity bit；未宣告有效時不能依數值推論。即使有效，也可能只描述多個失敗 logical blocks 中的一個，並非完整範圍。','Check its validity bit first; the value cannot be interpreted if it is not marked valid. Even when valid, it may identify only one of several failed logical blocks, rather than the complete range.'))
add(r,p,'hmb-ownership','HMB-OWNERSHIP,HMB-SEQUENCE',b('HMB 記憶體原本由 host 配置，host 是否能在 controller 使用時直接重用？','Can the host repurpose HMB memory while the controller is using it just because the host allocated it?'),b('不能。提供給 controller 的期間必須維持記憶體與描述資訊有效；應完成規定的停用及交還程序後才回收。實體配置者與目前可使用者是不同概念。','No. The memory and its descriptors must remain valid while provided to the controller. Reclaim it only after the specified disable and return procedure. Allocation ownership and current permitted use are distinct.'))
add(r,p,'hmb-size','HMB-DESCRIPTORS,HMB-NUMERIC',b('知道 HMB descriptor 有 4 筆，就知道總容量了嗎？','Does knowing that HMB has four descriptors establish its total capacity?'),b('還需要每筆 buffer size 和 page size。Descriptor 數只計算分段數；總容量是各段 page 數乘 page size 後加總，並需符合 HSIZE 與能力限制。','Each buffer size and the page size are also needed. Descriptor count measures segments; total capacity is the sum of segment page counts multiplied by page size, subject to HSIZE and capability limits.'))

r, p = 'base-self-test-namespace-management', 'BASENSMGMT'
add(r,p,'create-attach','CREATE-COMPLETION,ATTACH-COMMAND',b('Namespace Create 成功並回傳 NSID，為何還不能直接假設某 controller 可以對它做 I/O？','Why does a successful Namespace Create returning an NSID not establish I/O access through a controller?'),b('Create 建立 namespace；Attachment 決定哪些 controllers 可以存取。還要確認 attachment 與 Identify 所回報的可見性、格式及可用狀態。','Create establishes the namespace; Attachment determines which controllers can access it. Attachment, Identify visibility, format, and availability still require confirmation.'))
add(r,p,'granularity','ALLOCATION-ROUNDING,GRANULARITY-HINTS',b('Namespace granularity hint 與實際媒體配置的 rounding，為何不能混為一談？','Why distinguish a namespace granularity hint from rounding in media allocation?'),b('Hint 協助 host 選擇合適的 size 或 capacity；rounding 描述實際配置可能耗用的資源。Hint 不是任意加上的命令合法性限制，容量規劃也不能只看 host 要求的數值。','A hint helps the host choose a suitable size or capacity; rounding describes resources that actual allocation may consume. A hint is not an extra command-validity restriction, and capacity planning must account for more than the requested values.'))
add(r,p,'restore-default','RESTORE-DEFAULT,DELETE',b('Restore Default Namespace 是否表示恢復已刪除 namespace 的原有資料？','Does Restore Default Namespace recover the original data of a deleted namespace?'),b('它處理預設 namespace 配置，不是資料復原命令。Namespace 的建立、刪除與預設配置流程，不能被當成保留或找回舊資料的保證。','It concerns the default namespace configuration, not data recovery. Creation, deletion, and default-configuration operations do not guarantee preservation or recovery of prior data.'))
add(r,p,'test-history','SELFTEST-CURRENT,SELFTEST-HISTORY',b('最新一筆 self-test 歷史紀錄，是否必定屬於目前正在執行的測試？','Does the newest self-test history record necessarily describe the test currently in progress?'),b('歷史紀錄描述已產生的結果；目前 operation 與其進度另有欄位。閱讀時先分清 ongoing test 與 completed result，才不會把上一次結果當作這次結果。','History contains results already produced, while separate fields describe the current operation and progress. Distinguish an ongoing test from a completed result to avoid attributing the previous outcome to the current test.'))
