from scripts.nvme_scenarios import case

case('logs',('SMART 顯示 120%，是不是已經不能用了？','Does 120% Percentage Used mean the drive has failed?'),
('健康報告只顯示一個紅色「120%」。請把真正能從 SMART 得到的結論拆開。','A health report shows only a red “120%.” Separate the conclusions that SMART actually supports.'),
[('LID=02h：Percentage Used=120；Available Spare=9；Available Spare Threshold=10；Critical Warning 的 spare 位=1。','LID=02h: Percentage Used=120; Available Spare=9; Available Spare Threshold=10; the spare critical-warning bit is one.'),('Composite Temperature=300 K；本次沒有提供近期 I/O 成敗紀錄。','Composite Temperature=300 K; no recent I/O success/failure trace is provided.')],
('Get Log Page LID=02h 取得 SMART／Health；保留 warning bitmap 與各自的數值欄位，不合併成一個「健康分數」。','Get Log Page LID=02h for SMART/Health; retain the warning bitmap and individual measurements instead of combining them into one health score.'),
[('Percentage Used 是預估壽命耗用，容許超過 100；120 不等於已損壞 120%，也不能單獨證明裝置現在不能讀寫。','Percentage Used estimates endurance consumption and may exceed 100. A value of 120 is not 120% damaged and does not alone establish inability to read or write.'),('Available Spare=9 低於門檻 10，且對應 warning 已置位，這才是本例可直接說明的備援空間警告。300 K 約為 26.85°C，屬另一種量測，不應與百分比相加。','Available Spare=9 is below threshold 10 with the corresponding warning asserted. That is a directly supported spare warning. Temperature 300 K is about 26.85°C, a different measurement that cannot be added to percentages.'),('完整報告應分列壽命估計、目前警告及近期錯誤／I/O 行為。要判定能否繼續服務，還需要系統需求與實際行為資料；這份 log 不提供一個能替代全部判斷的總分。','Report endurance estimate, current warnings and recent error/I/O behavior separately. Continued service decisions also need system requirements and observed behavior; the log does not supply one universal decision score.')],
'B213','B213:247-251')

case('logs',('Data Units Written 增加 4，實際寫了多少？','How much data does a four-unit DUW increase represent?'),
('監控程式將 SMART 的 Data Units Written 差值乘以 512，得到很小的寫入量。這少算了什麼？','Monitoring multiplies a SMART Data Units Written delta by 512 and reports a tiny workload. What is missing?'),
[('相同對象的兩次 DUW：1000 → 1004；計數有效，無重置或飽和；取樣相隔 60 seconds。','DUW for the same target changes from 1000 to 1004; counters are valid, without reset or saturation; samples are 60 seconds apart.'),('Host Write Commands 同期增加 80；沒有完整命令大小清單。','Host Write Commands rises by 80; no complete list of command lengths is available.')],
('兩次 Get Log Page LID=02h；同時保存 NSID、取樣時間、DUW 與 Host Write Commands。','Take two LID=02h samples, retaining NSID, timestamps, DUW and Host Write Commands.'),
[('DUW 以 1000 個 512-byte units 為一個回報單位，並向上取整。差值 4 對應約 4×1000×512=2048000 bytes 的量級，不是 2048 bytes。','DUW reports thousands of 512-byte units, rounded up. A delta of four corresponds to roughly 4×1000×512=2048000 bytes, not 2048 bytes.'),('兩個端點都經過取整，因此這不是精確的 60 秒 payload byte 數。拿它除以 80，也只能得到粗略平均，不能反推每個 Write 都是同樣大小。','Both endpoints are rounded, so this is not the exact payload byte count for those 60 seconds. Dividing by 80 yields only an approximate average, not proof that all Writes had the same size.'),('要驗證某筆命令的長度，回到命令 NLB 與使用中 LBA 格式；要看长期趨勢，才使用這種累計差值。也不要把 host 寫入量直接當作 NAND 實際寫入量。','For one command’s length, use its NLB and active LBA format; cumulative deltas serve longer-term trends. Host-written data also must not be equated directly with physical NAND writes.')],
'B213 N54 N125','B213:247-251 N54:49 N125:94')

case('logs',('指定 NSID，就能得到該 namespace 的 SMART 嗎？','Does specifying an NSID guarantee per-namespace SMART?'),
('報表把同一張 SMART 複製到每個 namespace，並聲稱是各自的使用量。能力資料是否支持這樣標示？','A report copies one SMART page to every namespace and labels each as individual usage. Does capability data support that?'),
[('Identify Controller 的 LPA：per-namespace SMART／Health 支援位=0。','Identify Controller LPA reports no per-namespace SMART/Health support.'),('目前讀取的是 NSID=FFFFFFFFh 的 LID=02h；controller 有 4 個 active namespaces。','The current LID=02h sample uses NSID=FFFFFFFFh; the controller has four active namespaces.')],
('Identify CNS=01h 查 LPA；按 SMART 定義選擇 NSID；能力不提供的細分資訊不能靠改報表標籤補出來。','Identify CNS=01h for LPA; select NSID according to SMART rules. A report label cannot create a granularity the capability does not provide.'),
[('此份資料不是 4 份獨立的 per-namespace 統計。NSID=FFFFFFFFh 的回報應依該 log 的總體範圍標示，不能複製後再相加，否則同一份量會被重複算 4 次。','This is not four independent per-namespace measurements. Label the FFFFFFFFh report by its aggregate scope; copying and summing it would count the same measurement four times.'),('想改用特定 NSID，先要有 per-namespace SMART 支援，並遵守該 log 的 namespace 規則。不能因 Get Log Page 有 NSID 欄位，就假設每個 LID 都提供任意層級的統計。','A specific-NSID request requires per-namespace SMART support and the log’s namespace rules. The existence of an NSID field in Get Log Page does not grant every LID arbitrary reporting granularity.'),('若需要區分 Endurance Group，可再查 namespace 的 ENDGID 與 LID=09h；那仍是 group 統計，不是自動變成單一 namespace 或檔案系統統計。','For Endurance Group granularity, inspect namespace ENDGID and LID=09h. Those remain group statistics, not automatically individual namespace or filesystem measurements.')],
'B338 B213 B225','B338:381-382 B213:247-251 B225:264-265')

case('logs',('兩個 namespace 的警告其實來自同一個 group？','Do two namespace alerts describe one shared group?'),
('管理系統對 NSID=2、NSID=9 各發出一次耐久度警告。要怎麼判斷是否重複通報同一個對象？','Management issues endurance alerts for NSID=2 and NSID=9. How can you determine whether they duplicate one group-level condition?'),
[('兩個 namespace 的 Identify 資料均為 ENDGID=3；LID=09h、LSI=3 的 Critical Warning 非零。','Both namespaces identify ENDGID=3; LID=09h with LSI=3 has a nonzero Critical Warning.'),('沒有 group 4 的查詢結果，也沒有證據顯示 namespace 配置在期間變更。','No result is available for group 4, and no inventory change is observed during the interval.')],
('Identify CNS=00h、各自 NSID → ENDGID → Get Log Page LID=09h、LSI=ENDGID。','Identify CNS=00h for each NSID → ENDGID → Get Log Page LID=09h with LSI=ENDGID.'),
[('兩個 namespace 都指向 group 3，因此同一份 group log 可以影響兩個 namespace 的風險呈現；但警告來源只有一個 group。報表應保留 namespace 與 group 的對應，不把它算成兩個獨立 group 故障。','Both namespaces map to group 3. One group condition can affect how both namespaces are presented, but it remains one group-level source. Retain the mapping rather than counting two independent group failures.'),('LSI 在這個 LID 用來選 Endurance Group，不是 NSID，也不是傳輸長度的高位。把 NSID=9 填成 LSI=9，會查另一個對象，無法回答 group 3 的問題。','For this LID, LSI selects the Endurance Group, not an NSID or high transfer-length bits. Substituting NSID=9 into LSI would select another target rather than answer the group-3 question.'),('group 3 的警告也不能延伸成所有 group 都有警告。若要比較 group 4，必須先確認其存在並取得同時段、相同欄位的資料。','A warning in group 3 does not establish a warning in every group. To compare group 4, verify its existence and obtain corresponding measurements from the same interval.')],
'B225 B205 N123','B225:264-265 B205:240 N123:90-93')

case('logs',('Self-test 沒有在跑，FLBA=0 就表示 LBA 0 壞了？','Does FLBA=0 identify a failed LBA when self-test is idle?'),
('工具同時顯示「測試卡在 45%」及「LBA 0 故障」。請用欄位有效性找出兩個誤判。','A tool reports both “test stuck at 45%” and “LBA 0 failed.” Find the two validity errors.'),
[('LID=06h：目前 DSTOS=0，完成百分比 bytes 留著 45。最新結果 DSTR=2。','LID=06h: current DSTOS=0, with percentage bytes containing 45; newest result DSTR=2.'),('最新結果的 VDINFO.FVLD=0，而 FLBA 原始 bytes 全為 0。','The latest result has VDINFO.FVLD=0 and all-zero raw FLBA bytes.')],
('Get Log Page LID=06h；先讀目前 operation，再讀最新 Result 的 DSTR 與 VDINFO，最後才使用診斷欄位。','Get Log Page LID=06h; read current operation, then newest-result DSTR and VDINFO, and only then interpret diagnostic fields.'),
[('DSTOS=0 表示沒有正在執行的 self-test，進度欄應忽略。它不是一個仍有效但停住的 45% 進度，不能拿來計算「已經卡住多久」。','DSTOS=0 means no self-test is in progress, so ignore the percentage field. It is not a valid stalled 45% progress measurement from which to calculate a stall duration.'),('DSTR=2 表示操作因 Controller Level Reset 中止，與測試發現媒體失敗不同。應報告中止原因，而不是將所有非零結果統稱為測試失敗。','DSTR=2 identifies termination by Controller Level Reset, distinct from a test detecting media failure. Report the termination reason rather than collapsing every nonzero result into a detected media defect.'),('FVLD=0 使 FLBA 無效；零只是無效欄位中的原始值，不是有效的故障 LBA 0。對 NSID、SCT、SC 也要依各自有效位判斷，不能從填充 bytes 編造診斷。','FVLD=0 makes FLBA invalid. Zero is merely raw content in an invalid field, not evidence of failed LBA zero. Apply the respective validity bits to NSID, SCT and SC as well.')],
'B218 B219','B218:256 B219:257-258')

case('logs',('分段 Telemetry 可以把兩個 generation 拼在一起嗎？','Can Telemetry chunks from different generations be combined?'),
('你要保存一次 controller-initiated telemetry，讀完後才發現前後 header 不同。這份合併檔還能當同一次快照嗎？','You collect controller-initiated Telemetry in chunks and then notice different headers. Is the combined file one coherent capture?'),
[('LID=08h 首次 header：TCDGN=10、TCDA=1、DA1LB=3；最後重讀：TCDGN=11、TCDA=1。','Initial LID=08h header: TCDGN=10, TCDA=1, DA1LB=3; final reread: TCDGN=11, TCDA=1.'),('兩次 header 之間分段讀取資料；無完整紀錄證明各 chunk 屬於哪一代。','Data is read in chunks between the headers; there is no complete record assigning each chunk to a generation.')],
('Get Log Page LID=08h，保留 RAE、header 與每次 offset；對照 TCDGN、TCDA 及 Data Area 邊界。','Get Log Page LID=08h, retaining RAE, headers and each offset; compare TCDGN, TCDA and Data Area boundaries.'),
[('generation 改變表示不能直接把這些 chunks 宣稱為同一份 capture。應標示一致性未確認，重新按該 log 的擷取與確認流程取得一份可追蹤的資料，而非只保留最後的 header。','The generation change prevents claiming these chunks as one coherent capture. Mark consistency as unverified and reacquire through the log’s capture/acknowledgment process rather than merely replacing the file header.'),('DA1LB=3 表示 Data Area 1 到 block 3；block 0 是 512-byte header，因此 header 加 Area 1 的範圍是 4×512=2048 bytes。這個長度資訊不會消除 generation 不一致。','DA1LB=3 places the Area 1 endpoint at block three; block zero is the 512-byte header. Header plus Area 1 therefore spans 4×512=2048 bytes. Correct length does not resolve generation inconsistency.'),('TCDA 是更新確認相關狀態，不是 payload 格式解碼器。即使完整取到同一代資料，內部內容仍可能由廠商定義；不能從共同 header 推測每個 vendor byte 的意義。','TCDA concerns update acknowledgment, not payload decoding. Even a coherent capture can contain vendor-defined internals; a common header does not define every vendor byte.')],
'B223 B204 B208','B223:262-263 B204:239 B208:240-241')

case('logs',('Persistent Event Log 的下一筆應從哪裡開始？','Where does the next Persistent Event Log record begin?'),
('解析器讀完第一筆就錯位，而且重新建立 context 後遇到 Command Sequence Error。請分別檢查生命週期與長度計算。','A parser loses alignment after its first record and gets Command Sequence Error when establishing context again. Inspect lifecycle and length separately.'),
[('ACT=3 成功回傳 header，RCE=0；未釋放 context。第一筆 offset=512、EHL=21、EL=28、VSIL=8。','ACT=3 succeeds with header RCE=0; the context has not been released. First record: offset=512, EHL=21, EL=28, VSIL=8.'),('header 的總長度足以容納此筆；ET／ETR 已確認為支援的格式。','The header’s total length accommodates this record; ET/ETR identify a supported format.')],
('Get Log Page LID=0Dh，以 ACT 管理 context；讀 header 後使用 ACT=0 讀取同一份 report，按 event header 走訪。','Get Log Page LID=0Dh with ACT-controlled context; after the header, use ACT=0 on the same report and traverse event headers.'),
[('ACT=3 的 RCE=0 表示命令處理前沒有 reporting context，不表示成功後仍沒有。此時再送 ACT=1 去建立，會與已存在的 context 衝突；後續讀取應沿用它。','For ACT=3, RCE=0 means no reporting context existed before processing, not that none exists after success. A subsequent ACT=1 establishment conflicts with that context; subsequent reads should use it.'),('共同 header 長度為 EHL+3=24 bytes；EL=28 已包括 VSIL=8。Event Data 為 28−8=20 bytes，下一筆起點為 512+24+28=564，不能再加一次 VSIL。','The common header is EHL+3=24 bytes. EL=28 already includes VSIL=8, leaving 20 bytes of Event Data. The next record begins at 512+24+28=564; do not add VSIL again.'),('每筆仍要檢查長度是否超出 TLL、ET／ETR 是否可解，再繼續讀。完成後按規則釋放 context；讀完整個報告並不代表其中一定保存了系統歷史上每件事。','For each record, check bounds against TLL and whether ET/ETR can be decoded before continuing. Release the context when finished. A complete report does not imply that every event in system history was retained.')],
'B232 B233 B234','B232:272 B233:273-275 B234:275-276')
