"""Local definitions; the reader deduplicates them across visible and folded text."""
TERMS = {
 'NVM subsystem':('NVMe 中的儲存子系統，可以包含多個控制器；本篇的全體控制器以這個範圍計算。','The NVMe storage subsystem, which may contain multiple controllers; all-controller scope refers to this subsystem.'),
 'controller':('控制器；接收並處理 NVMe 命令的介面實體，同一 subsystem 可有多個。','A controller receives and processes NVMe commands; one subsystem may contain several.'),
 'namespace':('主機透過控制器存取的一份邏輯儲存空間；不是本篇 CSS 要選的控制器。','A logical storage space accessed through a controller, distinct from the controller selected by CSS.'),
 'Admin Submission Queue':('主機提交管理命令的佇列，本文也簡稱 Admin Queue。','The queue through which the host submits Admin commands, also shortened to Admin Queue here.'),
 'opcode':('操作代碼；先選要執行的命令，再由該命令的其他欄位提供參數。','An operation code selecting the command whose remaining fields supply its parameters.'),
 'buffer':('資料緩衝區；本篇指主機預留給 Log 回覆資料的記憶體。','A data buffer; here, host memory reserved to receive log data.'),
 'header':('資料結構開頭的固定欄位區，用來說明後方內容的種類、長度或數量。','The leading fields describing the following data, such as its type, size and count.'),
 'descriptor':('描述器；清單裡描述一個項目的資料結構。','A descriptor is the structure describing one list item.'),
 'payload':('命令另外傳送的資料內容，與 SQE 裡的命令參數區分。','Additional command data, distinct from the command parameters carried in the SQE.'),
 'SQE':('Submission Queue Entry；提交佇列中承載一筆命令及參數的項目。','Submission Queue Entry; contains a command and its parameters.'),
 'CQE':('Completion Queue Entry；完成佇列中回報某筆命令結果的項目。','Completion Queue Entry; reports the result of a command.'),
 'CID':('Command Identifier；主機指定的命令編號，配合佇列編號對應提交與完成。','Command Identifier; assigned by the host and paired with queue identity to match a completion.'),
 'DPTR':('Data Pointer；指定命令資料 buffer 的指標欄位。','Data Pointer; identifies the command data buffer.'),
 'LSP':('Log Specific Parameter；Get Log 中依 Log 種類解讀的 7-bit 參數。','Log Specific Parameter; a seven-bit parameter interpreted according to the requested log.'),
 'LSI':('Log Specific Identifier；Get Log 中依 Log 種類解讀的 16-bit 識別值。','Log Specific Identifier; a sixteen-bit identifier interpreted according to the requested log.'),
 'NUMD':('Number of Dwords；本篇 Get Log 傳輸長度採 Dword 數量減 1。','Number of Dwords; the Get Log transfer count encoded as Dwords minus one.'),
 'NUMDL':('Number of Dwords Lower；Get Log 傳輸計數的低 16bits。','Number of Dwords Lower; the low sixteen bits of the Get Log transfer count.'),
 'NUMDU':('Number of Dwords Upper；Get Log 傳輸計數的高 16bits。','Number of Dwords Upper; the high sixteen bits of the Get Log transfer count.'),
 'LPOL':('Log Page Offset Lower；Log 起讀位置的低 32bits。','Log Page Offset Lower; the low thirty-two bits of the starting position.'),
 'LPOU':('Log Page Offset Upper；同一 Log 起讀位置的高 32bits。','Log Page Offset Upper; the high thirty-two bits of that same starting position.'),
 'OT':('Offset Type；0 以 byte 距離指定 Log 起點，1 是需另有支援的清單索引方式。','Offset Type; zero selects byte offsets and one selects separately supported entry indices.'),
 'RAE':('Retain Asynchronous Event；控制讀 Log 是否保留相關非同步事件。','Retain Asynchronous Event; controls retention of the associated asynchronous event.'),
 'SZE':('Size；增強 Log 的完整 byte 大小，不是項目數。','Size; the enhanced log’s total size in bytes, not an item count.'),
 'VER':('Version；此 Log 資料格式的版本值。','Version; the version value of the log format.'),
 'CS':('Contents Selected；header 回報這份清單選的是可禁止或哪個入口已禁止。','Contents Selected; the header’s echo of eligibility or the selected incoming-interface prohibition query.'),
 'SS':('Scope Selected；header 回報清單內代碼所屬的種類。','Scope Selected; identifies the class of codes in the returned list.'),
 'DNR':('Do Not Retry；1 表示相同命令重送預期仍會失敗。','Do Not Retry; one indicates that resubmitting the same command is expected to fail.'),
 'CRD':('Command Retry Delay；在有效條件成立時選擇命令重試延遲。','Command Retry Delay; selects a retry delay when its validity conditions are met.'),
 'ACRE':('Advanced Command Retry Enable；主機是否啟用進階命令重試延遲的設定。','Advanced Command Retry Enable; the host setting enabling advanced retry-delay behavior.'),
 'PPS':('Personality Properties Size；一筆 personality 屬性結構的 byte 大小。','Personality Properties Size; bytes in a personality-properties structure.'),
 'PKAS':('Programmable Key Authentication Support；支援以可程式化金鑰認證解凍。','Programmable Key Authentication Support; support for the programmable-key unfreeze method.'),
 'PCAS':('Physical Credential Authentication Support；支援以實體憑證認證解凍。','Physical Credential Authentication Support; support for the physical-credential unfreeze method.'),
 'PSCUDE':('Personality Settings Change User Data Effect；表示配置變更是否可能影響使用者資料。','Personality Settings Change User Data Effect; indicates whether changing the configuration can affect user data.'),
 'ULEH':('UUID Lists Entry Header；單一 UUID 項目的 header。','UUID Lists Entry Header; the header within a UUID entry.'),
 'IDASSOC':('Identifier Association；UUID 與廠商識別資訊的關聯分類。','Identifier Association; classifies the UUID’s vendor association.'),
 'Lockdown':('本篇指 Command and Feature Lockdown：以操作種類、接收介面與控制器範圍限制管理操作的機制。','Command and Feature Lockdown restricts management operations by operation class, incoming interface and controller scope.'),
 'OFI':('Opcode or Feature Identifier；Lockdown 要禁止或允許的代碼，其種類由 SCP 選定。','Opcode or Feature Identifier; the target code interpreted according to SCP.'),
 'SCP':('Scope；指定代碼屬於 Admin opcode、Set Features FID 或管理介面命令集。','Scope; selects the code class: Admin opcode, Set Features FID or a management-interface command set.'),
 'IFC':('Interface；指定受限制操作從哪個介面收到時套用限制。','Interface; selects where an incoming operation is subject to the restriction.'),
 'CSEL':('Controller Select；選全部、單一或某 primary 所屬 secondary 控制器集合。','Controller Select; chooses all controllers, one controller or a primary’s secondaries.'),
 'CSS':('Controller Select Specific；在本命令 CDW14 中依 CSEL 提供目標或 primary 控制器編號。','Controller Select Specific; supplies the controller or primary identifier required by CSEL in this command.'),
 'PRHBT':('Prohibit；1 要求禁止，0 要求允許，作用對象由其餘選擇欄位決定。','Prohibit; one prohibits and zero allows the operation selected by the other fields.'),
 'OACS':('Optional Admin Command Support；Identify Controller 的選用管理命令與功能能力位元欄位。','Optional Admin Command Support; the Identify Controller capability bitmap for optional Admin commands and features.'),
 'CFLS':('Command and Feature Lockdown Supported；基本 Lockdown 支援位元。','Command and Feature Lockdown Supported; the basic capability bit.'),
 'CCFLS':('Controller-scoped Command and Feature Lockdown Supported；可選控制器範圍的擴充支援位元。','Controller-scoped Command and Feature Lockdown Supported; the controller-selection extension capability.'),
 'CNTTS':('Contents；選可禁止清單，或某種接收介面目前禁止的清單。','Contents; selects eligibility or current prohibitions on a particular incoming interface.'),
 'ELPF':('Enhanced Log Page Format；選一般或增強版 LID14h 資料格式。','Enhanced Log Page Format; selects the basic or enhanced LID14h structure.'),
 'CNTLID':('Controller Identifier；控制器的識別編號，增強 Log 查詢以 FFFFh 指定全體。','Controller Identifier; FFFFh selects all controllers for this enhanced-log query.'),
 'CFILA':('Command and Feature Identifier List Attributes；一般 Log 中描述清單種類的屬性。','Command and Feature Identifier List Attributes; the basic log’s list-meaning attributes.'),
 'CFIA':('Command and Feature Identifier Attributes；header 中的此欄說明清單種類，描述器中的同名欄說明 ACNTL，需看所在結構。','Command and Feature Identifier Attributes; the header field describes list meaning, while the descriptor field carries ACNTL.'),
 'CFIL':('Command and Feature Identifier List；一般格式內由小到大排列的代碼清單。','Command and Feature Identifier List; the ascending list of codes in basic format.'),
 'CFI':('Command and Feature Identifier；一筆增強描述器中，依 SCP 解讀的操作代碼。','Command and Feature Identifier; the descriptor’s operation code, interpreted by SCP.'),
 'LNGTH':('Length；一般格式代碼清單的 byte 數，直接計數，0 表示空清單。','Length; a direct byte count of the basic code list, with zero meaning empty.'),
 'NCFID':('Number of Command and Feature Identifier Descriptors；增強 Log 中的描述器數量，直接計數。','Number of Command and Feature Identifier Descriptors; a direct descriptor count.'),
 'CFIDS':('Command and Feature Identifier Descriptors Size；增強 Log 每筆描述器占用的 byte 數。','Command and Feature Identifier Descriptors Size; bytes per enhanced descriptor.'),
 'ACNTL':('All Controllers；1 表示所有控制器回報此項，0 表示至少一台但非全部。','All Controllers; one means every controller reports the item, zero means at least one but not all.'),
 'LDPE':('Lockdown Persistence Enable；啟用全體限制跨 power cycle 保留的設定。','Lockdown Persistence Enable; enables power-cycle persistence for all-controller prohibitions.'),
 'LDPS':('Lockdown Persistence State；讀回目前持續性是否啟用。','Lockdown Persistence State; reports whether persistence is currently enabled.'),
 'CDP':('Configurable Device Personality；將裝置配置分為可查詢、設定或凍結的 personality。','Configurable Device Personality; provides device configurations with query, change and freeze state.'),
 'personality':('規格中的一組裝置配置；本篇只用 Lockdown Persistence 這一種配置及其必要條件。','A device configuration defined by the specification; this report focuses on Lockdown Persistence.'),
 'frozen':('已凍結；表示這組 personality 設定不能任意改成其他值，不表示控制器停止所有 I/O。','Frozen settings cannot freely be changed to other values; this does not mean all controller I/O is stopped.'),
 'PERID':('Personality Identifier；選 CDP 功能中的一組配置，02h 是 Lockdown Persistence。','Personality Identifier; selects a CDP configuration, with 02h selecting Lockdown Persistence.'),
 'PERFS':('Personality Freeze State；在 Set 是凍結請求，在 Get 是凍結或待凍結的回報。','Personality Freeze State; a freeze request in Set and frozen/pending-freeze state in Get.'),
 'CHPS':('Change Personality Settings；指定 Set 是否要改變 personality 設定。','Change Personality Settings; selects whether Set changes the personality settings.'),
 'PPSC':('Pending Personality Settings Change；表示存在尚待生效的 personality 設定變更。','Pending Personality Settings Change; indicates a pending settings change.'),
 'PMDSS':('Personality Manufacturing Default Settings State；表示設定是否為製造預設值。','Personality Manufacturing Default Settings State; indicates manufacturing-default settings.'),
 'MRSTT':('Minimum Required Reset Type；使 personality 變更生效所需的最低 reset 類型。','Minimum Required Reset Type; the minimum reset type required to apply a personality change.'),
 'AUS':('Authenticated Unfreeze Support；支援哪些認證解凍方法的位元欄位。','Authenticated Unfreeze Support; a bitmap of supported authenticated-unfreeze methods.'),
 'SPSP':('Security Protocol Specific；Security 命令的協定專用選擇，本篇 0002h 限定 CDP Authentication 用途。','Security Protocol Specific; 0002h identifies the CDP Authentication use covered here.'),
 'UUID':('Universally Unique Identifier；128-bit 識別值，本篇用來區分同一廠商 FID 的不同定義。','Universally Unique Identifier; a 128-bit value distinguishing vendor definitions in this context.'),
 'UIDX':('UUID Index；命令帶入的 UUID List 索引，0 不指定 UUID。','UUID Index; the command’s UUID List index, with zero selecting no UUID.'),
 'Management Endpoint':('帶外管理接收入口；與主機的 Admin Submission Queue 分開選擇限制。','An out-of-band management endpoint, selected separately from the host Admin Submission Queue.'),
 'primary':('主要控制器；本篇 CSEL=2 用它的 Identifier 選其所屬 secondary 控制器集合。','A primary controller whose identifier can select its associated secondary controllers with CSEL=2.'),
 'secondary':('附屬控制器；本篇只需知道其與 primary 的所屬關係，不以名稱推論效能或優先級。','A secondary controller associated with a primary; the name does not indicate performance or priority.'),
 'index-offset':('以清單項目索引表示起點；和按 byte 距離表示起點不同，必須由該 Log 明確支援。','A starting position measured in list entries rather than bytes; the log must explicitly support it.'),
 'byte offset':('以 byte 計算、相對結構起點的距離；索引 2 不一定代表 offset2。','Distance in bytes from a structure’s start; index two need not mean byte offset two.'),
 'little-endian':('低位 byte 先存，例如 00 24 組成 16-bit 數值 2400h。','Least-significant byte first; bytes 00 24 form the 16-bit value 2400h.'),
 'power cycle':('整個指定裝置或 subsystem 的電源循環；本篇不能以一般 Controller Reset 代替。','A power cycle of the specified subsystem, distinct from an ordinary Controller Reset.'),
}
