from scripts.nvme_scenarios import case

case('command',('同一個 CID 出現兩次，是重複完成嗎？','Does the same CID twice imply duplicate completion?'),
('除錯工具只以 CID 比對命令，看到兩筆 CID=12h 就報重複完成。請設計正確的比對順序。','A debugger matches commands only by CID and reports two entries with CID=12h as duplicate completions. What is the correct matching order?'),
[('兩筆新 CQE 的 SQID 分別為 2、5，CID 都是 12h；兩個 SQ 各有一筆該 CID 的 outstanding command。','Two new CQEs have SQID=2 and SQID=5, both CID=12h; each SQ has one matching outstanding command.'),('另有一個 CQ slot 的 phase 不符合本輪 host 預期值；讀取記憶體的同步條件已滿足。','Another CQ slot has a phase different from the host’s expected phase for this traversal; memory synchronization requirements are satisfied.')],
('先檢查預期 phase → 只對新 CQE 讀 SQID／CID → 找回原 SQE → 再解 SCT／SC。','Check expected phase → read SQID/CID only from new CQEs → recover the SQE → decode SCT/SC.'),
[('CID 的唯一性是針對同一 SQ 的 outstanding commands，不是全 controller 的永久流水號。因此 (SQID=2, CID=12h) 與 (SQID=5, CID=12h) 可以代表不同命令。','CID uniqueness applies to outstanding commands within an SQ, not a controller-wide permanent sequence. Thus (SQID=2, CID=12h) and (SQID=5, CID=12h) can identify different commands.'),('phase 不符合預期的 slot 不能當本輪的新完成項目。若先掃 CID 再看 phase，可能把上輪殘留 bytes 誤判成重複完成；CQ wrap 後 host 也要更新預期 phase。','A slot with the wrong phase is not a new completion in this traversal. Scanning CID before phase can mistake previous contents for a duplicate, and the host must update expected phase on CQ wrap.'),('即使 SQID／CID 一致，跨 queue 刪除重建或命令結束後重用 CID，仍需要生命週期與時間資訊。留下完整 SQE／CQE 及 queue 身分，才有足夠資料追查。','Even matching SQID/CID requires lifecycle and timing context across queue recreation or later CID reuse. Preserve complete SQEs/CQEs and queue identity for reliable correlation.')],
'B92 B97 B98 B99','B92:165-166 B97:170 B98:170 B99:171')

case('command',('Invalid Field 指的是哪一個 bit？','Which bit does Invalid Field identify?'),
('CQE 只說 Invalid Field in Command。Error Information 提供的位置要怎麼對回 64-byte SQE？','CQE reports Invalid Field in Command. How do you map the Error Information location into a 64-byte SQE?'),
[('已比對同一命令的 SQID／CID；Error Information 的 ECNT 非零、位置有效，BYTLOC=52、BITLOC=6。','SQID/CID identify the same command; Error Information has nonzero ECNT and a valid location, BYTLOC=52, BITLOC=6.'),('保留原始 SQE、opcode、CSI 與完整 completion status。','The original SQE, opcode, CSI and full completion status are retained.')],
('從 CQE 的 SCT／SC 確認錯誤類型 → Get Log Page LID=01h 找相符 entry → 用 byte offset 對回原命令格式。','Use CQE SCT/SC to identify the error class → Get Log Page LID=01h for the matching entry → map its byte offset into that command’s format.'),
[('每個 Dword 是 4 bytes，因此 byte 52 是 CDW13 的第一個 byte；BITLOC=6 指向 CDW13 bit 6。BYTLOC 不是 Dword 編號，也不是資料 buffer 的 byte 52。','Each Dword has four bytes, so byte 52 is the first byte of CDW13; BITLOC=6 identifies CDW13 bit six. BYTLOC is neither a Dword index nor byte 52 of the data buffer.'),('接著要依 opcode 與 command set 查 CDW13 的定義，才能知道該 bit 屬於哪個欄位。共同 SQE 格式只能提供位置，不能替每種命令決定此處語意。','Next use opcode and command set to interpret CDW13 and identify the containing field. The common SQE layout supplies a location, not the command-specific meaning of that location.'),('錯誤位置指出值得檢查的參數，不能自行推導成「那個 bit 必須翻轉」。可能是保留值、能力不支援，或與別的欄位組合不合法；修正仍要核對該命令條件。','A reported location identifies a parameter to inspect, not an instruction to flip that bit. It may contain a reserved value, unsupported choice or invalid combination; a correction requires the command’s conditions.')],
'B212 B93 B101 B103','B212:244-246 B93:166-168 B101:171-172 B103:173-176')

case('command',('PRP2 是第二個資料頁，還是 list 位址？','Is PRP2 a data page or a list address?'),
('同樣的起始位址，把傳輸長度從 5120 改成 6144 bytes，就可能需要改變 PRP2 的解讀。為什麼？','Why can changing transfer length from 5120 to 6144 bytes change the interpretation of PRP2 at the same starting address?'),
[('目前記憶體頁大小 4096 bytes；PRP1 在第一頁內的 offset=3072，位址符合要求。','Current memory page size is 4096 bytes; PRP1 has offset=3072 within its first page and meets alignment requirements.'),('資料頁彼此不連續；使用 PRP，沒有 metadata 影響本例長度。','Data pages are noncontiguous; PRPs are used, with no metadata affecting these lengths.')],
('讀 CC.MPS 確定頁大小 → 由命令與格式算傳輸 bytes → 計算第一頁剩餘空間，再決定 PRP2 類型。','Read CC.MPS for page size → calculate transfer bytes from command and format → calculate first-page space before interpreting PRP2.'),
[('第一頁只剩 4096−3072=1024 bytes。長度 5120 時，剩下 4096 bytes 恰可放一個後續資料頁，PRP2 可直接指向該頁。','The first page has 4096−3072=1024 bytes remaining. A 5120-byte transfer leaves exactly 4096 bytes, so PRP2 directly identifies the one additional data page.'),('長度 6144 時，剩下 5120 bytes，需兩個後續資料頁。此時 PRP2 指向 PRP list，list entries 再指向那兩個資料頁；不能仍把 PRP2 當第一個後續資料 buffer。','A 6144-byte transfer leaves 5120 bytes requiring two additional data pages. PRP2 then points to a PRP list whose entries identify those pages, rather than directly pointing to the first subsequent data buffer.'),('判斷關鍵是跨越的頁數，不是總長是否大於某個固定常數。把 6144 bytes 改成從頁首開始，又只跨兩個頁面，PRP2 的角色便可能不同。','The deciding factor is pages spanned, not whether total length exceeds a fixed constant. Moving the same 6144-byte transfer to a page-aligned start spans only two pages and changes PRP2’s role.')],
'B111 B113 B41','B111:184 B113:185 B@4.3.1:184-186 B41:86-89')

case('command',('SGL 地址正確，長度還可能不夠嗎？','Can correct SGL addresses still describe too little data?'),
('buffer 的地址都能存取，但命令仍有資料長度問題。如何在不讀取實體記憶體的情況下先檢查描述子？','Buffer addresses are accessible, but the command has a transfer-length problem. What can descriptor inspection establish before reading memory?'),
[('命令要求 8192 data bytes；完整 SGL 只有兩個合法 Data Block descriptors，Length 分別為 4096、2048。','The command requires 8192 data bytes; its complete SGL contains two valid Data Block descriptors with Length=4096 and 2048.'),('沒有 Bit Bucket、metadata 或其他 descriptors；SGL 支援與排列方式已確認。','There are no Bit Bucket, metadata or additional descriptors; support and SGL arrangement are valid.')],
('由命令與 LBA 格式計算需求 → 按 descriptor type 走訪完整 SGL → 加總 Data Block lengths。','Compute required bytes from command and LBA format → traverse the complete SGL by descriptor type → sum Data Block lengths.'),
[('兩段合計 6144 bytes，比命令需要的 8192 少 2048。地址合法只回答可指向哪裡，Length 才界定可傳輸的範圍；兩者不能互相代替。','The descriptors total 6144 bytes, 2048 short of the required 8192. Address validity identifies where memory is; Length defines the described extent. One cannot substitute for the other.'),('Segment descriptor 的 Length 用來描述另一段 descriptors 所占的範圍，不能當作 payload bytes 加進資料總量。先按 type 區分「描述資料」與「描述下一段清單」，才不會把缺少的資料藏在表頭長度裡。','A Segment descriptor’s Length describes a segment of descriptors, not payload bytes to add to the data total. Distinguish data descriptors from list-segment descriptors before summing.'),('本例可確定描述的 payload 不足；實際 controller 回覆仍要保留 SCT／SC，按 SGL validation 規則比對。不能因找出一個長度問題，就忽略可能同時存在的其他格式錯誤。','The described payload is insufficient here. Retain actual SCT/SC and compare with SGL validation rules; identifying one length problem does not rule out concurrent format errors.')],
'B114 B116 B119 B121','B114:187 B116:187 B119:188-189 B121:189')

case('command',('要從 offset 1024 讀 3 KiB，NUMD 應填多少？','Which NUMD retrieves 3 KiB from offset 1024?'),
('一個一般 byte-offset log 支援這個讀取範圍。請分別編碼長度與起點，不把 byte 數直接填進 NUMD。','A conventional byte-offset log supports this range. Encode length and starting position separately rather than putting a byte count in NUMD.'),
[('需 3072 bytes，起點距 log 開頭 1024 bytes；OT=0，無特殊長度覆寫規則。','Required length is 3072 bytes, starting 1024 bytes from the log origin; OT=0, with no special length override.'),('LID、NSID、CSI、LSP、LSI 都已依目標 log 正確選定。','LID, NSID, CSI, LSP and LSI are correctly selected for the target log.')],
('Get Log Page：NUMDU／NUMDL 控制長度；LPO 配 OT 控制位置；先查該 log 是否有例外。','Get Log Page uses NUMDU/NUMDL for length and LPO with OT for position; first check for log-specific exceptions.'),
[('3072÷4=768 Dwords，減 1 後 NUMD=767=02FFh，所以 NUMDU=0、NUMDL=02FFh。填入 3072 會被解成另一個 Dword 數，而不是 3072 bytes。','3072÷4=768 Dwords; subtracting one gives NUMD=767=02FFh, so NUMDU=0 and NUMDL=02FFh. Encoding 3072 directly requests a different Dword count, not 3072 bytes.'),('OT=0 時 LPO=1024 表示 byte offset；本次範圍為 bytes 1024–4095。若改成 OT=1，LPO 變成資料結構 index，只有支援該模式的 log 才能使用，不能把同一數字當相同位置。','With OT=0, LPO=1024 is a byte offset, yielding bytes 1024–4095. With OT=1 it is a structure index, usable only by supporting logs; the same number does not identify the same position.'),('還要確認讀取是否保留事件：RAE 的選擇可能有通知確認效果。像 Persistent Event Log 的 ACT=3 另有固定 header 規則，就不能套用本題的一般長度算法控制回傳範圍。','Also choose RAE deliberately because retrieval may acknowledge notifications. Persistent Event Log ACT=3 has a fixed-header rule, so this ordinary length calculation does not control its returned range.')],
'B204 B205 B208 B232','B204:239 B205:240 B208:240-241 B232:272')

case('command',('Effects log 說會改 namespace，就表示剛剛新增了嗎？','Does an effects flag prove that a namespace was just created?'),
('操作後，工具只靠 NIC=1 就把 namespace 數量加 1。這是能力查詢還是歷史查詢？','After an operation, a tool increments its namespace count solely because NIC=1. Is that interpreting capability data or history?'),
[('Commands Supported and Effects 中，目標 Admin opcode 的 CSUPP=1、NIC=1。','Commands Supported and Effects reports CSUPP=1 and NIC=1 for the target Admin opcode.'),('一筆該 opcode 的命令已完成，但工具未保留 action、status 或新的 Identify 清單。','A command with that opcode completed, but its action, status and updated Identify lists were not retained.')],
('Get Log Page LID=05h 查對應 Admin／I/O opcode 區；再取得實際命令及完成紀錄，必要時重新 Identify。','Get Log Page LID=05h for the correct Admin/I/O opcode table; then obtain the actual request/completion and refresh Identify where necessary.'),
[('CSUPP 說明命令支援，NIC 說明命令可能改 namespace inventory。它們不是事件時間線，也沒說該命令這一次一定成功或一定執行 Create。','CSUPP reports support and NIC possible namespace-inventory change. Neither is an event timeline nor proof of success or a Create action in this execution.'),('正確做法是依命令 action 與完成狀態決定是否更新盤點，再取得 Allocated／Active lists。若一律加 1，Delete、失敗的 Create、或沒有變更的動作都會把快取搞錯。','Use the action and completion status to decide when to refresh allocated/active inventories. Unconditionally adding one corrupts cached inventory for Delete, failed Create or non-changing operations.'),('I/O opcode 還要在正確 command set 下解讀。相同數字出現在另一張 opcode 表，不一定是同一個命令；effects 的作用範圍與協調要求也不能取代實際結果。','Interpret I/O opcodes in the correct command set. The same numeric opcode in another table need not name the same command; effects scope and coordination rules do not replace outcome evidence.')],
'B217 B336','B217:254-255 B336:364-365')
