"""Local definitions; the reader emits each at most once per document."""
TERMS={
 'Namespace Write Protection':('namespace寫入保護；控制一份namespace能否接受受限制的修改操作。','A mechanism controlling whether a namespace accepts operations restricted by its protection state.'),
 'WPS':('Write Protection State，namespace目前的寫入保護狀態代碼。','Write Protection State, the namespace’s current protection-state code.'),
 'NWPC':('Namespace Write Protection Capabilities，控制器支援哪些保護狀態的位元欄位。','Namespace Write Protection Capabilities, a controller bit field advertising supported protection states.'),
 'WPC':('Write Protection Control，決定是否接受進入特定保護狀態之要求的控制欄位。','Write Protection Control, the field permitting requests to enter particular protection states.'),
 'WPUPCC':('Write Protect Until Power Cycle Control，WPC內允許進入狀態2的控制位。','Write Protect Until Power Cycle Control, the WPC bit permitting entry into state 2.'),
 'PWPC':('Permanent Write Protect Control，WPC內允許進入永久保護的控制位。','Permanent Write Protect Control, the WPC bit permitting entry into permanent protection.'),
 'MDS':('Multi-Domain Subsystem，Identify Controller中表示支援多domain的位元。','Multi-Domain Subsystem, the Identify Controller bit indicating multiple-domain support.'),
 'domain':('subsystem內用來界定通訊與故障影響的範圍；本篇用它判斷是否允許直到斷電的保護。','A subsystem boundary for communication and fault effects, relevant here to until-power-cycle protection.'),
 'RPMB':('Replay Protected Memory Block，使用認證與防重播機制存取的記憶區；本篇只取其WPC控制欄位。','Replay Protected Memory Block, an authenticated, replay-protected area; this report uses its WPC control field.'),
 'Device Configuration Block':('RPMB target0的裝置設定資料結構，WPC位於其中byte2。','The RPMB target 0 configuration structure containing WPC at byte 2.'),
 'power cycle':('電源循環，即斷電後重新上電；不等同於所有形式的控制器重設。','A power-off/power-on cycle, distinct from controller resets that do not cycle power.'),
 'Controller Level Reset':('控制器層級重設；狀態2是否解除仍要辨認有沒有發生power cycle。','A controller-level reset; whether state 2 is released depends on whether power cycling occurred.'),
 'SV':('Save，Set Features中要求保存屬性值的位元。','Save, the Set Features bit requesting that an attribute value be saved.'),
 'SEL':('Select，Get Features中選擇目前值、預設值、已保存值或能力的欄位。','Select, the Get Features field choosing current, default, saved or capability information.'),
 'SSFS':('Save and Select Feature Support，表示是否支援非零SV與SEL選項。','Save and Select Feature Support, indicating support for nonzero SV and SEL options.'),
 'CHANG':('Changeable，能力回覆中表示此Feature有可變更值的位元。','Changeable, the capability bit indicating that some value of the feature can be changed.'),
 'NSSPEC':('NS Specific，能力回覆中表示namespace作用範圍的位元。','NS Specific, the capability bit indicating namespace scope.'),
 'SVBL':('Saveable，能力回覆中表示是否可保存屬性值的位元。','Saveable, the capability bit indicating whether attribute values can be saved.'),
 'AMRO':('All Media Read-Only，SMART健康資訊中表示全體媒體唯讀的警告位。','All Media Read-Only, the SMART health-warning bit for an all-media read-only condition.'),
 'volatile write cache':('揮發性寫入快取；尚未提交到非揮發媒體的資料可能暫存在這裡。','Volatile write cache, which can hold data not yet committed to non-volatile media.'),
 'active':('已附接於處理命令之控制器的namespace狀態。','A namespace attached to the controller processing the command.'),
 'inactive':('已配置但未附接於該控制器的namespace狀態，與無效識別值不同。','An allocated namespace not attached to that controller, distinct from an invalid identifier.'),
 'invalid':('無效；此處指無效namespace識別值，而非僅未附接。','Invalid; here an invalid namespace identifier, not merely an unattached namespace.'),
 'offset':('相對於資料結構起點的位移；本篇byte offset以byte計算，從0起算。','A displacement from a structure’s start; byte offsets here count bytes from zero.'),
 'SCT':('Status Code Type，完成狀態碼所屬的類型。','Status Code Type, the category of a completion status code.'),
 'SC':('Status Code，在指定SCT類型內的完成狀態代碼。','Status Code, the completion code within a specified SCT category.'),
}
