from scripts.nvme_qa_model import add

add(1,'Host 應如何從 CAP 與 VS 確認 NVMe 版本、最大 Queue 大小、Timeout、Doorbell 間距、Memory Page Size 及支援的 Command Set？ || How does a host discover version, queue limits, timeouts, doorbell stride, page sizes and command sets from CAP and VS?', 'register',['cap','crto','init'],'''
Host 必須先知道 controller 支援哪些配置，才能正確初始化介面。CAP 用來宣告支援能力，CC 則記錄 Host 實際選用的設定，因此不能直接把 CAP 的能力位元複製到 CC。 || Discover legal interface configurations before issuing commands. CAP advertises capabilities; CC contains host selections. Capability bits are not values to copy blindly into configuration fields.
讀取 CAP 與 VS 只會取得目標 controller 的資訊，不會改變 queue 或媒體狀態。即使已確認 NVMe 版本，Host 仍須逐項檢查選配功能，因為版本相同不代表支援的功能完全相同。 || These reads observe one controller without changing queues or media. A version number does not establish support for every optional feature.
VS 的 MJR、MNR、TER 欄位共同表示版本。Queue 與命令集能力則由 CAP 提供：MQES+1 是單一 I/O queue 的 entry 數量上限，CQR 說明是否要求實體記憶體連續，CSS 則說明支援哪些命令集選擇方式。 || VS.MJR/MNR/TER encode the version. CAP.MQES+1 limits I/O queue entries, CQR specifies physical-contiguity requirements, and CSS describes command-set support.
這些欄位使用不同的編碼方式。CAP.TO 以 500 ms 為單位；相鄰 Doorbell 的間距是 2^(2+DSTRD) bytes；可選的記憶體頁面大小則介於 2^(12+MPSMIN) 與 2^(12+MPSMAX) bytes。判斷啟用逾時時，還必須一併讀取 CRTO。 || CAP.TO uses 500 ms units. Doorbell stride is 2^(2+DSTRD) bytes; supported pages range from 2^(12+MPSMIN) to 2^(12+MPSMAX) bytes. Enable timeout also requires CRTO.
Host 先建立 NVMe Register 的位址映射，再讀取 VS 與 CAP。根據讀到的能力，選擇合法的 MPS、CSS、AMS 與 Ready Mode，接著配置 queue。若 IOCSS=1，則在啟用後以 Identify CNS 1Ch 查詢可使用的命令集組合。 || Map the NVMe registers, read VS/CAP, select legal MPS/CSS/AMS and ready mode, then configure queues. If IOCSS=1, discover combinations with Identify CNS 1Ch after enabling.
讀取成功後，Host 應能算出合法的配置範圍；這次 Register 讀取本身不會產生 CQE。例如，MQES=03FFh 表示最多 1024 個 queue 位置，而 DSTRD=2 表示相鄰 Doorbell 相隔 16 bytes。 || The result is configuration information, not a CQE. For example, MQES=03FFh means up to 1024 slots; DSTRD=2 means adjacent doorbells are 16 bytes apart.
讀取唯讀 Register 不會以 Invalid Field CQE 回覆錯誤。至於後續設定，若 Host 把不支援的值寫入 CC.MPS 或 CC.AMS，規範可能將結果定義為 undefined behavior；此時不能要求 controller 回傳某個固定錯誤碼。 || Reading read-only registers has no Invalid Field CQE. Later programming unsupported CC.MPS/AMS values can be undefined behavior, not a condition with a guaranteed error completion.
驗證時，應確認 CC.CSS 選用的命令集符合 CAP.CSS 宣告的能力及 Identify 回報的組合。同樣地，Create Queue 的 QSIZE 必須符合 MQES 限制。Admin Queue 則另受 AQA 的 4096 個位置上限約束，不能與 I/O queue 的上限混為一談。 || Cross-check CAP.CSS against CC.CSS and Identify combinations, and MQES against Create Queue QSIZE. Admin queues have their separate 4096-slot AQA limit.
先檢查欄位的位元位置、little-endian 解讀方式，以及數量是否採 zero-based 編碼。例如，MQES=1023 代表 1024 個位置；如果只配置 1023 個，便是漏算了編碼中的加 1。 || First check bit positions, little-endian decoding and zero-based encoding. MQES=1023 does not mean only 1023 physical slots.
''', {12:'CAP 與 VS 分別提供能力及版本資訊。Controller Reset 後，Host 重新讀取它們，再設定 CC 中需要選擇的值；這些唯讀能力欄位本身不需要、也不是由 Host 寫回。 || CAP/VS are capability and version registers. Re-read them after Controller Reset before configuring CC; do not write capabilities back as settings.',13:'NVM Subsystem Reset 後，先確認 Register 已可存取，再重新查詢版本與能力。若這次重設同時啟用新韌體，更要以恢復後的實際回覆為準。 || Rediscover register accessibility and capabilities after NVM Subsystem Reset, especially if it also activates firmware.',14:'Power Cycle 後，Host 重新讀取 CAP 與 VS。本題只是查詢能力與版本，沒有因這次讀取而需要保存的 Host 設定。 || Rediscover CAP/VS after a power cycle; the read itself creates no host setting to persist.',15:'讀取 Register 不會改變其他 controller 或 namespace。不過，不同 controller 可以有不同能力，因此不能拿其中一個 controller 的回覆代替全部。 || Reads do not change another controller or namespace. Controllers may differ in capability, so one snapshot is not a substitute for all of them.'})

add(2,'AQA、ASQ、ACQ 與 CC 各欄位應按照什麼順序設定？設定錯誤時可能發生什麼？ || In what order are AQA, ASQ, ACQ and CC programmed, and what happens if they are wrong?', 'register',['adminreg','cc','init'],'''
Host 必須先準備 Admin SQ 與 CQ 的記憶體，再把位置與大小告訴 controller。這樣 controller 啟用後，才有可用的通道接收管理命令並回報結果。 || Provide valid Admin SQ/CQ storage before enabling the controller. Establish memory and pointers before allowing command processing.
這些設定影響目標 controller 的管理介面。若 queue 位址填錯，controller 就可能無法讀取命令或寫入完成結果，導致後續 Identify、Get Features 等命令都無法正常完成。 || This controls the controller's management interface. A wrong queue address may prevent every subsequent Identify or Get Features from completing.
先從 CAP 確認可用的 MPS 範圍、CSS、AMS 與 CRMS，再檢查 AQA 對 Admin Queue 長度的限制。Host 選用的配置必須同時符合這些條件。 || Check CAP's MPS range, CSS, AMS and CRMS, together with AQA's Admin queue limits.
AQA.ASQS 與 ACQS 儲存的是 entry 數量減 1；ASQ 與 ACQ 則提供實體起始位址，且必須依 CC.MPS 對齊。CC 還需設定 CSS、MPS、AMS 與 CRIME。若使用 NVM I/O，IOSQES 與 IOCQES 分別設為 6 與 4。 || AQA.ASQS/ACQS encode entries−1. ASQ/ACQ contain physical bases aligned to CC.MPS. Configure CSS, MPS, AMS and CRIME in CC; NVM I/O uses IOSQES=6 and IOCQES=4.
先等待前一次重設完成，確認 RDY=0，再配置實體連續的 Admin Queue 記憶體，並把 Admin CQ 的 Phase 初始化為 0。接著，在 EN=0 時寫入 AQA、ASQ、ACQ 及合法的 CC 設定。將 EN 設為 1 後，等待 RDY=1。I/O entry 大小則必須在建立 I/O Queue 前設定完成。 || Wait for the previous reset to reach RDY=0. Allocate contiguous Admin queues and clear Admin CQ phases. Program AQA/ASQ/ACQ and legal CC fields with EN=0, then enable and wait for RDY=1. Set I/O entry sizes before Create I/O Queue.
初始化成功後，Host 可以透過 Admin Queue 提交 Identify。不過，I/O Queue 仍需另外建立；若採 Independent mode，也不能只憑 RDY=1 就認定所有媒體都已就緒。 || The Admin queues become usable for Identify. I/O queues are not automatically created, and independent mode does not imply that every medium is ready.
例如，以 AQA size=0 的配置啟用 controller、在 EN=1 時修改 MPS，或選用不支援的 MPS／AMS，都可能落入規範所稱的 undefined behavior。這些是 Register 使用方式的問題，不能擅自規定 controller 必須回傳 Invalid Field CQE。 || Enabling with an AQA size of zero, changing MPS while enabled or selecting unsupported MPS/AMS has undefined results. Do not invent Invalid Field CQEs for these register violations.
驗證時，先確認 Register 的編碼正確，再確認 Admin CQ 能收到與原命令 CID 相符的 Identify 完成結果。CC.EN=1 只表示 Host 已要求啟用，單憑這個值還不足以證明初始化完成。 || Validate register encodings and then a correctly identified Identify completion. CC.EN=1 alone does not establish successful initialization.
先確認 ASQ、ACQ 指向的是裝置可存取的位址，再檢查頁面對齊與實際配置長度。一般程式使用的虛擬位址，不能直接當成 queue 的實體基底位址。 || First check device-usable queue addresses, page alignment and allocation length. An ordinary process virtual address is not automatically a valid queue base.
''')

add(3,'Host 設定 CC.EN 後，應如何根據 CAP.TO 與 CSTS.RDY 判斷 Controller 是否成功 Enable？ || How does a host judge enable completion using CC.EN, CSTS.RDY and the timeout fields?', 'register',['cap','crto','ready','init'],'''
Host 寫入啟用要求後，controller 還需要時間準備。這題要分辨「已要求啟用」與「已能處理命令」，並選對等待期限，避免過早重設；在 Base 2.4 中，判斷時也必須納入 CRTO。 || Separate the enable request from readiness and avoid premature recovery caused by a wrong timeout. Base 2.4 requires considering CRTO as well.
這裡判斷的是目標 controller 的啟用狀態。至於媒體是否已可存取，還要配合所選的 Ready Mode，不能只看一個 RDY 值。 || This establishes readiness of the target controller; media availability also depends on the selected ready mode.
讀取 CAP.CRMS、CC.CRIME、CRTO.CRWMT／CRIMT 及 CAP.TO，確認目前採用哪種 Ready Mode 及等待期限。不能假設所有啟用情況都只需要查看 CAP.TO。 || Read CAP.CRMS, CC.CRIME, CRTO.CRWMT/CRIMT and CAP.TO. CAP.TO alone does not cover every enable timeout.
計時從 CC.EN 由 0 變成 1 開始，Host 則透過 CSTS.RDY 觀察是否就緒。CRTO 的單位是 500 ms：With Media 模式使用 CRWMT；Independent 模式先以 CRIMT 判斷介面就緒期限，再以 CRWMT 判斷媒體就緒期限。 || Start timing at CC.EN 0→1 and observe CSTS.RDY. CRTO units are 500 ms: use CRWMT for With Media, CRIMT for Independent readiness, and CRWMT for its media deadline.
Host 先記錄 Ready Mode 與啟用時間，再持續讀取 RDY、CFS。當 RDY=1 時，才能開始提交該模式允許的命令。若初始化失敗，還須依失敗條件判斷後續處理，因此不能把每次讀到 RDY=1 都解讀成媒體健康。 || Record mode and enable time, poll RDY/CFS, then issue commands permitted by that mode. Initialization-failure rules also apply; RDY=1 is not an unconditional media-health verdict.
正常情況在適用期限內 RDY=1。例：CRIMT=2、CRWMT=20，分別是 1 s 的介面就緒期限與 10 s 的媒體期限，兩者都從 Enable 起算。 || Normally RDY becomes 1 within the applicable deadline. CRIMT=2 and CRWMT=20 mean 1 s for interface readiness and 10 s for media readiness, both measured from enable.
透過 Register 啟用 controller，不會產生 CQE。若媒體尚未就緒，只有符合對應條件的命令，才能回報 Namespace Not Ready（SCT=0, SC=82h）或 Admin Command Media Not Ready（0/24h）。 || Register enabling has no CQE. While media is unready, eligible commands may return Namespace Not Ready (SCT=0, SC=82h) or Admin Command Media Not Ready (0/24h).
應把啟用時間、CRIME、命令種類與回傳 Status 放在同一條時間軸上核對。Figure 84 只允許列出的 Admin 命令在特定條件下回報媒體尚未就緒，並非所有 Admin 命令都能用這個理由暫時拒絕執行。 || Correlate timing, CRIME, command type and status. Figure 84's eligible Admin commands and restrictions do not permit rejecting every Admin command temporarily.
先確認使用哪個 timeout、從何時開始計時，以及是否正確換算 500 ms 單位。媒體的等待期限同樣從 Enable 起算，不能等 RDY=1 才重新計時。 || First check timeout selection, starting time and the 500 ms unit. Do not restart the media deadline when RDY becomes 1.
''',{8:'透過 Register 啟用 controller，不會產生 CQE，因此這個動作本身沒有 DNR 或 More。Independent mode 在合法等待期間，若命令因媒體尚未就緒而失敗，可以回報 DNR=0；超過 CRWMT 後，就不得繼續以相同的暫時性理由回報 DNR=0。More 則依 Error Information Log 是否有該命令的補充資訊設定。 || Enabling has no DNR/More. Eligible media-not-ready responses may have DNR=0 during the allowed Independent-mode interval; that transient explanation cannot continue with DNR=0 beyond CRWMT. More reflects additional Error Information.',11:'若發生 §3.5.4.1 定義的初始化期限失敗，而且 controller 支援 PEL，必須記錄 NVM Subsystem Hardware Error Event，原因為 Controller Ready Timeout Exceeded。這是失敗條件觸發的紀錄，不是每次 Enable 成功都必須新增的事件。 || For an initialization-deadline failure meeting §3.5.4.1, a controller supporting PEL shall record an NVM Subsystem Hardware Error Event with Controller Ready Timeout Exceeded. This is not a record for every successful enable.'})

add(4,'Host 清除 CC.EN 後，應如何判斷 Controller 是否成功 Disable？尚未 Disable 完成時能否重新 Enable？ || How is disable completion detected, and may the host re-enable before it completes?', 'register',['cc','cap','reset'],'''
Host 必須確認上一輪命令處理已停止，才能開始下一輪初始化。等待停用完成，就是為了建立這個明確的分界。 || Establish that old command processing has stopped before beginning another initialization lifetime.
清除 EN 會觸發目標 controller 的重設，影響其所有 I/O Queue。因此，這個動作並不是只暫停其中一條 SQ。 || Clearing EN resets this controller and all its I/O queues; it does not merely pause one SQ.
CAP.TO 說明清除 EN 後，Host 應等待 RDY 從 1 變成 0 的最長時間。驗證時，也應保存 CC、CSTS 的讀值及時間，才能確認轉移是否在期限內完成。 || CAP.TO defines the worst-case wait for RDY 1→0 after EN is cleared. Preserve CC/CSTS snapshots too.
在正常停用流程中，Host 從 EN=1、RDY=1 的狀態清除 EN。清除後還必須等到 RDY=0，才能重新啟用 controller。 || In the normal enabled state, initiate EN 1→0 with RDY=1; RDY=0 indicates readiness to enable again.
Host 先停止提交新命令，再清除 EN，並持續讀取 RDY。等到 RDY=0 後，重新初始化 Admin CQ 與 Host 的命令追蹤資料，完成 CC 設定，最後才把 EN 設回 1。 || Stop new submissions, clear EN and poll RDY. Once zero, reinitialize Admin CQ and host tracking, configure CC and enable again.
RDY=0 才是停用完成的判斷依據，不需要等到每筆舊命令都收到獨立 CQE。此時原有的 I/O Queue 已失效，不能繼續使用。 || RDY=0 establishes disable completion; receiving a CQE for every old command is not required. Old I/O queues are invalid.
若 RDY 還是 1，Host 就把 EN 從 0 設回 1，結果屬於 undefined behavior。由於這是 Register 操作，不是提交 Admin 命令，因此不能要求 controller 以 Command Sequence Error 回覆。 || Setting EN 0→1 while RDY remains 1 has undefined results. This is not an Admin request requiring Command Sequence Error.
核對 EN、RDY 的轉移順序後，還應確認 Host 已停止使用舊 queue。即使舊記憶體裡仍看得到資料，也不代表該 queue 仍可繼續運作。 || Check EN/RDY transitions and retirement of old queues. Residual data in an old queue does not prove it is reusable.
先看是不是清 EN 後立刻設回 1，或把 CAP.TO 當成毫秒值直接使用。 || First check for an immediate re-enable or interpretation of CAP.TO as plain milliseconds.
''')

add(5,'Host 能否在 CSTS.RDY 為 0 時送出 Command 或更新 Doorbell？ || May a host submit commands or update doorbells while CSTS.RDY is zero?', 'register',['qattr','queue','cc','pcie'],'''
Host 可以先在記憶體中準備 SQE，但準備完成並不等於已提交命令。更新 SQ Tail Doorbell 才會通知 controller 有新命令，因此必須等到 controller 與 queue 都可用時才能進行。 || Distinguish preparing an SQE in host memory from submitting it. A doorbell is the submission boundary and cannot be used prematurely.
這個限制適用於該 PCIe controller 的 Admin 與 I/O 命令提交。初始化時先設定 Admin Queue Register 是建立通道的步驟，不能將它視為已經送出命令。 || This applies to Admin and I/O submission on this PCIe controller. Configuring Admin queue registers during initialization is different from command submission.
判斷能否提交時，必須同時確認 CSTS.RDY、CC.EN 及目標 queue 是否存在。即使 RDY=1，也仍需檢查 queue 是否已建立，以及 controller 是否處於 shutdown 狀態。 || Check CSTS.RDY, CC.EN and queue existence. Even RDY=1 requires a created queue and consideration of shutdown state.
SQ Tail Doorbell 告訴 controller 哪些新命令已提交；CQ Head Doorbell 則告訴 controller，Host 已處理到哪個完成位置。這兩種通知都不能讓尚未就緒的 controller 提前進入 Ready 狀態。 || SQ Tail announces submissions; CQ Head announces consumed completions. Neither is a command for making the controller ready.
先等到 RDY=1，並確認目標 queue 已建立且尚未刪除。接著，讓 SQE 的內容對裝置可見，再更新 SQ Tail Doorbell，完成提交。 || Wait for RDY=1 and a valid queue lifetime, make the SQE visible to the device, then update SQ Tail.
正確提交後，controller 才能取得命令。Host 即使已將 SQE 寫入記憶體，只要尚未更新 SQ Tail，就還沒有完成提交。 || The controller can fetch a correctly submitted command. Prepared memory without an updated tail is not yet a submission.
若 Host 在 controller 或 queue 尚不可用時提交，不能期待收到固定的錯誤 CQE。原因是停用中的 Admin Queue 本來就無法作為可靠的錯誤回報通道。 || Violating readiness or queue-lifetime preconditions has no guaranteed CQE. A disabled Admin Queue cannot be relied upon to report the misuse.
如果看到 EN=1、RDY=0 且等待逾時，應先檢查初始化是否完成。此時尚未合法提交的 Identify 沒有回覆，不能據此判定裝置不支援 Identify。 || EN=1, RDY=0 and a timeout first indicate an initialization-state issue; an illegally early Identify is not evidence that Identify is unsupported.
先比對 Doorbell 寫入時間與 RDY 變成 1 的時間，再檢查 queue 建立成功時間。 || First compare doorbell timing with the RDY transition, then with successful queue creation.
''')

add(6,'CSTS.CFS 代表什麼？Controller 初始化失敗或進入 Fatal 狀態時，Host 應如何恢復？ || What does CSTS.CFS mean, and how should the host recover from initialization failure or a fatal state?', 'register',['cc','fatal','ready','reset'],'''
CFS 是 controller 發生嚴重故障的狀態指示，不是單一 Read／Write 的一般失敗碼。 || CFS indicates a serious controller failure, not an ordinary error code for one Read or Write.
嚴重的 controller 異常可能影響整個命令服務；某個 namespace 的媒體錯誤，則不一定具有相同的影響範圍。兩者需要分別判斷。 || The failure may affect controller-wide command service. CFS and an individual namespace media error are not interchangeable.
應一併觀察 CSTS.CFS、RDY、CC.EN 與適用的等待期限。Identify 中宣告支援某項選配功能，並不會讓 Host 可以忽略 CFS 所指出的狀態。 || Observe CSTS.CFS with RDY, CC.EN and the applicable timeout. No Identify optional-capability bit permits ignoring CFS.
先保存 Register，以及已取得的 CQE 和 Log。若管理通道仍可使用，再讀取其他診斷資訊；若通道已無回應，就不能無限等待 Get Log Page 完成。 || Preserve registers and available CQEs/logs first. Collect diagnostics if the Admin path still works, without waiting indefinitely for an inaccessible Get Log Page.
Host 應根據故障情況，以及目前還能存取哪些控制介面，選擇適當的 Controller Level Reset。等狀態轉移完成後，再重新初始化。若控制介面完全沒有回應，則需要平台層的恢復處理；一次清除 CC.EN 並不保證能排除所有故障。 || Perform Controller Level Reset as appropriate to the failure and accessible interface, then reinitialize. An unresponsive interface requires platform recovery; a CC.EN reset is not guaranteed to repair every fault.
恢復後，還要確認 RDY 正常、Identify 可完成，而且新 queue 能正確處理命令。CFS 已清除只表示該狀態不再成立，不能單憑這點認定資料完整性也已通過驗證。 || Verify RDY, Identify and command completion on new queues after recovery. Clearing CFS alone does not validate data integrity.
若 controller 還能回報受影響命令的結果，Internal Error（SCT=0, SC=06h）可能適用。若故障已嚴重到無法透過 CQE 溝通，則可能改由 CFS 指示異常；此時不能要求每筆命令都留下 CQE。 || Internal Error (SCT=0, SC=06h) may apply when affected commands can still complete. Serious failure preventing CQE communication may set CFS; do not require a CQE for every command.
應對照同一時間的 CFS、初始化等待期限與硬體錯誤紀錄，確認它們是否指向相同事件。單筆命令回傳 Invalid Field，並不足以證明 controller 已進入 Fatal 狀態。 || Correlate CFS, initialization deadlines and hardware records at the same time. One Invalid Field completion is not itself controller-fatal evidence.
先確認 Register 讀取仍有效，以及 CFS 真的是 1；不可將失效讀取的全 1 值直接解碼成每個狀態位都成立。 || First confirm valid register access and an actual CFS value of 1. An all-ones failed read is not evidence that every status bit is asserted.
''')

add(7,'Controller 初始化後可能進入哪些 Ready Mode？Host 應如何處理暫時或限制性的 Ready 狀態？ || Which ready modes exist, and how should the host handle limited readiness?', 'register',['ready','crto','cc'],'''
Ready Mode 決定 controller 何時可以開始服務。Independent 模式允許管理命令在媒體初始化完成前先開始執行，但媒體仍必須在規定的期限內就緒。 || Allow management work before media initialization finishes while retaining an explicit media-readiness deadline.
這裡討論兩種模式：Controller Ready With Media，以及 Controller Ready Independent of Media。它們規定的是介面與媒體的就緒關係，而不是額外定義一組可任意解讀的 degraded-ready 狀態碼。 || The modes are Controller Ready With Media and Controller Ready Independent of Media, not arbitrary degraded-ready encodings.
CAP.CRMS 中的 CRWMS、CRIMS 分別宣告兩種模式的支援能力。當 CAP.CRMS=11b 時，Host 可以透過 CC.CRIME 選擇要使用的模式。 || CAP.CRMS.CRWMS/CRIMS advertise support. With CAP.CRMS=11b, CC.CRIME selects the mode.
CRIME=0 選擇 With Media，CRIME=1 選擇 Independent。判斷當下允許執行哪些命令時，要一起檢查 CSTS.RDY、CRTO.CRIMT／CRWMT，以及 Figure 84 的命令分類。 || CRIME=0 selects With Media; CRIME=1 selects Independent. RDY, CRTO.CRIMT/CRWMT and Figure 84's command classes determine permitted work.
Host 必須在啟用前選好模式。若選擇 Independent 模式，RDY=1 後可先執行不依賴媒體的查詢；需要媒體的命令若收到允許的暫時性 Status，則延後處理。同時仍要追蹤從 Enable 開始計算的 CRWMT，不能重新起算。 || Select before enable. After Independent-mode RDY=1, perform media-independent discovery; defer eligible media operations based on transient status and track CRWMT from enable.
With Media 模式正常就緒時，controller 應已能處理所要求的媒體存取。Independent 模式的 RDY=1 則先表示介面及適用命令已可服務，尚不能據此認定所有 namespace 都已就緒。 || Normal With Media readiness includes required media readiness. Independent RDY=1 initially establishes interface and eligible-command readiness, not readiness of every namespace.
在規範允許的條件下，controller 可以回傳 0/82h 或 0/24h；其中 0/24h 只適用於 Independent 模式下特定的 Admin 命令。超過媒體就緒期限後，若仍以同一個暫時等待理由回報 DNR=0，就不符合該期限的要求。 || Eligible cases may return 0/82h or 0/24h. The latter is restricted to appropriate Admin commands in Independent mode. Continuing the same transient DNR=0 explanation beyond the media deadline violates that timing rule.
同時核對 CAP 宣告、CC 選擇、timeout 與命令行為。CSTS.PP 是另一種暫停處理指示，不是第三個 Ready Mode。 || Cross-check CAP support, CC selection, timeouts and behavior. CSTS.PP is a separate processing-pause indication, not a third ready mode.
先問正在失敗的命令是否需要媒體，再看它是否真的屬 Figure 84 允許的種類。 || First determine whether the failing command needs media and whether Figure 84 permits that response for it.
''',{8:'本題的 Register 讀寫沒有 DNR 或 More。若命令因媒體尚未就緒而回報 CQE，則另依條件判斷：允許等待期間可以使用 DNR=0，但超過 CRWMT 後，不得繼續以相同的暫時性理由回報 DNR=0。More 仍用來表示 Error Information Log 是否有補充資訊。 || Register accesses have no DNR/More. Eligible media-not-ready CQEs may use DNR=0 during the permitted interval, not indefinitely after CRWMT. More still identifies additional Error Information.',11:'若符合 §3.5.4.1 的初始化失敗條件，而且 controller 支援 PEL，必須記錄 NVM Subsystem Hardware Error Event，原因為 Controller Ready Timeout Exceeded。正常選用某種 Ready Mode，本身不會要求產生這筆錯誤事件。 || An initialization failure meeting §3.5.4.1 requires a Controller Ready Timeout Exceeded hardware event when PEL is supported. Normal selection of a ready mode does not require that error event.'})

add(8,'Controller Enable、Disable、Controller Reset、NVM Subsystem Reset 與 Shutdown 有什麼差異？ || How do Enable, Disable, Controller Reset, NVM Subsystem Reset and Shutdown differ?', 'register',['cc','shutdown','reset'],'''
這幾個動作分別處理開始服務、停止並重設，以及移除電源前的準備。先分清它們的目的，才能避免用 Reset 取代原本需要的正常 Shutdown。 || Separate starting service, stopping/resetting and preparing for power removal. Reset is not a replacement for orderly shutdown.
啟用或清除 CC.EN 的作用對象是單一 controller。NVM Subsystem Reset 則依規範涵蓋相應的 subsystem 或 domain 範圍；Shutdown 也另有 controller 與 subsystem 層級，必須先確認使用的是哪一種。 || Enable and CC.EN clearing target a controller. NVM Subsystem Reset covers its defined subsystem/domain scope. Shutdown also distinguishes controller and subsystem types.
CAP.NSSRS 可用來確認是否支援 NSSR。判斷 Shutdown 的作用範圍時，則還要查看 CAP 宣告的 shutdown 能力與 CSTS.ST。 || CAP.NSSRS advertises NSSR support; shutdown capability and CSTS.ST distinguish shutdown scope.
Enable：EN 0→1。Controller Reset：EN 1→0。NSSR.NSSRC 寫 4E564D65h 觸發支援的 subsystem reset。正常 controller shutdown 用 CC.SHN=01b，觀察 CSTS.SHST=10b。 || Enable is EN 0→1; Controller Reset is EN 1→0. Writing 4E564D65h to supported NSSR.NSSRC requests subsystem reset. Normal controller shutdown uses CC.SHN=01b and waits for SHST=10b.
若準備正常移除電源，Host 應先協調 I/O，再送出 Shutdown 通知，並等待關機處理完成。若目的是故障恢復，則選擇合適的 Reset，之後重新建立命令處理環境。 || Coordinate I/O, notify shutdown and await completion before normal power removal. Select a suitable reset for recovery, then rebuild the operating environment.
不同動作有不同的完成判斷：啟用時等待 RDY=1；停用或重設時檢查對應的狀態轉移；Shutdown 則等待 SHST=10b。Shutdown 完成不表示所有 Register 都已回到重設值。 || Enable uses RDY=1; disable/reset uses its corresponding state; shutdown uses SHST=10b. Completed shutdown does not mean every register has its reset value.
Register 操作本身沒有 CQE。Shutdown 過程中，controller 可以對適用命令回報 Commands Aborted due to Power Loss Notification（0/05h）；但不能因此把所有 Reset 中未完成的命令，都預期為相同 Status。 || Register operations have no common CQE. During shutdown, commands may return Commands Aborted due to Power Loss Notification (0/05h); that code is not universal for commands interrupted by reset.
應先記錄觸發方式與影響範圍，再比較操作前後保留了哪些值。如果紀錄只寫「reset」，就無法說明 AQA、PCIe 狀態與 Feature 為何有不同的保留結果。 || Record the trigger and scope before comparing retained state. A log saying only “reset” cannot explain differences in AQA, PCIe state or features.
先辨認到底寫了 EN、SHN 還是 NSSRC，以及是否有平台重設同時發生。 || First identify whether EN, SHN or NSSRC was written and whether a platform reset occurred concurrently.
''')

add(9,'Controller Reset 後，哪些 Register、Admin Queue、Feature 與 I/O Queue 需要重新設定？ || What must be reinitialized after Controller Reset?', 'register',['reset','feature','setfeat','adminreg'],'''
重設後，Host 需要重新建立可用的命令處理環境。這樣才能把新命令與上一輪的 queue 指標、Phase 及未完成命令分開處理。 || Establish a fresh operating lifetime rather than reusing old pointers, phases and outstanding commands.
本題只討論清除 CC.EN 所觸發的 Controller Reset。FLR 與 NVM Subsystem Reset 來自不同觸發方式，不能直接套用這裡的 Register 保留規則。 || Here Controller Reset specifically means clearing CC.EN. Do not mix in the register-retention rules of FLR or NVM Subsystem Reset.
先查看 §3.7.2 的重設例外，以及各 Register 的 Reset 欄，確認哪些值會保留。Feature 則還要考慮作用範圍、是否可保存設定，以及 Figure 126、127、466 的恢復規則。 || Use §3.7.2's exceptions and register Reset columns; for features examine scope, saveability and Figures 126/127/466.
這種重設會保留 AQA、ASQ、ACQ、指定的 PMR Register 與 CMBMSC，但仍會重設 Admin Queue 的指標，並刪除所有 I/O SQ／CQ。Host 因此需要重新配置 CC。Feature 的恢復方式則另行判斷：可保存設定者依重設範圍恢復 Saved，沒有 Saved 時使用 Default；不可保存設定者依持續性規則處理。HMB 也需要重新配置。 || This reset preserves AQA/ASQ/ACQ, specified PMR registers and CMBMSC, but still resets Admin Queue pointers. All I/O queues are deleted and CC selections require reconfiguration. Saveable features restore Saved, or Default without Saved, under reset-scope rules; unsaveable features use their persistence rules. Reconfigure HMB.
先等到 RDY=0，確認保留的 Admin Queue 記憶體仍可使用，並把 Admin CQ 的 Phase 初始化為 0。完成配置並啟用後，重新查詢必要的能力與 Feature，再協商 Number of Queues，最後依序建立 CQ 與 SQ。 || Wait for RDY=0, verify retained Admin memory remains valid and initialize Admin CQ phases to zero. Configure and enable, rediscover needed capabilities/features, renegotiate Number of Queues, then create CQs before SQs.
重建成功後，新命令應能在新建立的 queue 上正常完成。即使沿用相同的 QID 或記憶體位址，也不表示上一輪 queue 可以接續使用。 || New commands complete in the new queue lifetime. Reusing a QID or address does not resume the old queue.
重設中斷的舊命令沒有統一、必須回傳的「Reset Status」。重建時若使用非法 QID 或大小，則依對應 Create 命令的規則判斷。直接對舊 queue 更新 Doorbell，不能代替重建流程。 || There is no universal Reset Status owed for every old command. Invalid reconstruction parameters follow Create-command rules; writing doorbells for stale memory is not a recovery method.
應比較重設前後的 Register、Get Features 回覆與實際可用的 Queue 配置。尤其要分清楚：AQA 的值被保留，不代表 Admin CQ 裡的舊內容仍然有效。 || Compare register values, Get Features and actual queue capability. Retention of AQA is distinct from validity of Admin CQ contents.
先確認 Host 已清除上一輪未完成命令的對照資料，並重新初始化 Phase。即使新命令重用了相同 CID，也不能把它對應到上一輪的命令。 || First check retirement of old outstanding tracking and phase reinitialization. A reused CID must not resolve to a command from the previous lifetime.
''')
