"""Previously reported topics retained by the corrected Chapter 5 scope."""

def add(unit, BASE):
    unit('selftest',BASE,'5.2.6, 5.2.13.1.7','225-227,256-258',
      ('Device Self-test：從啟動要求到檢查結果','Device Self-test: from request to result'),
      ('Device Self-test 的命令完成表示已處理啟動或中止要求；背景作業進度與結果要從 LID 06h 分別讀取。STC 選動作，NSID 選測試對象，結果欄位的有效旗標決定哪些資訊可用。',
       'Device Self-test command completion acknowledges the start or abort request. LID 06h separately reports background progress and results. STC selects the action, NSID the target, and validity flags qualify result fields.'),
      [('先確認能力，再決定要測誰','Identify Controller 的 OACS 表示是否支援 Device Self-test；DSTO 說明可同時執行作業的範圍，EDSTT 提供 extended test 的估計時間。NSID=0 只選控制器本身；一般 NSID 選控制器及指定 namespace；FFFFFFFFh 選控制器及測試開始時可存取的 attached namespaces。Host-Initiated Refresh 不使用 NSID 選對象。'),
       ('用 STC 選動作，不用測試時間猜動作','CDW10 的 STC=1 啟動 short test，2 啟動 extended test，3 啟動 Host-Initiated Refresh，Eh 是廠商自訂測試，Fh 要求中止。CDW15 的 DSTP 只在 STC=Eh 時有廠商定義的用途；其他 STC 下是保留欄位。一般 NSID 若無效，回 Invalid Namespace or Format；若 namespace 存在但目前 inactive，回 Invalid Field in Command。存在與目前可存取是兩項不同判斷。'),
       ('把兩種命令衝突放到時間順序裡','已有作業時再要求 short、extended 或 refresh，新命令以 Device Self-test In Progress 結束，舊作業繼續。要求 abort 則會中止舊作業、把結果放進紀錄，並將目前作業設成沒有作業。沒有作業時收到 abort，命令成功而紀錄不變；不能把這種成功解成曾經中止過一次測試。'),
       ('目前進度和最近結果可能屬於兩次測試','LID 06h 的 Current Device Self-test Operation 與 Completion 描述正在進行的作業。後面最多 20 筆 Self-test Result Structure 是歷史紀錄，最新的一筆放最前面。因此畫面可能同時顯示 extended test 進行 50%，以及前一次 short test 成功；這兩件事並不矛盾。'),
       ('先確認有效性，再解讀失敗位置','一筆結果先看 DSTC 的作業種類、DSTR 的結果，再看 SEGN 指出的失敗測試區段及 POH 的時間背景。VDINFO 分別標示 NSID、Failing LBA、SCT、Status Code 是否有效。未設有效旗標的 FLBA=0 不能解成 LBA 0 損壞；有效 FLBA 提供定位線索，也不是整顆 SSD 的完整壞區清單。')],
      ('啟動 extended test 後，命令先成功，LID 06h 顯示作業進行 50%；等目前作業變成 none，再讀最新結果判斷成功、中止或失敗。',
       'After an extended-test request succeeds, LID 06h may report 50% progress. When the current operation becomes none, inspect the newest result to distinguish success, abortion, and failure.'),
      ('Figure 176–180 說明選對象、選動作和命令互動；218–219 把目前進度與歷史結果分開。先讀有效旗標，再讀失敗位置。',
       'Figures 176–180 define target selection, actions, and command interactions; 218–219 distinguish progress from history. Check validity before interpreting failure locations.'))

    unit('namespace',BASE,'5.2.24, 5.2.25','471-474',
      ('Namespace：建立儲存空間，再建立存取關係','Namespaces: create storage, then attach access'),
      ('Namespace Management 建立或刪除 namespace；Namespace Attachment 改變 controller 與 namespace 的連接關係。Create 成功回傳 NSID，不代表已附加；Detach 移除存取關係，不等於刪除資料對象。',
       'Namespace Management creates or deletes namespaces; Namespace Attachment changes controller associations. Create returns an NSID without automatically attaching it. Detach removes access rather than deleting the namespace object.'),
      [('用房間和入口理解兩種操作','把 namespace 想成已劃出的儲存空間，controller 則是主機存取它的入口。Create 產生空間，Attach 指定哪些入口連得到；Detach 只關掉某些入口，Delete 才移除 namespace。這個比喻只說明物件與連接關係，不表示 namespace 對應一組固定 NAND 顆粒。'),
       ('Create 的命令與資料結構要配成一組','Namespace Management 的 SEL=0 選 Create，SEL=1 選 Delete，SEL=2 選 Restore Default。Create 的 CSI 決定如何解讀 DPTR 指向的資料；對 NVM 命令集，容量以 logical blocks 表示，格式選擇決定每 block 有多少 data 與 metadata。成功時 CQE DW0 回傳新 NSID。容量、格式與回傳 ID 分屬輸入條件和輸出結果，不能把要求的容量當成 NSID。'),
       ('把 NVM Create 的必要欄位一起算','NSZE 是可定址的 block 數，NCAP 是可配置容量，NCAP 不得大於 NSZE；FLBAS 選資料格式。DPS 選保護資訊，NMIC 指定共享能力，NVMSETID 與 ENDGID 選資源歸屬；有支援 storage tag 的保護格式時，LBSTM 參與 storage tag 檢查設定。例如 NSZE=NCAP=1000，選 4096-byte data 格式，資料容量就是 4,096,000 bytes。metadata 與 PI 的設定仍必須與該格式能力相容。'),
       ('Attach 用 NSID 選空間，用清單選入口','Namespace Attachment 的 SEL=0 是 Attach，SEL=1 是 Detach；命令的 NSID 指定 namespace。DPTR 指向 Controller List，開頭 NUMCIDS 是 controller ID 的數量，後面每筆 CID 佔 2 bytes。若要連到 controller 3 和 5，NUMCIDS=2，清單放 3、5；這裡的 CID 是 controller identifier，與 SQE 用來追蹤命令的 Command Identifier 同名但用途不同。'),
       ('從錯誤回到具體對象','Namespace Already Attached 表示指定的關係已存在；Namespace Not Attached 表示要移除的關係不存在。Namespace Attachment Limit Exceeded 是可附加數量限制；Namespace Insufficient Capacity 則是 Create 的容量問題。先確認操作是 Create、Attach、Detach 還是 Delete，再看錯誤，才知道應檢查空間、關係或控制器能力。')],
      ('Create 得到 NSID=7，接著附加到 controller A、B。Detach A 後，B 的附加關係仍在；不能因 A 看不到 namespace 7，就宣稱它已被 Delete。',
       'Create returns NSID=7, which is then attached to controllers A and B. Detaching A leaves B attached; disappearance from A does not mean namespace 7 was deleted.'),
      ('Figure 442–444 把 Attachment 的對象、controller 清單及錯誤連起來；445–450 解 Management 的 SEL、CSI、Create 資料及回傳 NSID。',
       'Figures 442–444 connect attachment targets, controller lists, and errors; 445–450 explain Management SEL, CSI, Create data, and the returned NSID.'))

    unit('boot',BASE,'5.2.9, 5.2.13.1.21, 5.2.30.1.39','228-230,309-310,539-540',
      ('Boot Partition：讀映像、寫映像與切換啟動來源','Boot partitions: read, update, and select an image'),
      ('Boot Partition 與一般 namespace 是不同對象。LID 15h 讀取所選 partition 的資訊與內容；Firmware Commit CA=6 寫入映像、CA=7 選啟動來源；FID 85h 管理寫入保護。',
       'Boot partitions are distinct from ordinary namespaces. LID 15h reads a selected partition, Firmware Commit CA=6 writes its image and CA=7 selects the boot source, and FID 85h controls write protection.'),
      [('先分清映像位置和啟動選擇','裝置的 Boot Partition 以 BPID 區分，不能用一般 Read 命令的 NSID 選取。支援情況由控制器的 Boot Partition 能力確認；active partition 表示被選為啟動來源，不等於另一個 partition 沒有有效映像。更新時可以先準備另一份映像，再決定何時切換來源。'),
       ('讀 Log 時，映像前面還有 16-byte header','LID 15h 的 LSP 用 BPID 選 partition；Figure 280 的前 16 bytes 是識別、容量等資訊，Boot Partition Data 從 byte 16 開始。若要讀映像內 offset 4096 的 4096 bytes，採 byte offset 的 Get Log Page 應用 LPO=16+4096=4112，NUMD=4096/4−1=1023。這裡多出的 16 來自 Log header，與映像本身的位置無關。'),
       ('寫好內容不會自動切換 active partition','Firmware Image Download 先送映像，Firmware Commit 的 CA=6 再將下載內容寫到 BPID 指定的 Boot Partition；CA=7 選定 active partition。這兩種操作不使用 firmware slot 的語意。先確認映像寫入成功，再決定啟動來源，才不會把「已下載」當成「已在指定 partition 保存」。'),
       ('Set 和 Get 的保護值不能直接互抄','FID 85h 的 BP0WPS 位於 bits 2:0，BP1WPS 在 bits 5:3。Set 時 000b 表示該 partition 不變，001b 是 Unlocked，010b 是 Locked，011b 是 Locked Until Power Cycle。Get 回的是目前狀態，不會用 000b 表示不變；100b 表示由 RPMB 控制，不能拿來當一般 Set 值。例如只解鎖 BP1，BP0 不變，CDW11=(1<<3)=08h。'),
       ('把共享限制翻成一個可觀察的情境','假設同一個 Boot Partition 由兩個 domain 共用，不能用這個 Feature 將它設成 Locked Until Power Cycle；限制的是這種鎖定方式，不是說 partition 無法讀取或完全不能使用。已由 RPMB 控制的保護也不能透過一般 Set Features 改寫。對由此 Feature 設定的保護，Controller Level Reset 不會替主機重新上鎖；power cycle 後則回到 Locked，兩種事件要分開。')],
      ('映像 offset 4096 對應 LID 15h 的 byte offset 4112；BP1 的 Unlock 編碼是 08h。前者在選資料位置，後者在改保護狀態，數字不可互換。',
       'Image offset 4096 maps to byte offset 4112 in LID 15h; unlocking BP1 uses 08h. The first selects a data position, the second changes protection.'),
      ('Figure 279 選 partition，280 分 header 和映像；542 分開解釋 Set／Get 的狀態值，再對回 Firmware Commit 的 CA=6／7。',
       'Figure 279 selects a partition and 280 separates its header from image data. Figure 542 distinguishes Set/Get values; connect these to Commit CA=6/7.'))

    unit('telemetry',BASE,'5.2.13.1.8, 5.2.13.1.9','258-263',
      ('Telemetry：完整取得同一次診斷資料','Telemetry: retrieve one consistent capture'),
      ('LID 07h 由主機要求建立 Telemetry，LID 08h 回報控制器建立的資料。讀取時要同時處理 512-byte block 邊界、累積 Data Area 範圍與 generation，避免拼接不同次擷取。',
       'LID 07h supports host-initiated telemetry; LID 08h reports controller-initiated data. Retrieval combines 512-byte block boundaries, cumulative data areas, and generation checks to avoid mixing captures.'),
      [('這份 Log 解決的是取得診斷材料','Telemetry header 提供資料範圍、產生資訊及原因識別；後面的診斷內容可有廠商定義的格式。知道怎樣完整取回資料，與知道廠商如何解釋每一個診斷 byte，是兩個層次。主機至少能檢查長度是否齊全、擷取版本是否一致，並保留 header 供後續解讀。'),
       ('Data Area 是累積範圍，不是四塊相鄰分區','每個 block 為 512 bytes，block 0 是 header，各 Data Area 都從 block 1 開始。若 Data Area 1 Last Block=65，其資料有 65×512=33280 bytes；若 Data Area 2 Last Block=1000，Area 2 包含 Area 1，新增部分是 blocks 66–1000。不能把 65 與 1000 相加當成 Area 2 的長度。'),
       ('只在開始擷取時要求建立資料','讀 LID 07h 時，CTHID=1 要求建立 Host-Initiated Data；後續分段取同一份資料時用 CTHID=0。每段都設 1，可能每次都重新擷取，最後拼出不同時間的內容。先取得 header 決定所需範圍，再分批讀取，LPO 使用 byte offset 時等於 block number×512。'),
       ('用 generation 辨認資料是否在途中更換','取得資料前後核對相應 Generation Number。假設第一次 header 是 generation 7，取完 payload 後變成 8，代表中間有新擷取，不能把現有片段當成同一份完整紀錄。應重新以一致的擷取取得所需範圍。generation 是有限寬度的計數，不是永久唯一識別碼。'),
       ('控制器擷取另有可用性和確認時機','LID 08h 的 TCDA 表示 Controller-Initiated Data 是否可用。要分段保留事件時使用 RAE=1，待資料已完整取得後，再依事件確認機制用 RAE=0 讀取。Data Area 4 另需裝置支援與主機的 Extended Telemetry Data Area 4 宣告；未符合這些條件時，不能只因 header 有固定欄位位置就假設 Area 4 可取。')],
      ('header 為 block 0、Area 1 到 block 65：完整 header 加 Area 1 共 66×512=33792 bytes；block 66 的 byte offset 恰為 33792。',
       'With header block 0 and Area 1 ending at block 65, header plus Area 1 occupies 66×512=33792 bytes. Block 66 starts at byte offset 33792.'),
      ('Figure 220／222 的建立與選擇參數決定讀哪一份資料；221／223 的邊界、可用性和 generation 決定如何完整取回。',
       'Figures 220/222 select or create a capture; 221/223 provide boundaries, availability, and generation for complete retrieval.'))

    unit('sanitize',BASE,'5.1.1, 5.2.26, 5.2.13.1.38, 5.2.30.1.16','204-205,340-345,475-477,503-504',
      ('Sanitize：清除要求、背景進度與最終狀態','Sanitize: request, background progress, and final state'),
      ('Sanitize 依支援能力選 Block Erase、Overwrite 或 Crypto Erase；命令成功不表示背景清除已完成。LID 81h 回報狀態、進度與估計時間；FID 17h 的設定會影響要求不解除配置時的處理方式。',
       'Sanitize selects supported Block Erase, Overwrite, or Crypto Erase actions. Command success is not completion of background sanitization. LID 81h supplies state, progress, and estimates; FID 17h affects handling of no-deallocation requests.'),
      [('先看能做哪一種清除，再選方法','Identify Controller 的 SANICAP 分別表示 Block Erase、Overwrite、Crypto Erase 等能力。Block Erase 透過媒體清除機制，Overwrite 以指定樣式覆寫，Crypto Erase 則使保護舊資料的金鑰無法再用。不能把一般 Write Zeroes 或 Dataset Management 的 AD 當成 Sanitize；它們的目標和完成保證不同。'),
       ('把 action 和只對該 action 有效的欄位配在一起','CDW10 的 SANACT=2 是 Block Erase，3 是 Overwrite，4 是 Crypto Erase；1 用於離開 Sanitize Failure Mode，5 用於離開 Media Verification State。Overwrite 才需要用 CDW11 的 OVRPAT 指定 32-bit 樣式，並以 OWPASS 選 pass 數：1–15 就是對應次數，0 表示 16 次。OIPBP 決定 pass 間是否反轉樣式，不能把它當成增加 pass 數。'),
       ('清除資料和解除 LBA 配置分開判斷','NDAS=1 要求清除後不要解除配置。若 SANICAP.NDI=1，代表禁止這種要求，此時 FID 17h 的 NODRM=0 會使命令回 Invalid Field in Command；NODRM=1 則處理清除，若成功會以 SOS=100b 告知仍發生解除配置。NDI=0 時，NODRM 不改變處理方式。解除配置是後续邏輯 block 的配置狀態，清除則是舊 user data 的保護目標。EMVS 另外要求完成清除後進入 Media Verification State；它也不是一般清除成功的同義詞。下方欄位表按支援能力、命令要求、設定、結果逐項配對。'),
       ('先看 SSTAT，再決定 SPROG 是否值得換算','Sanitize 命令可在背景工作完成前就回 CQE。主機讀 LID 81h 時，先以 SSTAT 判斷目前是否正在清除，再將有效的 SPROG 換算為約 SPROG×100/65536%。例如 32768 約為 50%。狀態若是已完成或失敗，就直接解讀該狀態，不能只看進度數字宣布成功；估計時間欄位也不是成功期限。'),
       ('完成、失敗與驗證狀態各有下一步','清除完成後，以 Log 的最終狀態確認結果；若進入 Failure Mode，應辨認是清除失敗狀態，不能把命令曾回成功當成舊資料已處理完。Exit Failure Mode 和 Exit Media Verification State 是不同 SANACT。讀共同命令限制表時，先選目前狀態對應的欄，再看要執行的命令，不能把 Format 期間的允許規則直接套到 Sanitize。')],
      ('以 OWPASS=2、OVRPAT=11223344h、OIPBP=0 要求 2 次同樣樣式的 Overwrite。收到命令成功後繼續讀 LID 81h，直到最終狀態明確回報結果。',
       'OWPASS=2, OVRPAT=11223344h, and OIPBP=0 request two passes with the same pattern. After command success, continue reading LID 81h until the final state reports the result.'),
      ('Figure 451–453 解 action、Overwrite 與命令結果；312 解背景狀態與時間；492 解 no-deallocate 設定。Figure 144 用狀態判斷其他命令能否執行。',
       'Figures 451–453 explain actions, Overwrite, and command results; 312 covers background state and time; 492 covers no-deallocate configuration. Use Figure 144 for state-dependent command permission.'))
