from scripts.nvme_qa_model import add

add(54,'Feature 的 Current、Default、Saved Value 及 Supported Capabilities 分別代表什麼？ || What do Current, Default, Saved and Supported Capabilities mean?','feature',['feature','getfeat','idctrl'],'''
Current 是目前使用的值，Default 是預設值，Saved 是已保存的值；Supported Capabilities 則說明這項 Feature 能否變更或保存。前三者描述設定內容，最後一項描述能力，不能當成四份相同設定。 || Separate the active value, manufacturing default, saved value and change/save capabilities; these are not four identical settings.
比較這些回覆時，必須使用相同 FID、相同作用範圍及對應的選擇欄位。例如，兩個不同 namespace 的 Current 值，本來就可能不同。 || Compare the same FID, scope and selectors; Current can differ across namespaces.
Identify.ONCS.SSFS 表示是否支援 Save／Select 機制。確認支援後，再以 Get Features.SEL=3 查詢個別 FID 的 CHANG、NSSPEC 與 SVBL，了解它是否可變更、是否以 namespace 為範圍，以及是否可保存。 || ONCS.SSFS advertises Save/Select support. Under that mechanism, Get Features.SEL=3 returns CHANG/NSSPEC/SVBL for the FID.
SEL=0 Current、1 Default、2 Saved、3 Supported Capabilities。SEL=3 的 DW0 bit2／1／0 分別是 CHANG／NSSPEC／SVBL，不是 Feature 的工作值。 || SEL0/1/2/3 select Current/Default/Saved/Supported Capabilities. With SEL3, DW0 bits2/1/0 are CHANG/NSSPEC/SVBL, not operational values.
先查能力，再讀 Current。若要判斷重設後應使用哪個值，才進一步查 Saved 與 Default。Feature 不可保存或尚未有 Saved 值時，SEL=2 回傳 Default；若個別 Feature 本身沒有 Default，則依它的例外規則處理。 || Read capabilities and Current first, then Saved/Default for reset analysis. If unsaveable or never saved, SEL2 returns Default, subject to features that define no Default.
例如 SEL=3 回傳 DW0=5，表示 CHANG=1、SVBL=1、NSSPEC=0，也就是可變更、可保存，而且不是 namespace scope。這不表示 Current=5；NSSPEC=0 也不足以單獨判定它一定是 controller scope。 || SEL3 result5 means changeable, saveable and NSSPEC=0, not Current=5. NSSPEC=0 alone does not establish controller scope.
不支援 FID 時，回報 Invalid Field（0/02h）；SEL=4～7 則是保留編碼。若 controller 不支援所要求的 SEL，不能將回傳內容當成有效的 CHANG 或 SVBL 來解讀。 || Unsupported FID uses Invalid Field (0/02h); SEL4–7 are reserved. Without Select support, do not treat a response as valid CHANG/SVBL discovery.
比較結果時，同時保留 FID、SEL 與回傳值。若只留下 DW0 的數字，之後就無法確認它是工作設定值，還是 Supported Capabilities 的能力 bitmap。 || Preserve FID and SEL with the returned DW0 to distinguish a value from a capability bitmap.
先確認 Get Features 使用的 SEL。若其實查的是能力而不是 Current，即使數字與 Set 值不同，也不能據此判定設定沒有生效。 || First check SEL before concluding that Set failed to take effect.
''')

add(55,'Set Features 的 Save 位元如何影響 Controller Reset 與 Power Cycle 後的 Feature 值？ || How does Set Features.Save affect values after reset and power cycling?','feature',['feature','setfeat','getfeat'],'''
Save 位元讓 Host 選擇：只改變目前使用的值，或同時更新日後恢復設定時使用的保存值。 || Let the host change only the active value or also the persistent value used on restoration.
保存的作用範圍由各 Feature 決定。針對 namespace 保存的設定，與針對 controller 保存的設定，不能當成同一份全域資料。 || Saving follows feature scope; namespace-scoped and controller-scoped settings are not one global value.
先確認 ONCS.SSFS，再確認這個 FID 的 SVBL。controller 支援 Save 機制，不表示每一種 Feature 都可以保存。 || Check ONCS.SSFS and the FID's SVBL. Controller Save support does not make every feature saveable.
Set Features 的 SV=0 時，只改 Current，不改 Saved；SV=1 且設定成功時，則同時更新 Current 與 Saved。這兩種操作都不會把 Default 改成 Host 新設定的值。 || SV=0 changes Current without updating Saved; successful SV=1 updates both. Default does not become the host's chosen value.
先確認保存能力，送出 Set 並等待成功，再分別讀取 Current 與 Saved。執行指定的重設後，依該 Feature 的作用範圍與例外規則，確認 Current 恢復成正確的值。 || Discover support, Set and await completion, then read Current/Saved separately. After the chosen reset, verify Current under scope and exception rules.
例如原本 Saved=A，Host 以 SV=0 將 Current 改為 B，此時功能使用 B。之後若發生會從 Saved 恢復設定的重設，Current 應回到 A，而不是保留 B。 || With Saved=A and an SV=0 change to B, Current becomes B; a reset that restores Saved returns it to A, not B.
Feature 不可保存，Host 卻使用 SV=1 時，必須回報 Feature Identifier Not Saveable（SCT=1, SC=0Dh）。controller 不能先回報保存成功，之後卻因原本不支援保存而遺失設定。 || SV=1 for an unsaveable feature shall return Feature Identifier Not Saveable (1/0Dh), not silently succeed and lose the saved setting.
目前是否生效、Saved 是否更新，以及重設後是否正確恢復，是三個不同驗證點。只讀到 Current=B，不能證明 Saved 也已變成 B。 || Save success, active application and restoration are three separate checks. Current=B does not establish Saved=B.
先核對原 Set 命令的 SV 及該 FID 的 SVBL，再確認發生的是哪一種重設，以及重設涵蓋哪些物件。 || First inspect original SV/SVBL, then reset type and coverage.
''')

add(56,'不支援的 Feature、不合法 Feature 值或 Controller 不支援 Save 時，應如何回應？ || Which errors apply to unsupported features, invalid values and unsupported Save?','feature',['feature','setfeat','getfeat','status'],'''
不支援 Feature、Feature 目前不可變更、不可保存，以及設定值非法，是不同失敗原因。先分清楚是哪一種，才能選擇正確的 Status 與修正方法。 || Distinguish unsupported function, unchangeability, unsaveability and invalid value; their causes and corrections differ.
判斷時要看這次 Set 或 Get 使用的 FID、目標範圍及目前狀態，不能只根據 controller 型號就推論命令應成功。 || Evaluate the FID, target scope, current state and this Get/Set operation, not merely the controller model.
使用 SEL=3 的能力資料前，先確認 ONCS.SSFS。CHANG=1 只表示這項 Feature 存在可變更的設定，不保證它進入永久狀態後仍可改回。 || SEL3 capabilities require SSFS. CHANG=1 means some values are changeable, not that a current permanent state can be reversed.
一起檢查 FID、SV、NSID、CDW11 及資料 buffer。有些 Feature 還需要額外的選擇欄位，因此只看 CQE DW0，無法確認原命令的全部參數是否合法。 || Check FID, SV, NSID, CDW11 and payload. Some features require selectors beyond a single value.
先用合法的 Current 值建立比較基準，再分別測試不支援的 FID、非法設定值、SV=1 及作用範圍錯誤。每次只改一項，避免同一筆命令同時違反多條規則。 || Establish a valid baseline, then separately test unsupported FID, bad values, SV=1 and wrong scope.
合法 Set 成功完成後，才表示設定已完成。對不可變更的 Feature 寫入與目前相同的值時，規範允許成功，也允許回報 Feature Not Changeable；驗證不能只接受其中一種結果。 || Successful Set establishes completion. Setting an unchangeable feature to its existing value may succeed or return Feature Not Changeable; both are permitted.
不支援的 FID 或已定義欄位的非法值，一般回報 0/02h；不可保存回報 1/0Dh；不可變更回報 1/0Eh。若對 controller scope 的 Feature 執行 Set，卻指定有效 NSID，則回報 1/0Fh。個別 FID 若對操作順序或狀態另有規定，優先依專用規則判斷。 || Unsupported FID/invalid defined value:0/02h; unsaveable:1/0Dh; unchangeable:1/0Eh; controller-scoped Set with a valid NSID:1/0Fh. Specific FID ordering/state errors take precedence.
收到錯誤 completion 後，重新 Get，確認目前值符合該 Feature 的錯誤處理規則。回報錯誤不一定等於完全沒有副作用，必須依個別定義判斷。 || Re-read after failure according to the feature's error rules; an error is not a universal proof of no side effects.
先確認測試命令是否同時包含多個非法條件。如果是，controller 可能合法地選擇其中一個錯誤回報，不能只因它沒回預想的那個 Status 就判錯。 || First exclude multiple simultaneous faults that allow different valid error choices.
''')

add(57,'Host 如何判斷某個 Feature 是否需要指定 NSID？ || How does the host determine whether a feature requires NSID?','feature',['feature','getfeat','setfeat','nvmfeat'],'''
設定 Feature 前，必須先確認它作用於哪個物件，才能正確填寫 NSID 及其他選擇欄位。 || Select the correct target before changing configuration.
Feature 的作用範圍可能是 controller、namespace、NVM subsystem、NVM Set、Endurance Group 或其他管理物件，並非只有 controller 與 namespace 兩種。 || Feature scope can be controller, namespace, subsystem, set, group or another management entity, not just two categories.
SEL=3 回傳 NSSPEC=1，表示 Feature 以 namespace 為範圍。若 NSSPEC=0，則還要查 Feature Identifiers Supported and Effects 的 scope，以及 Base Figure 466 或 NVM Figure 92，才能確認真正的作用對象。 || SEL3.NSSPEC=1 indicates namespace scope. With zero, inspect the feature-effects scope and Figure466/NVM Figure92.
對 controller scope 的 Feature，Get 與 Set 可以使用 NSID=0 或 FFFFFFFFh。若改填有效 namespace ID，Get 可以回傳 controller 的值，但 Set 必須回報作用範圍錯誤。兩種命令不能套用完全相同的 NSID 判斷。 || Controller-scoped Get/Set accepts NSID0 or FFFFFFFFh. A valid namespace ID on Get can return the controller value, whereas Set must report the scope error.
先確認 FID 的作用範圍，再填入 NSID 及其他物件選擇欄位。namespace scope 通常使用 active NSID；若使用 broadcast，Get 與 Set 的規則不同，multi-domain 配置也可能有額外限制。 || Determine scope, then NSID and other selectors. Namespace scope normally uses an active NSID; broadcast Get/Set differ and multi-domain restrictions apply.
例如 FID05h Error Recovery 設定的是 namespace，FID01h Arbitration 設定的是 controller。即使兩者都在 CDW11 放入數值，也不能因此使用相同的 NSID 規則。 || FID05h Error Recovery is namespace-scoped and FID01h Arbitration controller-scoped; numeric CDW11 values do not make their NSID rules interchangeable.
對 controller scope 的 Feature 執行 Set，卻給入有效 NSID 時，回報 Feature Not Namespace Specific（1/0Fh）。對 namespace scope 的 Feature 執行 Get，卻使用 FFFFFFFFh 時，一般回報 Invalid Namespace or Format（0/0Bh）；若個別 Feature 有例外，則依例外規則處理。 || Controller-scoped Set with a valid NSID returns1/0Fh. Namespace-scoped Get with FFFFFFFFh generally returns0/0Bh, subject to specific exceptions.
NSSPEC=0 的 Feature 仍可能以 subsystem 或 NVM Set 為範圍。不能把這個值直接解釋為「所有 namespace 都使用同一個 controller 設定」。 || NSSPEC=0 can coexist with subsystem/set scope; it does not universally mean one controller value for all namespaces.
先讀取 Feature 的作用範圍定義，再檢查原命令的 NSID。若作用對象選錯，失敗不一定與 namespace 本身的狀態有關。 || First read the scope definition and original NSID before suspecting namespace failure.
''')

add(58,'Arbitration、Number of Queues 及 I/O Command Set Profile Feature 如何設定與驗證？ || How are Arbitration, Number of Queues and I/O Command Set Profile configured and checked?','feature',['arbit','number','profile','idlist','setcomplete','status'],'''
Arbitration 控制排程參數，Number of Queues 協商 queue 配額，I/O Command Set Profile 則選擇可使用的命令集組合。三者用途不同，也各有合適的初始化時機。 || These control scheduling parameters, queue allocations and allowed command-set combinations at different initialization stages.
這三種 Feature 都透過 controller 設定；不過，改變 Command Set Profile 還會影響 namespace 及命令集的可用性。 || All three target controller configuration, while Profile affects namespace/command-set usability.
Arbitration 要搭配 CAP.AMS 與 CC.AMS；Number of Queues 以成功 Set 的回覆確認實際配額；Command Set Profile 則先查 CAP.CSS.IOCSS 及 CNS1Ch 回傳的組合 vectors。 || Arbitration uses CAP.AMS/CC.AMS; queue allocation uses successful Set results; Profile requires CAP.CSS.IOCSS and CNS1Ch vectors.
FID01h 使用 AB、HPW、MPW、LPW 設定仲裁；FID07h 由 NSQR、NCQR 提出 queue 數量要求，再以 NSQA、NCQA 回報實際配置。FID19h 的 IOCSCI 則是命令集組合的索引，三者的數值不能使用相同方式解讀。 || FID01h uses AB/HPW/MPW/LPW; FID07h maps requested to allocated SQ/CQ counts; FID19h.IOCSCI is a combination index.
依初始化流程，先選擇 Command Set Profile 並確認 namespace，再設定 Number of Queues，之後才建立 CQ 與 SQ。Arbitration 的參數則必須與 CC.AMS 及各 SQ 的 QPRIO 一起驗證。 || Select the profile and discover namespaces, allocate queues and create CQs/SQs; verify arbitration parameters together with CC.AMS/QPRIO.
讀回設定時，使用相同 FID 及對應的選擇欄位。CC.CSS≠110b 時，Set FID19h 會成功，但不產生作用；CC.CSS=110b 時，才使用所選命令集組合。Profile index=0 表示第 0 組，不表示停用命令集。FID07h 回傳的配額也不等於已建立的 queue 數量。 || Read back the same FID/selectors. With CC.CSS other than110b, Set FID19h succeeds without effect; with110b, the selected combination applies. Profile index0 selects combination0, not no command sets. FID07h allocation is not instantiated queue count.
I/O queue 建立後再 Set FID07h，回報 0/0Ch。CC.CSS=110b 時，若 IOCSCI 選到內容為 0 的組合，或已附加的 namespace 使用了該組合不支援的命令集，FID19h 必須回報 Combination Rejected。規格對此 Status 有內部差異：Figure 104 列為 1/2Bh，Figure 554 列為 1/15h。因此，本題保留兩處資訊，不單憑其中一張表判定韌體違規。 || Setting FID07h after queue creation returns0/0Ch. With CC.CSS=110b, FID19h shall return Combination Rejected if IOCSCI selects a zero-valued combination or an attached namespace uses an I/O command set absent from that combination. The supplied spec conflicts: Figure104 lists Combination Rejected as1/2Bh, Figure554 as1/15h. Preserve that discrepancy rather than declaring noncompliance from either table alone.
同時驗證設定值、實際可建立的 queue 範圍，以及可使用的命令集。三個 Feature 各自提供不同證據，不能用其中一項的 Get 結果代替另外兩項。 || Verify settings, creatable queue ranges and usable command sets independently.
先檢查初始化順序，確認 Host 是否在 I/O queue 已建立後，才嘗試重新設定 Number of Queues。 || First check whether queue allocation was attempted after I/O queue creation.
''')

add(59,'Interrupt Coalescing 與 Interrupt Vector Configuration 如何設定與驗證？ || How are interrupt coalescing and vector configuration set and verified?','feature',['irqfeat','irq','create'],'''
Interrupt Coalescing 讓 controller 合併中斷通知，在通知延遲與 Host 處理負擔之間取捨。CQE 已寫入的時間，與中斷實際產生的時間，因而不一定相同。 || Trade notification latency against interrupt overhead; posting a completion and generating an IRQ are different events.
FID08h 控制 I/O interrupt coalescing；FID09h 則指定某個 vector 是否使用 coalescing。Admin CQ 不支援 coalescing，不能拿它套用相同的聚合預期。 || FID08h controls I/O interrupt coalescing; FID09h selects its application per vector. Admin CQ does not support coalescing.
一起檢查 Create CQ 的 IEN／IV、PCIe 中斷模式及 mask。PCIe 規範要求支援這些 Feature，但實際如何合併通知，允許存在實作差異。 || Check CQ.IEN/IV, PCIe interrupt mode and masks. Feature support is required, while aggregation algorithms remain implementation-specific.
FID08h 的 TIME 以 100 μs 為單位，THR 使用 zero-based 編碼；任一欄位為 0，都會隱含停用 coalescing。FID09h 透過 IV 指定 vector，CD=1 表示不對該 vector 聚合通知，不是遮蔽中斷。 || FID08h TIME uses100 μs units and THR is zero-based; either zero implicitly disables coalescing. FID09h uses IV/CD; CD=1 disables coalescing, not interrupts.
先透過 Create CQ 將 CQ 關聯到合法 vector，再設定 FID09h。設定 FID08h 後，以 Get Features 讀回確認，並一起觀察多筆 completion 的寫入時間與中斷通知行為。 || Associate a valid vector with a CQ before Set FID09h. Set/read FID08h and observe CQE timing alongside interrupts.
設定成功不代表每一種工作負載下，中斷都必須在 TIME 或 THR 指定的精確時點產生。PCIe 規範將這些參數的使用方式留給實作決定，甚至允許不實際執行聚合，因此不能把它們當成固定的通知時間保證。 || Settings can complete successfully without defining exact IRQ timing for every workload. PCIe makes parameter use implementation-specific and permits no coalescing implementation.
FID09h 指定的 IV 非法，或未關聯到既有 I/O CQ 時，應回報 Invalid Field（0/02h）。這與 Create CQ 所使用的 Invalid Interrupt Vector（1/08h）不同，要依失敗的是哪一條命令判斷。 || Invalid or unassociated IV in FID09h should return Invalid Field (0/02h), unlike Create CQ's Invalid Interrupt Vector (1/08h).
將 Get 值、CQ 配置、mask 與通知行為一起比對。即使 CD=1 已停用聚合，MSI-X mask 仍可能遮蔽中斷；沒有收到中斷，不一定表示 CD 設定失敗。 || Check readback, CQ mapping, masks and notification behavior. CD=1 does not override an MSI-X mask.
先分清楚「停用中斷聚合」與「遮蔽中斷」。前者改變通知如何合併，後者控制通知是否被遮蔽，不能用同一個 bit 解釋。 || First distinguish disabling coalescing from masking interrupts.
''')

add(60,'Volatile Write Cache 與 Write Atomicity Normal 控制什麼行為？ || What do Volatile Write Cache and Write Atomicity Normal control?','feature',['vwc','nvmfeat','nvmatomic','idns'],'''
持久性問的是資料是否已進入非揮發儲存；原子性問的是一組 logical blocks 是否依規定單位完整更新。這是兩種不同保證，必須分開判斷。 || Separate persistence from atomicity: reaching nonvolatile storage is different from updating logical blocks as a defined unit.
FID06h 控制 controller 的揮發性寫入快取；FID0Ah 控制正常情況下的寫入原子性要求。設定 FID0Ah 不會直接改寫 namespace 宣告的原子寫入單位。 || FID06h controls controller volatile caching; FID0Ah controls normal atomicity requirements, not the advertised namespace atomic units.
先用 VWC 確認是否存在揮發性寫入快取，再查看 AWUN、AWUPF、namespace 的覆寫欄位及邊界資訊，判斷適用的原子性保證。 || VWC advertises cache presence; AWUN/AWUPF, namespace overrides and boundaries describe atomicity.
FID06h.WCE=0 時，寫入的使用者資料必須符合持久性要求。FID0Ah.DN=1 則解除 AWUN／NAWUN 的正常寫入原子性要求，但不解除 AWUPF／NAWUPF 的斷電原子性要求。 || With FID06h.WCE=0, written user data must be persistent. FID0Ah.DN=1 removes AWUN/NAWUN requirements while retaining AWUPF/NAWUPF.
先讀取能力與 namespace 格式，Set 成功後再 Get 確認。接著以符合原子單位及邊界的 Write 情境，比較規範允許的結果。若要明確區分新舊設定，應先等既有命令完成，再變更 Feature。 || Read capabilities/format, Set/Get, then compare allowed outcomes for Writes respecting units/boundaries. Drain first for a clean setting transition.
WCE=0 不會讓任意大小的 Write 都具備原子性；DN=1 也不會自動讓已完成的資料具有持久性。兩個設定控制不同性質，不能互相替代。 || WCE=0 does not make arbitrary-size writes atomic; DN=1 does not make completion persistent. The controls are not substitutes.
controller 沒有揮發性寫入快取，Host 卻 Get 或 Set FID06h 時，必須回報 Invalid Field（0/02h）。其他參數及 namespace 原子性條件，則依適用命令的規則判斷。 || Get/Set FID06h without volatile cache shall return Invalid Field (0/02h). Other conditions follow applicable command/namespace/atomicity rules.
一起查看 Current.WCE、Current.DN，以及 Identify 中對此 namespace 有效的原子單位。FUA 是個別命令的持久性要求，不會擴大原子寫入單位。 || Correlate Current.WCE/DN with the effective atomic units. FUA requests persistence for a command without enlarging its atomic unit.
先釐清要驗證的是「一組資料會不會只更新一部分」，還是「已完成的資料會不會因斷電而遺失」，再選擇對應欄位及測試條件。 || First identify whether the requirement is no torn update or survival of power loss.
''')

add(61,'Asynchronous Event Configuration 如何決定哪些事件需要回報？ || How does Asynchronous Event Configuration select reported events?','feature',['aec','aer','idctrl','nvmfeat'],'''
Asynchronous Event Configuration 讓 Host 選擇要接收哪些狀態變更通知。不過，設定通知種類後，Host 仍須自行提交 Asynchronous Event Request，等待 controller 回報事件。 || Select desired change notifications; configuration does not submit an event request on the host's behalf.
FID0Bh 設定的是此 controller 的通知行為。各種通知所描述的狀態，則可能屬於 SMART、namespace 或其他不同範圍的物件。 || FID0Bh configures controller notifications about state with various scopes.
OAES 表示選配事件支援，SMART 的警告也有相應能力；NVM 特定 bit 另見 NVM 規格。 || OAES advertises optional event support, with applicable health capabilities and NVM-specific bit definitions.
CDW11 的啟用位決定要接收哪些通知；AER completion 中的 AET、AEI、LID 則描述實際發生的事件。兩者用途及編碼不同，不能當成同一份 bitmap 解讀。 || CDW11 enable bits select notifications. AER completion AET/AEI/LID describes the event; it is not the same bitmap.
先確認事件支援能力，設定合法的通知 mask，再提交 AER。事件條件成立並收到回報後，讀取事件資訊及對應 Log，依該事件的規則完成確認，並補送新的 AER，繼續接收後續通知。 || Discover support, Set the mask, post AER, observe a condition, read the event/log, acknowledge under its rules and replenish requests.
啟用通知時，如果事件條件已經成立，controller 也會依此 Feature 的規則回報。因此，可能收到的事件不只限於設定完成後才新發生的變化。 || A condition already true when enabled is also reported under this feature's rules; reporting is not limited to later state changes.
嘗試啟用 controller 不支援的事件時，必須回報 Invalid Field（0/02h）。若只是沒有未完成的 AER 可供回報，導致 Host 尚未收到通知，則不是 Set Features 的錯誤 Status。 || Enabling an unsupported event shall return Invalid Field (0/02h). No outstanding AER can delay notification without being a Set Features error.
一起檢查 OAES、Current mask、是否有等待中的 AER，以及事件是否仍處於遮蔽狀態。通知啟用位為 1，並不足以證明 Host 一定會立即收到事件。 || Correlate OAES, Current mask, pending requests and event masking. An enabled bit alone does not guarantee immediate delivery.
先確認 Host 確實提交了尚未完成的 AER，再確認先前事件是否已依規則完成確認，讓後續通知可以繼續回報。 || First check outstanding AERs and acknowledgement of prior events.
''',{9:'FID0Bh 用來設定通知，但每種事件仍有各自的發生條件與清除規則。它不是所有 Error 類型事件的總開關；讀取 Get Features，也不能代替提交新的 AER 來接收通知。 || This feature configures notifications, with event-specific conditions and clearing rules. FID0Bh is not a universal switch for every Error event, and Get Features does not replenish AERs.'})

add(62,'Power Management、Autonomous Power State Transition 及 Host Controlled Thermal Management 有何差異？ || How do Power Management, APST and Host Controlled Thermal Management differ?','feature',['power','thermal','idctrl'],'''
Power Management 讓 Host 直接選擇 power state；APST 依閒置條件自動轉換狀態；HCTM 則依溫度進行熱管理。三者可能都影響功耗與效能，但觸發原因不同。 || Separate explicit host power-state selection, idle-driven automatic transitions and temperature-driven power/performance management.
這些設定透過 controller 操作。多個 controller 共用同一 domain 時，功耗狀態可能互相影響，因此不能只觀察單一路徑就解釋全部變化。 || Configuration targets a controller, while shared-domain controllers can interact in power behavior.
讀 NPSS／Power State Descriptors、APSTA 與 HCTMA、MNTMT／MXTMT。 || Read NPSS/power-state descriptors, APSTA, HCTMA and MNTMT/MXTMT.
FID02h 選擇 PS 及相關限制。FID0Ch 的 APSTE 啟用一張 32-entry 表；每格的 ITPT 是在該狀態下的閒置時間，單位為 ms，ITPS 則指定要進入的非工作狀態。FID10h 的 TMT1 與 TMT2 是熱管理溫度門檻，單位為 Kelvin。 || FID02h selects PS and related limits. FID0Ch.APSTE enables a32-entry table with ITPT idle milliseconds in that state and ITPS targeting a nonoperational state. FID10h TMT1/TMT2 use kelvins.
先查看可用狀態及進出延遲，再決定由 Host 選擇 PS，或使用 APST 表自動轉換。熱管理門檻另外設定；TMT1、TMT2 都非零時，必須符合 TMT1<TMT2。APST 進入新狀態後，接著使用該新狀態所對應的閒置條件。 || Discover states/latencies, select explicit PS or an APST table and separately set legal TMT1<TMT2 when both are nonzero. Each new state uses its own idle-transition condition.
Set FID02h 成功時，controller 已到達指定 PS；但若 APST 已啟用，之後仍可能再自動轉換狀態。HCTM 因溫度觸發的調整，也不表示 Host 另外送出了一筆 Power Management 命令。 || Successful FID02h Set establishes the requested PS, but enabled APST may transition again. HCTM activity is not another host Power Management command.
不支援的 power state、非法 APST 目標，以及不符合範圍或順序的溫度門檻，依各欄位規則判定 Invalid Field（0/02h）。設定看似比較省電，也不能使非法參數變成合法。 || Unsupported states, invalid APST targets and illegal thermal ranges/order follow the relevant Invalid Field (0/02h) requirements.
分別比對 Get Features 的設定、目前操作狀態、SMART 溫度與 HCTM 計數。單憑功耗下降，無法確定是 APST、Host 指定狀態，還是熱管理造成。 || Compare configuration, operational state, SMART temperature and HCTM counters separately. Lower power alone does not identify APST as the cause.
先辨認狀態變化由什麼觸發：Host 的 Set、閒置計時，還是溫度條件。確認原因後，再檢查該機制的設定。 || First identify whether the trigger was host Set, idle timing or temperature.
''',{12:'Power Management 與 APST 若不可保存，重設後依 Figure 466 回到預設；HCTM 即使不可保存，仍規定具有持續性。若 Feature 可保存，則改依 Saved 恢復規則判斷。同一 domain 有多個 controller 時，還要協調它們的控制設定。 || Non-saveable Power Management/APST follows Figure466 defaults; non-saveable HCTM is persistent. Saveable configurations use Saved rules, with coordination among controllers sharing a domain.',14:'不能假設這三個 FID 都會在斷電後清除。在不可保存的情況下，HCTM 具有持續性，Power Management 與 APST 則不持續；若 Feature 可保存，就依 Saved 恢復規則處理。 || Do not classify all three as volatile: non-saveable HCTM persists, whereas Power Management/APST do not; saveable features restore Saved.'})

add(63,'Timestamp、Keep Alive Timer 及 Host Memory Buffer 如何設定與驗證？ || How are Timestamp, Keep Alive Timer and Host Memory Buffer configured and verified?','feature',['timestamp','keepalive','hmb','idctrl'],'''
Timestamp 提供事件的時間基準，Keep Alive Timer 監測通訊是否持續，HMB 則提供 controller 可專用的 Host 記憶體。三者解決的問題不同，需要各自的驗證方法。 || These provide event time, communication-liveness monitoring and dedicated host memory, requiring different validation methods.
Timestamp 與 Keep Alive 管理 controller 的時間相關狀態；HMB 還涉及 Host 記憶體的使用權，以及何時能安全回收記憶體。 || Timestamp/Keep Alive are controller time state; HMB also controls ownership/lifetime of host memory.
Timestamp 看 ONCS；Keep Alive 看 KAS 與 CTRATT.TBKAS；HMB 看 HMPRE、HMMIN、HMMINDS、HMMAXD。 || Check ONCS for Timestamp, KAS/CTRATT.TBKAS for Keep Alive, and HMPRE/HMMIN/HMMINDS/HMMAXD for HMB.
FID0Eh 使用 8-byte buffer 設定 48-bit Timestamp，單位為 ms。FID0Fh 的 KATO 也以 ms 表示，並依 KAS×100 ms 的單位向上取整。FID0Dh 則設定 EHM、MR、HSIZE，以及 descriptor 的位址與數量。 || FID0Eh sets a48-bit millisecond Timestamp in an8-byte buffer. FID0Fh sets KATO milliseconds rounded up to KAS×100 ms. FID0Dh configures EHM/MR, HSIZE and descriptor address/count.
設定 Timestamp 後再 Get，應將兩次操作間經過的時間納入比較。設定 KATO 後，Get 讀到的是實際取整後的值。HMB 則要先準備合法頁面再啟用，停用成功後才能回收；使用 MR=1 時，記憶體內容及 descriptors 都必須與先前相同。 || Timestamp Get should reflect elapsed time; KATO Get returns the rounded value. Allocate valid HMB pages before enabling and reclaim only after successful disable. MR=1 requires unchanged contents and descriptors as well as layout.
例如 KAS=10，Host 要求 KATO=1500 ms，實際會向上取整為 2000 ms。HMB 的 Get 則同時回傳 CQE 狀態與 attributes buffer，不能只讀一個開關值就認為取得了全部設定。 || KAS=10 rounds requested KATO1500 ms to2000 ms. HMB Get returns CQE state and an attributes buffer, not only an enable bit.
HMB 已啟用卻再次要求 Enable 時，回報 Command Sequence Error（0/0Ch）；HMDLEC=0 時，回報 Invalid Field（0/02h）。PCIe 可以用 KATO=0 停用 Keep Alive，不能套用其他 transport 的強制啟用規則。 || Re-enabling enabled HMB returns0/0Ch; HMDLEC=0 returns0/02h. PCIe allows KATO=0 to disable; do not import another transport's mandatory-enablement rule.
Timestamp 要搭配 Origin 與 Synch 判讀，不能直接當成已同步的絕對時鐘。KATO 要比較取整後的 Current；HMB 則需一起確認能力、配置、EHM 狀態，以及 Host 是否仍保留原記憶體。 || Check Timestamp Origin/Synch rather than assuming a perfect wall clock, rounded KATO Current and HMB support/configuration/EHM/memory retention.
先確認這個 FID 的結果放在 CQE、資料 buffer，還是兩者都有，再核對每個時間與大小欄位的單位。 || First locate the result in CQE versus data buffer and verify time/size units.
''',{11:'若支援 PEL，Timestamp Change 按事件條件記錄；Set Features 的記錄則查該 FID 的要求與 PEL 支援。不能把時間每增加 1 ms 都當一筆 Timestamp Change。 || With PEL support, Timestamp Change follows its event conditions; feature logging follows per-FID requirements. Ordinary one-millisecond advancement is not a Timestamp Change event.',12:'HMB 不保留啟用設定，重設後必須重新配置；只有原記憶體及內容完整保留時，才能使用 MR=1。Timestamp 若在該種 Controller Level Reset 中繼續更新，必須保留 Origin；若不繼續更新，則會清為 0。如果還有 Saved 值需要恢復，須依保存規則判斷，並讀回 Origin 確認。Keep Alive 則依其保存能力及預設規則重新確認。 || HMB enable configuration is not retained and must be restored; MR=1 requires fully retained memory/content. A Timestamp maintained across that CLR must retain Origin; otherwise CLR clears the timestamp to zero; also account for a restored Saved value and read back Origin. Recheck Keep Alive under its save/default rules.',13:'受影響 controller 的 HMB 需要重新配置。Timestamp 是否繼續更新，要看實際的 Controller Level Reset 類型，不能假設全部相同。Keep Alive 則要依恢復後的 Current 值，重新安排 Host 維持通訊的計時。 || Reconfigure HMB on affected controllers, do not assume identical Timestamp continuity for all CLR methods, and rebuild host Keep Alive timing from restored Current.',14:'HMB 不是非揮發儲存；記憶體位址相同，不足以證明內容仍完整，也不足以使用 MR=1。Timestamp 若恢復 Saved，可能回到較早的保存時間。PCIe Keep Alive 若沒有另外保存設定，預設 KATO=0。 || HMB is not nonvolatile storage; equal addresses do not justify MR=1. Restoring Saved Timestamp may move time backward. PCIe Keep Alive defaults to KATO=0 unless restoration rules provide otherwise.'})

add(64,'Host Behavior Support、Error Recovery 及 Read Recovery Level 有什麼用途？ || What do Host Behavior Support, Error Recovery and Read Recovery Level do?','feature',['behavior','nvmfeat','rrl','status'],'''
Host Behavior Support 告訴 controller，Host 能處理哪些擴充行為；Error Recovery 設定指定 namespace 的錯誤恢復屬性；Read Recovery Level 則選擇讀取錯誤的恢復策略。 || Advertise host understanding of extensions, configure namespace error recovery and choose a read-recovery strategy.
FID16h 以 controller 為範圍，FID05h 以 namespace 為範圍。FID12h 則依支援的 NVM Set 模型，以 NVM Set 或 NVM subsystem 為範圍。 || FID16h is controller-scoped, FID05h namespace-scoped, and FID12h set/subsystem-scoped according to NVM Set support.
ACRE 必須搭配相關能力使用。設定 DULBE 前，先查 namespace 的 NSFEAT.DAE；設定 Read Recovery Level 前，則先查 RRLS bitmap，確認要選的等級受支援。 || Pair ACRE with relevant capabilities, check NSFEAT.DAE before DULBE and RRLS before selecting a recovery level.
FID16h 的 data buffer 含 ACRE、LBAFEE 等；FID05h.TLER 單位100 ms、DULBE 在 bit16；FID12h 的 RRL 是等級碼，不是 RRLS bitmap。 || FID16h payload includes ACRE/LBAFEE. FID05h TLER uses100 ms and DULBE bit16. FID12h RRL is a level code, not the RRLS bitmap.
先確認能力，再設定對應欄位。TLER 從錯誤恢復開始時才計時，不能把它當成所有命令從提交起算的 timeout。設定 RRL 時，也要選擇受支援的目標與等級，再讀回確認。 || Discover support before Set. TLER starts when error recovery begins, not at command submission as a universal timeout. Set/read an advertised RRL for the correct target.
ACRE 允許使用適用的進階重試行為；DULBE 改變讀取未寫入或已 deallocate 區塊時的回應。選用 Fast Fail 則不表示每次都保證固定延遲，也不表示 controller 完全不能嘗試內部恢復。 || ACRE enables applicable advanced retry behavior; DULBE changes unwritten/deallocated-block responses. Fast Fail does not promise fixed latency or zero internal attempts.
不支援的等級或非法設定，依對應規則回報 Invalid Field（0/02h）等 Status。Command Interrupted（0/21h）只有在 ACRE=1 時才能回報，而且 DNR 必須為 0。 || Unsupported levels/invalid settings follow0/02h and applicable rules. Command Interrupted0/21h requires ACRE=1 and DNR=0.
LBAFEE 會影響擴充 LBA 格式如何呈現及使用。因此，controller 能力、Host 宣告支援的行為，以及 namespace 的實際格式，必須放在一起判讀。 || LBAFEE affects exposure/use of extended formats; interpret capability, host declaration and namespace format together.
先檢查是否誤把 TLER 當成整筆命令的期限，或把 RRLS 支援 bitmap 直接當成要設定的 RRL 值。 || First check whether TLER was treated as whole-command timeout or RRLS was confused with an RRL code.
''',{12:'在不可保存的情況下，Host Behavior Support 與 Error Recovery 不具持續性，Read Recovery Level 則持續保留。若 Feature 可保存，就改依 Saved 及作用範圍對應的重設規則處理。 || Non-saveable Host Behavior Support and Error Recovery are nonpersistent, while Read Recovery Level persists. Saveable cases follow Saved and scope-dependent reset rules.',14:'Power Cycle 後，重新讀取各 FID 的 Current。Read Recovery Level 即使不可保存，仍具有持續性，不能因為沒有 Saved 就要求它回到 0。Host Behavior Support 與 Error Recovery 則各依自己的恢復規則處理。 || Re-read Current after a power cycle. Non-saveable RRL still persists; absence of Saved does not mean it must return zero. Host Behavior Support/Error Recovery use their separate restoration rules.'})

add(65,'Namespace Write Protection 如何設定？不同保護模式在 Reset 與 Power Cycle 後是否保留？ || How is namespace write protection configured, and which modes survive reset or power cycling?','feature',['nwp','idctrl'],'''
Namespace Write Protection 用來防止 namespace 被修改。不同模式分別提供可解除、直到 Power Cycle 才解除，以及永久的保護，必須分清楚它們的有效期間。 || Prevent namespace modification with reversible, until-power-cycle and permanent protection lifetimes.
保護狀態屬於 namespace；其他可存取同一 namespace 的 controller 也必須遵守。它不是只影響某條 queue 的 Host 軟體旗標。 || Protection belongs to the namespace and applies through other controllers accessing it, not just one queue's software flag.
Identify.NWPC 宣告支援哪些保護能力；WPC 中的 WPUPCC 與 PWPC 控制是否允許進入特定模式；Get FID84h 回傳的 WPS 才是目前保護狀態。能力、進入許可與實際狀態是三種不同資訊。 || NWPC advertises capability, WPC.WPUPCC/PWPC permits entering specific modes and Get FID84h.WPS reports current state.
WPS=0 表示無保護，1 表示基本保護，2 表示保護持續到 Power Cycle，3 表示永久保護。這項 Feature 不可保存，也沒有 Default；其持續性由模式本身定義，不能靠 SV=1 改變。 || WPS0/1/2/3 means none/basic/until-power-cycle/permanent. This feature is unsaveable and has no Default; SV=1 does not create persistence.
先確認能力及進入該模式的許可，再針對 NSID 設定 WPS，並讀取 Current 確認。進入保護時，controller 必須將該 namespace 仍在揮發性儲存中的資料與 metadata 寫入非揮發媒體。 || Check support/entry permission, Set WPS for NSID and read Current. Entering protection commits that namespace's volatile data/metadata to nonvolatile media.
設定成功後，受保護模式禁止的操作必須被拒絕；一般 Read 仍依可讀狀態處理。除了確認 Set 成功，也要核對實際命令行為是否符合該模式。 || After success, prohibited operations must obey protection rules while ordinary reads remain governed by readable state. Verify behavior in addition to Set success.
若嘗試改變 WPS=2 或 3 的狀態、缺少進入模式的許可位，或在 multi-domain 配置中要求被禁止的 WPS=2 轉換，回報 Feature Not Changeable（1/0Eh）。Get Default 回報 0/02h；執行受寫保護禁止的命令，則可回報 Namespace is Write Protected（0/20h）。 || Changing WPS2/3, missing entry permission or prohibited multi-domain WPS2 transition uses1/0Eh; Get Default uses0/02h; prohibited commands may return Namespace is Write Protected0/20h.
CHANG=1 不表示 namespace 進入永久保護後仍可解除。另外，WPC 控制位在重設後的變化，與 namespace 已經具有的 WPS 狀態，是不同規則，不能互相推論。 || CHANG=1 does not promise reversal of permanent protection. Reset of WPC permission bits differs from the namespace's existing WPS state.
先讀 Current.WPS 與 WPC，分辨失敗原因是能力不支援、目前不允許進入該模式，還是 namespace 已處於不可再變更的保護狀態。 || First read Current.WPS and WPC to separate missing support, denied entry and an already unchangeable state.
''',{12:'Controller Reset 會保留既有 WPS，包括 Until Power Cycle 模式。FID84h 不可使用 Save 保存，不表示 Controller Reset 會解除它的保護。 || Controller Reset preserves existing WPS, including Until Power Cycle; unsaveability does not remove protection.',13:'NVM Subsystem Reset 與 Power Cycle 是不同事件。WPS 依狀態機規則保留，不能用 NVM Subsystem Reset 來解除 Until Power Cycle 保護。 || NVM Subsystem Reset is not a power cycle; WPS follows its state machine. NSSR is not a method to remove Until Power Cycle protection.',14:'實際發生 Power Cycle 後，WPS=2 會回到 No Write Protect；基本保護 WPS=1 與永久保護 WPS=3 則繼續保留。永久保護不能透過一般 Set 或 Reset 解除。 || An actual power cycle returns WPS2 to No Write Protect; basic WPS1 and permanent WPS3 persist. Ordinary Set/reset cannot remove permanent protection.'})

add(66,'Set Features 成功後，為什麼還應使用 Get Features 確認？ || Why read Get Features after a successful Set Features?','feature',['getfeat','setfeat','setcomplete','keepalive','number'],'''
Set 成功後再 Get，可以確認 controller 實際使用的值，以及它與 Host 要求值之間是否存在規範允許的換算。只看成功 Status，無法取得這些資訊。 || Verify transformations between the requested and effective value rather than relying only on success status.
Set 與 Get 必須針對相同 FID、相同作用範圍及對應的選擇欄位，而且中間沒有其他配置變更，才適合直接比較。Get Supported Capabilities 也不能拿來代替 Get Current。 || Compare identical FID/scope/selectors and time; Supported Capabilities is not Current.
先確認這項 Feature 的支援能力及回覆格式。有些結果位於 CQE，有些位於資料 buffer，也有些需要同時讀取兩者。 || Know the response format and support; values may be in CQE, a payload or both.
保留原 Set 命令的 SV、設定參數及 CQE 結果。接著以 Get Features.SEL=0 讀取 Current；若還要確認保存結果，再以 SEL=2 讀取 Saved。 || Preserve original SV/parameters and Set results, read Current with SEL0 and Saved with SEL2 when needed.
等待 Set 成功完成後再 Get，並排除其他 Host 同時修改共用設定的情況。Timestamp 等動態值會隨時間增加，應將經過時間納入比較，而不是要求逐 bit 相同。 || Await successful Set before Get and coordinate concurrent shared-scope writers. Compare dynamic values such as Timestamp with elapsed time rather than byte equality.
controller 不得在屬性尚未設定完成前，就回報 Set 成功。但成功後的實際值仍可能經過規範允許的處理，例如 KATO 向上取整，或 Number of Queues 回傳實際配置。因此，與原請求數字不同，不一定代表錯誤。 || Successful Set completion cannot precede completion of attribute setting. Rounded KATO and allocated queue counts may validly differ from requests.
如果後續 Get 失敗，應保留它自己的 Status，不能用它取代原 Set 的成功結果。先檢查 Get 的選擇欄位、作用範圍，以及兩次命令之間是否發生 Reset。 || A later Get failure has its own status and does not replace the Set result. Check selectors, scope and intervening reset.
Get 能確認 Host 讀到的設定值；實際行為驗證則確認 controller 是否採用該設定。兩者提供不同證據，應互相配合，而不是反覆讀同一數值就當成已驗證全部功能。 || Readback establishes reported configuration; behavioral checks establish its use. Both are needed, without duplicating the same comparison as separate tests.
先確認 SEL 是否選了 Current，再檢查 Set 與 Get 之間是否發生 Reset，或另有一筆 Set 改變了設定。 || First confirm SEL=Current and no intervening reset or other Set.
''')

add(67,'Firmware Activation、Namespace 刪除、Controller Reset 及 Power Cycle 後，Feature 應如何變化？ || How should features change after activation, namespace deletion, reset and power cycling?','feature',['feature','setfeat','timestamp','hmb','nwp','nsmanage'],'''
Feature 在事件之後應保留或恢復成什麼值，要依事件種類與個別 Feature 規則判斷。不能一律假設全部清除，也不能一律假設全部保留。 || Establish persistence expectations per event and feature instead of assuming universal clearing or retention.
先確認設定屬於 controller、namespace，還是其他共用管理物件，再分別追蹤 Current、Saved 與 Default。作用範圍不同，事件造成的影響也可能不同。 || Separate controller, namespace and shared-object scope, then Current/Saved/Default.
查詢 SEL=3 的 SVBL，並參考 Base Figure 466 或 NVM Figure 92，再核對個別 FID 的特殊規定。Feature 不可用 Save 保存，不等於它的狀態一定無法跨越重設或斷電。 || Check SVBL, Figure466/NVM Figure92 and feature-specific exceptions. Unsaveable and nonpersistent are not synonyms.
記錄事件是否真的觸發 Controller Level Reset，以及是否影響整個 NVM subsystem。Namespace Delete 則是移除原物件；即使之後建立了相同 NSID，也不能視為舊 namespace 的設定自然延續。 || Record actual CLR occurrence and coverage. Namespace deletion removes an object; a new namespace reusing its number is not automatically the same configured object.
先保存操作前的設定，執行指定事件，等管理通道恢復後，再讀取 Current、Saved 及能力，最後驗證行為。若事件是 Firmware Activation，還要先確認使用哪種啟用方式，以及過程中是否伴隨 Reset。 || Snapshot, perform the defined event, restore management access, reread values/capabilities and verify behavior. For activation, identify its actual activation/reset path.
例如，可保存的 Feature 若只用 SV=0 修改 Current，重設後可能恢復成較舊的 Saved 值。HMB 需要重新配置；WPS=2 則在 Controller Reset 後保留，但會在 Power Cycle 後解除。這些差異都來自各自的規則。 || An SV=0 change to a saveable feature can revert to older Saved after reset; HMB needs reconfiguration; WPS2 survives Controller Reset but ends at a power cycle.
namespace 已刪除後，再 Get 或 Set 它的 Feature，依該 FID 與 NSID 的規則回應。不能只因無法讀取已刪除 NSID 的設定，就判定 controller 保存失敗。 || Access after object deletion follows that FID's NSID rules; failure to read a deleted namespace is not evidence of failed saving.
比較前後結果時，一起保留 namespace 身分、SV、作用範圍、重設原因及時間。只記錄「Feature 值不同」，不足以判斷這項變化是否合法。 || Preserve object identity, SV, scope, reset cause and timing, not merely a changed-value flag.
先確認前後查詢的是同一物件，再確認事件實際造成的重設範圍，是否就是測試預期的範圍。 || First confirm the same object and the actual reset coverage.
''')

add(68,'Feature 宣告支援但 Get、Set 或實際功能行為不一致時，應如何驗證？ || How should supported-feature claims be checked when Get, Set and behavior appear inconsistent?','feature',['feature','getfeat','setfeat','setcomplete','irqfeat','effects'],'''
用可重現且條件明確的情境，分辨矛盾來自能力宣告、設定方式、觀察方法，還是 controller 的實際行為。 || Isolate whether the contradiction lies in capability, configuration, observation or firmware behavior under reproducible conditions.
固定 controller、FID、NSID 或其他選擇欄位，並確認配置在比較期間沒有改變，避免把不同作用範圍的值混在一起。 || Fix controller, FID, NSID/other selectors and configuration interval to avoid mixing scopes.
交叉比對 Identify、Feature Identifiers Supported and Effects，以及 SEL=3 的能力資訊。NSSPEC=0 不一定表示 controller scope；CHANG=1 也不表示任何狀態下都可以變更。 || Compare Identify, feature-effects information and SEL3. NSSPEC=0 is not necessarily controller scope; CHANG=1 is not unconditional changeability.
保留原 Set 與 Get 的 FID、SEL、SV、CDW11、資料 buffer 及 CQE。另外記錄開始驗證前，哪些命令已經提交但尚未完成，避免混用新舊設定下的行為。 || Preserve FID/SEL/SV/CDW11/payloads and CQEs, and identify commands already outstanding before behavioral checks.
先查能力，再送出合法 Set，等待成功後讀取 Current，最後提交新命令驗證效果。Saved 及重設後的行為則另外驗證，每次只改一項條件，讓差異有明確原因。 || Discover, legally Set, await completion, Get Current and submit new affected work; test saving/reset separately, changing one factor at a time.
判斷一致性時，應接受規範允許的結果範圍。例如 KATO 可以取整、Timestamp 會隨時間改變，中斷聚合也允許實作差異；不能只因結果不等於原請求，就直接判錯。 || Consistency means conformance to allowed outcomes. Rounded KATO, dynamic Timestamp and implementation-specific coalescing cannot be rejected simply for differing from a request.
先分別排除不支援 FID（0/02h）、非法保存要求（1/0Dh）、不可變更（1/0Eh）及作用範圍錯誤（1/0Fh）。若同時存在多項錯誤，也要保留規範允許 controller 選擇其中一項回報的空間。 || First distinguish unsupported FID0/02h, unsaveable1/0Dh, unchangeable1/0Eh and wrong-scope1/0Fh; retain allowed status choices for multiple faults.
提出不符合規範的結論時，應附上明確要求、已成立的前提、原始命令與回覆，以及能排除選擇欄位或先後順序誤用的證據。 || A noncompliance finding should include the explicit requirement, established prerequisites, raw request/response and evidence excluding selector/timing misuse.
先確認 Get 沒有使用錯誤的 SEL 或 NSID，再確認拿來驗證行為的命令，確實是在 Set 成功後才提交。 || First check wrong SEL/NSID or behavioral test commands submitted before Set completed.
''')
