"""Source-specific explanations for the older reports' specification figures.

Related figures share one explanation and are presented together by the reader.
This replaces the old title-only 'defines this format' placeholder paragraphs.
"""
NOTES = {}


def add(source, numbers, zh, en):
    for number in numbers.split(','):
        NOTES[(source, int(number))] = {'zh':zh, 'en':en}


def base(numbers, zh, en):
    add('NVME-BASE-2.4', numbers, zh, en)


def pcie(numbers, zh, en):
    add('NVME-PCIE-TRANSPORT-1.4', numbers, zh, en)


base('1,5', 'Base 定義共同命令及資料結構，Transport 說明交換方式，I/O Command Set 定義特定儲存資料的操作。讀圖時先把正在研究的問題放到對應層次，再沿引用取得其他層的必要資訊。', 'Base defines common commands and structures, Transport defines exchange mechanisms, and an I/O Command Set defines operations on its storage data. Place the question at the appropriate layer before following references to supporting layers.')
base('2,3', '十進位與二進位容量單位先分開：1 kB=1000 bytes，1 KiB=1024 bytes。Word 為 2 bytes，Dword 為 4 bytes；它們描述資料寬度，不會替某個數量欄位決定是否需要加 1。', 'Distinguish decimal and binary units: 1 kB is 1000 bytes and 1 KiB is 1024 bytes. A word is two bytes and a Dword four bytes. These widths do not determine whether a particular count field requires adding one.')
base('6,7', '1:1 圖中每個 SQ 對應自己的 CQ；n:1 圖中多個 SQ 共用一個 CQ。沿完成項目的 SQID、CID 回到原 SQ，才能在共用 CQ 中辨認是哪一筆命令完成。', 'A 1:1 arrangement associates each SQ with its own CQ; n:1 lets multiple SQs share a CQ. Use the completion’s SQID and CID to identify the originating command in a shared CQ.')
base('11,14,67,68,69', 'NVM Set 把相關儲存資源與 namespace 的關係分組。先找 namespace 隸屬哪個 Set，再看命令是否需要選擇 Set；多個 namespace 的數量不等於有同樣多個獨立儲存裝置。', 'NVM Sets group relationships between storage resources and namespaces. Establish namespace membership before interpreting Set-aware commands. Multiple namespaces do not imply the same number of independent storage devices.')
base('12,13,15,70', 'Reclaim Group 與資料放置的關係圖，說明儲存資源如何分組及共享。比較單一和多個群組時，追蹤同一 namespace 能使用哪些資源，不要將圖中的每個方框當成額外增加的一份總容量。', 'Reclaim Group and placement diagrams show how storage resources are grouped and shared. When comparing single and multiple groups, follow the resources available to a namespace rather than counting every box as additional total capacity.')
base('16,17,18,19', '先固定 NVM subsystem，再數其中的 controllers 和 namespaces。Namespace 是可定址的儲存物件，controller 是處理命令的對象；新增一個 namespace 並不必然新增一個 controller。', 'Hold the NVM subsystem fixed and identify its controllers and namespaces. A namespace is an addressable storage object and a controller processes commands; adding a namespace does not necessarily add a controller.')
base('20,21,24,25,26', '將 controller、port 與 namespace 分別標示，再沿連線看存取關係。多個控制器可以處在同一 subsystem；Administrative controller 的管理角色不能用來推論它也處理 namespace 資料 I/O。', 'Label controllers, ports, and namespaces separately and follow their access relationships. Multiple controllers can belong to one subsystem. An Administrative controller’s management role does not imply that it handles namespace data I/O.')
base('22', 'SR-IOV 圖把 PCIe 裝置呈現的 Physical Function 與 Virtual Functions 分開。Function 是介面呈現的層次；要知道它通往哪份儲存資源，仍須沿控制器與 namespace 的關係閱讀。', 'The SR-IOV diagram separates a Physical Function from Virtual Functions exposed by a PCIe device. Function identity is an interface-level distinction; follow controller and namespace relationships to identify the storage resource behind it.')
base('23,27', 'Controller type 決定控制器角色，Controller ID 辨認具體對象。高值識別碼另有保留或特殊用途，應依清單解讀，不能把 FFF0h–FFFFh 全部當成一般可指派的控制器編號。', 'Controller type determines role while Controller ID identifies an instance. High-valued identifiers have reserved or special meanings; interpret the list rather than treating FFF0h–FFFFh as ordinary assignable controller IDs.')
base('28,30,31,32', '先選控制器類型，再讀命令、log 或 Feature 所在列的支援標示。帶有數字註腳的標示必須連同條件閱讀；同一功能在另一種控制器類型下可能有不同要求。', 'Choose the controller-type column before reading support markers for commands, logs, or Features. Numbered footnotes are part of the condition; requirements can differ for another controller type.')
base('33,34', 'Property 索引先列出位址與名稱，個別欄位表再定義讀寫方式和內容。Memory-based 的 Doorbell 間距由 CAP.DSTRD 決定，不能把索引表中的第一組位置直接複製到所有佇列。', 'The property index gives locations and names; individual tables define access and contents. CAP.DSTRD determines memory-based doorbell spacing, so the first pair’s locations cannot simply be reused for every queue.')
base('36', 'CAP 回報支援能力、大小與時間限制，主機以這些資訊選擇可用設定。讀到支援位並不表示對應功能已啟用或控制器已就緒；設定與目前狀態要再讀各自的欄位。', 'CAP reports capabilities, size limits, and timing limits used to choose valid settings. A support bit does not establish enablement or readiness; read configuration and current-status fields separately.')
base('37,38', '版本描述子把 major、minor、tertiary 分開編碼。先分解欄位再比較版本；Version property 的重設值描述回報的版本，不是命令執行次數，也不代表所有選用功能都支援。', 'The version descriptor encodes major, minor, and tertiary components separately. Split the fields before comparing versions. The Version property’s reset value identifies the reported revision, not operation counts or support for every optional feature.')
base('39,40', 'INTMS 和 INTMC 分別用來設定與清除中斷遮罩。相同 bit 位置對應相同遮罩對象，但寫入語意相反；清除遮罩不代表已移除 CQ 中尚未處理的完成項目。', 'INTMS sets interrupt mask bits and INTMC clears them. Matching positions refer to the same mask target but use opposite write semantics. Clearing a mask does not remove unconsumed completions from a CQ.')
base('41,42', 'CC 記錄主機的設定與要求，CSTS 回報控制器當前狀態。例如 EN 與 RDY 分別是啟用要求和就緒結果；SHN 與 SHST 則對應關機要求及處理階段。不要只看要求位就判斷動作已完成。', 'CC carries host settings and requests; CSTS reports controller state. EN/RDY distinguish enablement request from readiness, while SHN/SHST distinguish shutdown request from progress. A request bit alone does not establish completion.')
base('43,56', 'NSSR 與 NSSD 分別關係到 subsystem 重設及關機，作用範圍比單一控制器的設定更大。先確認能力及合法寫入值，再依對應操作流程解釋結果，不能把兩者都視為一般 controller disable。', 'NSSR and NSSD concern subsystem reset and shutdown, with broader scope than a single controller setting. Establish support and permitted writes, then interpret the relevant operation flow rather than treating either as ordinary controller disablement.')
base('44,45,46', 'AQA 描述 Admin SQ／CQ 的大小，ASQ 與 ACQ 提供兩個佇列的基底位址。大小欄位採其數量編碼解讀，位址則依所選 page size 對齊；大小正確不能取代位址對齊檢查。', 'AQA describes Admin SQ/CQ sizes; ASQ and ACQ provide their base addresses. Decode queue counts under their field rules and align addresses to the selected page size. Correct size does not establish correct alignment.')
base('47,48,52,53', 'CMBLOC 與 CMBSZ 一起決定 CMB 的位置、大小及允許用途，CMBMSC 控制其位址空間，CMBSTS 回報相關狀態。先確認用途支援，再計算位置和大小；有足夠空間不表示允許放入任意資料結構。', 'CMBLOC/CMBSZ establish CMB location, size, and supported uses; CMBMSC controls its address space and CMBSTS reports status. Establish supported use before calculating location and size; sufficient space does not permit arbitrary structures.')
base('49,50,51', 'BPINFO 提供 active partition、大小與讀取狀態；BPRSEL 選擇要讀取的 partition、範圍；BPMBL 指向主機接收資料的記憶體。要求讀哪個 partition 與目前 active partition 是兩個不同資訊。', 'BPINFO reports the active partition, size, and read status; BPRSEL selects the partition and range; BPMBL points to host memory receiving the data. The requested partition need not be the active partition.')
base('54,55', 'CMB 的彈性緩衝大小與持續寫入吞吐量是兩種資源資訊。大小欄位先配對其尺度換成 bytes，吞吐量則配對其速率尺度；不能把容量數值直接當成每秒可寫入量。', 'CMB elasticity-buffer size and sustained write throughput are different quantities. Pair sizes with their scales to obtain bytes and throughput values with their rate scales; capacity is not a per-second transfer rate.')
base('57,84', 'Ready timeout 與選擇的就緒模式有關。先核對 CAP.CRMS 的支援及 CC.CRIME 的設定，再選 CRTO 中適用時間；某些 Admin 命令的媒體尚未就緒狀態另依命令清單判斷。', 'Ready timeouts depend on the selected readiness mode. Match CAP.CRMS support and CC.CRIME configuration to the relevant CRTO timeout. Media-not-ready status for Admin commands additionally depends on the applicable command list.')
base('58,59,60,63,64', 'PMRCAP 描述 PMR 支援、位置與等待條件，PMRCTL 提出啟用要求，PMRSTS 回報就緒或錯誤。PMRMSCL／PMRMSCU 組成位址控制；位址、啟用與就緒必須分開讀取。', 'PMRCAP describes PMR support, location, and timing; PMRCTL requests enablement and PMRSTS reports readiness/errors. PMRMSCL/PMRMSCU form address control. Address selection, enablement, and readiness are separate facts.')
base('61,62', 'PMR 的彈性緩衝量與持續寫入速率使用各自的數值和尺度。先將 size 與 throughput 分成不同單位，再與相應操作需求比較；兩者不是可以直接相加的容量。', 'PMR elasticity-buffer size and sustained write throughput have separate values and scales. Convert them into their respective units before comparison with operation needs; they are not capacities that can be added together.')
base('65,66', 'NSID 的狀態要放在 namespace 與控制器的關係中理解。Namespace 可以已配置但尚未對指定控制器啟用；特殊 NSID 值還可能選擇整個集合，不能把所有非零值都當成單一有效 namespace。', 'Interpret NSID state in the namespace/controller relationship. A namespace can be allocated without being active on a controller. Special NSID values may select a set rather than one object, so nonzero alone does not establish a valid individual namespace.')
base('71,86,87,88,89', '容量關係圖先按 subsystem、domain、group、set 與 namespace 分層。容量欄位描述的是特定層級的總量、可用量或群組量；在比較或相減前，先確認兩個值的對象與單位相同。', 'Read capacity relationships by subsystem, domain, group, set, and namespace. Fields describe totals, availability, or group quantities at particular levels. Establish matching objects and units before comparing or subtracting values.')
base('73,74', '環狀佇列用 head／tail 及各自的使用規則區分空與滿。索引回到開頭不代表所有舊資料都可覆寫；必須看對方是否已消費或釋放相應位置。', 'Ring queues distinguish empty and full using head/tail and their ownership rules. An index wrapping to the beginning does not make every old slot reusable; consumption or release determines reuse.')
base('80,81', 'Round Robin 輪流選取候選佇列，Weighted Round Robin 再考慮優先級及權重。圖中選取先後不是完成順序，因為不同命令的執行時間及相依條件可能不同。', 'Round Robin rotates selection among candidate queues; Weighted Round Robin additionally considers priority and weights. Selection order is not completion order because execution times and dependencies can differ.')
base('85', 'Shutdown processing 的互動圖把主機要求與控制器處理階段分開。沿每個條件判斷可執行的動作，並以 SHST 等狀態確認進度；不能只因已寫 SHN 就判斷關機完成。', 'Shutdown interactions separate host requests from controller-processing stages. Follow the conditions for permitted actions and use status such as SHST to establish progress; writing SHN alone does not establish shutdown completion.')
base('90', 'Keep Alive 的圖以 KATT 時間間隔說明逾時判斷。不同檢查時點可使偵測延後，因此圖中的最長偵測時間不是單次命令允許的執行時間，也不表示媒體發生錯誤。', 'The Keep Alive diagram relates timeout detection to KATT intervals. Sampling times can delay detection; the illustrated maximum detection time is neither an individual command deadline nor evidence of media failure.')
base('91', 'Privileged Action 的例子描述需要特定授權條件的管理操作。先辨認操作對象與權限要求，再看命令格式；僅有 Admin Queue 並不會自動消除這些操作要求。', 'Privileged Action examples describe management operations with specific authorization conditions. Identify the target and privilege requirement before the command layout; the existence of an Admin Queue does not remove those requirements.')
base('92,93', '共同 SQE 先以 CDW0 描述 opcode、命令識別與資料指標選擇，再以 NSID 選對象、MPTR／DPTR 指向資料。CDW10–15 的意義由個別命令決定，不能跨 opcode 沿用。', 'The common SQE uses CDW0 for opcode, command identity, and data-pointer selection, then NSID for the target and MPTR/DPTR for buffers. CDW10–15 meanings come from the specific command and cannot be borrowed across opcodes.')
base('94', '廠商自訂命令的標準格式以 NDT 和 NDM 分別描述 data 與 metadata 的 Dword 數量，兩者是直接計數。先確認 VSCF／SNVSCF 對應的格式支援，再解讀指標和長度；格式本身不定義廠商 payload。', 'The standard vendor-command format uses NDT and NDM as direct Dword counts for data and metadata. Check the relevant VSCF/SNVSCF support before interpreting pointers and lengths; the format does not define vendor payload semantics.')
base('97,98,99', 'CQE 用 SQID／CID 找回原命令，SQHD 回報提交佇列的消費位置，Status 則描述完成結果。這些欄位不能互代：SQHD 前進不表示所有較早提交命令都已完成。', 'SQID/CID associate the CQE with a command, SQHD reports SQ consumption, and Status describes the result. SQHD advancing does not mean every earlier submitted command has completed.')
base('101,102,103,104,105,107,108', '先讀 SCT 選擇狀態類別，再用 SC 查該類別中的結果。Generic、command-specific、media/data integrity 和 path-related 分別解釋不同原因；DNR 與 CRD 補充重試資訊，不能由單一 SC 數字推論全部處理方式。', 'Read SCT to select the status class before using SC within that class. Generic, command-specific, media/data-integrity, and path-related results explain different causes. DNR/CRD add retry information; SC alone does not determine all handling.')
base('109', 'Phase Tag 讓主機區分 CQ slot 中的新完成項目與上一次繞行留下的內容。讀圖時沿同一個 slot 追蹤每次繞回後的 phase，而不是把 P=1 永遠當成新項目的通用條件。', 'Phase Tag distinguishes a new CQ entry from contents left by an earlier traversal. Follow one slot across wraps; P=1 is not a universal condition for a new entry.')
base('110,111,112,113', 'PRP1 可同時帶頁基底與頁內位移，後續資料頁依相應對齊規則描述。PRP2 的解讀取決於剩餘資料跨幾頁；PRP List 可以指向不連續的資料頁，所以清單順序與實體位址是否連續是不同問題。', 'PRP1 may contain a page base and in-page offset; later data pages follow their alignment rules. PRP2 interpretation depends on the remaining page span. PRP Lists can reference noncontiguous data pages, separating transfer order from physical contiguity.')
base('114,115,116,117,118', 'SGL 先用 descriptor type 和 subtype 決定後續位址、長度如何解讀，再檢查該類型允許的組合。描述子清單中的長度與資料傳輸量不同，不能先把所有 LEN 相加再判斷類型。', 'SGL type and subtype select the meanings of addresses and lengths and their permitted combinations. Descriptor-list length differs from data-transfer length; do not total all LEN fields before interpreting types.')
base('119,120,121,122,125', 'Data Block 指向資料，Segment／Last Segment 指向描述子清單，Bit Bucket 則有自己的傳輸量語意。沿 Read 例子的箭頭先辨認目的物件，再加總資料量；存放描述子的記憶體不是使用者資料。', 'Data Block points to data, Segment/Last Segment to descriptor lists, and Bit Bucket has its own transfer-length semantics. Follow the Read example by identifying each destination object before totaling data; descriptor storage is not user data.')
base('126,127', 'Feature current value 在重設後如何改變，需要同時看 Feature 的作用範圍與重設影響的範圍。整個 subsystem 與其子集合的重設可能影響不同對象，不能把一張保留表套到所有重設事件。', 'A Feature’s current value after reset depends on both Feature scope and reset scope. Resetting a whole subsystem versus a subset can affect different objects; one retention table cannot govern every reset event.')
base('128,129', 'VID／SSVID 辨認廠商，SN／MN 描述序號與型號。固定字串欄位要依寬度及填補規則閱讀；不能把字串直接當成以零結尾的任意長度資料。', 'VID/SSVID identify vendors, while SN/MN describe serial number and model. Read fixed string fields using their widths and padding rules rather than assuming arbitrary null-terminated strings.')
base('130,131,132,133,134,135,136,137,138', 'OUI、EUI64、NGUID 與 WWN 對照圖用來辨認識別值的組成及配置關係。外觀相似不代表格式可互換；先確認欄位寬度及定義，再辨認廠商部分與其他識別部分。', 'OUI, EUI64, NGUID, and WWN comparison diagrams describe identifier composition and allocation relationships. Similar appearance does not make formats interchangeable; establish width and definition before identifying vendor and other components.')
base('139,140', 'Controller List 以 NUMCIDS 開頭，後接 16-bit controller IDs；Namespace List 直接列出 32-bit NSIDs。兩者都依各自排序及未使用項目規則讀取，但不能共用同一種 header。', 'A Controller List begins with NUMCIDS and 16-bit controller IDs; a Namespace List directly contains 32-bit NSIDs. Follow each list’s ordering and unused-entry rules without sharing the same header interpretation.')
base('142', 'UTF-8 的一個字元可由多個 bytes 編碼。沿輸入處理圖分辨起始 byte 與後續 bytes，長度限制仍按所定義的 byte 數計算；字元數不是 buffer 長度。', 'A UTF-8 character can occupy multiple bytes. Distinguish initial and continuation bytes in the input-processing flow. Byte-defined limits still apply to bytes, not character counts.')

base('155,474', '事件種類與事件啟用是兩份不同資訊。先以通知種類找到本篇使用的事件，再看相應啟用位；取得通知後仍需讀對應狀態或 log，通知本身不包含完整結果。', 'Event identity and event enablement are separate information. Identify the notice used in this report, then its enable bit. A notice still requires reading the associated status or log; it does not contain the complete result.')
base('176,177,178,179,180', 'Self-test 的 NSID 選擇測試範圍，STC 選動作，DSTP 則依相應測試格式解讀。狀態流程區分啟動、已在執行及中止；啟動命令的完成不表示背景測試通過。', 'Self-test NSID selects scope, STC selects the action, and DSTP follows the applicable test format. The processing flow distinguishes starting, already-running, and abort cases; start-command completion does not establish that the test passed.')
base('187,188,189', 'Firmware Commit 的 CA 選保存或啟用動作，FS 選 slot，完成欄位則回報結果及重疊更新資訊。要求某種啟用方式，仍須與能力和 reset-required 狀態配對閱讀。', 'Firmware Commit CA selects storage/activation behavior, FS selects a slot, and completion fields report results and overlapping-update information. Pair the selected activation method with capabilities and reset-required statuses.')
base('190,191,192,193', 'Download 的 DPTR 指向本段主機資料，NUMD 以從 0 起算的 Dword 數描述長度，OFST 以 Dword 描述映像內位移。先換算 bytes，再檢查 FWUG 及範圍是否重疊；長度與位移不能使用相同加 1 規則。', 'Download DPTR points to the host portion, NUMD is a zero-based Dword length, and OFST is an image-relative Dword offset. Convert to bytes before checking FWUG and overlap; length and offset do not share the same plus-one rule.')
base('197,198,199,200,201,202,463,464,465,466', 'Get／Set Features 共用命令外框，但 Get 的 SEL 選擇要讀哪種值，Set 的 SV 決定是否要求保存。CHANG、NSSPEC、SVBL 描述使用能力，資料指標和 UIDX 則按所選 Feature 的要求使用。', 'Get/Set Features share a command framework, but Get SEL chooses which value to retrieve and Set SV requests saving. CHANG/NSSPEC/SVBL describe supported use; data pointers and UIDX follow the selected Feature’s requirements.')
base('203,204,205,206,207,208,209', 'Get Log Page 先由 LID 選資料，再以 NUMDU／NUMDL 描述傳輸長度、LPOU／LPOL 描述位移，RAE 控制事件保留。LSI、CSI、UIDX 的意義由所選 log 決定，不能直接沿用其他 log 的選擇值。', 'Get Log Page selects data with LID, length with NUMDU/NUMDL, offset with LPOU/LPOL, and event retention with RAE. LSI, CSI, and UIDX meanings depend on the selected log and cannot be borrowed from another log’s selectors.')
base('213', '溫度、熱管理轉換次數與累計時間回答不同問題。感測器溫度是讀取到的量測值，計數與時間是累積結果；先配對名稱與單位，不能把歷史次數當成目前正在執行的熱管理級別。', 'Temperature, thermal-transition counts, and accumulated times answer different questions. Sensor temperature is a measurement, while counts/times are accumulated results. Historical counts do not identify the currently active thermal-management level.')
base('215', 'AFI 內的 CAFS 指目前 slot，NAFS 指下次預定 slot，FRS1–FRS7 是各 slot 的版本字串。先由 slot 編號選 FRSx，再比較目前與預定版本；字串存在不表示已在執行。', 'CAFS in AFI identifies the current slot, NAFS the next scheduled slot, and FRS1–FRS7 each slot’s revision string. Select FRSx by slot number and distinguish current from scheduled firmware; an existing string does not establish execution.')
base('218,219', 'Self-test log 把 current operation 與最多 20 筆歷史結果分開。歷史項目先讀測試種類和結果碼，再按有效位讀 NSID、FLBA 或狀態；有數值不代表欄位有效。', 'The Self-test log separates current operation from up to twenty historical results. Read test type and result code before using validity bits for NSID, FLBA, or status; a nonzero value does not establish validity.')
base('304', 'DNCS 描述是否處於製造商預設 namespace 配置。它是一個狀態判斷，並未列出每個預設 namespace 的容量及格式；這些內容仍需重新 Identify。', 'DNCS indicates whether the manufacturer-default namespace configuration is in use. It does not enumerate the capacity and format of every default namespace; retrieve those through Identify.')
base('337', 'CSI 選擇 I/O Command Set 的識別空間。先確認目前命令及查詢是否使用 CSI，再用該 Command Set 定義解讀延伸結構；CSI 和 FID、LID 不是同一種編號。', 'CSI identifies an I/O Command Set. Establish whether the command/query uses CSI before interpreting extensions under that command set. CSI, FID, and LID are separate identifiers.')
base('338', 'Identify Controller 的欄位分別描述能力、限制、身分與目前資訊。依本篇主題選出需要的欄位後，再連到相應命令；支援位和大小上限必須一起用，不能以單一旗標推論所有參數都有效。', 'Identify Controller fields describe capabilities, limits, identity, and current information. Select the fields relevant to this report and connect them to the command. Support bits and limits work together; one flag does not make every parameter valid.')
base('340,738,739,740', 'Power State Descriptor 把功率、進出延遲和相對效能分開。轉移成本要從目前狀態的離開時間與目標的進入時間計算；Workload Hint 描述負載提示，不是直接指定保證的延遲。', 'Power State Descriptors separate power, entry/exit latency, and relative performance. Calculate transitions from the current state’s exit and target state’s entry. Workload Hints characterize load rather than specifying guaranteed latency.')
base('346', 'Command Set Independent Identify Namespace 提供跨命令集的 namespace 屬性。ANAGRPID、NVMSETID、ENDGID 分別連到不同資源群組，不能因都是 ID 就把它們當成同一層級。', 'Command Set Independent Identify Namespace supplies shared namespace attributes. ANAGRPID, NVMSETID, and ENDGID associate the namespace with different resource groups; they do not identify the same level merely because all are IDs.')
base('347,348', 'UUID List 包含有識別關聯的項目，命令可在適用時用 UIDX 選擇。清單索引是選項位置，UUID 是被選到的識別值；兩者不能互換，也不能把保留或無效項目當作一般 UUID 使用。', 'UUID List entries carry identifier associations and may be selected with UIDX when applicable. The index is an entry position; UUID is the selected identity. Reserved/invalid entries are not ordinary usable UUIDs.')
base('442,443,444', 'Namespace Attachment 的 DPTR 指向 Controller List，SEL 選 Attach 或 Detach。命令改變的是指定控制器與 namespace 的關係；完成狀態如已連接、未連接或清單不合法，要按該關係解讀。', 'Namespace Attachment DPTR points to a Controller List and SEL selects Attach or Detach. The command changes relationships between specified controllers and the namespace. Interpret already/not-attached and invalid-list results in that context.')
base('445,446,447,448,449,450', 'Namespace Management 用 SEL 選 Create、Delete 或 Restore，Create 的資料依 CSI 解讀。成功建立時 CQE DW0 回傳 NSID；這表示儲存物件已建立，並未自動替主機完成 Attachment。', 'Namespace Management uses SEL for Create, Delete, or Restore; CSI selects the interpretation of creation data. Successful creation returns NSID in CQE DW0, establishing object creation rather than automatic Attachment.')
base('468', 'PS 選擇電源狀態，WH 提供工作負載提示。PS 必須對應控制器支援的狀態，WH 則按允許的提示值解讀；提示不會替主機指定一個新的 Power State Descriptor。', 'PS selects a supported power state and WH supplies a workload hint. Interpret WH under its allowed hint values; a hint does not create a new Power State Descriptor.')
base('470', 'TMPSEL 選感測器，THSEL 選高溫或低溫方向，TMPTH 設門檻，TMPTHH 設遲滯。先固定感測器和方向，再在溫度軸上標出觸發與解除條件，不能把遲滯當成另一個獨立觸發門檻。', 'TMPSEL chooses a sensor, THSEL over/under-temperature direction, TMPTH the threshold, and TMPTHH hysteresis. Fix sensor and direction before marking assertion/clearing conditions; hysteresis is not a second independent assertion threshold.')
base('475,476,477,478,483', 'APSTE 啟用自動轉換，32 個 entry 共 256 bytes，每筆用 ITPT 指定閒置毫秒數、ITPS 指定目標狀態。NOPPME 另外控制 non-operational 狀態的背景工作規則；有 APST 表不表示它已啟用。', 'APSTE enables autonomous transitions. Thirty-two entries total 256 bytes, with ITPT specifying idle milliseconds and ITPS the target state. NOPPME separately governs background work in non-operational states; an existing APST table does not establish enablement.')
base('482,741', 'TMT1 與 TMT2 是兩級熱管理門檻，須符合控制器允許範圍及彼此關係。圖中的控制活動與門檻設定分開閱讀；降溫後的解除條件也不等於將兩個門檻設成同一值。', 'TMT1 and TMT2 are two thermal-management thresholds subject to supported ranges and their relationship. Distinguish configured thresholds from control activity; cooling-related release behavior does not mean setting the two thresholds equal.')
base('545,546,547,548,549', 'HMB 命令先用 EHM、MR 等選擇啟用及記憶體處理方式，再提供 HSIZE、描述子清單位址與 HMDLEC。HSIZE 以 CC.MPS 頁計算，清單位址低／高部分要組合為完整位址。', 'HMB selects enablement and memory handling with EHM/MR and related fields, then supplies HSIZE, descriptor-list address, and HMDLEC. HSIZE uses CC.MPS pages; combine the address halves into the full list address.')
base('550,551', '每個 HMB 描述子占 16 bytes，BADD 指向記憶體區域，BSIZE 以 CC.MPS 頁表示大小。HMDLEC 計描述子數，不是總頁數；應將各有效 BSIZE 加總後與 HSIZE 對照。', 'Each HMB descriptor occupies sixteen bytes. BADD points to a region and BSIZE gives its size in CC.MPS pages. HMDLEC counts descriptors, not total pages; sum valid BSIZE values and compare with HSIZE.')
base('552,553', 'HMB 完成欄位中的 HMNAR 描述目前限制狀態，Attributes 結構回報已提供的大小與描述子清單資訊。設定 HMNARE 與目前 HMNAR 可能不同；取得相同大小也不能證明地址與內容全相同。', 'HMNAR in HMB completion reports the current restriction state; Attributes reports supplied size and list information. Configured HMNARE may differ from current HMNAR. Equal sizes do not establish identical addresses and contents.')
base('700,701', '自我測試操作圖是說明性例子，不能將它的每個 segment 當成裝置必須採用的實作。Format NVM 是否中止測試，則要把 Format 的對象、設定與目前測試範圍一起比較。', 'The Self-test operation illustration is informative, not a mandatory implementation of every segment. Whether Format NVM aborts a test depends on its target/settings and the current test scope.')

pcie('1,2', '層次圖區分 NVMe 命令機制與 PCIe 的實際交換方式。資料指標、佇列記憶體及 Doorbell 共同完成操作，但命令的區塊行為仍由相應 NVMe 規格定義。', 'Layer diagrams separate NVMe command mechanisms from PCIe exchange details. Data pointers, queue memory, and doorbells work together, while block-operation semantics remain defined by the appropriate NVMe specification.')
pcie('3,4,10', '先由 Configuration Space 找到 BAR 及 capabilities，再進入記憶體映射的控制器空間。Configuration Space 的 offset 與 BAR 內的 offset 使用不同起點，兩種地址不能直接互換。', 'Use Configuration Space to locate BARs and capabilities before entering memory-mapped controller space. Configuration offsets and offsets within a BAR have different origins and are not interchangeable.')
pcie('5,6', 'SQ Tail 與 CQ Head 的位置由 queue ID 和 4×2^DSTRD 的間距計算。兩個 Doorbell 交錯排列，寫入內容是佇列位置；位置通知本身不包含命令或完成資料。', 'SQ Tail and CQ Head locations depend on queue ID and spacing of 4×2^DSTRD. The registers alternate, and their contents are queue positions rather than command or completion data.')
pcie('7,8,9', 'Create CQ 的 IV 把完成佇列連到中斷向量。控制器先完成相應的 CQ 更新，再依中斷方式通知；多個 CQ 共享向量時，主機仍需檢查所有對應 CQ。', 'Create CQ IV associates a completion queue with an interrupt vector. The controller updates the CQ and notifies under the chosen interrupt mechanism. Shared vectors require examining all associated CQs.')
pcie('11,14,15,18,24', '裝置識別、revision、class code、header type 與 subsystem 識別描述不同屬性。先按 Configuration Space 的欄位定位，再解釋該類數值；PCIe Class Code 的 PI 不是 NVM 資料保護資訊的 PI。', 'Device identity, revision, class code, header type, and subsystem identity describe different attributes. Locate each Configuration Space field before interpretation. PI in PCIe Class Code is not NVM Protection Information.')
pcie('12,13,16,17,19,23,28,29', '這組共同 Configuration Space 欄位包含控制、狀態及相容性欄位。以 Transport 規格指定的存取方式和固定值閱讀；PCIe BIST 也不等同 NVMe Device Self-test 命令，不能共用其結果格式。', 'These common Configuration Space fields include control, status, and compatibility fields. Follow the access types and fixed values specified by Transport. PCIe BIST is distinct from NVMe Device Self-test and does not share its result format.')
pcie('20,21,22,25,26', 'BAR0／BAR1 的低高部分共同描述控制器記憶體基底，其他 BAR、Expansion ROM 與 Capabilities Pointer 各有不同用途。組合位址時保留地址位與屬性位的區別，不把 capabilities 清單指標當成 MMIO 資料位址。', 'BAR0/BAR1 halves describe the controller memory base, while other BARs, Expansion ROM, and Capabilities Pointer serve different purposes. Separate address and attribute bits; a capability-list pointer is not an MMIO data address.')
pcie('27,30,31,32,33', 'Interrupt Information 描述傳統中斷資訊，Power Management capability 則描述 PCIe 電源能力與狀態。PCIe 電源狀態和 NVMe Power State 是不同層次，不能因數值相同就視為同一設定。', 'Interrupt Information describes legacy interrupt information; the Power Management capability describes PCIe power capabilities and state. PCIe power state and NVMe Power State are different levels, even when numeric values happen to match.')
pcie('34,35,36,37,38,39,40,41', 'MSI 以 message address 與 data 傳遞中斷，Message Control 決定啟用及訊息數相關設定。Mask 控制回報，Pending 記錄待處理通知；它們都不是 CQ 的命令完成內容。', 'MSI signals interrupts through message address/data, with Message Control governing enablement and message counts. Masks control reporting and Pending records deferred notification; none is the command-completion content stored in a CQ.')
pcie('42,43,44,45,46', 'MSI-X 的控制欄位描述啟用、Function Mask 與表大小；MTAB、MPBA 分別用 BIR 與 offset 找到 Table 和 Pending Bit Array。BIR 先選 BAR，再加位移，不能把整個欄位當成絕對位址。', 'MSI-X control describes enablement, Function Mask, and table size. MTAB/MPBA locate the Table and Pending Bit Array with a BIR and offset. Select the BAR using BIR before adding the offset; the whole field is not an absolute address.')
pcie('47,48,49,50,51,52,53,54,55,56,57', 'PCIe capabilities、control、status 分別描述能做什麼、主機設定及目前結果。Link Capabilities 的上限與 Link Status 的實際協商值要分開；Device Control 的傳輸設定也不能直接當成 NVMe 的最大 I/O 長度。', 'PCIe capabilities, control, and status describe support, configuration, and current results. Separate Link Capability limits from negotiated Link Status values. Device Control transfer settings are not directly the NVMe maximum I/O size.')
pcie('58,59,60,61,62,63,64,65,66,67', 'AER 的 Status 回報錯誤，Mask 決定回報遮罩，Severity 分類不可修正錯誤的嚴重程度，Header／Prefix Log 提供相關交易資訊。先辨認可修正或不可修正類別，再將同一錯誤的各欄位配對。', 'AER Status reports errors, Mask controls reporting, Severity classifies uncorrectable errors, and Header/Prefix logs provide transaction context. Select correctable or uncorrectable class before pairing fields for the same error.')
pcie('68,77', 'Printable Eye 把量測結果轉成可讀的眼圖。比較前先確認量測條件和座標尺度，不能把字元或像素的寬度當成規格沒有定義的 I/O 效能數字。', 'Printable Eye presents measurement results as a readable eye diagram. Establish measurement conditions and coordinate scales before comparison; character or pixel width does not define an unspecified I/O performance metric.')
pcie('69', 'DEVICE_INTERFACE_REPORT 描述裝置介面的回報結構。依各區域的長度及定義閱讀，並將其中介面資訊與一般 PCIe error log 分開；它不是 CQE 的另一種排列。', 'DEVICE_INTERFACE_REPORT defines a device-interface reporting structure. Follow each region’s length and definition and distinguish interface information from PCIe error logs; it is not another CQE layout.')
pcie('70,71,72,73,74,75,76', '眼圖量測 log 先用參數及識別值選擇要求，再從 header 取得資料布局，沿 lane descriptors 找個別結果。總長度、lane 數與量測狀態是不同資訊，不能由資料項目數推論量測品質。', 'Eye-measurement logs use parameters and identifiers to select requests, a header to describe layout, and lane descriptors to locate results. Total length, lane count, and measurement status are separate; entry count does not establish measurement quality.')


def note(figure, language):
    key = (figure['source_id'], int(figure['number']))
    if key in NOTES:
        return NOTES[key][language]
    return None
