"""Authored bilingual content for the approved Boot/Telemetry/Sanitize report."""
from __future__ import annotations

REPORT_ID = "base-boot-telemetry-sanitize"
PREFIX = "BASEBTS"
BASE = "NVME-BASE-2.4"
NVM = "NVME-NVM-CS-1.3"


def b(zh, en):
    return {"zh": zh, "en": en}


# key, heading pair, section, PDF pages, statement pair, source
CLAIMS = [
    ("BOOT-MODEL", b("兩個 Boot Partitions", "Two Boot Partitions"), "8.1.3", "612", b("Boot Partitions 是選用功能；支援時有兩個等大的 partition，ID 為 0h、1h。Host 可在未建立 queues、未啟用 controller 時透過 properties 讀取。", "Boot Partitions are optional; support provides two equally sized partitions with IDs 0h and 1h. A host can read through properties without creating queues or enabling the controller."), BASE),
    ("BOOT-READ", b("Property 讀取與 BRS", "Property reads and BRS"), "8.1.3.1", "612-613", b("Host 先檢查 CAP.BPS、BPINFO 的 active ID/size，再配置連續 buffer 與 BPMBL，確認沒有讀取進行中後寫入 BPRSEL。BRS=01b 表示傳輸中，10b 表示成功，11b 表示錯誤；讀取中不得 reset、shutdown 或改動 transport-specific properties。", "The host checks CAP.BPS and the active ID/size in BPINFO, allocates a contiguous buffer and programs BPMBL, then writes BPRSEL only when no read is active. BRS=01b means transfer in progress, 10b success, and 11b error; reset, shutdown, and changes to transport-specific properties are prohibited during the read."), BASE),
    ("BOOT-LOG", b("LID 15h 的另一條讀取路徑", "The alternative LID 15h read path"), "5.2.13.1.21", "309-310", b("LID 15h 以 CDW10.LSP 的 BPID 選 partition，回傳 16-byte header 與其後的資料；BPSZ 以 128 KiB 計。此 log 讀取不改變 BPINFO、BPRSEL 或 BPMBL properties。", "LID 15h selects a partition through BPID in CDW10.LSP and returns a 16-byte header followed by data; BPSZ is measured in 128 KiB units. Reading this log does not modify the BPINFO, BPRSEL, or BPMBL properties."), BASE),
    ("BOOT-UPDATE", b("下載、寫入、驗證、切換", "Download, write, verify, activate"), "8.1.3.2", "613-614", b("Boot image 從開頭依序用 Firmware Image Download 傳送；將目標解鎖後，以 Firmware Commit CA=110b 寫入 BPID 指定的 partition。Host 可讀回驗證，再以 CA=111b 更新 active ID，最後重新上鎖。更新中斷可能留下新舊混合內容，因此宜先驗證再設為 active。", "A boot image is downloaded in order from its beginning using Firmware Image Download. After unlocking the target, Firmware Commit CA=110b writes the partition selected by BPID. The host may read it back, use CA=111b to change the active ID, and relock it. An interrupted update can leave mixed old/new contents, so verification before activation is recommended."), BASE),
    ("BOOT-SEQUENCE", b("更新序列的邊界", "Update-sequence boundaries"), "8.1.3.2", "614", b("Host 不宜在寫入 Boot Partition 時同時讀取，也不宜重疊 firmware/boot image 更新序列。單一序列宜使用同一 controller 或 Management Endpoint；跨端點提交可能使 Commit 以 Invalid Firmware Image 結束。", "The host should avoid reading a Boot Partition while it is being written and should avoid overlapping firmware/boot-image update sequences. A single sequence should use the same controller or Management Endpoint; crossing endpoints may cause Commit to end with Invalid Firmware Image."), BASE),
    ("BOOT-CAP", b("保護能力與控制權", "Protection capabilities and ownership"), "8.1.3.3", "614-615", b("BPCAP 回報 Set Features 與 RPMB Boot 保護能力。只有 Set Features 機制或 RPMB 尚未啟用時由 FID 85h 控制；RPMB 保護啟用後由 RPMB 控制。同一時刻只有一套機制控制狀態，共享 partition 的所有 controllers 都須執行其保護。", "BPCAP reports Set Features and RPMB boot-protection capabilities. FID 85h controls protection when it is the only mechanism or RPMB protection is not enabled; enabled RPMB protection takes control. Only one mechanism owns the state at a time, and all controllers sharing a partition enforce its protection."), BASE),
    ("BOOT-FID", b("FID 85h 逐欄判讀", "Decoding FID 85h"), "5.2.30.1.39", "539-540", b("BP0WPS 位於 CDW11[2:0]，BP1WPS 位於 [5:3]。000b 僅用於 Set 的不改變請求；001b/010b/011b 分別為 unlocked/locked/locked until power cycle；100b 由 Get 回報 RPMB 控制，不能作為 Set 值。此 Feature 不可 save，power cycle 後預設 locked。", "BP0WPS occupies CDW11[2:0] and BP1WPS [5:3]. Value 000b is a Set-only no-change request; 001b/010b/011b mean unlocked/locked/locked until power cycle. Get reports 100b for RPMB ownership, but it is not a valid Set value. This Feature is not saveable and defaults to locked after a power cycle."), BASE),
    ("BOOT-RESET", b("兩套保護的 reset 差異", "Reset differences between protection mechanisms"), "8.1.3.3.1-8.1.3.3.3", "615-620", b("Set Features 的 unlocked 狀態跨 Controller Level Reset 保留，但 power cycle 後回到 locked；locked-until-power-cycle 也不能用一般 Set 解開。RPMB 保護啟用後，unlocked 遇 power cycle 或 Controller Level Reset 會回到 locked，且啟用本身不可撤回。", "Set Features unlocked state survives a Controller Level Reset but returns to locked after a power cycle; ordinary Set cannot escape locked-until-power-cycle. With RPMB protection enabled, either a power cycle or Controller Level Reset relocks an unlocked partition, and enabling protection is irreversible."), BASE),
    ("BOOT-REJECT", b("保護狀態的拒絕條件", "Protection-state rejection conditions"), "5.2.30.1.39; 8.1.3.3.3", "539-540,619-620", b("嘗試修改 locked-until-power-cycle 或 RPMB 控制中的狀態，FID 85h 以 Feature Not Changeable 拒絕。Multi-domain subsystem 中共享的 partition 不允許 locked-until-power-cycle。兩套機制並存時，只要任一 partition 在該狀態，就不得啟用 RPMB Boot 保護來繞過它。", "FID 85h rejects changes to locked-until-power-cycle or RPMB-owned states with Feature Not Changeable. A shared partition in a multi-domain subsystem cannot use locked-until-power-cycle. When both mechanisms exist, RPMB boot protection cannot be enabled while either partition is in that state to bypass it."), BASE),
    ("TEL-MODEL", b("Header 與累積式 Data Areas", "Header and cumulative Data Areas"), "8.1.30; 5.2.13.1.8-5.2.13.1.9", "258-263,759-763", b("Telemetry 的 header 為 block 0，每個 block 是 512 bytes；所有 Data Areas 都從 block 1 起算。Area 2/3/4 是更大的累積集合，不是接在 Area 1 後的獨立區塊。Last Block 是包含在內的最後 block 編號；payload 格式與大小由廠商定義。", "Telemetry uses block 0 for its header and 512-byte blocks. Every Data Area begins at block 1. Areas 2/3/4 are larger cumulative sets, not disjoint regions placed after Area 1. Last Block is an inclusive block number; payload format and size are vendor-defined."), BASE),
    ("TEL-CREATE", b("CTHID 與 MCDA", "CTHID and MCDA"), "5.2.13.1.8", "258-261", b("LID 07h 的 CTHID 是 CDW10 bit 8；設為 1 要求新 capture，0 不更新該 snapshot。MCDA 是 bits 11:9，只有 MCDAS=1 且 CTHID=1 時適用；001b 至 100b 分別要求建立至 Area 1 至 Area 4，000b 由 controller 決定。MCDAS 來自 Supported Log Pages 的 LID Specific Parameter。", "CTHID for LID 07h is CDW10 bit 8: one requests a new capture and zero does not update that snapshot. MCDA occupies bits 11:9 and applies only when MCDAS=1 and CTHID=1; 001b through 100b request creation through Areas 1 through 4, while 000b lets the controller decide. MCDAS comes from the LID Specific Parameter in Supported Log Pages."), BASE),
    ("TEL-DA4", b("Area 4 的雙方支援條件", "Both sides of Data Area 4 support"), "8.1.30; 5.2.30.1.15", "502,759-760", b("Controller 以 LPA.TS 宣告 Telemetry 支援，以 LPA.DA4S 宣告 Area 4；Host 以 FID 16h Host Behavior Support 的 ETDAS=1 宣告支援。DA4S 與 ETDAS 一起決定 Area 4 是否適用；建立 Area 4 時也須建立有資料的 Area 3。", "The controller advertises Telemetry through LPA.TS and Area 4 through LPA.DA4S; the host advertises support with ETDAS=1 in FID 16h Host Behavior Support. DA4S and ETDAS together determine Area 4 applicability; creating Area 4 also requires a populated Area 3."), BASE),
    ("TEL-ALIGN", b("Offset、長度與保留範圍", "Offsets, lengths, and defined ranges"), "5.2.13.1.8-5.2.13.1.9", "258-263", b("讀取 LID 07h/08h 時，offset 與 transfer length 必須是 512 bytes 的倍數，否則回報 Invalid Field in Command。Controller 回傳被要求的 blocks，但超過適用最後 Data Area 邊界的資料不具規格定義的內容。", "For LID 07h/08h, offset and transfer length must be multiples of 512 bytes or the command reports Invalid Field in Command. The controller returns requested blocks, but data beyond the applicable final Data Area boundary has undefined contents."), BASE),
    ("TEL-CONSISTENCY", b("一致性與完成讀取", "Consistency and read acknowledgement"), "8.1.30", "760-761", b("Host 讀 header 記住 generation，以 RAE=1 分段收集，再重讀 header 比對 generation；不同就重新讀取。讀 08h 還需確認 TCDA 未被其他讀取者清除；完成後用 RAE=0 讀任一部分來 acknowledgement。Generation 是 8-bit，FFh 後回到 0h。", "The host records the header generation, collects chunks with RAE=1, and rereads the header; a changed generation calls for rereading. For 08h it also checks that another reader has not cleared TCDA, then acknowledges completion by reading any portion with RAE=0. Generation is eight bits and wraps from FFh to 0h."), BASE),
    ("TEL-TCDA", b("2.4 的 TCDA=0", "TCDA=0 in revision 2.4"), "5.2.13.1.9", "263", b("Base 2.4 的 TCDA=0 表示自上次成功 RAE=0 讀取後沒有更新。第一次 capture 前 header 可讀；capture 過後，即使 TCDA=0，仍回傳 header 與目前保存的 internal state。不能把舊版『0 表示只有 header』的解讀沿用至 2.4。", "In Base 2.4, TCDA=0 means no update since the last successful RAE=0 read. The header is readable before the first capture; after a capture, both the header and current saved internal state are returned even with TCDA=0. The older interpretation that zero means header-only must not be carried into 2.4."), BASE),
    ("TEL-PERSIST", b("Snapshot 的保留條件", "Snapshot persistence conditions"), "5.2.13.1.8-5.2.13.1.9", "259,261,263", b("07h 的 snapshot 不變，直到新的 CTHID=1、Firmware Commit 或 power-on reset。08h Areas 1–3 跨所有 resets 保留，Area 4 可跨 Controller Level Resets 保留；08h 的 TCDA、TCDGN 跨 power cycles 與 resets 保留。", "The 07h snapshot stays unchanged until another CTHID=1 request, Firmware Commit, or power-on reset. For 08h, Areas 1–3 persist across all resets and Area 4 may persist across Controller Level Resets; TCDA and TCDGN persist across power cycles and resets."), BASE),
    ("TEL-EVENT", b("Telemetry Notice 的啟用", "Enabling Telemetry notices"), "8.1.30; 5.2.30.1.6", "760-761,492-494", b("Host 以 FID 0Bh 的 TLN bit 10 啟用 Telemetry Log Notices；controller 以 Notice 類型的 Telemetry Log Changed AER 通知，也可由 07h/08h 的 TCDA 得知資料更新。8.1.30 指向 .1.5 的引用錯置；同版的 AEC 實際在 5.2.30.1.6。", "The host enables Telemetry Log Notices with TLN bit 10 of FID 0Bh. The controller reports a Notice-type Telemetry Log Changed AER; TCDA in 07h/08h also exposes an update. The .1.5 reference in 8.1.30 is misplaced: AEC is actually in 5.2.30.1.6 in this revision."), BASE),
    ("SAN-SCOPE", b("Subsystem 與 namespace 的不同範圍", "Subsystem versus namespace scope"), "8.1.27", "737-738", b("Subsystem sanitize 與 namespace sanitize 的資料範圍不同。逐一 sanitize 全部 namespaces 不等同 subsystem sanitize，也不能因此把 subsystem GDE 設為 1。兩者都不影響 Boot Partitions 或 RPMB；含 user data 的 logs/features 則可能必須修改。", "Subsystem and namespace sanitize cover different data. Sanitizing every namespace individually is not equivalent to subsystem sanitize and does not thereby set subsystem GDE to one. Neither affects Boot Partitions or RPMB; logs/features containing user data may need modification."), BASE),
    ("SAN-MEDIA", b("快取與記憶體邊界", "Cache and memory boundaries"), "8.1.27", "737-738", b("Sanitize 涵蓋 target 的 allocated/deallocated media 與含其 user data 的快取。Subsystem sanitize 對 CMB queue 內容是否修改由實作定義，其餘 CMB 資料須處理；HMB 不受影響。PMR 必須先 disabled，subsystem sanitize 才可開始，且其資料在處理範圍內；namespace sanitize 不影響 CMB、HMB、PMR 或 PDA。", "Sanitize covers the target's allocated/deallocated media and caches holding its user data. For subsystem sanitize, modification of CMB queue contents is implementation-defined while other CMB data is processed; HMB is unaffected. PMR must be disabled before subsystem sanitize starts and its data is within scope; namespace sanitize does not affect CMB, HMB, PMR, or PDA."), BASE),
    ("SAN-METHOD", b("三種方法與 clear/purge", "Three methods and clear/purge"), "8.1.27.2-8.1.27.3", "740-743", b("Block Erase 使用媒體特有 erase；Crypto Erase 改變所有相關 media encryption keys，未加密資料另以適合方法處理；Overwrite 寫入 pattern。PREQ/SPRRS 控制 purge 要求與回報；Crypto Erase 遺留舊 key 或應處理的未加密資料時須失敗。", "Block Erase uses media-specific erasure; Crypto Erase changes all relevant media encryption keys and processes unencrypted data with appropriate methods; Overwrite writes a pattern. PREQ/SPRRS govern purge requests and reporting. Crypto Erase must fail if old keys or unencrypted data requiring sanitization remain unaltered."), BASE),
    ("SAN-COMMAND", b("Sanitize 命令編碼", "Sanitize command encoding"), "5.2.26", "474-477", b("CDW10 包含 SANACT[2:0]、AUSE[3]、OWPASS[7:4]、OIPBP[8]、NDAS[9]、EMVS[10]、PREQ[11]；CDW11 是 OVRPAT。SANACT 001b=Exit Failure Mode、010b=Block Erase、011b=Overwrite、100b=Crypto Erase、101b=Exit Media Verification；其他值保留。", "CDW10 contains SANACT[2:0], AUSE[3], OWPASS[7:4], OIPBP[8], NDAS[9], EMVS[10], and PREQ[11]; CDW11 contains OVRPAT. SANACT 001b selects Exit Failure Mode, 010b Block Erase, 011b Overwrite, 100b Crypto Erase, and 101b Exit Media Verification; other values are reserved."), BASE),
    ("SAN-NAMESPACE", b("Sanitize Namespace 不是相同欄位布局", "Sanitize Namespace has a different field layout"), "8.1.27.1; 5.2.27", "739,479", b("被主範圍引用的 Figure 454 定義 namespace 命令：SANACT 只允許 001b、100b、101b；AUSE 在 bit 3、PREQ 在 bit 4、EMVS 在 bit 10。它沒有 Overwrite/NDAS 欄位，不可直接複製 subsystem Sanitize 的 CDW10。", "Figure 454, referenced by the main scope, defines the namespace command: SANACT permits only 001b, 100b, and 101b; AUSE is bit 3, PREQ bit 4, and EMVS bit 10. There are no Overwrite/NDAS fields, so subsystem Sanitize CDW10 cannot be copied unchanged."), BASE),
    ("SAN-NDAS", b("NDAS、NDI、NODRM 與 NODMMAS", "NDAS, NDI, NODRM, and NODMMAS"), "5.2.30.1.16; 8.1.27.2-8.1.27.3", "503-504,741-745", b("NDAS 是本次命令的保留配置要求；NDI 表示 controller 是否抑制它。NDAS=1 且 NDI=1 時，FID 17h 的 NODRM=0 使命令以 Invalid Field in Command 拒絕，NODRM=1 可接受並在成功後以 SOS=100b 回報 unexpected deallocation。NODMMAS=10b 則描述適用時的額外 media modification。", "NDAS requests retained allocation for this command; NDI indicates inhibition of that request. With NDAS=1 and NDI=1, NODRM=0 in FID 17h rejects the command with Invalid Field in Command, while NODRM=1 permits processing and reports unexpected deallocation as SOS=100b after success. NODMMAS=10b separately describes additional media modification when applicable."), BASE),
    ("SAN-EMVS", b("Media Verification 的命令組合", "Command combinations for Media Verification"), "5.2.26", "475", b("Subsystem sanitize 要求 EMVS=1 時，需要 VERS=1、SANACT 為 Block Erase 或 Crypto Erase，且 NDAS=0；Overwrite 或 NDAS=1 的組合以 Invalid Field in Command 拒絕。SANACT=101b 只可在 Media Verification state 使用，並啟動後續 deallocation 而非新的 sanitize。", "Subsystem sanitize with EMVS=1 requires VERS=1, Block Erase or Crypto Erase, and NDAS=0; combining it with Overwrite or NDAS=1 is rejected with Invalid Field in Command. SANACT=101b applies only in Media Verification and starts subsequent deallocation rather than a new sanitize operation."), BASE),
    ("SAN-PREFLIGHT", b("開始前的拒絕條件", "Rejections before starting"), "5.2.26; 8.1.27.1", "475-477,738-740", b("PMR enabled、namespace write protection、controller suspended 或 pending firmware activation/reset 都可能阻止 subsystem sanitize。若啟動命令不是 Successful Completion，就不開始該 operation、不改 target 的 Sanitize Status，也不改 user data；已能預知的 operation 失敗則宜由後續 log 回報。", "Enabled PMR, namespace write protection, a suspended controller, or pending firmware activation/reset may prevent subsystem sanitize. If the initiating command does not return Successful Completion, it starts no operation, changes no target Sanitize Status, and alters no user data; an anticipated operation failure should instead be reported through the subsequent log."), BASE),
    ("SAN-BACKGROUND", b("CQE 不是 sanitize 完成", "A CQE is not sanitize completion"), "5.2.26.1; 8.1.27.1", "477,738-739", b("Sanitize 在背景執行。開始 operation 後先更新 LID 81h，再完成啟動命令；Host 需用狀態 log 與事件判定後續進度。執行中的 operation 不能被 abort，並持續跨 reset/power cycle，但 verification 階段可能因指定 reset 被取消。", "Sanitize runs in the background. Starting an operation updates LID 81h before completing its initiating command; the host uses the status log and events for subsequent progress. An active operation cannot be aborted and continues across reset/power cycle, although specified resets may cancel verification."), BASE),
    ("SAN-OVERWRITE", b("Overwrite passes 的奇偶", "Overwrite-pass parity"), "5.2.26; 8.1.27.3", "477,743", b("OWPASS=0h 表示 16 passes。OIPBP=0 時 user data 使用 OVRPAT、PI bytes 為 FFh。OIPBP=1 且總次數為偶數時第一輪使用反相 pattern、PI=00h；奇數時第一輪使用原 pattern、PI=FFh，其後逐輪反相。", "OWPASS=0h means 16 passes. With OIPBP=0, user data uses OVRPAT and PI bytes are FFh. With OIPBP=1 and an even pass count, the first pass uses the inverted pattern and PI=00h; with an odd count it starts with the original pattern and PI=FFh, then inverts on each subsequent pass."), BASE),
    ("SAN-STATE", b("七個狀態與兩種失敗路徑", "Seven states and two failure paths"), "8.1.27.4", "745-756", b("每個支援的 target 有一份狀態機。AUSE=0/1 分別進入 Restricted/Unrestricted Processing；失敗落入對應 Failure。Restricted Failure 必須以 restricted sanitize 重試；Unrestricted Failure 可重試或 Exit Failure Mode 回 Idle。Idle 因而不必然表示最後一次 sanitize 成功。", "Each supported target has its own state machine. AUSE=0/1 selects Restricted/Unrestricted Processing, and failure enters the corresponding Failure state. Restricted Failure requires a restricted sanitize retry; Unrestricted Failure permits retry or Exit Failure Mode to Idle. Idle therefore does not necessarily mean the last sanitize succeeded."), BASE),
    ("SAN-VERIFY-STATE", b("Verification 與 deallocation 的銜接", "Verification and deallocation transitions"), "8.1.27.4.6-8.1.27.4.7", "753-756", b("Processing 成功且 EMVS 要求未被取消時進入 Media Verification。Exit Media Verification、適用 reset 或阻止驗證的 composition change 使 target 進入 Post-Verification Deallocation；成功才回 Idle，失敗依原 AUSE 回 Restricted/Unrestricted Failure，FAILS=6h。", "Successful processing enters Media Verification when requested by EMVS and not canceled. Exit Media Verification, an applicable reset, or a composition change preventing verification moves the target to Post-Verification Deallocation. Success returns to Idle; failure follows the original AUSE into Restricted/Unrestricted Failure with FAILS=6h."), BASE),
    ("SAN-STATUS", b("LID 81h 的 scope 與狀態", "Scope and state in LID 81h"), "5.2.13.1.38", "339-345", b("LID 81h 的 NSID=0h 或 FFFFFFFFh 指 subsystem，allocated NSID 指 namespace。SSTAT 含 SOS、OPC、GDE、MVCNCLD、NDE、PRGD；SSI 含 SANS/FAILS；SCDW10 保存啟動參數。MNSOIP 回報並行 namespace operations 上限，STNSID 識別 namespace target。Log 跨 power cycles/resets 保留。", "For LID 81h, NSID=0h or FFFFFFFFh selects the subsystem and an allocated NSID selects a namespace. SSTAT includes SOS, OPC, GDE, MVCNCLD, NDE, and PRGD; SSI contains SANS/FAILS; SCDW10 records initiating parameters. MNSOIP reports the concurrent namespace-operation limit and STNSID identifies a namespace target. The log persists across power cycles/resets."), BASE),
    ("SAN-PROGRESS", b("SPROG 與時間估計", "SPROG and time estimates"), "5.2.13.1.38; 8.1.27.3", "340-345,744", b("SPROG 的比例是 raw/65536，分別表示 Processing 或 Post-Verification Deallocation 的進度，進入這些階段時重設為 0。Media Verification 時可為 FFFFh 而 SOS 仍是 Sanitizing；不能只看 SPROG 判斷完成。時間估計依方法與額外 media modification 分開，FFFFFFFFh 表示未回報。", "SPROG is raw/65536 and reports progress for Processing or Post-Verification Deallocation, resetting to zero on entry. It can be FFFFh in Media Verification while SOS still says Sanitizing, so it cannot alone prove completion. Time estimates distinguish method and additional media modification; FFFFFFFFh means no estimate is reported."), BASE),
    ("SAN-EVENT", b("三種 Sanitize 事件", "Three Sanitize events"), "8.1.27.1; 8.1.27.4", "738-739,746", b("Sanitize AER 使用 AET=110b、LID=81h，AEI=01h/02h/03h 分別表示 Completed、Completed With Unexpected Deallocation、Entered Media Verification。DW1 的 EVNTSP 為 subsystem 的 0h 或 target NSID。事件要與 log 一起判讀，Completed 不自動代表成功。", "Sanitize AERs use AET=110b and LID=81h; AEI=01h/02h/03h means Completed, Completed With Unexpected Deallocation, or Entered Media Verification. DW1 EVNTSP is zero for the subsystem or the target NSID. Interpret the event together with the log: Completed does not automatically mean success."), BASE),
    ("SAN-RESTRICT", b("執行中的命令限制", "Command restrictions during execution"), "8.1.27.5; 5.1.1-5.1.2", "204-207,756-758", b("Subsystem sanitize 進行中以 Figure 144 判斷允許的 Admin 命令及 log pages；Boot Partition log 在清單內，Telemetry 07h/08h 不在。未被允許的操作受 Sanitize In Progress 限制；namespace sanitize 另依 Figures 145/146 與 target NSID 判斷。Media Verification 的 NVM Read 有特定例外。", "During subsystem sanitize, Figure 144 identifies allowed Admin commands and log pages; Boot Partition is listed but Telemetry 07h/08h is not. Disallowed operations are restricted with Sanitize In Progress. Namespace sanitize instead uses Figures 145/146 and the target NSID. NVM Reads in Media Verification have a specific exception."), BASE),
    ("SAN-POWER", b("多 controller、電源與韌體限制", "Multiple controllers, power, and firmware restrictions"), "8.1.27.5", "756-758", b("Sanitize 開始時 controllers 更新 target log 並暫停 autonomous power state management。依 target 中止受影響 I/O/self-test、釋放相關 streams；進行中不得 activation 新 firmware。Subsystem operation 也阻止 PMR enable 與 PDA access。", "Starting sanitize updates the target log on controllers and suspends autonomous power-state management. Affected I/O/self-tests are aborted and relevant streams released according to the target; new firmware activation is prohibited while the operation is active. A subsystem operation also prevents PMR enablement and PDA access."), BASE),
    ("NVM-BRIDGE", b("NVM Command Set 的補充位置", "Where the NVM Command Set extends behavior"), "4.1.7; 5.12", "113,173-175", b("NVM 4.1.7 沿用 Base 的 Sanitize command；5.12 補充允許的 Admin 行為、sanitize 後的資料值與 Media Verification Read。Error Information 的 LBA 要回傳 0，其他含 user data 的欄位仍依 Base 處理。", "NVM 4.1.7 uses the Base Sanitize command; 5.12 adds permitted Admin behavior, post-sanitize data values, and Media Verification Reads. Error Information returns zero in LBA, while other fields containing user data remain subject to Base processing."), NVM),
    ("NVM-VALUES", b("Sanitize 後不一定讀到零", "Sanitize does not imply zero-filled reads"), "5.12", "174", b("成功後 audit 讀到的值：Block Erase 為 vendor-specific，Crypto Erase 為 indeterminate，Overwrite 依 Base 的 pattern 機制。若已 deallocate，讀取另依 Deallocated or Unwritten Logical Blocks 規則；未 deallocate 且啟用 PI checking 的讀取可能發生 PI check error。", "After success, audit values are vendor-specific for Block Erase, indeterminate for Crypto Erase, and governed by the Base pattern mechanism for Overwrite. Reads of deallocated blocks instead follow Deallocated or Unwritten Logical Blocks rules; PI-checking reads without deallocation may encounter PI check errors."), NVM),
    ("NVM-VERIFY", b("Media Verification Read 的三條分支", "Three Media Verification Read branches"), "5.12.1", "174-175", b("Media Verification Read 不要求 PI checking，即 PRCHK=000b 且 STC=0。Allocated media 能讀時回傳實際資料並忽略可讀情況下的 integrity errors，未被其他錯誤中止就以 Successful Media Verification Read 完成；不能讀取 allocated media 時回 Unrecovered Read Error。指定 PI checking 則回 Invalid Field in Command。", "A Media Verification Read requests no PI checking: PRCHK=000b and STC=0. Readable allocated media returns its data while ignoring integrity errors when the media can be read, completing with Successful Media Verification Read unless another error aborts it. Unreadable allocated media produces Unrecovered Read Error. Requesting PI checking produces Invalid Field in Command."), NVM),
    ("SOURCE-XREF", b("原稿交叉引用的核對", "Checking source cross-references"), "8.1.3.1; 8.1.27.4.2", "613,747", b("原稿 Boot log 的 section 0 可由同版 LID 15h 定位到 5.2.13.1.21。SPROG 段落寫 Figure 311，但該圖實際為 Reservation Notification；SPROG 定義在 Figure 312。這是附件內部核對的疑似引用錯置，不宣稱為官方勘誤。", "The boot-log section 0 reference can be resolved within the same revision to LID 15h in 5.2.13.1.21. The SPROG paragraph cites Figure 311, which actually describes Reservation Notification; SPROG is defined in Figure 312. These are suspected cross-reference defects found by internal comparison, not claimed official errata."), BASE),
]


def install(reports, titles, modules, glossaries):
    def shift(pages):
        import re
        return re.sub(r"\d+", lambda m: str(int(m.group()) - 26), pages)
    claims = []
    for key, heading, section, pdf, text, source in CLAIMS:
        keyword = 'should' if key == 'BOOT-SEQUENCE' else (
            'shall' if key in {'BOOT-READ', 'BOOT-FID', 'TEL-ALIGN', 'TEL-TCDA', 'SAN-EMVS', 'SAN-BACKGROUND', 'SAN-OVERWRITE', 'SAN-RESTRICT', 'NVM-VERIFY'} else 'none'
        )
        claims.append(dict(key=key, section=section, pdf_pages=pdf,
                           printed_pages=pdf if source == NVM else shift(pdf),
                           zh_tw=text["zh"], en=text["en"], normative_keyword=keyword,
                           source_id=source, scope_entry_id="NVMCS-BTS-INCLUDE" if source == NVM else "BASE-BTS-INCLUDE"))
        titles[f"{PREFIX}-{key}"] = (heading["zh"], heading["en"])
    reports[REPORT_ID] = dict(
        prefix=PREFIX, title_zh="NVMe 2.4：Boot Partitions、Telemetry 與 Sanitize 完整教學",
        title_en="NVMe 2.4: Boot Partitions, Telemetry, and Sanitize",
        source_id=BASE, supporting_source_ids=[NVM], scope_entry="BASE-BTS-INCLUDE",
        date="2026-09-03", verified_date="2026-09-03",
        range="Base §§8.1.3、8.1.30、8.1.27（排除 8.1.27.6）、5.2.26；LID 15h/07h/08h/81h；FID 85h/17h；NVM §§4.1.7、5.12，以及被引用的必要圖表",
        range_en="Base §§8.1.3, 8.1.30, 8.1.27 (excluding 8.1.27.6), 5.2.26; LIDs 15h/07h/08h/81h; FIDs 85h/17h; NVM §§4.1.7 and 5.12, with required referenced figures",
        diagram=["Discover capability", "Read / capture / sanitize", "Track state and evidence", "Verify outcome"],
        diagram_note_zh="Boot、Telemetry、Sanitize 分別管理開機映像、診斷快照與 user-data sanitization；它們共享能力、命令與證據的閱讀方法，卻有不同的 scope 與完成條件。",
        diagram_note_en="Boot, Telemetry, and Sanitize manage boot images, diagnostic snapshots, and user-data sanitization. They share a capability-command-evidence reading method but have different scopes and completion conditions.", claims=claims)
    modules[REPORT_ID] = MODULES
    glossaries[REPORT_ID] = [(term, f"{PREFIX}-{key}") for term, key in [
        ("BPID", "BOOT-LOG"), ("BRS", "BOOT-READ"), ("BPCAP", "BOOT-CAP"), ("BP0WPS", "BOOT-FID"),
        ("CTHID", "TEL-CREATE"), ("MCDA", "TEL-CREATE"), ("MCDAS", "TEL-CREATE"), ("ETDAS", "TEL-DA4"),
        ("TCDA", "TEL-TCDA"), ("TCDGN", "TEL-CONSISTENCY"), ("RAE", "TEL-CONSISTENCY"),
        ("SANACT", "SAN-COMMAND"), ("AUSE", "SAN-STATE"), ("NDAS", "SAN-NDAS"), ("NODRM", "SAN-NDAS"),
        ("EMVS", "SAN-EMVS"), ("PREQ", "SAN-METHOD"), ("SPROG", "SAN-PROGRESS"), ("SOS", "SAN-STATUS"),
        ("MVCNCLD", "SAN-VERIFY-STATE"), ("PRCHK", "NVM-VERIFY"), ("STC", "NVM-VERIFY")]]


def m(key, title, lead, nodes, rows, example, pitfall, sources, figures):
    return dict(id=key, title=title, lead=lead, nodes=nodes, rows=rows, example=example,
                pitfall=pitfall, sources=[f"{PREFIX}-{s}" for s in sources], figures=figures)


MODULES = [
    m("boot-read", b("Boot 的兩條讀取路徑", "Two Boot read paths"),
      b("先問 controller 是否已建立 Admin command 環境，再選 property 或 LID 15h。兩條路徑讀同一類 Boot 內容，但回傳格式與狀態觀察點不同。", "First determine whether an Admin-command environment exists, then choose properties or LID 15h. Both access boot contents, but their return formats and observation points differ."),
      b(["CAP.BPS", "BPINFO active/size", "BPMBL buffer", "BPRSEL request", "BRS result"], ["CAP.BPS", "BPINFO active/size", "BPMBL buffer", "BPRSEL request", "BRS result"]),
      b([["Properties", "BRS 回報讀取狀態", "不要求 CC.EN=1"], ["LID 15h", "16-byte header + data", "由 Admin command CQE 判斷命令結果"], ["BPID", "選取讀取 partition", "不等於 active ID"], ["BPSZ", "每單位 128 KiB", "不是 bytes"]],
        [["Properties", "BRS reports read state", "Does not require CC.EN=1"], ["LID 15h", "16-byte header + data", "The Admin-command CQE reports the command result"], ["BPID", "Selects the partition to read", "Not the active ID"], ["BPSZ", "128 KiB per unit", "Not a byte count"]]),
      b("BPSZ=2 的 LID 15h 包含 262144 bytes 的 Boot data，加上 16-byte header，共 262160 bytes。讀 BP1 並不把 BP1 設為 active；讀 log 也不會推進 property 的 BRS。", "With BPSZ=2, LID 15h contains 262144 bytes of boot data plus a 16-byte header, totaling 262160 bytes. Reading BP1 does not activate BP1, and a log read does not advance the property's BRS."),
      b("若 property 讀取未完成，先檢查 BRS 與 buffer，不能用 reset 當作允許的正常完成步驟。LID 15h 的 BPINFO 是回傳欄位，讀它不會改動同名 property。", "For an unfinished property read, inspect BRS and the buffer; reset is not an allowed normal completion step. BPINFO in LID 15h is a returned field and reading it does not modify the property of the same name."),
      ["BOOT-MODEL", "BOOT-READ", "BOOT-LOG"], [36,49,50,51,279,280,679]),
    m("boot-protection", b("更新與保護的完整生命週期", "The complete update and protection lifecycle"),
      b("把 image transfer、partition content、active selection、write protection 分開追蹤。成功下載尚未寫入 Boot Partition；寫入成功也未自動選成 active。", "Track image transfer, partition contents, active selection, and write protection separately. Successful download has not yet written a Boot Partition, and a successful write has not automatically activated it."),
      b(["Download in order", "Unlock target", "Commit CA=110b", "Read/verify; CA=111b", "Relock"], ["Download in order", "Unlock target", "Commit CA=110b", "Read/verify; CA=111b", "Relock"]),
      b([["FID 85h unlocked", "Controller reset 後保留", "Power cycle 後 locked"], ["FID 85h until power cycle", "一般 Set 不可解鎖", "共享 multi-domain partition 不可用"], ["RPMB enabled/unlocked", "Controller reset 即 relock", "啟用保護不可撤回"], ["兩套機制", "同時只有一套控制", "RPMB enable 是控制權轉移"]],
        [["FID 85h unlocked", "Survives controller reset", "Locked after power cycle"], ["FID 85h until power cycle", "Ordinary Set cannot unlock", "Unavailable for shared multi-domain partitions"], ["RPMB enabled/unlocked", "Controller reset relocks", "Protection enablement cannot be reversed"], ["Both mechanisms", "Only one owns control at a time", "RPMB enablement transfers ownership"]]),
      b("保留 BP0 不變、要求 BP1 unlocked 的 FID 85h CDW11 是 (001b << 3) | 000b = 08h。讀回時 BP0 不會回傳 000b，而會回報它真正的狀態；RPMB 控制時則回報 100b。", "To leave BP0 unchanged and unlock BP1, FID 85h CDW11 is (001b << 3) | 000b = 08h. A subsequent Get does not return 000b for BP0; it returns its actual state, or 100b when RPMB owns protection."),
      b("用相同 reset 測試兩套機制時，預期結果不同。也要保留 power-cycle/reset 類型，否則無法證明 relock 是正常行為或錯誤。", "The same reset test has different expected results for the two mechanisms. Preserve the power-cycle/reset type so that relocking can be classified as expected behavior or a defect."),
      ["BOOT-UPDATE", "BOOT-SEQUENCE", "BOOT-CAP", "BOOT-FID", "BOOT-RESET", "BOOT-REJECT"], [187,542,680,681,682,683,684,756,765,766]),
    m("telemetry-layout", b("從 Last Block 計算快照", "Computing snapshots from Last Block"),
      b("Area 是從同一 block 1 起算的不同大小視圖。先解碼 header，再選擇適用且有資料的最後 area；不要把三個 Last Block 數字相加。", "Areas are differently sized views starting at the same block 1. Decode the header, select the final applicable populated area, and do not add the three Last Block numbers."),
      b(["Read 512-byte header", "Check DA4S/ETDAS", "Decode last blocks", "Compute inclusive extent", "Read aligned blocks"], ["Read 512-byte header", "Check DA4S/ETDAS", "Decode last blocks", "Compute inclusive extent", "Read aligned blocks"]),
      b([["Area 1", "1 到 L1", "L1=0 表示沒有資料"], ["Area 2", "1 到 L2", "L2 >= L1"], ["Area 3", "1 到 L3", "L3 >= L2"], ["Area 4", "1 到 L4", "支援條件另行檢查"]],
        [["Area 1", "1 through L1", "L1=0 means no data"], ["Area 2", "1 through L2", "L2 >= L1"], ["Area 3", "1 through L3", "L3 >= L2"], ["Area 4", "1 through L4", "Check support separately"]]),
      b("Last Blocks=65/1000/30000 時，Area 3 payload 為 30000×512=15360000 bytes；包含 header 的 log 為 15360512 bytes。0/1000/1000 則表示 Area 1 空、Area 3 沒有超出 Area 2 的新增內容。", "For Last Blocks=65/1000/30000, Area 3 payload is 30000×512=15360000 bytes and the log including its header is 15360512 bytes. Values 0/1000/1000 mean Area 1 is empty and Area 3 adds no content beyond Area 2."),
      b("LID 07h 的 THS 與 LID 08h 的 TCS 位置不同；不能把一份 header 的 offset 套在另一份。Snapshot payload 由廠商定義，不能把未知 bytes 解碼成假設的診斷欄位。", "THS in LID 07h and TCS in LID 08h have different offsets; do not reuse one header layout for the other. Snapshot payload is vendor-defined, so unknown bytes cannot be assigned invented diagnostic fields."),
      ["TEL-MODEL", "TEL-DA4", "TEL-ALIGN"], [221,223,338,491,780,781]),
    m("telemetry-capture", b("建立、讀取、確認一致、acknowledge", "Create, read, verify consistency, acknowledge"),
      b("07h 的 create 與後續讀取分開；08h 的 capture 由 controller 決定。Host 對兩者都要驗證 generation，並分清事件 acknowledgement 與刪除 payload。", "Separate creating 07h data from subsequent reads; the controller decides 08h capture timing. For both, verify generation and distinguish event acknowledgement from payload deletion."),
      b(["Capability / event setup", "Capture or observe update", "RAE=1 chunk reads", "Recheck generation/TCDA", "08h RAE=0 acknowledgement"], ["Capability / event setup", "Capture or observe update", "RAE=1 chunk reads", "Recheck generation/TCDA", "08h RAE=0 acknowledgement"]),
      b([["CTHID=1", "觸發新 07h capture", "後續分段讀不要再次 create"], ["MCDA", "限制建立到哪個 area", "先看 MCDAS"], ["RAE=1", "保留事件", "不保證沒有其他 reader"], ["TCDA=0", "上次 acknowledgement 後未更新", "2.4 不等於 payload 消失"]],
        [["CTHID=1", "Triggers a new 07h capture", "Do not create again for subsequent chunks"], ["MCDA", "Limits the areas created", "Check MCDAS first"], ["RAE=1", "Retains the event", "Does not exclude another reader"], ["TCDA=0", "No update since acknowledgement", "In 2.4 it does not mean payload disappearance"]]),
      b("讀取前 generation=2Ah，讀完變成 2Bh，這批 blocks 不能當成同一 capture 的一致資料。若值保持 2Ah 但 TCDA 被其他 host 清成 0，08h 收集仍需依流程檢查該競態。", "If generation is 2Ah before reading and 2Bh afterward, the chunks cannot be accepted as one consistent capture. Even if it remains 2Ah, an 08h collection must consider the race where another host clears TCDA to zero."),
      b("不要把 RAE=0 寫成『刪除 snapshot』，也不要把 AER 當成 payload 本身。事件只提供收集觸發與定位，資料仍由 Get Log Page 取得。", "Do not describe RAE=0 as deleting the snapshot or treat the AER as the payload. The event supplies a collection trigger and locator; Get Log Page still retrieves the data."),
      ["TEL-CREATE", "TEL-CONSISTENCY", "TEL-TCDA", "TEL-PERSIST", "TEL-EVENT"], [204,210,211,220,222,151,152,155,474]),
    m("sanitize-scope", b("先定義被清理的 target", "Define the sanitization target first"),
      b("Sanitize scope 不是『磁碟上所有東西』。以 target、資料來源、是否可能含 user data 判斷；Boot 與診斷機制的交叉關係也從這個範圍開始。", "Sanitize scope is not simply everything on a disk. Classify the target, data provenance, and whether it can contain user data; this also establishes its relationship with Boot and diagnostics."),
      b(["Select target", "Enumerate user-data locations", "Check method/support", "Apply purge requirement", "Audit permitted evidence"], ["Select target", "Enumerate user-data locations", "Check method/support", "Apply purge requirement", "Audit permitted evidence"]),
      b([["Boot/RPMB", "不受 sanitize 影響", "另由自身管理機制控制"], ["Logs/features", "必要時修改 user data", "不能只檢查 namespace media"], ["All namespace sanitizes", "只完成各 target 的工作", "不能因此宣告 subsystem GDE"], ["Crypto Erase", "改 key 並處理未加密資料", "舊 key 副本也是重要條件"]],
        [["Boot/RPMB", "Unaffected by sanitize", "Managed by their own mechanisms"], ["Logs/features", "Modify user data when necessary", "Namespace media alone is insufficient"], ["All namespace sanitizes", "Complete work on each target", "Does not thereby establish subsystem GDE"], ["Crypto Erase", "Changes keys and handles unencrypted data", "Old key copies matter too"]]),
      b("即使所有 namespaces 都已 sanitize，CMB 等 subsystem 層級資料仍不能由這個事實證明已完成 subsystem sanitization。相反地，成功 subsystem sanitize 也不會替 Boot Partition 更新或清除開機映像。", "Even after every namespace is sanitized, that fact does not prove subsystem-level data such as CMB has undergone subsystem sanitization. Conversely, successful subsystem sanitize does not update or erase the boot image in a Boot Partition."),
      b("把成功後 read 回零視為唯一成功標準會誤判。先確認方法、是否 deallocate、是否在驗證狀態，再套用 NVM Command Set 定義的結果。", "Using zero-filled reads as the only success criterion misclassifies results. Establish the method, allocation state, and verification state before applying NVM Command Set result definitions."),
      ["SAN-SCOPE", "SAN-MEDIA", "SAN-METHOD", "NVM-VALUES"], [770,771,200,201]),
    m("sanitize-command", b("命令參數與 capability 組合", "Combining command parameters with capabilities"),
      b("先把支援能力、命令要求與 Feature policy 分開。命令接受、operation 成功、符合 no-deallocate 要求是三個需要不同證據的結果。", "Separate advertised capabilities, command requests, and Feature policy. Command acceptance, operation success, and satisfaction of no-deallocate are three outcomes requiring different evidence."),
      b(["SANICAP / target", "SANACT and modifiers", "FID 17h policy", "Preflight and CQE", "LID 81h operation result"], ["SANICAP / target", "SANACT and modifiers", "FID 17h policy", "Preflight and CQE", "LID 81h operation result"]),
      b([["NDAS=1, NDI=0", "不得因成功 sanitize deallocate", "其他合法條件仍需符合"], ["NDAS=1, NDI=1, NODRM=0", "命令拒絕", "Invalid Field in Command"], ["NDAS=1, NDI=1, NODRM=1", "允許處理", "成功可回 SOS=100b"], ["EMVS=1", "Subsystem 要 VERS=1", "Block/Crypto + NDAS=0"]],
        [["NDAS=1, NDI=0", "Successful sanitize must not deallocate", "Other validity conditions still apply"], ["NDAS=1, NDI=1, NODRM=0", "Command rejected", "Invalid Field in Command"], ["NDAS=1, NDI=1, NODRM=1", "Processing permitted", "Success can report SOS=100b"], ["EMVS=1", "Subsystem requires VERS=1", "Block/Crypto + NDAS=0"]]),
      b("SANACT=010b、AUSE=0、EMVS=1、NDAS=0、PREQ=0 的 CDW10 是 0402h。只有支援 VERS/Block Erase 且其他前置條件成立時才適用。另一例：OWPASS=0h 是 16 次，不是『跳過 overwrite』。", "SANACT=010b, AUSE=0, EMVS=1, NDAS=0, and PREQ=0 encode CDW10=0402h. It applies only with VERS/Block Erase support and other preconditions satisfied. Separately, OWPASS=0h means 16 passes, not skipping overwrite."),
      b("Figure 454 的 PREQ 在 bit 4，Figure 451 則在 bit 11。兩種命令若共用未分型的 builder，容易在 namespace 命令寫入 reserved bits。", "PREQ is bit 4 in Figure 454 but bit 11 in Figure 451. Sharing an untyped builder between the two commands can set reserved bits in the namespace command."),
      ["SAN-COMMAND", "SAN-NAMESPACE", "SAN-NDAS", "SAN-EMVS", "SAN-PREFLIGHT", "SAN-OVERWRITE"], [338,451,452,453,454,492]),
    m("sanitize-state", b("用 state、log、AER 重建背景作業", "Reconstruct background work from state, log, and AER"),
      b("從 Figure 772 的七個 states 出發，逐一把 Figures 773–779 的 transition condition 接上。Status 描述結果，state 描述目前位置，事件描述發生的轉折。", "Start with the seven states in Figure 772 and attach transition conditions from Figures 773–779. Status describes results, state describes the current position, and events report transitions."),
      b(["Idle", "Restricted/Unrestricted Processing", "Failure OR Verification", "Post-Verification Deallocation", "Idle + final log"], ["Idle", "Restricted/Unrestricted Processing", "Failure OR Verification", "Post-Verification Deallocation", "Idle + final log"]),
      b([["Restricted Failure", "只以 restricted 重試", "Exit Failure Mode 不可解套"], ["Unrestricted Failure", "重試或 Exit Failure Mode", "回 Idle 不會改寫失敗歷史"], ["Media Verification", "Processing 已成功", "整個 operation 仍 Sanitizing"], ["Post-Verification Deallocation", "SPROG 重新由 0 起算", "失敗 FAILS=6h"]],
        [["Restricted Failure", "Retry in restricted mode", "Exit Failure Mode cannot escape it"], ["Unrestricted Failure", "Retry or Exit Failure Mode", "Idle does not rewrite failure history"], ["Media Verification", "Processing succeeded", "The operation is still Sanitizing"], ["Post-Verification Deallocation", "SPROG starts again at zero", "Failure records FAILS=6h"]]),
      b("SPROG=8000h 表示目前被量測的階段約 50%。進入 Media Verification 後 SPROG=FFFFh，SOS 仍可為 010b；退出驗證進入 deallocation 又從 0 開始。這不是進度倒退。", "SPROG=8000h represents 50% of the currently measured phase. Media Verification uses SPROG=FFFFh while SOS can remain 010b; leaving verification for deallocation starts progress again at zero. This is not progress regression."),
      b("保存 SCDW10、SOS、SANS、FAILS、MVCNCLD 與事件 timestamp。只記錄『完成事件』會把成功、失敗及進入驗證混成同一結論。", "Preserve SCDW10, SOS, SANS, FAILS, MVCNCLD, and event timestamps. Recording only a completion event conflates success, failure, and entry into verification."),
      ["SAN-BACKGROUND", "SAN-STATE", "SAN-VERIFY-STATE", "SAN-STATUS", "SAN-PROGRESS", "SAN-EVENT"], [312,151,152,156,772,773,774,775,776,777,778,779]),
    m("sanitize-read", b("操作限制與驗證讀取", "Restrictions and verification reads"),
      b("把 command allowlist 與 NVM Read 特例分開判斷。Host 先辨識 target/state，再確認 PI checking 與 allocation，不能把平常 read 的處理完全套入驗證狀態。", "Evaluate the command allowlist and the NVM Read exception separately. Determine target/state, then PI checking and allocation; ordinary-read behavior cannot be applied unchanged to verification."),
      b(["Target/state", "Admin/I/O permission", "PRCHK=000b and STC=0", "Allocated media readable?", "Data + specific status"], ["Target/state", "Admin/I/O permission", "PRCHK=000b and STC=0", "Allocated media readable?", "Data + specific status"]),
      b([["PI checking requested", "Invalid Field in Command", "驗證讀取不允許此組合"], ["Allocated media readable", "回實際 media data", "可忽略可讀情況的 integrity error"], ["Allocated media unreadable", "Unrecovered Read Error", "不可假造資料"], ["Deallocated LBA", "依 deallocated/unwritten 規則", "不是檢查原始 media pattern 的證據"]],
        [["PI checking requested", "Invalid Field in Command", "Not permitted for verification reads"], ["Allocated media readable", "Return media data", "Integrity errors can be ignored when readable"], ["Allocated media unreadable", "Unrecovered Read Error", "Do not invent data"], ["Deallocated LBA", "Use deallocated/unwritten rules", "Not evidence of the old media pattern"]]),
      b("驗證讀取 PRCHK=000b、STC=0，所有 allocated LBAs 都能讀取，且沒有其他 abort 原因時，預期 Successful Media Verification Read。只要請求 PI checking，預期分支即改為 Invalid Field in Command。", "A verification read with PRCHK=000b and STC=0, readable allocated LBAs, and no other abort cause completes as Successful Media Verification Read. Requesting PI checking changes the expected branch to Invalid Field in Command."),
      b("不要在 subsystem sanitize 期間假設所有 Get Log Page 都允許；07h/08h 不在 Figure 144 清單。Namespace sanitize 的限制必須另外以 attached/target 範圍判斷。", "Do not assume all Get Log Page requests are permitted during subsystem sanitize; 07h/08h are absent from Figure 144. Namespace sanitize restrictions require a separate attached/target-scope evaluation."),
      ["SAN-RESTRICT", "SAN-POWER", "NVM-BRIDGE", "NVM-VALUES", "NVM-VERIFY", "SOURCE-XREF"], [11,12,144,145,146,200,201,311]),
]
