from scripts.nvme_scenarios import case

case('init',('能枚舉 PCIe 裝置，為什麼還不能開始 I/O？','Why does PCIe enumeration not establish I/O readiness?'),
('系統已讀到 PCI Vendor ID、Device ID，便宣稱 NVMe 已就緒。還缺哪些層次的證據？','The system reads PCI Vendor ID and Device ID and declares NVMe ready. Which evidence layers are still missing?'),
[('PCI configuration 的 CMD.MSE=0、CMD.BME=0；BAR 已有配置值。','PCI configuration CMD has MSE=0 and BME=0; BARs have assigned values.'),('尚未確認 NVMe CAP、CC、CSTS，也沒有 Admin Queue 或 Identify 成功紀錄。','NVMe CAP, CC and CSTS have not been verified; there is no successful Admin Queue or Identify trace.')],
('PCI configuration → BAR 與 PCI CMD → NVMe memory-mapped properties → Admin Queue／Identify → I/O queues 與 namespace。','PCI configuration → BARs and PCI CMD → NVMe memory-mapped properties → Admin Queue/Identify → I/O queues and namespaces.'),
[('PCI configuration 能被讀取，只證明目前可取得該 function 的組態資訊。MSE 控制 memory space 存取，BME 關係到裝置發起的 memory transactions；本例仍未完成這些正常操作條件。','Readable PCI configuration establishes access to that function’s configuration, not full operation. MSE controls memory-space access and BME concerns device-initiated memory transactions; these operating conditions are not established here.'),('接著才是 NVMe 自己的 CAP 能力、CC 配置與 CSTS 狀態，以及 queue 記憶體位置。PCI CMD、NVMe CC、Identify Controller 是不同介面的資料，不能用其中一個欄位替代另外兩層。','Next come NVMe CAP capabilities, CC configuration, CSTS status and queue-memory locations. PCI CMD, NVMe CC and Identify Controller belong to different interfaces; one field cannot substitute for the other layers.'),('這題不要求實際啟用硬體，而是建立盤點順序。只讀識別碼無法回答可用 LBA 格式、Sanitize 方法或 namespace 數量；那些問題還需要 NVMe 命令回覆。','This exercise establishes an inspection sequence without enabling hardware. PCI IDs alone do not answer LBA formats, Sanitize methods or namespace capacity; those require NVMe command responses.')],
'P12 P20 B36 B41 B42','P12:17 P20:19 B36:81-84 B41:86-89 B42:89-91')

case('init',('64-bit BAR 與 doorbell offset 要怎麼合起來？','How do a 64-bit BAR and doorbell offset combine?'),
('記錄工具只保存 BAR0，將 queue 3 的 doorbell 算到 4 GiB 以下。請從原始配置重新定位。','A trace tool retains only BAR0 and places queue 3’s doorbell below 4 GiB. Reconstruct the address from configuration.'),
[('BAR0=40000004h，類型已確認為 64-bit memory BAR；BAR1=00000002h。','BAR0=40000004h, confirmed as a 64-bit memory BAR; BAR1=00000002h.'),('CAP.DSTRD=2；查詢 queue identifier y=3 的 SQ tail 與 CQ head doorbell。','CAP.DSTRD=2; target queue identifier y=3 for SQ tail and CQ head doorbells.')],
('PCI configuration BAR0／BAR1 → 組成 register base → CAP.DSTRD → 依 queue ID 算 SQ／CQ doorbell offset。','PCI configuration BAR0/BAR1 → register base → CAP.DSTRD → SQ/CQ doorbell offsets for the queue ID.'),
[('先去掉 BAR0 屬性位再組合：base=(2<<32)|40000000h=0000000240000000h。BAR0 末尾的 4 表示屬性，不是映射起點多 4 bytes。','Remove BAR0 attribute bits before combining: base=(2<<32)|40000000h=0000000240000000h. The trailing four in BAR0 is an attribute, not four extra address bytes.'),('stride=4<<2=16 bytes。SQ3 offset=1000h+(2×3)×16=1060h；CQ3 offset=1000h+(2×3+1)×16=1070h。這裡 3 是 queue ID，不是 ring 目前第幾個 entry。','Stride is 4<<2=16 bytes. SQ3 offset is 1000h+(2×3)×16=1060h; CQ3 offset is 1000h+(2×3+1)×16=1070h. Three is the queue ID, not a current ring-entry index.'),('所以兩個地址是 0000000240001060h 與 0000000240001070h。這只定位暫存器；寫入的 tail／head 數值要由 queue 狀態決定，不能把地址或 byte offset 當作 doorbell 值。','The addresses are 0000000240001060h and 0000000240001070h. This locates registers only; tail/head values come from queue state, not from register addresses or byte offsets.')],
'P20 P21 P5 P6 B36','P20:19 P21:19 P5:10 P6:10-11 B36:81-84')

case('init',('RDY=1，為什麼不能直接說所有媒體已準備好？','Why does RDY=1 not always establish media readiness?'),
('初始化紀錄在 1 秒時看到 RDY=1，測試便要求所有 namespace 命令立即可用。這忽略了哪個模式？','An initialization trace sees RDY=1 after one second and requires every namespace command to work immediately. Which mode did it overlook?'),
[('Controller 支援並啟用 media-independent ready：CC.CRIME=1；CSTS.RDY=1、CFS=0。','Media-independent readiness is supported and enabled: CC.CRIME=1; CSTS.RDY=1, CFS=0.'),('CRTO.CRIMT=3、CRWMT=12；尚無證據顯示必要媒體均已就緒。','CRTO.CRIMT=3, CRWMT=12; readiness of all required media has not been established.')],
('讀 CAP 的 ready 能力、CC.CRIME、CSTS 與 CRTO；將等待目標分為 media-independent ready 與 required-media ready。','Read CAP readiness capabilities, CC.CRIME, CSTS and CRTO; distinguish media-independent readiness from readiness with required media.'),
[('CRIMT=3 與 CRWMT=12 使用 500 ms 單位，對應 1.5 seconds 與 6 seconds。它們是對應模式下的等待上限資訊，不是聲稱每次都必須花滿這些時間。','CRIMT=3 and CRWMT=12 use 500 ms units, giving 1.5 seconds and six seconds. They describe timeout bounds for their conditions, not mandatory durations for every initialization.'),('在本題啟用的模式，RDY 可先表示 controller 已能處理不依賴媒體的命令。測試必須區分哪些命令需要媒體，而不是把這個 RDY 觀察延伸成所有資料路徑皆已就緒。','In this enabled mode, RDY can first establish readiness for media-independent commands. A test must distinguish commands requiring media rather than extending that observation to every data path.'),('可再用 Identify CNS=08h 讀目標 namespace 的 NSTAT.NRDY：1 才表示該 namespace 已就緒。保存 CC.EN 設為 1 的起點及實際 command status，再與對應 timeout 比較。CFS=0 只是未回報 controller fatal status，不能補足缺少的媒體就緒證據。','Identify CNS=08h additionally reports target namespace NSTAT.NRDY: one means that namespace is ready. Retain the CC.EN=1 timing origin and actual command status when assessing the corresponding timeout. CFS=0 means no reported controller-fatal status, not proof of media readiness.')],
'B36 B41 B42 B57 B346','B36:81-84 B41:86-89 B42:89-91 B57:99 B346:420')

case('init',('裝置支援 x4，現在卻只有 x2？','Can an x4-capable device currently operate at x2?'),
('產品與能力欄位都說支援 x4，效能卻較低。要到哪裡查目前實際 lane 數？','The device and its capability report x4 support, yet performance is lower. Where is the actual lane count reported?'),
[('PCIe link 已 up；Link Capabilities 表示最大 x4；Link Status 的 NLW=2。','The PCIe link is up; Link Capabilities reports maximum x4, while Link Status NLW=2.'),('CLS 已記錄，但沒有完整路徑、payload 或 workload 的吞吐資料。','CLS is retained, but complete path, payload and workload throughput evidence is unavailable.')],
('沿 PCI capability 結構找到 PCI Express Capability，讀 Link Capabilities 與 Link Status；這不是 Identify CNS 的回覆。','Locate PCI Express Capability in PCI configuration, then read Link Capabilities and Link Status; this is not an Identify CNS response.'),
[('能力欄位描述可以支援的最大寬度，NLW 描述目前協商的寬度。因此兩個值並不矛盾：裝置能支援 x4，這次 link 使用 x2。','Capability describes supported maximum width; NLW describes negotiated width. The values are consistent: the device can support x4 while this link uses x2.'),('這足以指出可用 lane 數低於最大值，但無法單靠 endpoint 的欄位定位是 slot、上游 port、平台配置或其他原因。下一步應比對整條路徑的能力與協商結果。','This establishes fewer negotiated lanes than the maximum, but endpoint fields alone cannot locate the cause among slot, upstream port, platform configuration or other factors. Compare capabilities and negotiated states along the path.'),('CLS 是速度編碼，不能把原始代碼直接當成 GT/s；x2 也不是實測 bandwidth。應先把協商結果與能力分開，再用適用的速度定義及實際測量分析吞吐。','CLS is a speed encoding, not a raw GT/s quantity; x2 is not measured bandwidth either. Separate capability from negotiation before applying the applicable speed definition and throughput measurements.')],
'P55','P@3.8.5.6:28-29 P55:29')

case('init',('CQE 已出現，為什麼 MSI-X 沒通知？','Why might a CQE appear without an MSI-X notification?'),
('主機輪詢看到新 CQE，但中斷處理常式沒有執行。請判斷應先查媒體還是 interrupt 設定。','Polling finds a new CQE, but the interrupt handler does not run. Should the first check concern media or interrupt configuration?'),
[('MSI-X：MXE=1、FM=0、TS=7；目標 CQ 使用 vector 5，該 vector 的個別 mask=1。','MSI-X: MXE=1, FM=0, TS=7; the CQ uses vector five, whose individual mask is one.'),('新 CQE phase 與成功 status 均已確認；尚未解讀 PBA 或 coalescing 設定。','The new CQE phase and successful status are verified; PBA and coalescing have not yet been inspected.')],
('CQ 的 interrupt vector 關聯 → PCI MSI-X Message Control → Table entry mask／PBA → 必要時 Get Features FID=08h 與 per-vector 設定。','CQ interrupt-vector association → PCI MSI-X Message Control → table-entry mask/PBA → FID=08h and per-vector settings where relevant.'),
[('TS=7 表示 8 個 table entries，所以 vector 5 在範圍內。FM=0 只解除整體 function mask，沒有把個別 vector 的 mask 一併清掉。','TS=7 means eight table entries, so vector five is within range. FM=0 removes the function-wide mask, not individual vector masks.'),('vector 5 仍被遮罩，已提供中斷未送達的一個直接解釋。CQE 的成功 status 與中斷通知是不同觀察：不能因 handler 沒跑，就否定已經看見的完成結果。','Vector five remains masked, directly explaining suppressed delivery. Successful completion and interrupt notification are separate observations; an absent handler invocation does not negate the observed CQE.'),('若個別 mask 也已解除，才進一步看 pending、coalescing、主機路由等條件。不要把這個單一分支寫成「所有沒中斷都由 mask 引起」，也不要把 vector 數當成 queue 數。','If the individual mask is also clear, inspect pending state, coalescing and host routing. This branch does not explain every missing interrupt, and vector count must not be equated with queue count.')],
'P44 P45 P46 B543','P44:24-25 P45:25 P46:25 B543:541')

case('init',('PCIe AER 與 NVMe AER 是同一種錯誤紀錄嗎？','Are PCIe AER and NVMe AER the same mechanism?'),
('追蹤檔寫著 AER，但沒註明介面。兩次 PCIe status 都是 1，又能否說新增兩次 NVMe 錯誤？','A trace says AER without naming the interface. Can two PCIe status samples equal to one establish two new NVMe errors?'),
[('PCIe AERCES.RTS 兩次取樣均為 1；兩次之間沒有清除或 reset。','PCIe AERCES.RTS is one in both samples, with no clearing or reset between them.'),('另有 NVMe Asynchronous Event Request 的完成紀錄，但尚未比對時間與通知內容。','An NVMe Asynchronous Event Request completion also exists, but its timing and notification contents are not correlated.')],
('先辨識資料來自 PCIe Advanced Error Reporting extended capability，還是 NVMe Asynchronous Event Request completion。','First identify whether the data comes from the PCIe Advanced Error Reporting extended capability or an NVMe Asynchronous Event Request completion.'),
[('PCIe 的 AER 是 Advanced Error Reporting，這裡的 RTS 是 Replay Timer Timeout 狀態位；NVMe 的 AER 是非同步事件命令。縮寫相同，不代表資料結構、對象或事件意義相同。','PCIe AER means Advanced Error Reporting, with RTS here reporting Replay Timer Timeout status. NVMe AER is an asynchronous event command. Shared initials do not imply the same structure, target or event semantics.'),('RTS 是狀態位而非次數。未清除時連續看到 1，可能只是同一個仍保留的狀態，不能由兩次取樣算成發生兩次，更不能算成兩筆 NVMe command failure。','RTS is a status bit, not a counter. Without clearing, repeated ones may reflect one retained state; two samples do not establish two occurrences or two failed NVMe commands.'),('要關聯兩邊，需要各自完整紀錄、時間與裝置身分。PCIe 錯誤可幫忙分析傳輸問題，但不能直接指定是哪個 SQID／CID，也不能代替 CQE 或 NVMe log 的結果。','Correlation needs complete records, timing and device identity from both interfaces. PCIe status can inform transport diagnosis but does not identify an SQID/CID or replace CQE and NVMe-log outcomes.')],
'P60 P63 B99','P60:31-32 P63:33 B@5.2.2:209-216')
