"""Context-local terminology; renderer enforces per-document definition limits."""
TERMS = {
 'scope': ('作用範圍；一份設定由哪些物件共用，例如同一 NVM Set 或整個 subsystem。', 'The objects sharing a setting, such as one NVM Set or an entire subsystem.'),
 'RRL': ('Read Recovery Level；讀取錯誤復原等級，用來選擇讀取遇到困難時投入的復原程度。', 'Read Recovery Level; selects the recovery effort applied to difficult reads.'),
 'Fast Fail': ('RRL Level 15 的正式名稱，表示最少復原量；沒有在此定義固定完成時間。', 'The name of RRL level 15, providing minimum recovery without a fixed completion-time guarantee here.'),
 'NVM Set': ('一組在邏輯上與其他集合分開的非揮發性儲存，可包含多個 namespace；本篇用它界定共用 RRL 的範圍。', 'A logically separate collection of non-volatile memory that may contain multiple namespaces sharing an RRL.'),
 'NVM subsystem': ('NVMe 儲存子系統，可包含多個控制器及 namespace。', 'An NVMe storage subsystem that may contain multiple controllers and namespaces.'),
 'namespace': ('主機透過控制器存取的一份邏輯儲存空間。', 'A logical storage space accessed by a host through a controller.'),
 'controller': ('控制器；接收並處理主機 NVMe 命令的介面實體。', 'The interface entity that receives and processes host NVMe commands.'),
 'CTRATT': ('Controller Attributes；Identify Controller 中的控制器屬性位元欄位。', 'Controller Attributes; a bitmap in Identify Controller.'),
 'RRLVLS': ('Read Recovery Levels；CTRATT 中表示是否支援 RRL 功能的 bit。', 'Read Recovery Levels; the CTRATT bit reporting RRL support.'),
 'RRLS': ('Read Recovery Levels Supported；每個 bit 對應一個等級是否受支援。', 'Read Recovery Levels Supported; each bit reports support for its corresponding level.'),
 'NSETS': ('NVM Sets；CTRATT 中的 NVM Set 支援 bit。', 'NVM Sets; the CTRATT bit reporting NVM Set support.'),
 'ONCS': ('Optional NVM Command Support；Identify Controller 中的能力欄位，本篇只使用其中 SSFS。', 'Optional NVM Command Support; this report uses its SSFS capability bit.'),
 'SSFS': ('Save and Select Feature Support；表示是否支援 Set 的非零 SV 與 Get 的非零 SEL。', 'Save and Select Feature Support; indicates support for nonzero SV and SEL.'),
 'SEL': ('Select；Get Features 要求回傳目前值、預設值、已保存值或能力的選擇欄位。', 'Select; chooses current, default, saved or supported-capability information in Get Features.'),
 'SV': ('Save；Set Features 中提出保存設定要求的 bit。', 'Save; the Set Features bit requesting a saved setting.'),
 'NVMSETID': ('NVM Set Identifier；16-bit 集合識別碼，與 namespace 的 NSID 分開。', 'NVM Set Identifier; a 16-bit set identifier distinct from a namespace NSID.'),
 'CHANG': ('Changeable；回報該 Feature 是否有可變更的設定值。', 'Changeable; reports whether feature values can be changed.'),
 'NSSPEC': ('NS Specific；1 表示 namespace scope，0 本身不指定其他範圍。', 'NS Specific; one indicates namespace scope, while zero does not identify another scope.'),
 'SVBL': ('Saveable；回報該 Feature 的值是否可保存。', 'Saveable; reports whether the feature values can be saved.'),
 'LR': ('Limited Retry；I/O 命令中與限制復原相關的控制資訊，和 RRL 的互動由實作決定。', 'Limited Retry; I/O-command recovery control whose interaction with RRL is implementation-specific.'),
 'bitmap': ('位元集合；每個位置各表示一個項目是否成立，不把整個值當成項目總數。', 'A set of bits, each representing a separate yes/no property rather than an item count.'),
 'little-endian': ('低位 byte 先存；例如 11 80 組成 16-bit 值 8011h。', 'Least-significant byte first; bytes 11 80 form the 16-bit value 8011h.'),
 'byte offset': ('相對資料結構起點、以 byte 計算的距離；和項目索引或識別值不同。', 'A byte distance from a structure’s start, distinct from an entry index or identifier.'),
 'current': ('目前值；控制器現在使用的 Feature 設定。', 'The feature value currently in use.'),
 'default': ('預設值；本篇 RRL 預設為 Level 4，與目前值分開。', 'The default value; RRL defaults to level 4, independently of the current value.'),
 'saved': ('已保存值；成功要求保存的 Feature 設定，用於適用的恢復情境。', 'The saved feature value used in applicable restoration cases.'),
 'saveable': ('可保存；表示本 Feature 接受保存要求，不等同於目前值一定會在所有重設中改變。', 'Able to accept a save request; this alone does not determine every reset outcome.'),
 'buffer': ('資料緩衝區；本 Feature 的參數與回覆不需要額外的資料緩衝區。', 'A data buffer; this feature does not require one for its attributes.'),
 'DPTR': ('Data Pointer；命令中的資料指標，本 Feature 不用它傳遞設定。', 'Data Pointer; unused for this feature’s settings.'),
 'CQE': ('Completion Queue Entry；完成佇列中回報命令執行結果的項目。', 'Completion Queue Entry; reports a command result.'),
 'domain': ('subsystem 內的劃分單位；此處只用來判斷一次重設是否涵蓋整個 subsystem。', 'A subdivision of a subsystem, used here to determine whether a reset covers the entire subsystem.'),
 'power cycle': ('斷電再供電的電源循環，與單純重設某個控制器分開。', 'A removal and restoration of power, distinct from resetting one controller.'),
}
