"""Q321–328: missing data-I/O reasoning, without repeating feature/queue lessons."""
from scripts.nvme_qa_extension import question
from scripts.nvme_qa_model import COMMON, REFS, QUESTIONS, pair

REFS.update({
 'iofields':'N|3.3.4, 3.3.6 (data pointers, SLBA, NLB, FUA and completion)|48-51,53-56|53–54, 59, 68, 70–71, 76',
 'flushdata':'B|7.2–7.2.1|593|',
 'atomicdata':'N|2.1.4–2.1.4.6|15-21|4–10',
 'comparedata':'N|3.3.1–3.3.1.1|27-30|24, 26–27, 31',
 'verifydata':'N|3.3.5–3.3.5.1|51-53|61–62, 66',
 'deallocateddata':'N|3.3.3–3.3.3.3, 3.3.8–3.3.8.2|44-48,57-61|45–47, 49, 83, 88–89',
 'pidata':'N|2.1.5, 5.3.1.1 (STS=0), 5.3.2.1–5.3.2.2, 5.3.3|21-22,131,141-145,151-152|11–12, 155, 174–175',
 'copydata':'N|3.3.2–3.3.2.3, 3.3.2.5 (Formats 0h/1h; cross-namespace formats only for contrast)|30-40,43-44|34–35, 39–40, 42–43',
 'uncorrectabledata':'N|3.3.7–3.3.7.1|56-57|77–80',
 'mediaerrors':'B|4.2.3 (Media and Data Integrity Errors only)|180-181|107',
})

COMMON['data_io']={**COMMON['command'],
 9:pair('一般 I/O 的成功 CQE 不是 Asynchronous Event。若另外發生符合定義的健康警告或錯誤事件，再依事件條件、AEC 設定及等待中的 AER 回報；故意製造一次 Compare 不相符，不能直接要求出現硬體故障通知。 || An ordinary successful I/O CQE is not an asynchronous event. Separately qualifying health/error events use their own conditions, AEC settings and outstanding requests. An intentional comparison mismatch does not by itself require a hardware-failure notice.'),
 10:pair('保留原始命令、CQE、資料與 metadata，再按實際命令種類核對 SMART 計數。More=1 時讀取相符的 Error Information；More=0 不代表禁止建立 entry，也不是每個失敗都必須新增 entry。計數或 Log 不能代替資料內容與範圍的核對。 || Preserve the request, completion, data and metadata, then interpret SMART counters for the actual command. More=1 calls for correlated Error Information; More=0 neither prohibits an entry nor makes one mandatory for every failure. Logs and counters do not replace checking data and ranges.'),
 11:pair('一般 Read、Write、Compare 或 Copy 不是 PEL 的逐筆命令歷史。若操作期間另有受支援的硬體、健康或電源事件，才依該事件的記錄條件檢查 PEL；不能因為有一筆失敗 CQE，就要求一筆同名 Persistent Event。 || PEL is not a per-command Read/Write/Compare/Copy trace. Check separately supported hardware, health or power events under their recording conditions; a failed CQE alone does not require a matching named persistent event.'),
 12:pair('Controller Level Reset 使原 I/O queues 與未完成命令的追蹤關係失效，但不會替 Host 撤銷已發生的資料修改。恢復後重建 queue，再查受影響 LBA；未完成寫入允許出現哪些結果，仍要配合有效原子單位、邊界及命令規則判斷。 || Controller Level Reset invalidates I/O queues and outstanding-command tracking without rolling back prior data changes. Rebuild queues and inspect affected LBAs. Permitted interrupted-write results depend on effective atomic units, boundaries and the command.'),
 13:pair('Subsystem Reset 後，受影響的 controllers 都要恢復命令通道。這不是清除 namespace 內容的操作，也不是重送所有舊 I/O 的理由；先確認操作結果及共用資料是否已被其他路徑更新，再決定後續動作。 || Restore command paths on all controllers affected by subsystem reset. Reset neither erases namespace contents nor authorizes blindly replaying every old I/O. Establish operation results and concurrent shared-data changes first.'),
 14:pair('Power Cycle 後，先分清「命令已成功完成且資料符合持久性要求」與「命令在寫入途中被中斷」。前者核對已提交到非揮發媒體的資料；後者依斷電原子性與命令專屬規則判讀。另行重新查詢 Feature，不能把暫存設定的恢復方式當成資料保留規則。 || After a power cycle, distinguish a successful persistent write from an interrupted write. Verify committed data in the former case and power-fail atomicity/command-specific outcomes in the latter. Rediscover feature state separately; configuration restoration is not a data-retention rule.'),
 15:pair('I/O 以指定 namespace 及 LBA 範圍為主要對象。共享 namespace 的其他 controllers 會存取同一份邏輯資料，因此讀回驗證前要排除其他寫入者。命令從哪條 queue 送入，不能用來推論資料只屬於該 controller。 || I/O targets a namespace and LBA range. Other controllers attached to a shared namespace access the same logical data, so exclude concurrent writers before readback verification. Submission queue ownership does not make the data private to that controller.'),
}

def q(n,title,refs,related,body,overrides=None):
    question(n,title,'data_io',refs+['idctrl','idns','iofields','mediaerrors'],body,overrides)
    QUESTIONS[-1]['related']=related

q(321,"一筆 Read／Write 的長度合法嗎？如何一起檢查 MDTS、NLB 與 Namespace 範圍？ || Is a Read/Write length valid across MDTS, NLB and namespace bounds?",
 ['cap','pointers'],[49,276,279,326],'''
長度是否合法，需要同時回答三件事：命令指定幾個 logical blocks、Host 要傳多少 bytes，以及最後一個 LBA 是否仍在 namespace 內。PRP 清單能描述這些 bytes，不代表傳輸大小就一定符合命令限制。 || Validate block count, host-transfer bytes and the final namespace LBA separately. A PRP list capable of describing the buffer does not establish a legal transfer size.
本題限定一般 Read／Write，先假設無其他命令擴充。命令作用於 NSID 指定的 namespace；MDTS 限制 Host 與 controller 之間的資料傳輸，NSZE 則界定合法 LBA，兩者衡量的對象不同。 || Consider ordinary Read/Write without other command extensions. NSID selects the namespace; MDTS limits host/controller transfer size while NSZE bounds LBA addresses.
Identify Controller 提供 MDTS 與 CTRATT.MEM，CAP.MPSMIN 提供最小記憶體頁面大小；Identify Namespace 提供 NSZE、目前 LBA Format、LBADS、MS 及 metadata 配置。MDTS 非零時，上限為 2^MDTS × 2^(12+MPSMIN) bytes，不能改用目前 CC.MPS。 || Read MDTS, CTRATT.MEM, CAP.MPSMIN, NSZE and the selected LBA format, including LBADS/MS and metadata layout. A nonzero MDTS gives 2^MDTS × 2^(12+MPSMIN) bytes, not a limit based on current CC.MPS.
SLBA 是起始位址；Read／Write 的 NLB 採 zero-based 編碼，所以實際區塊數為 NLB+1，最後一個 LBA 為 SLBA+NLB。LBADS 表示每個資料區塊有 2^LBADS bytes。若 metadata 與資料交錯傳輸且 MEM=0，MDTS 計算需包含 metadata；MEM=1 則排除 metadata。 || SLBA is the starting address, NLB+1 is the block count, and SLBA+NLB is the final LBA. Each data block has 2^LBADS bytes. Interleaved metadata counts toward MDTS when MEM=0 and is excluded when MEM=1.
先固定 namespace 格式並計算 LBA 範圍，再算實際傳輸 bytes，最後才配置 PRP／SGL。教學假設 MPSMIN=0、MDTS=5、資料4096 bytes、交錯 metadata 8 bytes（本例不使用 PI）、MEM=0：NLB=31 代表32個區塊，需傳131328 bytes，超過131072-byte上限；只算使用者資料就會漏掉256 bytes。 || Fix the namespace format, validate the LBA range, calculate transfer bytes, then construct pointers. With hypothetical MPSMIN=0, MDTS=5, 4096-byte data, 8-byte interleaved metadata without PI and MEM=0, NLB=31 requires 131328 bytes rather than 131072; ignoring metadata misses 256 bytes.
在同一假設下，31個區塊需127224 bytes，可以符合 MDTS；命令的 NLB 應填30。這只證明長度條件成立，還要滿足 NSID、存取權限、指標與 PI 等條件，成功 CQE 才代表這次 I/O 正常完成。 || Under that example, 31 blocks require 127224 bytes and encode NLB=30. This satisfies MDTS only; namespace access, pointers and any PI must also be valid for successful completion.
超過 MDTS 會以 Invalid Field in Command（SCT/SC=0/02h）中止；LBA 範圍超過 NSZE 則是 LBA Out of Range（0/80h）。例如 NSZE=1024、SLBA=1000、NLB=31，最後 LBA=1031，已超過1023。驗證特定錯誤時，一次只留下其中一種違規。 || Exceeding MDTS requires Invalid Field (0/02h); exceeding namespace bounds uses LBA Out of Range (0/80h). NSZE=1024, SLBA=1000 and NLB=31 end at LBA1031 beyond1023. Isolate one invalid condition when testing an exact status.
MDTS=0 只表示沒有 MDTS 這項上限，不會取消 NLB 的編碼範圍、namespace 邊界或命令專屬限制。也不能把 MDTS 直接套到不傳送 Host 資料的 Verify、Write Zeroes 或 Write Uncorrectable。 || MDTS=0 removes this particular limit, not NLB encoding, namespace bounds or command-specific limits. Do not apply MDTS directly to Verify, Write Zeroes or Write Uncorrectable, which do not transfer host payload data.
先檢查是否把 CC.MPS 當成 MDTS 的基準、漏算 NLB 的加1，或使用 Format 前的 LBA 大小。這三種錯誤都可能讓看似相同的 I/O 長度得到不同結果。 || First check for using CC.MPS as the MDTS base, omitting NLB+1 or retaining an obsolete pre-format LBA size.
''')

q(322,"Write 已成功，資料就一定耐斷電嗎？Flush 與 FUA 各保證什麼？ || Does successful Write imply power-loss persistence, and what do Flush and FUA guarantee?",
 ['flushdata','vwc','atomicdata'],[38,39,60,182],'''
Write 成功表示命令完成，但在允許使用揮發性寫入快取的情況下，資料可能仍在快取。持久性要判斷資料是否已符合非揮發儲存要求，不能只用一般讀回成功或 CQE Success 代替證明。 || Write success completes the command, but enabled volatile caching may retain the data. Persistence requires the applicable nonvolatile-storage guarantee; ordinary successful readback or a CQE alone is insufficient.
Write.FUA 作用於該筆命令的資料及 metadata。Flush 則作用於指定 namespace 中，在 Flush 提交前已由 controller 完成的命令；它不是自動排序其他仍在執行中命令的全域屏障。 || Write FUA applies to that command’s data and metadata. Flush covers commands for its namespace completed by the controller before Flush submission; it does not automatically order all still-running commands.
先確認 VWC.VWCP 是否有揮發性快取、FID06h.WCE 是否啟用，以及 VWC.FB 是否允許 Flush 的 NSID=FFFFFFFFh。namespace 的 VWCNP 也可能指出該 namespace 沒有揮發性快取，不能只看 controller 的整體宣告。 || Check VWC.VWCP, current FID06h.WCE, VWC.FB broadcast support and applicable namespace VWCNP. Controller-wide cache presence does not imply a cache for every namespace.
Write 的 FUA=1 要求其資料及 metadata 在命令完成前提交至非揮發媒體；FUA=0 本身不增加要求。Flush 使用 NSID 選範圍，其他命令專屬欄位為 Reserved。FB=11b 才表示廣播 Flush 涵蓋提交端已附加的 namespaces。 || Write FUA=1 commits its data and metadata before completion; FUA=0 adds no requirement. Flush selects scope with NSID and has reserved command-specific fields. FB=11b permits broadcast Flush over namespaces attached to the submitting controller.
要保證一組已提交寫入的持久性，Host 可先等所有目標 Write 成功，再對正確 NSID 提交 Flush，最後等 Flush 成功。假設 Write A 與 Flush 同時提交，不能因 Flush 比 A 先完成，就宣告 A 已被涵蓋。另一種做法是讓各筆 Write 自己帶 FUA=1，並等待各筆成功。 || For a batch, wait for the target Writes to succeed, submit Flush for the correct NSID and wait for its success. Concurrently submitting Write A and Flush does not establish that an earlier Flush completion covers A. Alternatively, use FUA=1 on each Write and await each success.
符合範圍與先後條件的 Flush 成功後，所涵蓋資料須具備持久性。沒有或未啟用揮發性快取時，Flush 沒有效果；若也沒有進行中的 Sanitize，仍須成功完成。這不是不支援 Flush 的錯誤。 || Successful Flush makes covered data persistent. Without a present/enabled volatile cache it has no effect and must succeed when no Sanitize is in progress; this is not an unsupported-Flush error.
FB=10b 時使用 NSID=FFFFFFFFh，須回 Invalid Namespace or Format（0/0Bh）；Base 2.4 controller 不得用 FB=00b 的舊版未定義廣播行為。進行中的 Sanitize 有自己的命令限制，不能把平常無快取時的成功要求直接套過去。 || Broadcast Flush with FB=10b requires Invalid Namespace or Format (0/0Bh). Base2.4 controllers cannot use the old FB=00b undefined broadcast behavior. Sanitize in progress has separate command rules.
FUA 與 Flush 不會增加原子寫入單位。原子性限制中斷或競爭時可觀察到哪些資料組合；持久性則約束成功後是否可因失電退回舊資料。應把命令時間線、Current.WCE、FUA 與 Flush 的涵蓋範圍放在一起判讀。 || FUA/Flush do not enlarge atomic write units. Atomicity constrains interrupted or concurrent data combinations; persistence constrains post-success loss of committed data. Correlate timing, WCE, FUA and Flush coverage.
先檢查 Flush 是否在目標 Write 完成之後才提交，以及是否指定同一 namespace。只看到一筆 Flush Success，還無法知道它是否涵蓋這次正在調查的資料。 || First establish that Flush was submitted after the target Write completed and addressed the same namespace. A Flush Success without that relationship does not establish coverage.
''')

q(323,"原子單位足夠，為什麼跨邊界的 Write 仍可能不具整筆原子性？ || Why can a small Write lose whole-command atomicity when it crosses a boundary?",
 ['atomicdata','nvmfeat'],[60,322],'''
判斷原子性不能只比較 Write 長度與某個最大值，還要確認 namespace 使用哪種原子模式，以及起訖 LBA 是否跨越邊界。長度相同的兩筆 Write，只因起點不同，就可能得到不同保證。 || Atomicity depends on effective size, namespace atomicity mode and boundary alignment. Equal-length Writes with different starting LBAs can have different guarantees.
正常原子性限制與其他 Read／Write 交錯時可見的結果；斷電原子性則限制寫入被失電或錯誤中斷時的新舊資料組合。本題的兩種保證都不是「成功之後必定持久」的替代說法。 || Normal atomicity constrains inter-command results; power-fail atomicity constrains old/new data after interruption by power failure or error. Neither is a substitute for post-success persistence.
先查 NSFEAT.NSABP 與 MAM。NSABP 決定 namespace 的 NAWUN／NAWUPF 是否有效；有效欄位若為0，表示退回 controller 的 AWUN／AWUPF，非零值則按 zero-based 編碼加1。MAM=0 是 Single，MAM=1 是 Multiple Atomicity Mode；正常原子性另確認 FID0Ah.DN 沒有解除該要求。 || Check NSABP, MAM and FID0Ah.DN. When namespace units are supported, a zero NAWUN/NAWUPF falls back to AWUN/AWUPF; nonzero values encode count−1. MAM distinguishes Single from Multiple Atomicity Mode, and DN can remove normal-atomicity requirements.
NABSN 與 NABSPF 分別定義正常及斷電邊界大小；0表示沒有這項邊界，非零編碼需加1才是區塊數。NABO 是第一個邊界的 LBA，不是數量欄位。解碼後的邊界位置為 NABO+y×邊界大小，y 為非負整數。 || NABSN/NABSPF define normal/power-fail boundary sizes: zero means no boundary, while nonzero encodings decode by adding one. NABO is an LBA offset, not a count. Decoded boundaries occur at NABO+y×size for nonnegative integer y.
教學假設 NSABP=1、MAM=0、DN=0、AWUN=AWUPF=0、NAWUN=7、NAWUPF=1、NABSN=NABSPF=15、NABO=0。正常單位是8個區塊，斷電單位是2個，邊界每16個區塊出現。Write 範圍14～15沒有跨界；改成15～16便跨過 LBA16。 || Assume NSABP=1, MAM=0, DN=0, baseline AWUN=AWUPF=0, NAWUN=7, NAWUPF=1, boundary encodings15 and offset0. The effective units are8 and2 blocks, with16-block boundaries. LBAs14–15 stay within one boundary region;15–16 cross LBA16.
正常完成的 Write 回報 Success；但若要驗證中斷時的原子性，還需讀回資料。前例14～15的2-block Write，在符合斷電原子性前提且被中斷時，後續讀回須是整組舊資料或整組新資料，不能一個新、一個舊。15～16則沒有這項整筆2-block保證。若另採合法的 Multiple Atomicity 配置，跨界命令按邊界拆成各自原子的子範圍，仍不等於整筆一起原子更新。 || A normally completed Write reports Success; interruption atomicity additionally requires readback evidence. An interrupted2-block Write at14–15 must yield all old or all new data under the stated power-fail conditions. At15–16 it lacks that whole2-block guarantee. A valid Multiple Atomicity configuration instead makes each boundary-delimited subrange atomic, not the whole crossing command.
一般 Write 超過原子單位或跨界，不代表 controller 一定要拒絕；命令仍可能成功，只是保證範圍不同。不能將 fused Compare-and-Write 的 Atomic Write Unit Exceeded 條件，直接套到所有 Write。 || Exceeding an atomic unit or crossing a boundary does not universally require rejection of an ordinary Write. It can succeed with different guarantees; fused-operation Atomic Write Unit Exceeded rules are not universal Write rules.
Format 後應重新取得 namespace 的原子欄位，不能沿用舊格式下的 bytes 換算。若同時測試其他寫入者，還要保留命令交錯證據；單次剛好讀到完整新資料，只證明這次結果，不能證明超出規範宣告的更大原子單位。 || Rediscover namespace atomic fields after Format and use the new LBA size. Capture concurrency when testing normal atomicity. One intact readback does not establish a larger guarantee than advertised.
先確認目前比較的是原始編碼還是解碼後的區塊數，再檢查邊界。尤其 NAWUN=0、NABSN=0 與 NLB=0 分別代表退回基準、無邊界與1個區塊，不能套用同一個加1公式。 || First separate raw encodings from decoded counts. NAWUN=0, NABSN=0 and NLB=0 respectively mean baseline fallback, no boundary and one block; they do not share one decoding rule.
''')

q(324,"Read、Compare 與 Verify 成功，各能證明什麼？ || What do successful Read, Compare and Verify actually prove?",
 ['comparedata','verifydata','smart'],[50,198,326],'''
這三種命令回答不同問題：Read 將資料交給 Host；Compare 用 Host 提供的預期內容做比對；Verify 檢查儲存資訊的完整性，不將資料傳回 Host。Verify 成功不能證明資料等於應用程式心中的預期值。 || Read returns data, Compare tests a host-supplied expected buffer, and Verify checks stored-information integrity without returning payload. Verify success does not establish equality with an application’s expected value.
三者都指定 namespace 與 LBA 範圍，但資料方向不同。Compare 的 buffer 由 Host 傳入，Read 的 buffer 接收資料，Verify 則沒有這份 Host 資料傳輸；不能用相同 buffer 期待三者留下同樣結果。 || All select a namespace/range, but Compare consumes host data, Read fills a host buffer and Verify transfers no host payload. They therefore do not produce identical buffer evidence.
先查對應 Opcode 的支援宣告與 Commands Supported and Effects。Verify 的大小需另外讀 VSL 及 ONCS.NVMVFYS：非零 VSL 搭配該支援位元，可表示建議最大值，而非一律拒絕超限。MDTS 不直接限制沒有 Host 資料傳輸的 Verify。 || Discover opcode support/effects and Verify’s VSL/NVMVFYS rules. A nonzero VSL can be a recommended maximum under the advertised variant, not universally a rejection threshold. MDTS does not directly limit payload-free Verify.
SLBA／NLB 選範圍，PRCHK 選要檢查的 PI。Compare 的非 PI metadata 也參與比對，PI 則依檢查規則處理。Verify 的 PRACT 必須為0；其 FUA=1 要求先提交相關快取，再對已提交至非揮發媒體的內容執行 Verify，仍不建立其他命令的提交順序。 || SLBA/NLB select the range and PRCHK selects PI checks. Compare includes non-PI metadata in equality checks. Verify requires PRACT=0; FUA=1 commits associated cached data before verifying nonvolatile contents, without ordering other commands.
教學假設 LBA100 的正確內容是 A。先等寫入 A 完成，Read 取得 A；Compare 的輸入 A 應可成功，輸入不同的 B 應得到 Compare Failure。Verify 只檢查所存資訊是否可通過完整性檢查，所以即使應用程式原本想存 B，它仍可能成功。 || With valid data A at LBA100, wait for the Write, read back A, then compare against A and against different B. The latter should report Compare Failure. Verify may still succeed even if the application intended B, because it checks stored integrity rather than that expectation.
Read Success 配合收到的 bytes，才可確認讀回內容；Compare Success 證明選定範圍與提供的比較資料相符；Verify Success 證明執行了所要求的完整性檢查。若有其他 controller 同時改寫同一範圍，三次不同時點的結果不能直接互相比較。 || Read success plus returned bytes establishes readback; Compare success establishes equality with its supplied data; Verify success establishes the requested integrity verification. Concurrent writes can invalidate comparisons across separate observations.
內容不符使用 Compare Failure（2/85h），不等於 Unrecovered Read Error（2/81h）。Verify.PRACT 非零須回 Invalid Field（0/02h）；已偵測到的 PI 錯誤另用對應的資料完整性 Status。規範不要求同一媒體問題讓 Verify 與 Read 回傳完全相同的錯誤代碼。 || Mismatch uses Compare Failure (2/85h), not Unrecovered Read Error (2/81h). Verify with nonzero PRACT requires Invalid Field (0/02h); detected PI failures have their own integrity statuses. Verify and Read need not report the same error for the same media problem.
Verify 沒有把資料送回 Host，但其讀取或檢查的資料仍須計入 SMART 的 Data Units Read。這個計數表示規範定義的工作量，不代表 Host 一定收到那些 bytes。比對時也要考慮計數的單位與向上取整。 || Data read or integrity-checked by Verify must contribute to SMART Data Units Read despite no host payload transfer. The counter represents defined work, not necessarily delivered bytes; account for units and rounding.
先釐清要證明的是「可讀」、「等於某份內容」還是「通過完整性檢查」，再選命令。若問題是應用程式資料不對，只做 Verify 不足以排除寫入錯誤內容的可能。 || First choose readability, equality or integrity as the claim. Verify alone cannot exclude an application writing the wrong but internally valid content.
''', {10:'Verify 的讀取及完整性檢查工作須計入 Data Units Read，即使沒有 Host 資料傳輸。錯誤細節仍依 CQE 的 More 及 Error Information 規則關聯；不是每次正常檢查都新增 Error entry。 || Verify reads/integrity checks contribute to Data Units Read even without host payload transfer. Correlate failures through More/error-log rules; normal verification does not require an error entry.'})

q(325,"Write Zeroes 與 Deallocate 之後，Read 一定回全零嗎？ || Must reads return zero after Write Zeroes or Deallocate?",
 ['deallocateddata','nvmfeat'],[64,127],'''
Write Zeroes 要讓後續成功讀取呈現全零；Dataset Management 的 Deallocate 則提供不再需要資料的資訊，controller 可選擇不採取動作。兩者的成功完成不能直接視為相同效果，也都不是敏感資料已不可復原的證明。 || Write Zeroes requires zero-valued successful readback; Dataset Management Deallocate supplies a no-longer-needed-data attribute that the controller may choose not to act on. Neither success is proof of irreversible data sanitization.
本題比較指定 namespace 中的 LBA 範圍，先以 NSZ=0 的一般 Write Zeroes 為例。整個 namespace 清零的 NSZ=1 有額外條件，不可用普通範圍操作的成功去推論一定支援。 || Compare range operations in one namespace, initially using ordinary Write Zeroes with NSZ=0. Whole-namespace NSZ=1 has extra requirements and is not implied by range-operation success.
先查 Write Zeroes／Dataset Management 支援、namespace 的 DLFEAT.DRB 與 NSFEAT.DAE，再讀 FID05h.DULBE。DRB 描述解除配置後的讀取值；DAE 表示能否回報解除配置或未寫入錯誤；DULBE 決定是否啟用該錯誤。 || Check command support, DLFEAT.DRB, NSFEAT.DAE and current FID05h.DULBE. DRB defines deallocated read values, DAE advertises the error capability, and DULBE enables that error.
Write Zeroes 的 NLB 採 zero-based，DEAC 表示 Host 是否請求解除配置；Dataset Management 的 NR 也是 zero-based，但每筆 Range 的 Length in Logical Blocks 是1-based數量。兩種命令都需區分「欄位的編碼」與「實際處理多少區塊」。 || Write Zeroes NLB and Dataset Management NR are zero-based; each Dataset Management range length is a one-based count. DEAC requests deallocation. Decode each field according to its own definition.
教學假設 DRB=001b、DAE=1，先完成一筆合法 Write Zeroes，再讀同一範圍。若 controller 有解除配置且 DULBE=1，Read 應回 Deallocated or Unwritten Logical Block；若 DULBE=0 且讀取成功，則回全零。DEAC=0 也不代表禁止 controller 在仍能保證全零讀值的情況下解除配置。 || Assume DRB=001b and DAE=1. After valid Write Zeroes, deallocated blocks with DULBE=1 produce Deallocated or Unwritten Logical Block. With DULBE=0, successful readback is zero. DEAC=0 does not prohibit deallocation when the required zero-read behavior is preserved.
不能把「Write Zeroes 後 Read 得到 DULBE 錯誤」直接判成清零失敗。另一方面，Dataset Management Success 也不能證明每個範圍真的被解除配置；其處理限制與允許不採取動作的規則，需和讀回結果分開判讀。 || A DULBE error after Write Zeroes is not by itself a zeroing failure. Dataset Management success likewise does not prove every range was deallocated; distinguish processing rules from actual effects.
已解除配置或未寫入，且錯誤已受支援並啟用時，適用 Read 類命令須回 Deallocated or Unwritten Logical Block（2/87h）。若 NSZ=1 但 DEAC=0，或 namespace 不支援解除配置後回全零，Write Zeroes 須回 Invalid Field（0/02h）。 || Supported/enabled DULBE requires 2/87h for applicable reads of deallocated/unwritten blocks. Write Zeroes with NSZ=1 but DEAC=0, or without zero-valued deallocated reads, requires Invalid Field (0/02h).
DULBE 停用時，真正已解除配置的區塊按 DRB 回全00h或全FFh；DRB=000b 可為其中之一，但同一區塊在再次寫入前必須保持確定的讀值。Read 或 Verify 不會把該區塊變回已配置。 || With DULBE disabled, genuinely deallocated blocks return all00h or allFFh according to DRB. DRB=000b permits either, but a block’s returned value must remain deterministic until a write. Read/Verify do not allocate it.
先讀回 DULBE 並確認 DRB，再分辨測的是 Write Zeroes 的讀值保證，還是 Dataset Management 的解除配置效果。把「命令成功」、「真的解除配置」及「後續讀取結果」分成三個觀察，才不會互相代替。 || First establish DULBE/DRB, then distinguish command success, actual deallocation and subsequent read behavior. Those three observations are not interchangeable.
''')

q(326,"PI 檢查為什麼沒有抓到錯誤？以 Type 1、16-bit Guard 格式逐步判讀 || Why did PI checking miss an error? A Type1, 16-bit Guard example",
 ['pidata'],[120,279,284],'''
Protection Information（PI）用來檢查資料完整性及區塊對應關係，但「namespace 有 PI」不代表每次命令都會檢查所有欄位。格式、PRACT、PRCHK 與 tag 的特殊值，共同決定哪些檢查真的發生。 || PI protects integrity and block association, but formatting a namespace with PI does not enable every check on every command. Format, PRACT, PRCHK and special tag values determine actual processing.
本題限定16-bit Guard、STS=0、Type 1 的8-byte PI 範例；不把這個位元配置套到32-bit或64-bit Guard。Guard 占2 bytes，Application Tag 占2 bytes，Reference Tag 占4 bytes，三者位於該區塊的 metadata。 || Limit the example to Type1,16-bit Guard, STS=0 and8-byte PI, not32/64-bit Guard layouts. Guard, Application Tag and Reference Tag occupy2,2 and4 metadata bytes respectively.
Identify 的 DPC 告訴你支援哪些保護配置，DPS 表示目前使用的保護類型，LBA Format 的 MS 表示 metadata 大小；另確認使用中的 PI Format 與 STS。只查支援能力，卻沒查目前格式，可能會拿錯長度或錯誤 tag 配置來驗證。 || DPC advertises protection capabilities, DPS selects the current protection type, and MS gives metadata size. Also establish the active PI format and STS; capabilities alone do not identify the current layout.
PRCHK 的 bit2、bit1、bit0 分別控制 Guard、Application Tag、Reference Tag 檢查；PRACT 控制 PI 的傳遞、產生或移除。本題啟用 Reference Tag 檢查時，Type 1 的 ILBRT／EILBRT 必須符合 SLBA 的低位元；Application Tag Mask 中的1表示要比較該位元，0表示遮蔽。 || PRCHK bits2/1/0 select Guard/Application/Reference checks; PRACT controls passing, generation or removal. With reference-tag checking enabled, Type1 ILBRT/EILBRT must match the relevant low SLBA bits. Application-tag mask bits set to1 are compared; zero masks them.
教學假設資料4096 bytes、MS=8、PRACT=0、PRCHK=111b，先準備正確 PI，並避免 Application Tag=FFFFh 這個免檢查值。先確認合法案例成功，再分別只改 Guard、Application Tag 或 Reference Tag，並保持其他欄位及資料不變，才能分辨是哪項檢查回報錯誤。 || With hypothetical4096-byte data, MS=8, PRACT=0 and PRCHK=111b, first use valid PI and avoid the FFFFh application-tag escape. Establish a valid baseline, then corrupt one Guard/Application/Reference field at a time while preserving other inputs.
合法基準案例應成功完成；Read 的資料與 metadata 則依 PRACT 決定傳回內容。在此格式且 MS=8 時，Write.PRACT=1 由 controller 產生並附加 PI，Host 不提供那8 bytes，PRCHK 會被忽略；Read.PRACT=1 則先按條件檢查，再移除 PI，只把資料交給 Host。若 MS 大於 PI 大小，不能再假設整份 metadata 都從 Host buffer 消失。 || The valid baseline should complete successfully; PRACT determines which data/metadata Read returns. With MS equal to the8-byte PI size, Write.PRACT=1 generates/appends PI without those host bytes and ignores PRCHK; Read.PRACT=1 checks as applicable, then strips PI before returning data. If MS exceeds PI size, the full metadata does not simply disappear from the host buffer.
已啟用且未被特殊值停用的檢查，失敗時分別回 Guard 2/82h、Application Tag 2/83h、Reference Tag 2/84h。本題若啟用該檢查，而 Type 1 命令中的 ILBRT／EILBRT 本身不符合 SLBA，則屬 Invalid Protection Information（1/81h）；這和資料中存放錯誤 tag 是不同條件。 || Enabled, non-escaped check failures use Guard2/82h, Application2/83h or Reference2/84h. With that check enabled, a Type1 command ILBRT/EILBRT inconsistent with SLBA instead requires Invalid Protection Information (1/81h), distinct from bad stored tags.
Type 1／Type 2 的 Application Tag=FFFFh 會停用 PI 檢查，即使 PRCHK 已開啟。因此，「故意放錯 Guard 卻成功」可能是 PRACT 讓 controller 重建 PI，或 tag 的特殊值停用了檢查；不能直接判定 controller 沒做資料保護。 || Type1/Type2 Application Tag=FFFFh disables PI checks despite PRCHK. An intentionally bad Guard can therefore succeed because PRACT regenerates PI or a special tag suppresses checking, rather than because the controller omitted a required check.
先確認 metadata 是否真的由 Host 傳入、PRACT 的處理方式，以及 tag 是否用了免檢查值。接著再看對應 PRCHK 位元與 mask，而不是只盯著錯誤 CQE 是否出現。 || First establish whether host PI was transferred, how PRACT processed it and whether a tag escaped checking. Then inspect the selected checks and masks before interpreting the absence of an error CQE.
''')

q(327,"Copy 失敗後，CQE.DW0 能告訴我哪些資料已經複製？ || What does CQE.DW0 establish after a Copy failure?",
 ['copydata','atomicdata'],[112,323],'''
Copy 可以在 controller 內把多個來源範圍接成一段連續目的資料，減少經過 Host 的資料搬移。但失敗時可能已複製部分資料，不能把錯誤 CQE 當成整筆回復原狀的交易。 || Copy assembles multiple source ranges into a consecutive destination without routing payload through the host. Failure may leave partial effects; its CQE does not provide transactional rollback.
本題先限定同一 namespace、Copy Descriptor Format 0h 的範例。NSID 指向目的 namespace，SDLBA 指向目的起點；來源範圍由 descriptor 順序排列。跨 namespace 的 Formats 2h／3h 還有額外規則，不能只換一個 NSID 就照抄。 || Use a same-namespace Format0h example. NSID selects the destination namespace and SDLBA its start; descriptor order determines destination placement. Cross-namespace Formats2h/3h add rules beyond merely changing NSID.
先確認 Copy 與 descriptor format 的支援，再讀 MSRC、MSSRL、MCL。MSRC 採 zero-based，限制來源範圍筆數；MSSRL 限制單一來源的區塊數；MCL 限制全部來源的總區塊數。目的端的原子單位另行限制可獲得的寫入原子性。 || Discover Copy/descriptor support, MSRC, MSSRL and MCL. MSRC is a zero-based source-range count; MSSRL and MCL bound per-range and total block counts. Destination atomicity remains a separate constraint.
命令的 NR 與每筆來源 NLB 都採 zero-based，先解碼再加總。教學假設 NR=1，兩筆來源 NLB 分別是3與1，表示4+2個區塊；若 SDLBA=1000，依序寫入1000～1003與1004～1005，而不是各自從1000開始。 || Decode zero-based NR and source NLB before summing. NR=1 with source NLB values3 and1 describes4+2 blocks. SDLBA=1000 places them at1000–1003 and1004–1005, not both at1000.
先確認來源與目的範圍有效、未重疊且符合三項 Copy 限制，再保留來源快照與目的舊內容。失敗時讀 CQE.DW0，將其解釋為「最低編號、未成功複製的 Source Range entry」，而非成功區塊總數或下一個一定尚未執行的位置。 || Validate ranges, nonoverlap and all three Copy limits, preserving source and old-destination data. On failure, DW0 identifies the lowest-numbered source entry not successfully copied, not a successful-block count or a guaranteed execution cursor.
Copy 成功時，目的範圍應依 descriptor 順序包含全部來源內容；失敗時則不能要求完全沒有修改。例如四筆來源中0、1、3已成功，但2未成功，DW0=2；它無法證明3完全沒執行，也無法證明2沒有任何部分寫入。若完全沒有寫入目的資料，DW0必須為0；反過來，DW0=0 並不能證明目的資料完全沒改變。 || Successful Copy places all source content consecutively in descriptor order. Failure does not imply no changes: if ranges0,1 and3 succeed but2 does not, DW0=2. It does not prove range3 was untouched or range2 had no partial effects. No destination writes requires DW0=0, but DW0=0 does not prove no writes.
超過來源範圍或總長度限制使用 Command Size Limit Exceeded（1/83h）。Format0h／1h 的來源與目的重疊是 Host 應避免的情況，不能一律要求 Overlapping I/O Range；Formats2h／3h 則明定禁止相應重疊並回1/87h。驗證 Status 前必須固定 descriptor format。 || Source-length/total-copy limit violations use1/83h. Hosts should avoid overlap for Formats0h/1h, but cannot universally demand Overlapping I/O Range there; Formats2h/3h explicitly prohibit relevant overlap and require1/87h. Fix descriptor format before testing status.
NVM 1.3 適用的 NVMCSA 規則，將 Copy 的目的寫入當成一個 Write 套用原子性要求，不表示任意大小的 Copy 都是整筆原子操作。失敗重試前，要查目的內容、原子子範圍與來源是否已被其他寫入者更動，不能只從 DW0 指定的位置繼續就宣告安全。 || Applicable NVM1.3 NVMCSA rules treat the destination write as one Write for atomicity, not as an unlimited atomic transaction. Before retrying, inspect destination effects, atomic subranges and source changes rather than treating DW0 as a safe resume cursor.
先檢查是否把 DW0 當成已完成數量，再確認來源 NLB 是否已加1。這兩種解讀錯誤會分別造成錯誤恢復位置與目的範圍偏移。 || First check whether DW0 was mistaken for a completion count and whether every source NLB was decoded with+1. These mistakes corrupt recovery decisions and destination offsets respectively.
''')

q(328,"Write Uncorrectable 後 Read 失敗，是媒體壞掉了嗎？ || Does a read failure after Write Uncorrectable prove damaged media?",
 ['uncorrectabledata','atomicdata','smart'],[96,199],'''
Write Uncorrectable 主動把指定 logical blocks 標示為無效，讓之後的讀取回報錯誤。這是 Host 要求的邏輯狀態變更；單憑隨後的 Unrecovered Read Error，不能推論 NAND 真的發生物理損壞。 || Write Uncorrectable deliberately marks logical blocks invalid so later reads fail. This is a requested logical state change; the resulting Unrecovered Read Error alone does not prove physical NAND damage.
操作影響 NSID 指定的 LBA 範圍，不等於停用整個 namespace。共享該 namespace 的其他 controllers 也可能觀察到這個無效狀態，因此比對前要確認是否有其他 Host 改寫相同範圍。 || The operation targets an LBA range rather than disabling the whole namespace. Other attached controllers can observe the invalid state, so account for concurrent writes.
確認 Write Uncorrectable 支援，以及 NVM Identify Controller 的 WUSL 與 ONCS.NVMWUSV。WUSL 非零時，NVMWUSV=1 表示建議最大大小；NVMWUSV=0 才依該值套用必須拒絕超限的規則。命令不傳 Host 資料，所以不能直接套 MDTS。 || Check command support, WUSL and NVMWUSV. With nonzero WUSL, variant1 makes it a recommended maximum; variant0 makes exceeding it a rejection condition. The command has no host payload, so MDTS is not its direct limit.
SLBA 指起點，NLB 採 zero-based。教學假設 SLBA=200、NLB=1，目標是200及201兩個區塊；它不使用 Read／Write 的資料 buffer 來裝無效標記，而是由命令本身要求狀態改變。 || SLBA selects the start and zero-based NLB selects count. SLBA200/NLB1 targets blocks200 and201. No host Read/Write payload buffer carries an invalid marker; the command requests the state change.
先對目標寫入已知合法資料並確認成功，再執行 Write Uncorrectable。等其成功後，單獨讀取標示範圍與一個未標示的對照範圍；最後以合法 Write 重新寫入目標，確認無效狀態被清除，而不是只做 Reset 期待它消失。 || Establish valid data, complete Write Uncorrectable, then read the marked range and an unmarked control range. A subsequent valid Write clears the invalid-block status; do not substitute Reset for that write.
Write Uncorrectable 本身可以成功；隨後對標示區塊的 Read 應回 Unrecovered Read Error。重新寫入該區塊會清除無效狀態，之後在沒有其他錯誤的情況下，可以讀回新寫入資料。這三個結果一起才構成完整驗證。 || The marking command can succeed while subsequent reads require Unrecovered Read Error. A new write clears invalid status, permitting new-data readback absent other errors. Verify all three stages together.
後續 Read 的 Unrecovered Read Error 是2/81h，不是標示命令必須回報失敗。WUSL 有效且 NVMWUSV=0 時，超過大小限制的標示命令須回 Invalid Field（0/02h）；NVMWUSV=1 的建議大小不能當成相同的強制拒絕條件。 || Subsequent read failure is2/81h; the marking command need not fail. Exceeding effective WUSL with NVMWUSV=0 requires Invalid Field (0/02h), unlike variant1’s advisory size.
將標示命令的成功、後續 Read 的錯誤及重寫後的結果，與當時 Error Information／SMART 一起保存。即使讀取錯誤被計入相應統計，也不能據此把已知由 Host 標示造成的錯誤，改解釋成硬體退化。 || Correlate marking success, read failure and rewritten data with applicable logs/counters. Even when a read error contributes to relevant statistics, a known host-requested invalid mark is not by itself evidence of physical degradation.
先查該 LBA 是否曾成功執行 Write Uncorrectable，以及之後是否已被重新寫入。若省略操作歷史，只看最後一筆 Read Status，很容易判錯原因。 || First check successful marking and subsequent rewrite history for that LBA. The last Read status alone can misidentify the cause.
''')
