"""Definitions rendered locally, at most twice per document."""
TERMS = {
 'SQ Associations': ('提交佇列關聯；建立 SQ 時，提示控制器這個佇列預計服務哪個 NVM Set。', 'A queue-creation hint identifying the NVM Set that an SQ is intended to serve.'),
 'SQ': ('Submission Queue，提交佇列；主機放置待執行命令的記憶體佇列。', 'Submission Queue; a memory queue in which the host places commands for execution.'),
 'CQ': ('Completion Queue，完成佇列；控制器放置命令完成結果的記憶體佇列。', 'Completion Queue; a memory queue in which the controller posts command completions.'),
 'SQE': ('Submission Queue Entry；SQ 內的一個命令項目。', 'Submission Queue Entry; one command entry in an SQ.'),
 'NVM Set': ('在邏輯上與其他集合分開的一組非揮發性儲存，可包含多個 namespace。', 'A logically separate collection of non-volatile memory that may contain multiple namespaces.'),
 'namespace': ('主機以 NSID 指定的一份邏輯儲存空間。', 'A logical storage space selected by NSID.'),
 'NSID': ('Namespace Identifier；I/O 命令用來指定 namespace 的識別值。', 'Namespace Identifier; identifies the namespace targeted by an I/O command.'),
 'Predictable Latency Mode': ('可預測延遲模式；以 NVM Set 為單位，在符合操作條件的工作視窗提供確定性讀寫延遲。', 'A mode providing deterministic read/write latency per NVM Set during operating windows subject to specified conditions.'),
 'CTRATT': ('Controller Attributes；Identify Controller 中由多個能力 bit 組成的屬性欄位。', 'Controller Attributes; a field of capability bits in Identify Controller.'),
 'SQA': ('SQ Associations；CTRATT 中表示是否支援提交佇列關聯的 bit。', 'SQ Associations; the CTRATT bit reporting support for queue-to-set association.'),
 'PLM': ('Predictable Latency Mode；CTRATT 中表示是否支援可預測延遲模式的 bit。', 'Predictable Latency Mode; the CTRATT bit reporting mode support.'),
 'NSETS': ('NVM Sets；CTRATT 中表示是否支援 NVM 集合的 bit。', 'NVM Sets; the CTRATT support bit for NVM sets.'),
 'DTWIN': ('Deterministic Window；Set 可以提供確定性讀寫延遲的工作視窗。', 'Deterministic Window; the operating window in which a set can provide deterministic read/write latency.'),
 'NDWIN': ('Non-Deterministic Window；Set 準備下一個 DTWIN，無法提供確定性讀寫延遲的工作視窗。', 'Non-Deterministic Window; preparation for a subsequent DTWIN prevents deterministic read/write latency.'),
 'Deterministic Excursion': ('subsystem 中罕見但需要控制器立即處理的事件，可能讓 Set 離開 DTWIN。', 'A rare subsystem occurrence requiring immediate controller action, which may cause departure from DTWIN.'),
 'CNS': ('Controller or Namespace Structure；Identify 用來選擇回覆哪種資料的欄位。', 'Controller or Namespace Structure; selects the data returned by Identify.'),
 'CNSSID': ('CNS Specific Identifier；用途由 CNS 選項決定的識別欄位。', 'CNS Specific Identifier; its meaning depends on the selected CNS value.'),
 'CNTID': ('Controller Identifier；只在需要指定控制器的 Identify 選項使用。', 'Controller Identifier; used by Identify options that select a controller.'),
 'CSI': ('Command Set Identifier；Identify 某些選項使用的 I/O Command Set 識別值。', 'Command Set Identifier; selects an I/O command set for applicable Identify options.'),
 'NVMSETID': ('NVM Set Identifier；Set 的 16-bit 識別值，和 SQ 編號、NSID 都不同。', 'A 16-bit NVM Set identifier, distinct from SQ identifiers and NSIDs.'),
 'NSETID': ('NVM Set Identifier；NVM Set Attributes Entry 內對 Set 識別欄位使用的縮寫。', 'NVM Set Identifier; the name used for the set identifier in an NVM Set Attributes Entry.'),
 'NUMENT': ('Number of Entries；這份清單中實際回傳的項目數。', 'Number of Entries; the number of entries actually returned in the list.'),
 'ENDGID': ('Endurance Group Identifier；Set 或 namespace 所屬耐用度群組的識別值。', 'Endurance Group Identifier; identifies the endurance group containing a set or namespace.'),
 'R4KRT': ('Random 4 KiB Read Typical；在指定視窗與在途命令數條件下，4 KiB 隨機讀取的典型完成時間。', 'Random 4 KiB Read Typical; typical completion time under the specified window and outstanding-command conditions.'),
 'OWS': ('Optimal Write Size；以 bytes 表示的最佳寫入大小。', 'Optimal Write Size; a preferred write size in bytes.'),
 'TNVMSC': ('Total NVM Set Capacity；Set 的總儲存容量，以 bytes 表示。', 'Total NVM Set Capacity, measured in bytes.'),
 'UNVMSC': ('Unallocated NVM Set Capacity；Set 中尚未配置給 namespace 的容量，以 bytes 表示。', 'Unallocated NVM Set Capacity, measured in bytes.'),
 'QID': ('Queue Identifier；本命令準備建立的 SQ 編號。', 'Queue Identifier; the identifier assigned to the SQ being created.'),
 'QSIZE': ('Queue Size；Create I/O SQ 中以項目數減 1 編碼的深度。', 'Queue Size; the SQ entry count encoded as count minus one.'),
 'CQID': ('Completion Queue Identifier；這個 SQ 的完成項目要送往哪個 CQ。', 'Completion Queue Identifier; selects the destination CQ for this SQ’s completions.'),
 'PC': ('Physically Contiguous；1 表示 SQ 的記憶體實體連續，0 表示用頁面清單描述。', 'Physically Contiguous; one selects contiguous queue memory, zero a page-list description.'),
 'QPRIO': ('Queue Priority；僅在指定的加權輪詢仲裁機制下使用的 SQ 優先級。', 'Queue Priority; used only by the applicable weighted round-robin arbitration mechanism.'),
 'PRP1': ('PRP Entry 1；本命令依 PC 選擇存放 SQ 基底位址或 PRP List 位址。', 'PRP Entry 1; holds the queue base or PRP List address according to PC.'),
 'PRP List': ('Physical Region Page List；依序列出組成佇列的實體記憶體頁位址。', 'A list of physical memory page addresses describing the queue.'),
 'CC.MPS': ('Memory Page Size；控制器目前設定的記憶體頁大小，用來判斷 PRP 對齊。', 'Memory Page Size; the configured page size used for PRP alignment.'),
 'CAP.CQR': ('Contiguous Queues Required；1 表示佇列必須採實體連續記憶體。', 'Contiguous Queues Required; one requires physically contiguous queues.'),
 'CAP.MQES': ('Maximum Queue Entries Supported；控制器每個佇列可支援項目數的上限，欄位採數量減 1。', 'Maximum Queue Entries Supported; the per-queue entry limit encoded as count minus one.'),
 'CC.IOSQES': ('I/O Submission Queue Entry Size；設定每個 I/O SQ 項目的大小。', 'I/O Submission Queue Entry Size; configures the size of each I/O SQ entry.'),
 'index': ('索引；項目在清單中的順序位置，這裡從 0 起算。', 'A zero-based entry position within the list.'),
 'byte offset': ('相對資料結構起點、以 byte 計算的距離；不等於項目索引或識別值。', 'A byte distance from a structure’s start, distinct from an index or identifier.'),
 'header': ('資料結構的前置區；NVM Set List 的前 128 bytes 保存項目數與保留空間。', 'The leading area; the NVM Set List uses 128 bytes for the count and reserved space.'),
 'entry': ('清單中的一筆資料；此處每筆 NVM Set Attributes Entry 為 128 bytes。', 'One list record; an NVM Set Attributes Entry occupies 128 bytes.'),
 'round robin': ('輪詢仲裁；輪流從佇列選取待處理命令，本例不使用加權優先級。', 'Round-robin arbitration; takes turns selecting queues without weighted priority in this example.'),
 'outstanding': ('已提交但尚未完成的命令；要按規定的 Set 範圍合計。', 'Submitted but not yet completed commands, counted over the specified set scope.'),
}
