from scripts.nvme_scenarios import case

case('io',('8 個 blocks 的寫入，斷電也一定不會寫一半嗎？','Is an eight-block Write also atomic across power failure?'),
('同事看到 AWUN=7，便宣稱一次寫 8 個 blocks 能抵抗斷電造成的部分更新。這個結論缺了什麼？','A colleague sees AWUN=7 and claims that an eight-block Write cannot be partially updated by power failure. What is missing?'),
[('AWUN=7、AWUPF=1；NSFEAT.NSABP=0、MAM=0；目前 Write Atomicity Normal 的 DN=0。','AWUN=7, AWUPF=1; NSFEAT.NSABP=0 and MAM=0; current Write Atomicity Normal has DN=0.'),('目標 LBA 資料大小 4096 bytes；這是單筆一般 Write，NLB=7。','LBA data size is 4096 bytes; this is one ordinary Write with NLB=7.')],
('Identify CNS=01h 讀 NVM 定義的 AWUN／AWUPF；CNS=00h 讀目標 namespace 的 NSFEAT；Get Features FID=0Ah、SEL=0 確認正常原子性未被停用。','Identify CNS=01h for the NVM-defined AWUN/AWUPF fields; CNS=00h for namespace NSFEAT; Get Features FID=0Ah, SEL=0 to confirm normal atomicity is not disabled.'),
[('AWUN 與 AWUPF 都以 blocks 數減 1 編碼。7 表示正常情況下的 8 blocks 保證；1 表示斷電或錯誤情況下的 2 blocks 保證。命令 NLB=7 也是 8 blocks，即 32768 bytes。','AWUN and AWUPF encode block counts minus one. Seven provides an eight-block normal-operation guarantee; one provides a two-block power-failure/error guarantee. NLB=7 requests eight blocks, or 32768 bytes.'),('這筆 Write 在所給條件下符合正常原子性的大小限制，卻超過斷電原子性的大小。超出保證不代表必定發生部分更新，而是不能用 AWUPF 保證整筆 8 blocks 不被撕裂。','Under these assumptions the Write fits the normal atomic limit but exceeds the power-failure limit. Exceeding a guarantee does not mean a torn write must occur; it means AWUPF cannot guarantee the whole eight-block update.'),('如果應用要求整筆 32 KiB 在斷電下也不可分割，需要其他符合規格的配置或上層資料保護方法。改成 FUA=1 會增加完成前持久化要求，但不會把 AWUPF 的 2 blocks 改成 8 blocks。','If the application needs an indivisible 32 KiB update across power loss, it needs an appropriate supported configuration or higher-level protection. FUA=1 adds a persistence requirement before completion; it does not expand AWUPF from two blocks to eight.')],
'N4 N123 N71','N@4.1.5.2:94-96 N123:85-86,88 N@2.1.4:15-18 N@4.1.3.4:67 N71:54')

case('io',('namespace 的 NAWUPF=0，為什麼不是 1 block？','Why does NAWUPF=0 not necessarily mean one block?'),
('一個解碼器對所有 atomic unit 欄位直接加 1。請用此例找出它會算錯哪裡。','A decoder adds one to every atomic-unit field. Which result does it get wrong here?'),
[('Controller：AWUN=7、AWUPF=3。Namespace：NSABP=1、NAWUN=15、NAWUPF=0、NABSN=0、NABSPF=0、MAM=0。','Controller: AWUN=7, AWUPF=3. Namespace: NSABP=1, NAWUN=15, NAWUPF=0, NABSN=0, NABSPF=0, MAM=0.'),('正常原子性未停用；LBA data size=4096 bytes。','Normal atomicity is enabled; LBA data size=4096 bytes.')],
('Identify CNS=01h 與 CNS=00h 配對取得 controller 基準及 namespace 覆寫值。','Pair Identify CNS=01h with CNS=00h to obtain the controller baseline and namespace-specific values.'),
[('先看 NSABP，才知道 namespace atomic 欄位是否有效。本例 NAWUN=15 是非零，採用它後得到正常情況 16 blocks，也就是 64 KiB；不是只看 controller 的 8 blocks。','Check NSABP before interpreting namespace atomic fields. NAWUN=15 is nonzero, providing 16 blocks, or 64 KiB, for normal operation rather than only the controller’s eight-block baseline.'),('NAWUPF=0 在這裡有特別意思：沿用 controller 的 AWUPF，不是把 0 加 1。AWUPF=3 所以斷電保證為 4 blocks，即 16 KiB。','NAWUPF=0 has a special meaning here: use controller AWUPF rather than adding one to zero. AWUPF=3 provides four blocks, or 16 KiB, for power-failure atomicity.'),('NABSN=NABSPF=0 表示未設此類 atomic boundary。這些 0、NAWUPF 的 0，以及 controller AWUPF=0 所表示的 1 block，語意各不同。解碼器必須按欄位定義分支，不能做全表統一加 1。','NABSN=NABSPF=0 specifies no corresponding atomic boundaries. These zeros, NAWUPF’s fallback zero and controller AWUPF=0 meaning one block have different semantics. A decoder needs field-specific rules.')],
'N4 N123','N@4.1.5.2:94-96 N123:85-86,88-89 N@2.1.4:16-19')

case('io',('大小符合，跨過 boundary 還算整筆 atomic 嗎？','Does a size-compliant Write remain atomic across a boundary?'),
('兩筆 Write 都只有 4 blocks，為什麼起始 LBA 不同，namespace 的原子性保證也可能不同？','Two Writes each contain four blocks. Why can their starting LBAs change the namespace atomicity guarantee?'),
[('AWUN=0、AWUPF=0；NSABP=1、NAWUN=7、NAWUPF=7；NABSN=7、NABSPF=7、NABO=0；DN=0。','AWUN=0, AWUPF=0; NSABP=1, NAWUN=7, NAWUPF=7; NABSN=7, NABSPF=7, NABO=0; DN=0.'),('先考慮 MAM=0。Write A：SLBA=8、NLB=3；Write B：SLBA=6、NLB=3。','First consider MAM=0. Write A: SLBA=8, NLB=3. Write B: SLBA=6, NLB=3.')],
('Identify CNS=00h 讀 unit、boundary、offset 及 NSFEAT.MAM；把命令轉成實際 LBA 區間後比較。','Identify CNS=00h for units, boundaries, offset and NSFEAT.MAM; convert commands into actual LBA intervals before comparing.'),
[('非零 boundary size=7 代表 8 blocks，NABO=0，所以分界在 0、8、16……。A 觸及 LBA 8–11，全在同一區間；B 觸及 6–9，跨過 8。兩者雖然都少於 8 blocks，位置並不等價。','A nonzero encoded boundary size of seven represents eight blocks. With NABO=0, boundaries occur at 0, 8, 16 and so on. A covers LBAs 8–11 within one interval; B covers 6–9 and crosses eight. Equal lengths do not make their positions equivalent.'),('MAM=0 是 Single Atomicity Mode。A 符合本例 namespace 的整筆原子性條件；B 跨界，不能套用同一個整筆 4-block 保證。這個限制要與 unit 大小一起檢查。','MAM=0 selects Single Atomicity Mode. A satisfies the namespace whole-Write conditions here; B crosses a boundary and cannot claim the same four-block guarantee. Boundary and unit-size checks belong together.'),('若改成規格允許的 MAM=1 配置，B 可分為 6–7 與 8–9 兩個 atomic LBA subranges，保證分別適用於各段，仍不是兩段合起來的一個不可分割更新。','With a valid MAM=1 configuration, B is divided into atomic LBA subranges 6–7 and 8–9. Each subrange receives its own guarantee; the two combined are still not one indivisible update.')],
'N8 N123 N4','N@2.1.4.4:19 N@2.1.4.5:19-20 N123:85,88-89')

case('io',('Write 已成功，資料現在一定不怕斷電嗎？','Does a successful Write already establish persistence?'),
('你只能看到能力資料、Feature 值與命令紀錄。如何判斷成功的 Write 是否已滿足持久化要求？','With capability data, feature values and a command trace, how can you assess persistence of a successful Write?'),
[('已確認此 namespace 有啟用中的 volatile write cache；Get Features FID=06h 的 WCE=1。','A volatile write cache is confirmed present and enabled for this namespace; Get Features FID=06h reports WCE=1.'),('A：一般 Write，FUA=0，成功，之後沒有 Flush。B：Write，FUA=1，成功。','A: ordinary Write, FUA=0, successful, with no later Flush. B: Write, FUA=1, successful.')],
('Identify CNS=01h 的 VWC、CNS=08h 的 VWCNP 與適用的 FDP 配置 → Get Features FID=06h、SEL=0 → 命令 FUA 與後續 Flush 紀錄。','Identify CNS=01h for VWC, CNS=08h for VWCNP and the applicable FDP configuration → Get Features FID=06h, SEL=0 → command FUA and subsequent Flush trace.'),
[('A 可能已經落到非揮發媒體，也可能仍依賴 volatile cache；從成功 CQE 無法區分這兩種情況。因此不能宣稱它一定已持久化，也不能反過來說它一定只在 cache。','A may already be on nonvolatile media or may still depend on volatile cache. Its successful completion alone does not distinguish those states, so neither definite persistence nor definite cache-only residency follows.'),('B 的 FUA=1 要求這筆命令的資料與 metadata 在回報完成前寫入非揮發媒體。持久性關注完成後能否保留，原子性則關注更新會不會部分發生；這兩個問題要分開回答。','B’s FUA=1 requires this command’s data and metadata to reach nonvolatile media before completion. Persistence concerns retention after completion; atomicity concerns whether an update can be partial. They are separate questions.'),('另一條路是先等 A 完成，再提交涵蓋它的 Flush，並確認 Flush 成功。Flush 保證涵蓋其提交前已完成的指定 namespace 寫入；若與 Write 同時送出，就少了這個先後條件。','Another route is to wait for A to complete, then submit a covering Flush and verify its successful completion. Flush covers completed commands for its target namespace before Flush submission. Concurrent submission would lack that ordering condition.')],
'B471 B338 B346 N71','B338:400 B346:417-420 B471:490-491 B@7.2:593 N71:54')

case('io',('資料與索引都用 FUA，為什麼還要排順序？','Why order data and index Writes if both use FUA?'),
('應用先把資料 Write 放進 SQ，再把指向該資料的索引 Write 放進同一 SQ。兩筆都 FUA=1，是否已保證索引不會先持久化？','An application places a data Write and then its index Write in the same SQ. Both use FUA=1. Is the index prevented from becoming persistent first?'),
[('資料與索引使用不同 LBA 範圍；不是 fused operation。','Data and index use different LBA ranges and are not a fused operation.'),('兩筆命令一起提交，尚未等待第一筆完成；目標是斷電後不出現「新索引指向尚未保存的資料」。','Both are submitted without waiting for the first completion. The goal is to avoid a new index pointing at data not yet persisted after power loss.')],
('檢查原始 SQE 的 FUA 與提交／完成時序；用 NVM 的 command ordering 與 Write FUA 規則判讀。','Inspect FUA in the SQEs and the submission/completion timeline; apply NVM command-ordering and Write FUA rules.'),
[('同一 SQ 的位置先後，不能替代這裡所需的資料依賴。FUA=1 對各筆命令提出完成前持久化要求，並沒有額外規定不同命令之間誰先完成。','SQ position does not enforce this data dependency. FUA=1 imposes persistence before each command completes; it does not add an ordering guarantee between separate commands.'),('符合目標的示範時序是：提交 data Write（FUA=1）→確認成功完成→才提交 index Write（FUA=1）→確認成功完成。第二步使資料的持久化先於索引寫入的提交。','A suitable illustrative sequence is: submit data Write with FUA=1 → verify successful completion → submit index Write with FUA=1 → verify successful completion. The first completion establishes data persistence before index submission.'),('這只解決題目中的依賴順序，並不把資料與索引兩筆寫入合成一筆跨範圍交易。若要求兩者一起回到舊值或一起變新值，還需要更完整的交易或復原設計。','This resolves the stated dependency, not a multi-command transaction. Requiring data and index to revert together or update together needs a fuller transaction or recovery design.')],
'N71 N4','N@2.1.2:14 N71:54')

case('io',('Metadata 比 PI 大，PRACT=1 要扣掉多少 bytes？','How does PRACT=1 affect metadata larger than PI?'),
('移植程式把 PRACT=1 的 metadata buffer 一律減掉 8 bytes／LBA。這在本例是否正確？','A port subtracts eight metadata bytes per LBA whenever PRACT=1. Is that correct here?'),
[('16-bit Guard 格式，PI 已啟用；LBA data=4096 bytes、MS=16，metadata 使用 separate buffer。','16-bit Guard with PI enabled; LBA data=4096 bytes, MS=16, separate metadata buffer.'),('Write 的 PRACT=1、NLB=3；其他保護設定均合法。','Write has PRACT=1 and NLB=3; other protection settings are valid.')],
('Identify CNS=00h 的 LBAF／DPS／metadata 設定，必要時 CNS=05h、CSI=00h 的 ELBAF → 對照 Write 的 16-bit Guard processing 規則。','Identify CNS=00h for LBAF, DPS and metadata settings, plus CNS=05h with CSI=00h for ELBAF where needed → apply Write 16-bit Guard processing rules.'),
[('NLB=3 是 4 blocks。資料 buffer 為 4×4096=16384 bytes；在這個 metadata 大於 8 bytes 的分支，host 仍傳輸 4×16=64 metadata bytes，不能只配置 32 bytes。','NLB=3 requests four blocks. The data buffer is 4×4096=16384 bytes. In this metadata-greater-than-eight branch, the host still transfers 4×16=64 metadata bytes, not 32.'),('PRACT 決定 PI 的產生與處理行為，不是通用的「buffer 長度減 8」開關。當 metadata 剛好只有 8 bytes 時，圖表中的另一個分支才有不同的傳輸規則，不能把它搬到 MS=16。','PRACT controls PI generation and processing, not a universal subtract-eight buffer rule. Exactly eight metadata bytes uses a different branch in the processing table; it cannot be applied to MS=16.'),('除長度之外，還要對齊 separate／extended 的放置方式、PI 類型及 Guard 格式。只有這些條件都相同，才適合拿前後兩次傳輸的 bytes 作比較。','Beyond length, align separate versus extended placement, PI type and Guard format. Only with matching conditions is a byte-level comparison between transfers meaningful.')],
'N125 N128 N154 N174','N125:94 N128:101-102 N154:130 N174:143')

case('io',('Deallocate 後讀到 FFh，是不是失敗？','Is FFh after deallocation a failure?'),
('驗證程式要求所有 deallocated LBA 都回傳 0。請判斷它是否把允許的行為誤當成錯誤。','A validator requires every deallocated LBA to return zero. Could it reject permitted behavior?'),
[('該範圍已確認 deallocated；DLFEAT.DRB=010b；Get Features FID=05h 的 DULBE=0。','The range is confirmed deallocated; DLFEAT.DRB=010b; Get Features FID=05h reports DULBE=0.'),('本例不啟用 PI；Read 成功且全部 data bytes 為 FFh。','PI is disabled in this example; Read succeeds and all data bytes are FFh.')],
('Identify CNS=00h 查 DLFEAT 與相關能力；Get Features FID=05h、SEL=0、目標 NSID 查 DULBE；再看 Read 結果。','Identify CNS=00h for DLFEAT and relevant capabilities; Get Features FID=05h, SEL=0 for the target NSID to read DULBE; then assess Read results.'),
[('DRB=010b 所描述的 deallocated 讀取內容就是 FFh，所以此例與規格回報一致。Read 成功不要求一定回 0；驗證器應由 DRB 選擇預期內容。','DRB=010b describes FFh contents for deallocated reads, so this example agrees with the reported behavior. Successful Read does not inherently require zero; the validator should derive its expectation from DRB.'),('若 namespace 支援 DULBE 且目前設為 1，對 deallocated／unwritten block 的讀取又可能走錯誤回覆的路徑。比較兩個裝置前，要把 Feature 狀態一起保存，不能只比較讀回 bytes。','If DULBE is supported and enabled, deallocated/unwritten reads can instead take the error-reporting path. Preserve the feature state when comparing devices rather than only comparing returned bytes.'),('這個讀取結果只驗證邏輯介面的 deallocation 行為，不能證明所有實體媒體副本已被安全清除。需要 Sanitize 保證時，應使用該操作的能力、目標及完成狀態證據。','This tests logical-interface deallocation behavior, not secure erasure of every physical-media copy. Sanitize claims require evidence about that operation’s support, target and completion state.')],
'N123 N47 B198','N123:88 N@3.3.3.2.1:48 N@4.1.3.3:66')
